### ISSUE TITLE
Core dependencies?

### ISSUE THREAD

**Issue by pjf** [KSP-RO/RP-0#1]
What are our core dependencies for RP-0? Those things which we require the user to have installed in order for things to work. Ideally, as a lightweight RO experience, these should be as few as possible.

Since we require RealismOverhaul, that already gives us a list of things which we know will be installed:

* AJE
* DeadlyReentry
* EngineIgnitor
* FerramAerospaceResearch
* ModuleManager
* ModuleRCSFX
* RealChute
* RealFuels
* RealSolarSystem
* TACLS

In addition, we require:

* SXT
* ProceduralFairings
* KerbalJointReinforcement

**Comment by NathanKell** [comment]
I think we can close this now.
