### ISSUE TITLE
R7 Block E Luna

### ISSUE THREAD

**Issue by EstrelaGaliza** [KSP-RO/RP-0#1010]
I'm playing soviet career and i've just realized about that the ''r7 block E Luna'' unlocks with ''1959 Orbital Rocketry'', but its the same engine as RD-105/109 which is at the previus node. 
Also taking into account that 1st Luna launches were at 1958, it would make sense to be unlocked at 1958 node.
I know there are many unconfigured parts from RN, but this one has his rp-0 config.

I don't really know how to config RP-0 parts, but I used to write just the prices and tech nodes at ''TREE-parts.cfg'' (I've just realized about there is a guide to making rp-1 configs, but I dont have enough time at this moment to learn to use it... I'll try do it in the future and share some configs from RN mods, which I love).

**Comment by pap1723** [comment]
Fixed with https://github.com/KSP-RO/RP-0/commit/85c2c73cb3bd7ec166e1ae7486b0cc332496fbe1
