### ISSUE TITLE
KCT recovery

### ISSUE THREAD

**Issue by ppboyle** [KSP-RO/RP-0#1014]
So - KCT recovery is going to be the new power-move for race players, and possibly anyone else who figures out how much it can help you.

Do we care?   It's clearly unrealistic, for the first 20-30 odd years for rockets.  

Ways we could handle it, that I see, in order of most sucky/easy to implement to the reverse.

1. Disable it completely.   Screw you, planes.
2. Disable it if the craft has a rocket engine.  Yay planes.  Screw you, RATO's.
3. Remove any part with a rocket engine, force the player to rebuild the craft in the VAB.   Screw craft with stuff on your rockets.  Delete anything branching from the rocket in the part tree as well.  Screw you SpaceX lovers.
4. Like #3, but remove any part with a rocket engine, except those tagged w/a reuseability tag, so SpaceX players aren't sad.
5.  Add a special field to all parts, where the recovery system can mark them as burned-out, and therefore when recovered, they cost full-fare to replace.
6.  Like #5, but some parts can only be partially used up, based off of burn-time, ignitions remaining, or just time in flight. 

Any other thoughts/solutions?   Doesn't need addressing for the next version of course.

**Comment by siimav** [comment]
As a quick and easy fix I currently tech-gated the VAB recovery behind the materialsScienceSpaceplanes node. Planes will still be fully recoverable and reusable as before.
But I think it would be a good idea to look into this problem again at a later date to see if some restrictions or recovery penalties could be made based on burn time or ignitions remaining. Although re-use wouldn't make much sense before we lower the launch costs or divide it into separate components like integration and rollout.

**Comment by pap1723** [comment]
Completed, we can re-open this if we don't like how it is working currently.
