### ISSUE TITLE
First Scientific Satellite contract clarification

### ISSUE THREAD

**Issue by andersschack** [KSP-RO/RP-0#1015]
The contract First Scientific Satellite states in the briefing, that you need a micrometeorite detector. The objectives only state that you need to transmit science.
The contract is configured to require a micrometeorite detector.

Perhaps emphasise the micrometeorite detector part in the briefing, if it's not possible to clarify it in the objectives.

**Comment by pap1723** [comment]
Fixed with commit https://github.com/KSP-RO/RP-0/commit/cca8acd7451bdd8576e78e5544fea60459c724b0 and actually changed the required experiment to be radiation study.
