### ISSUE TITLE
Geiger counter and high orbit biomes.

### ISSUE THREAD

**Issue by pjf** [KSP-RO/RP-0#102]
The geiger counter returns a decent chunk of science, and while
InSpaceHigh it's still biome-specific. Given the flavour text
implies discovery of the Van Allen belts, it doesn't feel right to
discover these (and net 15 science) once per biome.

**Comment by NathanKell** [comment]
The messages have not been corrected yet. The reason for biomes even in high space is that the Van Allen belts are belts, not shells, so the result will be different over the poles vs. over anywhere else, even in high space. There being no way to say "pole / no-pole" as the location mask, we're left with "biome-dependent".

**Comment by jwvanderbeck** [comment]
I really need to accelerate work on RealScience

- John Vanderbeck
- http://www.johnvanderbeck.com

**Comment by pjf** [comment]
> The messages have not been corrected yet. The reason for biomes even in high space is that the Van Allen belts are belts, not shells, so the result will be different over the poles vs. over anywhere else, even in high space. There being no way to say "pole / no-pole" as the location mask, we're left with "biome-dependent".

As far as I know it's not possible to say that an experiment is biome dependent for one body (Kerbin/Earth) and not others. So we're providing and 8x science return for *every body*, even though the result is mostly going to be "meh" for any body that doesn't have a magnetosphere.

I have to admit, this is where something like RealScience, or even RPL's single-shot experiments would come in handy.

I don't think it's terribly gameplay breaking if we remove the biome-dependency for the geiger counter in high space. If we still want to simulate the mapping of the van allen belts, then I think adding a *second* experiment to the geiger counter which is biome dependent, and *only* works InSpaceHigh is the way to go. This can have much lower pay-outs per experiment, but still provide a reasonable return for players who go to the effort of putting a probe in high orbit. (Unfortunately it also means payouts on other worlds, but it's better than what we have now.)

**Comment by NathanKell** [comment]
Yeah, it's *profoundly* annoying that experiments are so universal. Was actually just talking with @jwvanderbeck about that, and his RealSciencey ideas.

Is the 'meh' factor that it's boring, or that it shouldn't be giving that much science for bodies without belts? If the latter, well, finding no belt can be just as scientifically rewarding as finding a belt...

It seems to me, correct me if I'm wrong, the *fundamental* objection here is the grind, yes? Because the payout can be lowered across the board if biome dependency is kept--the experiment need not be OP in that sense.

Oh, and a final note: Everywhere but Earth, the threshold between space high / space low is *very* low, on the order of 100km or so for the Moon (maybe less).

**Comment by jwvanderbeck** [comment]
Initial design thoughts for RealScience, since it seems relevant:
https://github.com/jwvanderbeck/RealScience/wiki/Design

**Comment by BevoLJ** [comment]
@NathanKell 
>Is the 'meh' factor that it's boring, or that it shouldn't be giving that much science for bodies without belts? If the latter, well, finding no belt can be just as scientifically rewarding as finding a belt...

Like finding out Venus doesn't, wait.... oh right.  :D  I'd like to again apologise for my video and being so shocked it had such a strong one.  lol.

Off topic, how can we sort out those messages again?  I never got around to fixing that.

**Comment by pjf** [comment]
I have more to write, but I'm about to run out the door, so I just want to check something.

> Everywhere but Earth, the threshold between space high / space low is very low, on the order of 100km or so for the Moon (maybe less).

What's the border between high and low space defined as? Is it geosynchronous? Is it half the SOI radius? Is it something else?

The reason being that from a gameplay standpoint, it feels natural for low space to be "close enough to get high resolution data", and high space to be merely "near the body".

**Comment by NathanKell** [comment]
@pjf it was set per-body by Medieval Nerd and myself, basically as "whatever is hard to get to". For Earth, it's hard to get to High Earth Orbit so that's the line; for other bodies, it's hard to get closer, so the line is very low.

**Comment by pjf** [comment]
> Is the 'meh' factor that it's boring, or that it shouldn't be giving that much science for bodies without belts? If the latter, well, finding no belt can be just as scientifically rewarding as finding a belt...

I feel that biome-dependent science payouts are great for soil samples, imaging, and the like. I'm excited about @Felger's great work on them because it means I've got a reason to mount an expedition to Olympus Mons, or other unique areas in the solar system.

For the geiger counter, I feel biome-dependent experiments provide *too much* in science payouts. Given the part is available from the beginning, already has a large default payout, and is only available to players with FASA installed, I feel there's a real imbalance between RP-0 with geiger counter, and RP-0 without. But balancing science experiments should be another ticket. ( #46 and #42 may both already have discussions on this.)

However if we change InSpaceHigh to mean "within the sphere of influence" and InSpaceLow to mean "close enough for detailed study" (which I feel is a good distinction) then I think very few parts should be biome-dependent in high space, as one can see many parts of the planet from that distance. Obvious detection of Van Allen belts mean being *in* them, but that's really nothing to do with the "biomes" of the planet underneath, and I feel we detract from gameplay (as well as cheese science payouts) by having this.

In any case, I think we should get rid of the biome-dependency on the geiger counter for InSpaceHigh. If we want to continue to provide a science boost for high space with a geiger counter, then I suggest we add a second experiment to the part which *only* works InSpaceHigh, and has an appropriate payout attached.

@jwvanderbeck : Having glanced over your RealScience design documents, my reaction is "oh hell yes". Van Allen analysis is perfect if we can pop something into a polar orbit at the right altitude, and likewise almost every experiment is better designed. A lot of your ideas remind me of SCANsat (which gives science payouts once you have enough map data), and station science (which requires time and resources to get results), both of which are systems I really like.

**Comment by NathanKell** [comment]
Again, I'm not sure I understand the problem: if the geiger counter gives too much return, well, reduce the return. Biomes are neither here nor there; the experiment has a value, and that value is multiplied by all the situations you can do it in, so if the end result is too high, you can either decrease the number of situations, or you can decrease the data value. I've yet to hear an argument for why the former is a better approach than the latter except the following: it seems you are (implicitly) arguing that high space *generally* should be less scientifically valuable than low spacem and that biomes don't make sense, period, in high space. I agree that biomes are to some extent silly in (very high) high space, but I think having even GEO-level "high space", let alone 200km-high "high space" of other bodies, be non-location-dependent at all may be even sillier for certain experiments.

Also, I thought the geiger counter experiment *was* available without FASA--that's what the Vanguard X-Ray probe is supposed to be. Is that not working right? For the record I strongly support having a variety of early probes and/or instruments in base RP-0.

Finally, however, I agree that the real answer here is to divorce ourselves from KSP's silliness in science, just as we have in aerodynamics and engine performance and planet size.

**Comment by NathanKell** [comment]
That said let me be clear that I'm not at *all* opposed to balancing things as best we can *until* we can replace science wholesale, and I'm certainly not opposed to any of the three options in principle.
(The options being: 1, remove biomes from the instrument; 2, lower the returns of the instrument period, leading to the same net science change as 1; or 3, lowering Earth spacehigh returns generally, though that will affect all instruments.)

**Comment by pjf** [comment]
> Also, I thought the geiger counter experiment was available without FASA--that's what the Vanguard X-Ray probe is supposed to be. Is that not working right?

This may be our confusion!

The Vanguard X-ray has an experiment of `X-RayDetection`, the FASA geiger counter is `GeigerCounter`.

From my last ModuleManager dump (which is before #104 was applied):

```
EXPERIMENT_DEFINITION
{
        id = GeigerCounter
        title = Geiger Counter
        baseValue = 10
        scienceCap = 10
        dataScale = 1
        requireAtmosphere = False
        situationMask = 63
        biomeMask = 63
}
```

```
EXPERIMENT_DEFINITION
{
        id = X-RayDetection
        title = X-Ray Detection
        baseValue = 2.7
        scienceCap = 4.5
        dataScale = 2
        requireAtmosphere = False
        situationMask = 63
        biomeMask = 31
}
```

These are different experiments. The FASA Geiger counter pays out *way* more, and is biome-dependent everywhere. The X-Ray experiment pays out much less, and is *not* biome-dependent in high space (`biomeMask = 31`).

In this case, I suspect the FASA Geiger Counter has the default configuration shipped with FASA.

I am 100% super happy to make them the same experiment, using the existing X-Ray experiment as the authoritative definition. (Although in that case I'd probably tweak the returns up a little.)

**Comment by NathanKell** [comment]
I'd say we should use Geiger-Müller Tube as the experiment name, to no limit ourselves to x-rays, and to use the Xray defines--I agree that probably the FASA one is unchanged, except I'm pretty sure I did make it biomes in highspace for the reasons cited above.

Again I'd ask whether your objection to biomes in highspace is because:
1. It's grinding and boring and silly.
2. The experiment produces too much science
3. Highspace produces too much science compared to lowspace. (a, all-round; b, this experiment only).

The solutions to the three differ, and only in cases 1 and 3b is the obvious choice "make it non-biome-dependent"

**Comment by pjf** [comment]
> Again I'd ask whether your objection to biomes in highspace is because:
> 1. It's grinding and boring and silly.
> 2. The experiment produces too much science
> 3. Highspace produces too much science compared to lowspace. (a, all-round; b, this experiment only).

* 4. It's completely unexpected given the flavour text.
* 5. For Van Allen belts, it feels like a kludge.

Answers: All but 3.

**Comment by NathanKell** [comment]
For 4, that's because it hasn't been fixed yet. And IMO non-biome in highspace (where the belts *do* still depend on your location) would also be a kludge...
But anyway, I trust your gameplay sense on this, so I'm fine with the change, just wanted to have laid out *all* the reasoning behind it. :)

**Comment by pjf** [comment]
Since everything is now using the X-ray experiment, I'm marking this as resolved. (As always, please reopen if it's not.)
