### ISSUE TITLE
FPS drop in VAB with newest avionics change (commit 76faf1a1)

### ISSUE THREAD

**Issue by Zantigar** [KSP-RO/RP-0#1020]
Pulled master on evening of 2019-02-16 to commit 76faf1a1, along with top-of-tree KCT and RO. More or less everything works as expected in play and VAB with one exception:  if I click on the proc avionics part in VAB, the framerate reported in the alt-12 performance tab drops from ~60 to 12.5.  The frame rate goes right back to ~60 if I then dispose of the part (e.g., by clicking in the parts menu on the left).

The drop also disappears if I roll RP-0 back to commit baa6f82a, immediately preceding the most recent change to proc avionics, and leave everything else the same (and restart KSP, of course).  With that version of the .dll, I can wave proc avionics parts around to my heart's content and stay at ~60fps.

KSP log from most recent attempt (after rolling back to current master):  
[KSP.log](https://github.com/KSP-RO/RP-0/files/2872627/KSP.log)
Problem reappeared, but FPS dropped only to 25 rather than 12.5.

Happy to pull other logs or other diagnostics if that's helpful, but I'll need the path to where they are stored.

EDITED: fixed typo.

**Comment by NathanKell** [comment]
Fixed by 11d8c9dbe7b57eef34b40f7acdc1d7bac85a1677

**Comment by MikeOnTea** [comment]
For anybody else experiencing this, grab the latest master update, and also grab
the latest procedural parts release from https://github.com/MikeOnTea/ProceduralParts/releases/ until there's a new official release. If there are still problems with an existing save, do backup of the save, open it in a text editor and try replacing every occurrence of `postWarAvionics` with `avionicsPrototypes`.
