### ISSUE TITLE
Prerelease Race todos

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RP-0#1024]
- [ ] Payouts in RiS mod need to be rebalanced for the orbit changes
- [ ] (Related) RiS Contract patches need to use regular expressions (and let CC do the math, i..e appending - 10000 to the end of the line) instead of MM-math.
- [x] Remove experiments from early probes, rebalance masses
- [x] XM-20 Castor config
- [x] Geiger Muller Tier 2, make FSO require it
- [x] Bake down science (apply the 60% mult to all experiments, then make difficulty levels have 100% science)
- [x] ECM support for procedural avionics.
- [x] Move avionics upgrade PARTUPGRADE thingie to Avionics Prototypes.
- [x] Lunar Impact contract should require (a) minimum mass of 10kg, and (b) EC > 0 at time of impact.
- [x] Boattail should go in Start.
- [x] Atmospheric Analysis payout -> First Nav
- [x] Early Commerical Comms Satellite payout too high, make like Sun Synch Weather?
- [x] Commerical Comms too low - make like Geo Weather except more since payload is higher.
- [x] move Proc Battery to orphans
- [x] Downrange Milestone (3000km downrange,  Required for First Orbit. Pays 1.5x Karman, albeit split more like 2:4 instead of 1:5 advance/reward)
- [x] check science payouts
- [x] Non-Earth contracts have wrong payouts after recoveryValue changes
- [x] Fix balance between biome, non-biome science
- [x] Procedural Avionics Booster earlyAvionics partupgrade in wrong place
- [x] Verify new science / [x] Science
- [ ] Rebalance probe prices
- [x] Add IP/hibernate options to early upper proc avionics at high cost

**Comment by pap1723** [comment]
Updated, almost complete!

**Comment by NathanKell** [comment]
I need to check science payouts this weekend.

**Comment by leudaimon** [comment]
Some things I found playtesting for the race:
* Lunar contracts have higher payout than before, probably some issue with the change to the 100% multiplier.
* Micrometeorite seems to have too low science, even compared with the Thermometer/Barometer. It's a sat science tier experiment, could pay more.
* The icon for procedural "early avionics" booster in the tech tree is in the wrong node - it's in basic avionics and probes
* I think the early tv camera is bugged (not sure if the issue is with the part or more general with the science changes + [x] Science!). The first time I runned it, I'm sure it gave me 0.5 science, but in the other biomes it started giving 5.4 and I couldn't run it mannually - it said "no more samples can be collected"
* The First Nav Sat payload requirement is higher than Early Nav Sat, at 100. It is much higher than all other contracts available around this time, which makes me think it is a mistake.

**Comment by NathanKell** [comment]
@siimav what @leudaimon describes sounds like the DMOS interop code only ran the first time?

**Comment by Rockstar04** [comment]
What needs to be done for rebalancing probe prices? Is this to adjust for the science modules being removed from them?

https://github.com/KSP-RO/RP-0/commit/cef66f75dde19ee6d665bbb51e9dd9f3bc0070be

**Comment by pap1723** [comment]
Yes

**Comment by leudaimon** [comment]
I would say new science/[x] science! is working as intended right now. I tested it thoroughly yesterday. I will now fix the misplacement of the booster upgrade icon.

**Comment by siimav** [comment]
Updated version of [x] Science! is available [here.](https://github.com/siimav/KSP-X-Science/releases/tag/5.17-RP1v2) It should hopefully fix most of the issues with the new DMagic science system.

**Comment by leudaimon** [comment]
I rebalanced the cost on the 20in core and the Explorer 1 (and also the misplaced icon). Did we ever balance the prices of other probe cores with experiments for them to need rebalancing?

**Comment by pap1723** [comment]
We did not @leudaimon

**Comment by leudaimon** [comment]
Good, so I guess that is done ;)

**Comment by pap1723** [comment]
Wait, I think I misread the question, lolz

If the probes were accurately priced to begin with (I don't know if they were) based on real data, then they would be priced with the experiments included. I would say that we balance them to the costs of the similar probe cores that are unlocked at the time.

**Comment by leudaimon** [comment]
Yeah, my question was if they had real world cost to begin with. As the RN probes need also tech tree rebalancing, I guess we are kind of fine for now... I may try to fix some other probes if I get some time over the weekend though

**Comment by pap1723** [comment]
Orphan SSTU solids

**Comment by leudaimon** [comment]
`Add IP/hibernate options to early upper proc avionics at high cost`
Should be sorted by #1054
