### ISSUE TITLE
Nuclear engines are inexpensive

### ISSUE THREAD

**Issue by winged7** [KSP-RO/RP-0#1026]
Nuclear engines from Bornholio Nuclear mod are roughly 20-50x cheaper than stock/SXT ones. Is there any logic behind it?

**Comment by Bornholio** [comment]
take the 1.4B$ (2000 dollars of the rover program cost, divide by output power to find cost per engine, 
this gives the known per MW power of those, then multiply times engine power.  This is part cost, divide by 20 for VAB cost.  Notice also they have High rollout tag costs

**Comment by pap1723** [comment]
@Bornholio so yours are properly costed? I would have assumed you did.

What would you recommend for NERVA I and NERVA II?

**Comment by Bornholio** [comment]
NERVA I should be just a bit more than NERVA XE, but the stats are from '63 paper studies. Maybe it should ECN to the end of XE chain
![](https://cdn.discordapp.com/attachments/329685702247841792/550473274279067681/unknown.png)

**Comment by pap1723** [comment]
Addressed with https://github.com/KSP-RO/RP-0/commit/b673e3217b459478ce034104268ae280c13606b4

**Comment by pap1723** [comment]
After some conversation with @raidernick and tylerraiz, questions were raised about the cost of nuclear engines again...

**Comment by Bornholio** [comment]
I have very little time right now but i'll post research and ancedotes as i get a spare moment.  I'll also redo the spreadsheet i can't find that does all the money converting. ![](https://i.imgur.com/SKXRUeM.png)

**Comment by Bornholio** [comment]
![](https://i.imgur.com/OBIBXCh.png)  the SNTP did include costs of fuel and AES/DOE nuclear agency expenditures.

**Comment by pap1723** [comment]
Added the Turbopump tag to each engine with https://github.com/KSP-RO/RP-0/commit/d466327f3b34a4b9ea28d57610deaa47057c1e50
