### ISSUE TITLE
Place reaction wheels in RP-0 tree

### ISSUE THREAD

**Issue by pjf** [KSP-RO/RP-0#103]
The RemoteTech flight computer is *very* inefficient when it comes to RCS, and will burn oodles of fuel trying to keep the craft pointed in the desired direction. I suspect that kOS and potentially even MechJeb are the same. Given that we want to support players using RemoteTech (especially with signal delay on), this is a note to make sure we properly place and cost reaction wheels in the tech tree.

I know that real reaction wheels aren't very powerful, and need to be "spun down" if they build up too much momentum, but the RCS pain that RemoteTech experiences is such that it impacts on desired gameplay. If reaction wheels are used for fine-tuning heading (which they would be with RemoteTech) then this feels like an appropriate use of technology.

While I'd prefer reaction wheels to unlock at the same point for everyone, I'm happy with conditional staement which have them unlock early iff we discover the player has RemoteTech is installed, and later in the tree otherwise.

`advSasModule` currently unlocks in Advanced Flight Control, which feels right.

**Comment by NathanKell** [comment]
Also we can ask them to look into improving their PID controller; MJ's does not have the issues RT's does.

**Comment by jwvanderbeck** [comment]
Yeah I don't have any major problems with RCS using MJ.  Never used RTs
computer because its completely incomprehensible to me.  kOS generally
works fine for me but then I have a lot more control.  I also generally
tend not to instruct anything to **hold** an attitude very often, except of
course during burns.

Frankly i'm against changing gameplay to address deficiencies in other mods
though.  By that logic you should never use EngineIgnitor because MJ kills
your thrust and loses your stage.  By that logic we should add verniers
earlier in the tech tree because MJ and kOS (and presumably RT as well)
absolutely suck at flying ascents that don't have solid roll control.

That said I'm not against some tweakage with things like *placement* of
reaction wheels but I am against making them more powerful.  I wonder how
hard it would be to make a plugin to simulate spin-down of gyros?

- John Vanderbeck
- http://www.johnvanderbeck.com

**Comment by pjf** [comment]
> I am against making them more powerful.

I've actually done the reverse. The old small reaction wheel provided 0.5kNm of torque, which we've reduced to 0.1kNm. However even 0.1kNm is a *lot* compared to actual reaction wheels that I've found specs for (the largest of which was 0.028kNm). The radial wheel in RO is also hugely overpowered, providing a whopping 1kNm of torque.

I just popped a 0.5kNm wheel on a 1.2t craft, and it was able to turn on a dime, so I'd argue that our existing RO wheels are way overpowered. (The ones in stock, of course, are ludicrous.)

Reaction wheels are perfect for both gameplay and realism for providing *fine* attitude control. So I'll be submitting a PR to RO which nerfs everything down to more realistic levels.

I'm struggling to find good price information on reaction wheels, though.

**Comment by pjf** [comment]
It also looks like tweakscale scales the cost of wheels by the cube of their size, but I don't know if it scales the torque by the same amount. Since one can simply stack wheels on top of each other to provide more torque (10 x 0.01kNm wheels is the same as 1 x 0.1kNm wheel), torque and cost *should* scale linearly. I've not played with TweakScale's in anger, so I have no idea if that's easy or hard.

(This also means the "advanced" wheels can cost less per unit torque, to represent improvements in manufacturing processes, etc.)

**Comment by NathanKell** [comment]
Sadly, for things except fuel tanks and structural pieces, tweakscale is a right mess. Setting up dedicated scale types with their own scale exponents isn't that hard, but it is a bit tedious.

**Comment by jwvanderbeck** [comment]
That is odd.  I thought RO had nerfed reaction wheels down to realistic
settings.

- John Vanderbeck
- http://www.johnvanderbeck.com

**Comment by NathanKell** [comment]
We nerfed them, but since I didn't know what KSP's units *were*, I didn't know how far to nerf them. If KSP's units are in fact kNm (as seems likely, but one never knows) then they should indeed be lower.

**Comment by pjf** [comment]
The [KSP wiki](http://wiki.kerbalspaceprogram.com/wiki/SAS) suggests kNm, and their performance certainly feels in-line with this.

**Comment by NathanKell** [comment]
That would make sense given the units KSP uses, but I haven't dug enough in that part of the code to know.

**Comment by pjf** [comment]
*Back of the envelope calculations ahead, but citations are included.*

The ISS uses four Control Moment Gyros (plus two spares) each of which weighs 272kg and provides a maximum torque of [258 Nm](http://www.esmats.eu/amspapers/pastpapers/pdfs/2010/gurrisi.pdf), so a naive (stacked unit) CMG providing 1kNm of torque should be weighing about a tonne.

In terms of power consumption, a reaction wheel providing 0.1Nm of torque looks like it would require about 150W of power, and 1Nm would require upwards of 500W. Hence a 0.1kNm wheel would require... 50kW of power if we're sticking 1Nm wheels, or 8kW of power if we're somehow imagining we can increase wheel momentum high enough to gain higher power efficiencies, and power costs roughly quadruple for each order or magnitude increase.

A 0.1Nm CMG could be made to run off a mere 10W, and 1Nm would require about 25W. Assuming a 2.5-fold increase in power per order of magnitude, a 0.1kNm CMG would require about 160W.

For RO/RP-0, I suggest the early parts be reaction wheels; they're cheap to buidl, but expensive to run (power-wise) and provide low torque. Later-stage parts can be CMGs, they're more expensive to build, but require much less power for what they do, and can provide higher torques.

Since stock also provides radial reaction wheels, I suggest we clone the part so there are both early (reaction wheel) and late (CMG) versions with different stats.

Additional reading:

* [Reaction wheels and CMGs power costs.](http://digitalcommons.usu.edu/cgi/viewcontent.cgi?article=1080&context=smallsat)
* [Further stats on the ISS CMGs](http://www.boeing.com/assets/pdf/defense-space/space/spacestation/systems/docs/ISS%20Motion%20Control%20System.pdf).

**Comment by NathanKell** [comment]
Thanks for digging into this! Looks like our wheels are indeed *way* overpowered...

**Comment by NathanKell** [comment]
Opened an issue on RO, where the last bits belong. https://github.com/KSP-RO/RealismOverhaul/issues/197
