### ISSUE TITLE
Procedural Avionics explode at high time warp

### ISSUE THREAD

**Issue by thesciencenut** [KSP-RO/RP-0#1032]
It seems as if the current max temperature setting of 500k is too low. 

This seems to occur when any heat generating parts are active and larger radiators seem to have a very minimal effect to help. 

The setting of 520k for the guidance rings and other avionics packages seems to work fine, though the temperature gauge will still pop up.

**Comment by pap1723** [comment]
Fixed with https://github.com/KSP-RO/RP-0/commit/e08570ddca2bc93e41c3753e0dbc9bbf7ce1d9e4
