### ISSUE TITLE
Smart Parts Fuel Dumps

### ISSUE THREAD

**Issue by Rockstar04** [KSP-RO/RP-0#1042]
The commit dbfbd01de45f84fbf3dcbad817f768b358f675f5 orphaned the fuel vent parts with the commit message "I do not think this is something that is possible", not only are fuel vents possible, they are even mandated in some cases. https://ntrs.nasa.gov/archive/nasa/casi.ntrs.nasa.gov/20130000278.pdf

Page 11, Section 30.4.1 "Propulsion System Passivation"

**Comment by thesciencenut** [comment]
Yup, plus they are used all of the time on aircraft

**Comment by pap1723** [comment]
I concur. Fixed with https://github.com/KSP-RO/RP-0/commit/b9880c052366543fde9d24475778b41b3c6d8ab5
