### ISSUE TITLE
Heatshield decoupler size "gap"

### ISSUE THREAD

**Issue by jonassm** [KSP-RO/RP-0#1045]
With TweakScale the heatshield decouplers (the generic ones) only scale up to 2.5m. The next level up, the one made specifically made for the bigger stock style pod, is about 4.3m. This means there is a "gap" in the size between 2.5 to 4.3 (and above i guess)

**Comment by pap1723** [comment]
@jonassm TweakScale is not supported (in fact, it is very much dissuaded to use it) as it breaks functionality with FAR. We recommend that you use the Procedural Parts decoupler.

**Comment by jonassm** [comment]
> 
> 
> @jonassm TweakScale is not supported (in fact, it is very much dissuaded to use it) as it breaks functionality with FAR. We recommend that you use the Procedural Parts decoupler.

oh boy! my bad

**Comment by NathanKell** [comment]
Actually best use proc interstage with non decoupling fairing sides (the
gray interstage ones). That will work almost exactly like the heat shield
decoupler in terms of being concave.

Sent by my thumbs, slowly.
