### ISSUE TITLE
Downrange contracts show DEBUG info

### ISSUE THREAD

**Issue by gamer-rp1** [KSP-RO/RP-0#1048]
"Downrange Distance LV Development" contracts are showing their DEBUG info (noticed on both "Intermediate" and "Difficult" contracts).

![DEBUG](https://user-images.githubusercontent.com/47701718/54077869-9b91b280-4312-11e9-8b27-8e32d8771a81.png)

**Comment by pap1723** [comment]
Fixed with https://github.com/KSP-RO/RP-0/commit/529c7a41d995da670f637a78c7bb7545ede9b03d
