### ISSUE TITLE
Suggested change to the Agena Avionics

### ISSUE THREAD

**Issue by leudaimon** [KSP-RO/RP-0#1053]
@NathanKell, me and @pap1723 were discussing the fact the Agena avionics is very unbalanced in its current tech node - compared to procedural avionics and to all other avionics then available.

We think splitting it into two separate parts might be worthwhile. The current part would be moved into a later node (around Gemini era), probably with a bit higher price, and in basic avionics and probes we could have a part with the same mass and tonnage, but unable to be shut down, and with Interplanetary = False. 

What do you think?

**Comment by NathanKell** [comment]
The only reason proc avionics of that era doesn't support hibernation and interplanetary is that it would require making those optional (and having a big cost increase for them). However...does proc avionics require you to only have 1 choice per tech level? For a few tech levels we could have two options, cheap and expensive, and you could choose which.

In particular I definitely felt (and feel) that interplanetary should be an option from 1960 on, as should hibernation. Certainly the existing Agena shouldn't be nerfed much--that's the point of Delta, and Centaur unlocks at the era you're talking about and it's Agena but even better!

**Comment by NathanKell** [comment]
It looks like Agena A never stayed in orbit longer than a day or two, so maybe we can remove hibernation from it and have a quick followup guidance unlock in 1961 that does hibernate. Maybe same with interplanetary, but then--what's the difference between it and Delta? And certainly it's the case we should support interplanetary before Centaur.

**Comment by pap1723** [comment]
@NathanKell I would think there is no reason a second proc avionics option cannot unlock in teh same node. It should work perfectly fine. All it checks is if the node is unlocked. Doesn't care if there is anything else there.

**Comment by NathanKell** [comment]
Awesome then that's the fix IMO. Maybe need to bump up Agena's cost too, or push it 1 node back and call it Agena B.

**Comment by NathanKell** [comment]
Not or, and. Definitely should increase its price, 800 is too cheap.

**Comment by leudaimon** [comment]
Yeah, 800 is probably the cost of the current proc + 40k EC battery

**Comment by leudaimon** [comment]
So let me get this straight (@pap1723 and @NathanKell):

* We add an additional interplanetary (also hibernating?) upper avionics starting in basic avionics, and keep two types of uppers - one expensive hibernating interplanetary, other cheap, non-hibernating, non-interplanetary. Do these have different tonnage ratios too?

* What happens with the probe cores? They currently have higher cost and energy usage per ton than uppers, if we have uppers that are interplanetary and hibernating their use gets limited only by situations where you want a light probe (where minimum tonnage is relevant).

I can make the configs for the uppers if you agree with that plan of action. 
Also, people are reporting the huge spike in energy consumption from lunar era to space station era. This is because NK changed the configs to work with kW instead of W (and also lowered consumption overall), but changed values only up to TL4. I can divide everything by 1000, but it will still need to be lowered further.

**Comment by Schnobs** [comment]
Hibernation is for when your probe temporarily wanders off into deep space beyond where the solar panels will work (Rosetta), or when you have a battery-powered reconnaissance satellite and don't want to expose all film in one session (Corona). The latter is how our Agena first leaned that trick. I've always doubted whether it was reasonable and realistic to extend that ability to most every probe core.

I also don't know how Agena re-gained it's bearings on 1960 tech. Being in LEO and having a horizon to work with probably helped.

From what I know about the Rangers and Mariners and so on, the concept of hibernation simply doesn't apply. They kept their star trackers pointed at Sun & Canopus unless and until the mission called for another attitude (maneuvers, pointing sensors), and were sending telemetry data all the time.

**Comment by pap1723** [comment]
This was addressed and fixed with the recent round of Procedural Avionics fixes.
