### ISSUE TITLE
Feedback / Observations - First 3 years RP-1.0

### ISSUE THREAD

**Issue by MatBailie** [KSP-RO/RP-0#1056]
### RP-1 Experiences & Observations

**My story so far...**

The early game appeared to be dominated by racing for funds, which you can invest back in to being able to get more funds more quickly...
- Complete a contract
- Invest in build points
- Next contract can be completed more quickly

In effect playing out like a compound interest game.  The more you can earn, the faster you can earn even more.
- Was it Einstein that said compound interest is the most powerful force in the universe?

In my current play through:
- I'm at Year 3 Day 246
- Purchased 156 KCT Upgrade Points
- Unlocked Level 4 of the Launch Pad
- Unlocked Level 2 of Mission Control, Tracking Station and Astronaut Complex
- Completed 100+ sounding rocket contracts
- But completed very little else, and not made any particular effort to chase science
- To advance quickly all I needed was sounding rockets, they were the most efficient way forward

Maybe it's a quirk of the game being too simplistic, but I even reached 10,000km just with spin stabilisation from winglets during launch, so I never needed avionics, etc for any active control.  Also, even with triple RD103 and Quintuple AJ10-27, launches didn't fail enough to make me stop addind Moar Engines.  I even learned the best timing for hot-staging to minimise part counts and stage masses.
- Together these facts meant that I was never under much pressure to climb the tech tree

To begin with all of that felt good.  Very good.  Working out how to make the cheapest, simplest, lightest rockets that could complete the Sounding Rocket (Difficult) contracts.  Balancing when to invest in R&D Upgrade Points against the juicy compound interest of VAB Upgrade Points.  Predicting when I'd need a bigger launch pad.  It was a game of optimisations, and I get the feeling a lot of Realistic Progression players enjoy optimisation puzzles.

After 50 sounding rocket contracts it became a little grindy.  Then a little tedious.  And then boring.

By the 100th sounding rocket contract I started to lose interest.  I gave up my game of min-max optimisations and just pumped cash in to R&D Upgrade Points and warped to the next tech.  I could have done the Lunar Impactor contract, but my interest in getting things done "optimally"/"early" had lapsed.  Instead my optimisation game had become minimising the number of launches I needed.  Effectively optimising for "without having to play as much".

**Observations on experienced mechanics**

Tooling and Rushing builds
- Cash wasn't my limiting resource, time was
- It was very rare for me to not Tool or not Rush
- Even "inefficient" of cash was worth it
- Saving time earned kredits more quickly, which I re-invested in earning more kredits more quickly
- The rules of compound interest dominated almost every other consideration

Sounding Rocket contract "reverting" to easier levels
- If I couldn't complete a Sounding Rocket (Difficult) I did Sounding Rocket (Altitude)
- Eventually the Sounding Rocket (Difficult) lapsed and refreshed, and it was easier again
- Letting me earn silly money again
- This is great as a "Safety" mechanic; always being able to do Something, always being able to earn kredits
- It also de-incentivised early investment in Science and the Launch Pad

Sounding Rocket (Difficult) reward insanely high
- At one point I earned 194k kredits per launch, taking 12 days to build (7 days after rushing)
- The hardest Altitude contract only netted me 30k kredits
- Later satellite contracts only earned me 36k - 66k kredits

Sounding Rocker Rewards inversely proportional to Tech Level
- As tech level increased, the Sounding Rocket Reward decreased
- That incentivised me to delay tech levels as long as possible
- Unlocking them "just in time" for when they were needed
- And they were only needed for the next step up in completeing sounding rockets...

Rollout costs
- Were always less than the GUI said they would be

First Artificial Satellite
- Advance of 504k kredits, with an allowance of 2 years
- I just took it, invested the cash, massively ramping up production speeds
- Under a year later my Sounding Rockets had more than 10k dV
- My ability to put a satellite in orbit was incidental to completing Sounding Rocket contracts

Planning vehicles and tooled parts for future contracts was a pain
- I never had a clear idea of what would be expected from me after This contract
- Sometimes a light payload with a high altitude
- Sometimes a heavy payload with a lower altitude
- Felt very arbitrary and fake

**Brainstorm Ideas / Flights of Fancy**

Keep the balance, just with fewer launches?
- Double the build time for all vessels
- Double the rewards from all contracts (or just repeatable contracts?)

ATTACK (limit) the benefit of compound interest when investing in build points

- Rewarding skills is good
- Compound Interest is almost inherent to KCT's design
- Change contract behaviour somehow to incentivise other considerations?
- Limit how often contracts can be taken / completed?
   - If you can't complete more than one contract a month, building two vessels a month is pointless
   - Effectively a hard cap on the supply of contract reward funds?
   - Incentivising racing to opening the next set of contracts, so they can be "mined" too.
   - Contracts have a timer, while the results are analysed?

- Maximum reward gated by something other than your previous achievement
   - At present completing a contract unlocks a more lucrative contract
   - Thus, completing contracts faster increases the rewards faster
   - If the max reward is tied to unlocked science, for example, you have to divide your investment
   - Perhaps unlocking "Post war materials science" could unlock "Sounding Payload Version 2", which unlocks higher contract rewards
   - Maybe different payloads for atmosphere, upper atmosphere, space, speed, altitude, temperature, etc
   - Then you can still accelerate through the rewards, but only by also accelerating through the rest of the game too

Rebalance Sounding Rocket contract rewards

- If later satellite contracts rewards 36k+, Sounding Rockets shouldn't be able to reward more than 24k?
   - Then there's an incentive to progress from Sounding Rockets to Satellites as soon as possible
   - With such an incentive there's no need to make the Sounding Rocket reward decay as tech levels increase
   - Which then removes the incentive to slow down tech progression

- Harder Sounding Rocket contracts "feel like" they have a disproportionately high reward
   - In the formula equating difficulty to reward, introduce a limiting factor
   - So the reward grows more slowly (inverse square law, a formula the tends toward a ceiling, etc)

Rework sounding rocket contracts significantly
- One contract with multiple stages (same altitude, varying payload) (same payload, varying altitude) (etc)
   - Easier planning, clearer expectations

- Min altitude, then reward based on the highest payload you achieved
- Min payload, then reward based on the highest altitude you achieved
   - Significant rewards without having to grind through every tier of difficulty
   - Fewer launches, testing you to the limits every time, both reducing repetition

Increase in variety

- Sometimes I change a design just to earn research on an engine I'll need to use later
   - Introduce contracts for that?
   - Gain 2000du while in upper atmopshere / space / etc

- "Run" a sounding rocket "experiment" above X altitude for Y seconds, then transmit
- "Run" a sounding rocket "experiment" above X altitude for Y seconds, then recover
- Reach a certain skin temperature
   - Things to do while waiting for "contracts that are too hard" to lapse and reset to easier levels

Make gaining science less "bursty" (Lots of changes come to mind here, I'll skip most of them as it's so ingrained in KSP / so significant a change)

- I probably did 6 science focussed launches in total
   - New experiment?  Add it to a sounding rocket
   - Reached polar orbit?  Put all your experiments on and gather a ton of science
   - Getting low on science?  You can get a man to sub-orbital now, science And world first income

- If science was gathered more like Test Flight research, it may become more of a focus?
   - The longer you run a thermometer the more data it gathers
   - Takes so long that you need many multiple flights
   - The more data you've gathered, the more slowly it gathers (exponential decay?)

(There's much more to come, but I have to go out...)

**Comment by MikeOnTea** [comment]
Thanks for your detailed report! We have already reworked the early game and the sounding rocket contracts quite a bit as we noticed these issues as well and came to similar conclusions you did.
Hopefully we will have a new release out soon with the changes. For tech savvy people there's also the possibility of getting the latest development version from github to help test changes before release.

**Comment by misiektw** [comment]
I'm playing latest master and Downrange Rockets are not great IMO. It supposed to let you fine-tune launch angle, yet every time payload changes, which makes it pointless as a testing tool.
A better way would be a contract something like: "Make rocket you want with any SoundingPayload, and get a reward based on what you actually launched and how far it flew". Then, after the flight, calculate range*payload and reward credits according to that.
This way you could launch rockets with some specific SoundingPayload, and then later switch it for real payload you want to launch.

**Comment by MatBailie** [comment]
@misiektw 

I agree, the variable payload on these contracts really messes me up.   Especially when one contract could be as low as 50units and the next as high as 2000units.
- changes the flight profile / launch angle required
- has a non-linear (and hard to predict) effect on the distance the launch vehicle is capable of reaching
- makes tooling tanks for the payload frustrating
- if you don't tool the tank it has a disproportionate effect on build Time (early game)

As far as I understand it, however, the calculation for the contract reward has to happen Before the contract is offered, and can't happen after the contract is completed?  Perhaps something similar can happen with optional objectives ("parameters"?) though?

- If the requirement is for 50 units, but you succeed with 100+ units, you get a bonus reward And the next contract offered increases the requirement to 100 units?

- If the requirement is for 100km, but you exceed 150km, you get a bonus reward And the next contract offered increase the requirement to 150km?

This, to my mind has several advantages...

- Avoids randomly fluctuating masses that make configuring the launch angle "painful"

- Removes having Difficult and Intermediate contracts (selecting the Difficult contract and then finding you can't **_quite_** reach it is punitively painful)
- Instead the contracts "advance in difficulty" simply by exceeding the "standard" contract by "enough"

- Allows the player control over how they want to advance
- If they want to increase the distance difficulty, they can aim to achieve that
- If they want to increase the payload difficulty, they can aim to achieve that

The down side is a lack in variability, and so more obvious grind, repeating the exact same contract until you get new tech, launchpad, etc.  But at least during that time you can fine tune your launch angle to see if that can help, etc.  I'd rather that the the current frustrations.  I think...

**Comment by glilienthal** [comment]
I personally like that the contract system doesn't allow you to just optimize how far you fly. I like the challenge of being given a problem in payload, distance/height and figure out how to solve it. Adds excitement.
So, as far as I am concerned: no bonuses and eratically changing sounding payloads.
Just some more documentation on how this works, and what increases difficulty/payload and what doesn't would be cool. (I hope I didn't miss any of that documentation.)

**Comment by misiektw** [comment]
> I personally like that the contract system doesn't allow you to just optimize how far you fly

That's not what this contract description says it supposed be for... And there could be just another variant of contract. Choice is good.
After playing RP0 for n-th time usually there is not much challenge anyway just frustration. And I want to launch those early rockets with as little VAB time as possible.
Wildly different payloads come later with sattelite era and they make sense, as you launching what client wants, but you also have other things to do, if you don't want to grind.

> Just some more documentation on how this works, and what increases difficulty/payload

In current master there are difficulty levels, which increase max payload by 200 up to lvl18. Then it randomizes between 50 and level\*200. After level 18 minimum increases also by 50+25*level.

minimumPayload = @indexAbove18 < 1 ? 50 : 50 + ( 25 * @indexAbove18 )
currentMaxPayload = Min(@baseMaxPayload+((@soundingDifficultyLevel-1)* 200),RP0:payloadMax )
totalPayload = Random( @minimumPayload, @currentMaxPayload )

So range could be wild 50-3600 at levels 1-18, but I think RP0:payloadMax is limiting that, I'm not sure where that variable is calculated.

**Comment by siimav** [comment]
I would prefer to remove the randomness from contracts and cap the max altitude at 1000km and payload amount at 500 units. It doesn't make sense to use orbital-grade rockets to launch SR payloads. It would be better game design to nudge the player towards launching sats into orbit instead of grinding SR contracts. Historically SRs were never used to launch as large payloads at altitudes that our contracts currently require.

**Comment by siimav** [comment]
Thanks for the feedback. Closing this issue as a lot of the points have already been solved in the latest release or 2.
