### ISSUE TITLE
Feedback / Observations - Master vs Release

### ISSUE THREAD

**Issue by gamer-rp1** [KSP-RO/RP-0#1057]
New player here...started a few games with the Release version, then started a few more with Master. Just a few comments on how I see the differences in the (very!) early game. See attached spreadsheet for the numbers and more comments.

- **Science**: Master gives less Science, but more Funds. So I ended up buying Upgrade Points with Funds, instead of using Science to unlock TechTree nodes (that I probably didn't want just yet anyway) simply to get Upgrade Points.

- **Build Times**: Master starts out building rockets much more slowly, but it gets faster with upgrades. Release starts out with faster build times, but improves only slowly. By about 3 or 4 upgrade points Master has caught up and can build Aerobees just as fast as Release. Build times for actual rockets seem to be calculated differently, because even at the same rate (eg. 0.05 starting rate) Aerobee is much faster to build in Release than in Master.

- **R&D**: Master starts out very slow, and doesn't catch up until about 6 Upgrade Points have been spent. In Master the first four nodes each take 365 days, so to research them all (without doing any upgrades) will take 4 years game time.

- **Reward Rate (Contracts):** Master seems to give more funds rewards for Contracts, although individual contracts may vary.

- **Reward Rate (Milestones):** Master consistently gives much more funds for Milestones...more than double what Release gives.

**My Reflections:** I really like the way the game mimics the real-life history, congratulations on all the work put in so far, please don't stop! My approach will be to try and use 'real' parts as far as possible, and to manipulate the Reward Rates so I can buy enough Upgrade Points to make TechTree nodes unlock at historically accurate times. I want to re-live the space race! I remember going to my neighbour's place when I was a kid and trying to see Sputnik...I don't remember of we saw it or not. And my university suspended classes so we could watch Armstrong walk on the moon, which they displayed on screens all around campus. Anyway, good work everyone, and thanks.

[CareerRP Master vs Release Compare.xlsx](https://github.com/KSP-RO/RP-0/files/2974703/CareerRP.Master.vs.Release.Compare.xlsx)

**Comment by siimav** [comment]
The latest release should make it a bit easier to keep up with historical dates.
