### ISSUE TITLE
Feature suggestion At attitude launches for x-planes. or small rockets.

### ISSUE THREAD

**Issue by karlack26** [KSP-RO/RP-0#1059]
To overcome the the limitations of the weird wheels and runway bugs. Along with how building your own mother ship  and Launching your test craft is kinda of pain to do with how KSP works.  Plus this could also be great  the new downrange contracts for rockets. 
How about adding a alternate option to launch crafts at Altitude. 

This option would be tiered like the launch pads or the current runway. 
So we could set the limitations of how high and how heavy of a payload you can launch and the costs based on the large  aircraft available at the time. 
 So say lets  Tier one would be a B-29. This would have the option  to launch the craft at the max altitude of 10000m that weighs 3 tons  and  at x distance up range from your space center(example numbers but we could find the real world specs for these). 
X-planes or your small rocket would then would load at those specified  locations at the max speed of the mother ship. 
Roll out time would be based on how long we figure it would take to attach the test craft to the mother ship  get airborne and into potions
We can find the cost for operating these large planes and factor those into the upkeep and roll out costs.
 Now my understanding on the internal workings of KSP and the KCT are about 0 so how feasible this from a coding perspective i do not know. 
Any who thx for all your great work. 

PS PaP i am close to being done those configs for Niche Parts engines  :P You should see that pull request soon for RO-engines. :P

**Comment by siimav** [comment]
And it's done. Short video demonstration about it can be seen here: https://drive.google.com/open?id=1lt91tA-r3y1QaWFr3AA1forCAv8h-tQn
For testing you would need to download the master branch of RP-1 and TEST branch of KCT.

**Comment by karlack26** [comment]
Oh cool thx. No one showed any interest in this idea so what a surprise to see this in my email this morning. Will see if I have time to get a current rp-1 install up and running. Have not played for some time and I only have 1.3 install on my system.

**Comment by Rockstar04** [comment]
That is incredibly cool @siimav ! I may actually launch some planes in RP-1 when that hits master.

**Comment by siimav** [comment]
It already **is** on RP-1 master. It's just the KCT that needs to be downloaded from here: https://github.com/KSP-RO/KCT/tree/TEST

**Comment by pap1723** [comment]
Can we close @siimav ?

**Comment by siimav** [comment]
Might as well. It isn't officially out yet but the beta version has been available for a while.
