### ISSUE TITLE
Compile NoMoreGrind into RP-0

### ISSUE THREAD

**Issue by pjf** [KSP-RO/RP-0#106]
As per KSP-CKAN/CKAN-meta#292, we provide NoMoreGrind configs, but getting them to install nicely with the CKAN is tricky, as they try to overwrite existing files.

Given that the NoMoreGrind source is tiny, and @AlexanderDzhoganov has released it into the public domain and encouraged us to compile it into RP-0, I suggest we do exactly that.

However I'd like to tweak the code so that rather than reading a fixed filename for config, we instead query a ConfigNode. This means we can eliminate the NoMoreGrind directory from RP-0, players and modders can use ModuleManager to adjust the settings, and peace will be restored to the universe.

**Comment by NathanKell** [comment]
You can steal the code from, say, RealSolarSystem (CameraFixer.cs is short, so the relevant code is easy to find).
https://github.com/NathanKell/RealSolarSystem/blob/master/Source/CameraFixer.cs#L41-L43 gets the configNode; then you can HasValue and GetValue to get all the values (TryGetValue is an extension method Chris wrote; it's not a stock method).

**Comment by pjf** [comment]
Thank you! :)

**Comment by NathanKell** [comment]
@pjf, anything come of this?

**Comment by pjf** [comment]
Alas no. My workload turned into a mountain and I'm trying to catch up with all RP-0 things again now.

**Comment by Bornholio** [comment]
we have no more grind as default now, should close this.
