### ISSUE TITLE
Early Weather and Test Communications satellites balance

### ISSUE THREAD

**Issue by leudaimon** [KSP-RO/RP-0#1069]
The payout from these two contracts seems off.
Both are available around the same time and have very similar payouts, but the Weather sats are much easier than the communications ones.

**Comment by ec429** [comment]
Early Weather requires control, either of the payload or of a trim stage, to get the specified orbit.  (You can probably do it by split-second shutdown of an ordinary upper stage, but that _shouldn't_ be possible; big liquids ought to have residual thrust.)
Comms Test has much looser requirements, so can be done with an unguided kick stage.

I think they're roughly equally easy; Comms Test might require a _slightly_ gruntier LV (though not by much), but that's balanced by Early Weather requiring probe avionics.

**Comment by leudaimon** [comment]
I have to disagree... regardless of control, both the payload and orbital parameters requirement is very different:
![screenshot12](https://user-images.githubusercontent.com/16297822/55686430-5092ab80-5961-11e9-8523-a5fb688c14dc.png)
![screenshot11](https://user-images.githubusercontent.com/16297822/55686431-5092ab80-5961-11e9-84fc-46b680147e21.png)

Also, using RCS in an unguided stage to fine-tune apo- and perigee is quite trivial, so I don't think that is very relevant even for the Early Weather, Let alone the fact you don't need probe avionics, as you can complete this with control from your upper stage avionics as a short lived fine-tuning stage. 

The comm test satellite perigee requirement is higher than the apogee for the Early Weather, so even if you do it unguided, it will cost you a lot more delta-v, and require an additional control part in addition to the upper stage.

**Comment by Rockstar04** [comment]
I think the issue would be that you are able to use RCS to fine tune the orbit of an "unguided" stage.

**Comment by marb1** [comment]
I noticed the rewards for the early satellite contracts are all scaled differently, some by amount of payload and others by min Apoapsis.

Maybe payouts for early satellite contracts could all be scaled by payload mass and SMA (or maybe dv from parking orbit)? Then some constants could be added for precision in inclination or eccentricity.

As @leudaimon mentioned above, I think part of the difference in difficulty is that you can get away with launching to 589km and circularizing there, but you wouldn't launch to 819km and then burn for a 4357km Apo so you need an extra stage.

**Comment by siimav** [comment]
All the sat contracts received a tuning in https://github.com/KSP-RO/RP-0/commit/28fed57e2663de4935398697344066049711328a
