### ISSUE TITLE
Price non-pWings to have equivalent cost to pWings.

### ISSUE THREAD

**Issue by pjf** [KSP-RO/RP-0#107]
Do you *really* like making things and comparing them to other things? Gosh, do we have the job for you! In an ideal world, all our wings and control surfaces would have costs equal to their pWing equivalents, rather than being ten spacebucks regardless.

This ticket satisfies @NathanKell's request in #105.

**Comment by aw94** [comment]
If no one else has worked on this yet, I'll take a shot

**Comment by pjf** [comment]
Closed by #145.
