### ISSUE TITLE
Feedback / Observations - Balance and issues

### ISSUE THREAD

**Issue by ctiberious** [KSP-RO/RP-0#1071]
This is my first play through using RP-1 and RO in KSP 1.3.1 and I've come across a number of "issues".  For the most part I've held my tongue on most of them since I know you all are hard at work updating for 1.4.5 and/or 1.6 but there are some nagging things I just felt I needed to comment on.  I should start out saying I'm using CKAN so I've got all the mods that it installs with RO and RP-1 plus a number of part and misc mods.  The two biggie I'll focus with here are FASA (which covers about 95% of the builds I'll be referring to) and SSTU.  I've also got all the RN part mods but I know those aren't priced correctly so I won't go into much on those.

One thing I will say relating to the RN parts before I go to far is, there is a "bug" in the RP0_KCTPresets.cfg file.  If a part is named something like rn_vostok_sc in the part file, when that part gets pulled into KSP, it gets renamed rn.vostok.sc.  Whatever part of KCT reads the RP0_KCTPresets.cfg file is apparently not able to make that change.  So when you have a line that reads, "rn_vostok_sc = 0.1375", that multiplier is not currently being applied because once you're in the game there is no part named "rn_vostok_sc".  So either KCT will have to change the way that file is read or RP-0/RP-1 needs to update the file ahead of time to replace the underscore character with a period.

Ok.  So now to my main reason for this post.  I've worked up the build time of my major launch sites to have 3BP/s.  For most satellite launches, that's actually overkill:
Discoverer 1 - VAB cost 4052, Rollout cost 10131, Build time: 5 days
Explorer 1 - VAB cost 2533, Rollout cost 8122, Build time: 2.5 days
Pioneer 1 - VAB cost 6059, Rollout cost 10602, Build time: 5.5 days
Mariner 4 - VAB cost 10545, Rollout cost 17510, Build time: 12.5 days

But anything with a manned capsule and suddenly the prices and build times become crazy:
Freedom 7 (MR-3) - VAB cost 5021, Rollout cost 21160, Build time: 19+ days
Friendship 7 (MA-6) - VAB cost 6663, Rollout cost 27560, Build time: 19.5 days
Gemini 3 - VAB cost 19602, Rollout cost 44467, Build time: 45+ days
AS-101 - VAB cost: 70732, Rollout cost 172732, Build time: 178.5 days
Mercury capsule - VAB cost 3887, Rollout cost 17805, Build time: 16 days
Gemini capsule - VAB cost 15968, Rollout cost 34524, Build time: 38.5 days
Apollo CSM (minus engine) - VAB cost 29328, Rollout cost 111911, Build time: 134.5 days

I don't have the parts yet for the AS-201 or AS-501 but even the 4 manned rocket types I've built so far really show the issue rather well.  The Mercury capsule all on it's own is 77.5%/58.3% of the total VAB cost for a Mercury Redstone/Atlas.  The Gemini capsule is 81.5% of the GLV.  And the Apollo CSM (minus engine) is 41.5% of the AS-101.  Kind of all over the place but ultimately, maybe not really that much of a concern.
But when we look at rollout costs and build times, it's a completely different story.  The Mercury capsule accounts for 84.1%/64.6% of the rollout cost of the Mercury Restone/Atlas.  Which equates to about 82-84% of the build time.
The Gemini capsule accounts for 77.6% of the rollout cost for the GLV which equates to 85.5% of the build time.
The Apollo CSM accounts for 64.8% of the rollout cost for the AS-101 which equates to 75.4% of the build time.

I get that a manned capsule takes alot.  There's significantly more to building the Gemini or Apollo capsule than there is to building a large fuel tank and engines.  But I have to question if the difference should be as great as we currently have.  I'm not saying that the build times for the capsules is necessarily wrong.  Maybe we should have a BP/s of 7-10 by the time we're in the Apollo era.  But if the Gemini should take 45 days to build, then it shouldn't take 15 days to build a satellite that happens to launch on a Titan 2.
Right now what you end up with is, if you have your launch site setup to launch satellites in a reasonable time frame, (BP/s 1.5-3) then it's going to take ages to build manned rockets.  And if you setup your launch site for manned rockets (BP/3 7-10), your satellite launches are going to be ridiculously fast.  I wouldn't mind manned rockets taking 20%-30% longer .  But 75% longer or worse, just seems extreme.

Lastly, I've noticed some possibly questionable cost issues with some engines.  Most of the engines that I currently have access to (I'm up to 1966) seem to be a few hundred VAB cost.  But a handful of engines are very expensive.  I get that E-1 and XLR99 were basically experimental which may explain their costs.  But the others just don't make a lot of sense.
RL10 (Centaur): 1300
Transtage (Titan 3): 4300
E-1: 1300
Apollo LES: 5000+
XLR99: 1130

The Transtage is laughably expensive considering it's really just a pair of AJ10 (adv) engines which normally cost 300 each.  So apparently the fuel tank, missing rcs thrusters and avionics cost 3700 which seems a bit excessive.  Especially since the rest of the Titan 3A only costs about 3600.

**Comment by MikeOnTea** [comment]
Thanks for your feedback! The next release is about 99 % done and has quite some stuff you mentioned changed and fixed, for example some of the too expensive engines like the E-1 and RL10.
If you're spending so much effort on a detailed feedback report, it might be worthwhile to check the current master version btw, to see what has been worked on and maybe even give feedback on that current status. :)

**Comment by siimav** [comment]
Once again, thanks for the feedback. A lot of the issues that you mentioned should be fixed in the latest release.
