### ISSUE TITLE
Observations : Sounding Contracts - Master Branch

### ISSUE THREAD

**Issue by MatBailie** [KSP-RO/RP-0#1075]
A month ago I had the pleasure of trying RP1.0, the week I had the pleasure of trying the master branch.  I did like the improvements, well done, and thank you.  I have quite a few observations, but this time I'll limit myself to the sounding rocket contracts.

It took me a while to realise that completing the Intermediate difficulty contracts didn't increase the difficulty/reward, and that letting the contracts lapse didn't reduce the difficulty.  I now understand that the intermediate contracts allow grinding of cash if required, and completing difficult contracts increase the difficulty and reward.  But only because I read the contract configuration file.

> So, my first observation is that:
> - it was hard to learn the mechanics of the game I was playing
> - perhaps more explicit notes in the contracts could help?

Being a creature of habit I stuck to the Altitude contracts.  One thing hadn't changed; really wildly varying payload requirements.  I found it hard to predict whether the launch vehicle that I was using would be able to complete the contracts.  I initially mad a flawed assumption; if I had completed a Difficult contract, the same vehicle should be able to complete all of the immediately following Intermediate contracts.  (After all, they're now the same @soundingDifficultyIndex)

> So, my second observation:
> - The scaling formula that translates (Payment, Payload) into (Altitude) under-values the impact of mass
>   - Low mass contracts had the same reward as the high mass contracts
>   - But the Low mass contracts were Much easier to complete

I started collecting data and made a spreadsheet.  It's Open Office, sorry, but Excel should open it too?  (Attached)

Spreadsheet Tab : Altitude Map (Contract Vs Vehicle)
- Shows the altitudes different vehicles I used managed to achieve
- Some include partial engine failures and under-utilised payload tanks (noisy curves)
- Some were done in KRASH and are nice and smooth
- I also added the min and max ranges that the contracts would give
- Cell A1 lets you set the contract's difficulty level
  - It shows that the curves are different
  - The blue line (Altitude 996) is for an RD102, AJ10-27, Tank2 based vehicle
  - The light green bands are the min and max ranges for level 21 contracts (unless you changed it)
  - Up to a payload of about 300 units, the vehicle is fully capable of completing the contracts
  - Up to a payload of about 650 unit, the vehicle can sometimes complete the contracts
  - Over 650 units, the vehicle simply can't loft that mass to the required altitude
  - In fact, to complete the heaviest payloads (still same difficulty) I needed to upgrade...
    - RD102 to RD103
    - Tank2 to Tank3
    - Launch Pad from Level1 to Level2

I don't know if that's intended.  It certainly wasn't what I expected.

> So, my third observation (refining the second):
> - You might not always have the technology to complete the current Intermediate contract
> - Even though you Did have the technology to complete a Difficult contract to reach that difficulty

More than once that go me in to a situation where there were no contracts I could complete and had to let them lapse and "re-roll", hoping for a low payload that I could complete.

That lead me to wonder if there were any other "unusual" properties of the contracts, so I plotted a few of them against each other.

Spreadsheet Tab : Altitude Map (Contracts)
- Shows the range of parameters which can be generated by 6 different levels of difficulty
- Show very significant gaps between level 1 and level 2, and between level 2 and level 3
- Conversely, the level 23 ranges overlap with the level 24 ranges

> So, my fourth observation:
> - Increasing difficulty doesn't always really make things much more difficult (high difficulties)
> - Which can mean getting a higher payout for a contract that's actually easier than the previous difficulty

I set about wondering if there are alternative formulae that I could use instead.  I tried three times, and the third time was a good'un

Spreadsheet Tab : Gravitational Potential
- Same as the first tab, but with my own formula for calculating the target altitude
- Still not quite the same profile curve, but I never really expected it would be
- Is much closer though, and can be tweaked in various different ways
- By and large, avoids most of the "unexpected" behaviours described above

> So, my fifth observation:
> - If it is desired, there are alternative viable formulae available for calculating target altitudes**

Okay, that wasn't an observation, sue me :)

I played a little with the Distance contracts as well, and that has the same behaviours.  I didn't create a spreadsheet of data though (you're glad, right?), but it did make another "feature" of these contracts even more pronounced...
- It's actually Really hard to predict if a vehicle can achieve a contract
- Mass makes a huge difference to the TWR, which has a logarithmic impact
- That has an impact on altitude, which changes gravity, which has an inverse square impact
- On Distance contracts that also impacts the necessary launch angle, an extra degree of complexity
- I could never "reliably" set the launch angle in the VAB either (did I move three "ticks" or four!?)

> So, my Sixth observation:
> - Most of the time it was more prudent just to go with the Altitude contracts
> - Which were plenty lucrative enough anyway

That set me thinking of alternative contract approaches that had the same vehicle capability, design and piloting challenges, and were also less punitive about being wrong when estimating if a vehicle could succeed at the contract.

Prompted by a comment to another thread I opened, I came up with the following concept.
- Instead of Difficult and Intermediate contracts, have one contract with optional parameters.
- If you exceed the optional parameters, then increase the difficulty

For example, the contract may be 100 units to 500km.  There would be an optional target of 750km.  If you reach 500km, then you get your reward as usual, the difficulty doesn't change and the next contract's goal stays at 500km.  If you reach 750km, then you Also increase the difficulty level, causing your next contract(s) to have a target of 750km.

I call those optional target "stretch goals".

While farming / grinding contracts you could tweak the design in an attempt to reach the stretch goal.  Still being (relatively) confident that you'll reach the main goal, and not accidentally locking you in to a contract you don't have the technology to achieve.

Equally, there could be a second stretch goal.  In the example the target was to be reached with 100 units of payload, so the second stretch goal could be to achieve that with 150 units instead.  If you did manage that, then the required payload of the next contracts(s) would be increased to 150 units.

I'm confident something along those lines can be made to work in contract configurator using optional parameters.

- Let's the player push the difficulty up at their own pace
- Can allow mass and/or altitude and/or distance to be incremented separately
- Removes a certain amount of guess work from the grind
- Removes potentially disasterous penalties if you guess wrong
- Keeps Payouts (income) ties to vehicle capability (player's design and piloting ability)

- Also risks increasing the number of times you might fly the Exact same contract...

I'm nearly as tired writing this as you are reading this.  I'm amazed you got this far.  I'll add other comments tomorrow.

If you did read all of that, in particular the suggestion about contracts with Stretch Goals, please give me your feedback?  (Good, bad, or ugly)

If it's well enough received I can put together a sample contract file to test and validate the idea works, achieves it's goals, and doesn't make things worse.

If it's not well received, I hope you give enough information why that I can pontificate on other ideas to make things less grindy, less guessy, equally challenging, and more fun :)

[KSP Altitude Calculations.xlsx](https://github.com/KSP-RO/RP-0/files/3101716/KSP.Altitude.Calculations.xlsx)

Or Google Docs: https://docs.google.com/spreadsheets/d/1KhgWYdjl9YYfgia2Cixj9zMDrI7IgCUPkT5eewmLLqY/edit?usp=sharing

**Comment by MatBailie** [comment]
Another observation tangentially related to Sounding Rocket contracts...

Completing the First Artificial Satellite contract can happen "too early".
- I got bored of sounding rockets and so did the Satellite contract.
- But I don't have the tech for solar panels, or cosmic ray detection.
- My progress is now blocked, and there are no "grind" contracts to do
- I can't launch aircraft from the runway
- My progress is blocked until I unlock solar panels

My poor Kerbals will just have to sit idle for 9 months

**Comment by kurgut** [comment]
yeah, if you decide do to it early on, then you have to plan ahead to avoid  those kind of situations: eg, carefully choosing which tech you unlock.
and build points invest/distribution in vab and R&D.
thus, you can do FO veery early, and not being stoped in progress. (see RIS guys reports on discord)

**Comment by MatBailie** [comment]
Google Docs version of three relevant tabs : https://docs.google.com/spreadsheets/d/1KhgWYdjl9YYfgia2Cixj9zMDrI7IgCUPkT5eewmLLqY/edit?usp=sharing

**Comment by MatBailie** [comment]
> 
> 
> yeah, if you decide do to it early on, then you have to plan ahead to avoid those kind of situations: eg, carefully choosing which tech you unlock.
> and build points invest/distribution in vab and R&D.
> thus, you can do FO veery early, and not being stoped in progress. (see RIS guys reports on discord)

I get that, it's just unfortunate that the information needed to make that informed decision isn't available at the time.

You either need to have played through that situation before, or have alternative knowledge about the contract structure (reading config files?)

My perceived ideal situation is that achieving the hardest possible contract can never put you in a worse situation than you were in before, that incentivises you to stretch yourself.  If you can't go beyond that point due to lack of tech or funds, you should still be able to carry on progressing (grinding?) as you were before, or something similar.

In my opinion...

**Comment by IT-kone** [comment]
I had the same problems, I didn't like testing every single vessel for every mission. So I made a sounding rocket with capacity of 1000 sounding payloads, and tested it from 0 to 1000 payloads, with warying angles, and graphed the results. After that, everytime I did a contract, I wrote the results down, increasing the accuracy of the graphs. I found out that for that rocket/type, 5 degrees was the sweet spot. With that graph, I could estimate reliably what I could achieve with that rocket. Here's my Google Sheets if you are interested, Sondaus 4-1+ downrange is the tab you want to check. https://docs.google.com/spreadsheets/d/1mul2GyWfInswolpHaohHkW8mlG8ICfazVMT0adcS770/edit?usp=sharing
(Btw, it would be reaaaly really handy if you could somehow automatically extract the equation of the trendcurve from charts generated in google sheets. Just saying."

How did I know the angle? I have Editor Extensor Redux-mod in KSP, and it has a position debug-screen, that shows the vehicles rotation in quaternions. Very inefficient and complex, but it worked. Here's a converter for quaternions, I suggest using "Euler angles of multiple axis rotations (degrees)", z-units are rotation towards east. https://www.andre-gaschler.com/rotationconverter/

**Comment by pap1723** [comment]
These are all completely different now with how SR's are handled and done.
