### ISSUE TITLE
incorrect info on ion mass spectronomy

### ISSUE THREAD

**Issue by glilienthal** [KSP-RO/RP-0#1076]
Hi, 
I am playing RP-1 master as of about a week ago. 
Just launched my first ion mass spectrometer and found the documentation is contradictory.
https://github.com/KSP-RO/RP-0/wiki/Science#mass-spectrometry says that the results are **0% transmissable**, the part description says "this experiment can only be **transmitted to 50%**" and actually, it transmits 100% of the 25% science it can generate. 

So what is supposed to be true? 

I am happy to create pull requests for the documentations, but what was it supposed to be?  

(I don't have any strong preferences, but I think probably 0% transmission should fit the best.)

**Comment by siimav** [comment]
100% transmit for a total of 25% total science is correct. @pap1723 Recently changed it from 50% to 100 because partial transmit values were not working correctly. Unfortunately I can't remember what was the reasoning behind changing it to be transmittable in the first place.

**Comment by glilienthal** [comment]
OK. I'll change the description.

**Comment by pap1723** [comment]
Closed with https://github.com/KSP-RO/RP-0/commit/d17d97f75e3a5a319438c2156e3cd215b54cfd8d. Thanks @glilienthal
