### ISSUE TITLE
Procedural Avionics probe core density too low

### ISSUE THREAD

**Issue by Zantigar** [KSP-RO/RP-0#1081]
In GameData/RP-0/Tree/ProceduralAvionics.cfg, the standardAvionicsDensity of probe cores is only 0.25, much lower than boosters (1.5) or upper stages (1.0).  That results is probe cores that are wildly larger than tech-equivalent built-in parts.  For example, see the attached pic, showing an Early Controllable Core (approx 46cm diameter, 19-20cm tall) atop a first-tech-level procedural probe core that also controls 0.2T (46cm diameter, **1.143m** tall).

![screenshot40](https://user-images.githubusercontent.com/21177521/56863808-f053c000-6988-11e9-933b-d6d12fb6ae11.png)

Unless I'm missing some logical, balance, or historical reason for making the probe cores so large, it seems like a density of 1.5 or so would more closely match the built-in parts.  Or maybe slightly less (say, 1.25) if you want a slight space trade-off for the flexibility of the proc parts for gameplay reasons.  For example, here's the same setup, but with a density of 1.25, resulting in a part that's only slightly taller (at 229mm) than the built-in part.

![screenshot41](https://user-images.githubusercontent.com/21177521/56863959-02366280-698b-11e9-896e-48d22e8f20f2.png)

But 0.25 seems far too low to be useful.  

Also note that other parameters like mass, EC consumption, etc. seem to match the built-in parts just fine.  It's only the size/density of the probe cores.

**Comment by siimav** [comment]
@ppboyle Do you still have that avionics comparison spreadsheet somewhere? Can't remember whether it had size comparisons but I think we should use the same sheet for validating the density values as well.

**Comment by siimav** [comment]
Got the link to the spreadsheet from ppboyle and it already has some size comparisons: [link](https://docs.google.com/spreadsheets/d/1SP5r25o6YzM6PXQsrsRHU5J4t_HYrwIXfUkynJlKv4s/edit#gid=1333724699)

> The column for size comparisons isn't super clear but what it means is that the proc avionics appears (#) x the size of the non-procedural version
So if the value is .2, that means the proc version is 5x smaller than the non-proc version
There is also the issue that I didn't do a real apples -to-apples comparison for the avionics ring stuff, since there's no way to do a torodial proc avionics core.

It seems to confirm your observations of the first TL proc probe avionics being about 6x bigger than the Early Controllable Core. Interestingly based on the spreadsheet, the next TLs are actually smaller than the prefab parts. Can you confirm that this is the case?

**Comment by Zantigar** [comment]
The next TL that contains a proc-avionics upgrade is Interplanetary Probes, which also contains the Ranger I and Mariner built-ins.  The proc avionics are still bigger, but maybe only twice the size.  Here's a shot with the Mariner and the corresponding proc part.

![screenshot42](https://user-images.githubusercontent.com/21177521/56932451-e4afe880-6ab1-11e9-9dcf-2e42cf488d00.png)

The one after that (Mature Avionics) contains the Surveyor Core and the 1T Sat Bus.  Those two have very different densities, as you can see:

![screenshot43](https://user-images.githubusercontent.com/21177521/56932530-2b054780-6ab2-11e9-8637-153bb4712d79.png)

The Surveyor part looks similar in size, or maybe slightly larger than the proc part.  The 1T bus is maybe 2-3x larger than the proc part.  

So...yeah, it would seem that the densities of the built-ins are far from consistent.

**Comment by Zantigar** [comment]
Meanwhile, even the highest-tech-level procedural probe core is still somewhat larger than an equivalent stack of early controllable cores (minimum .35T at that level, so I set it to .4 and used two ECCs as a comparator):

![screenshot44](https://user-images.githubusercontent.com/21177521/56932927-bc28ee00-6ab3-11e9-84c9-eecb630c7a53.png)

So maybe the problem is that the Early Controllable Core is insanely dense?  Or that scaling avionics by volume is not the right approach?

**Comment by pap1723** [comment]
The probe cores also don't compare well size wise. The pre-built ones have a TON more EC storage as well.

**Comment by MaxsimalPD** [comment]
> The probe cores also don't compare well size wise. The pre-built ones have a TON more EC storage as well.

I stripped out the EC from any probe core that let me do it before I gathered numbers btw.

**Comment by MikeOnTea** [comment]
As i'm currently reworking proc avionics, i've looked at density as well, and went with a value of 0.75 so far for every configuration. I got that value by calculating the density of a random dell laptop. Calculating the density of mariner 2, however, i get to around 0.37 even if we assume all the mass is within the hexagon base which is of course not true, so i guess density should even be lower than 0.75, maybe something like 0.5?
Some prefab parts are way too dense it seems, and i think we should fix or remove them in the long run.

**Comment by siimav** [comment]
Should be a lot better now with the proc avionics overhaul
