### ISSUE TITLE
Lunar landing node depends on orbital rocketry

### ISSUE THREAD

**Issue by leudaimon** [KSP-RO/RP-0#1084]
The Lunar Landing node depends on the contemporary Orbital Rocketry node. As the lunar modules and landing legs, as well as the LMAE and LMDE are in this node, it's pretty damaging to soviet careers that focus on staged combustion engines instead of the regular orbital rocketry branch on the tree. Besides, I don't think it makes much sense to require the orbital rocketry branch for that regardless.

**Comment by siimav** [comment]
Changed in https://github.com/KSP-RO/RP-0/commit/061adb7ed5d78e18719fd16ad9283d8dfec7f35a
