### ISSUE TITLE
Make UniversalStorage CO2 wedges more realistic.

### ISSUE THREAD

**Issue by pjf** [KSP-RO/RP-0#109]
Right now the US CO2 wedges say they extract, pressurise, and store CO2.

That's not exactly an easy process. It's certainly not an early-tech process.

Our other CO2 gear uses lithium hydroxide, lithium peroxide, or potassium superoxide to scrub CO2. We should have the US CO2 wedges do the same. (Which probably means +PART'ing them.)

**Comment by NathanKell** [comment]
@pjf That sounds reasonable to me.

**Comment by pap1723** [comment]
The wedges are not configured, but no reason to keep this open.
