### ISSUE TITLE
US_Probes (rn_scansat.cfg) and RP-1 v1.1.1 incompability?!

### ISSUE THREAD

**Issue by JohnMcLane4** [KSP-RO/RP-0#1092]
I made two installs with the new RP-1 v1.1.1 in 1.3.1 and 1.6.1 and if i add US Probepack to the install, the RP-1 contracts disappear. I cant select them in the new game settings and also in existing games no contracts are available anymore.

I deleted the rn_scansat.cfg from rn_us_probes and the contracts are available again.
There seems to be an issue.
The 1.6.1 Log if that helps.
https://drive.google.com/open?id=1seFb7BhtHsZJJ6m7fAMRSJM2JkDKXM-L

Thanks for the great Mod!

**Comment by draqsko** [comment]
As I commented on in the thread, I'm not seeing this in 1.3.1 with a clean install of KSP and RO/RP-1 and a new career. I still have my old career from RP-1 v1.0, I'll give it a go to see if it happens there.

**Comment by draqsko** [comment]
No problems with existing save on 1.3.1 either.

Contracts are there: https://steamuserimages-a.akamaihd.net/ugc/799864653456968565/69BFA062A13481C91258C85DEC67D8E98872E03C/

And while the parts aren't supported by RP-1, they don't show any issues in the info panels: https://steamuserimages-a.akamaihd.net/ugc/799864653456968709/D3FD153E32249BC5CE355DB0FBF9ADAE45B0ACC1/

**Comment by JohnMcLane4** [comment]
I hope its not a common problem than. I just figured i had the problem in 1.3.1 and 1.6.1 with the US Probe pack, something is wrong.
