### ISSUE TITLE
Average biome scan contract not working.

### ISSUE THREAD

**Issue by Jerre122** [KSP-RO/RP-0#1095]
I just noticed the average biome scan contracts don't seem to be working. All the other scan contracts don't show any errors.
![contracts 2](https://user-images.githubusercontent.com/25416174/58491963-437b8700-8170-11e9-8a67-dc23369b90da.png)
![contracts](https://user-images.githubusercontent.com/25416174/58491972-46767780-8170-11e9-850c-0c3ba71d9d0a.png)

**Comment by pap1723** [comment]
Thanks, fixed with https://github.com/KSP-RO/RP-0/commit/8a115901f51adfce4adb6ac0fbdb5af3f5e72e47
