### ISSUE TITLE
RP-0 plugin does not declare dependency on RealFuels plugin

### ISSUE THREAD

**Issue by yump** [KSP-RO/RP-0#1097]
This causes the loading of some classes related to tooling to fail.  On my machine (KSP 1.6.1, Fedora Linux 29) the symptoms include:

- No prompt about crew retirement on starting a new career

- No £ toolbar button

- No tooling button in VAB part action menu

- This message in KSP.log:

>[ERR 00:06:21.162] ADDON BINDER: Cannot resolve assembly: RealFuels, Culture=neutral, PublicKeyToken=null

>[ERR 00:06:21.163] ADDON BINDER: Cannot resolve assembly: RealFuels, Culture=neutral, PublicKeyToken=null

>[ERR 00:06:21.165] AssemblyLoader: Exception loading 'RP-0': System.Reflection.ReflectionTypeLoadException: The classes in the module cannot be loaded.
>  at (wrapper managed-to-native) System.Reflection.Assembly:GetTypes (bool)
>  at System.Reflection.Assembly.GetTypes () [0x00000] in <filename unknown>:0 
>  at AssemblyLoader.LoadAssemblies () [0x00000] in <filename unknown>:0 

>Additional information about this exception:

> System.TypeLoadException: Could not load type 'RP0.ModuleToolingROTanks' from assembly 'RP0, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

> System.TypeLoadException: Could not load type 'RP0.ModuleToolingPTank' from assembly 'RP0, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

Seeing as this wasn't uncovered earlier, it might be a load-order-dependent problem that is only triggered on Linux due to file system differences.

**Comment by siimav** [comment]
When did you last update ROTanks? Was it before https://github.com/KSP-RO/ROTanks/commit/34aa573de8e3156047b802424e5c51f8c1b77dac ?

**Comment by yump** [comment]
The problem occurs without ROTanks present, using CKAN RealFuels as described in [the guide](https://github.com/KSP-RO/RP-0/wiki/Installation-for-1.6.1-(WIP\)).

To be sure, I tried it just now with the current ROTanks and bundled RealFuels.  Same symptoms, same error in the log.
