### ISSUE TITLE
[Question - not bug] Future reliability of control lock name "RP0ControlLocker"

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-RO/RP-0#1101]
The file Avionics/ControlLocker.cs contains this line:
```
 const string lockID = "RP0ControlLocker";
```
This is used as the string ID name of the control lock that RP uses to prevent user input when avionics requirements are not satisfied.

My question is this: Is it safe for another mod (kOS in this case) to presume this input lock name will always be called "RP0" ControlLocker, or will that name change to RP1ControlLocker at some point (and perhaps RP2ControlLocker later, etc.)  I just received a Pull Request for kOS to make kOS respect this lock if present (i.e. make kOS look for a control input called "RP0ControlLocker" and if present, kOS would disable its steering controls.)

(That pull request is here: https://github.com/KSP-KOS/KOS/pull/2546/files )

I was wondering if it was a deliberate decision to continue calling this lock by the name "RP0" for all time, or if it just hasn't been changed (or noticed?) *yet*.

(Better yet, is it possible to request that a name be used that doesn't encode the RP version number inside the name, so it can be left untouched in future versions?)

(You might argue that kOS shouldn't pay attention to *who* made the lock, and instead just obey the fact that the lock says steering is disabled, regardless of whether it comes from RP or someone else - but the problem with that is that RP's reason for the lock is different from most other reasons. Most of the time, a mod locks out the control to represent the player's having no ability to communicate input to the craft (i.e. bad comms).  In that case kOS shouldn't block itself from moving the controls.  But in RP's case, it's because the hydraulics or servos themselves are supposed to be disabled regardless of whether the input to them came from a human or a computer, so in that case kOS should block itself from moving the controls.  Thus kOS needs to reliably know whether the lock is RP's lock or someone else's.)

**Comment by pap1723** [comment]
Thanks for the question! You can feel safe that RP0 will stay that way. RP-1 had initially started as an internal joke, but caught on. Most (all) of our internal MM patches and code still and alw

**Comment by pap1723** [comment]
Sorry, didn't mean to close, mobile issue

**Comment by Dunbaratu** [comment]
Thanks for the info.  I'll call it closed.
