### ISSUE TITLE
DMagicScienceAnimate bundled with RP-0 is for 1.3

### ISSUE THREAD

**Issue by marb1** [KSP-RO/RP-0#1102]
The DMagicScienceAnimate that is in the GameData folder is v0.19 for KSP 1.3.
There is a v0.21 for KSP 1.4-1.6 that should probably go there instead, https://github.com/DMagic1/DMModuleScienceAnimateGeneric/releases/tag/v0.21.

**Comment by siimav** [comment]
https://github.com/KSP-RO/RP-0/commit/8092c35603da49e825f8fb79ec15de6b70a9c555 removed it from gamedata. From now on it should be installed through CKAN.
