### ISSUE TITLE
Auto-recruit bypasses training

### ISSUE THREAD

**Issue by Dunkhan** [KSP-RO/RP-0#1107]
This is only a minor thing, I only found it because I didnt know about the training and thought it was broken so I tried everything.

If there are no trained crews available for a mission that has been rolled out, and the use checks the auto recruit button before clicking the fill button, a new recruit will be placed in the capsule. This recruit will not have the required training but will be able to proceed with the mission anyway.

Also it might be sensible to have a message that informs the user why they cant place the crew in the capsule, it drove me nuts for ages until I learned there was a training mechanic.

**Comment by siimav** [comment]
Disabled Auto-Hire and added a training reminder in https://github.com/KSP-RO/KCT/commit/dcbf25c20590c9be768ae5cfd16442de705c28f9
