### ISSUE TITLE
GuidanceEarly1m is missing the avionics tag

### ISSUE THREAD

**Issue by siimav** [KSP-RO/RP-0#1112]
See: https://github.com/KSP-RO/RP-0/blob/master/GameData/RP-0/Tree/TREE-Parts.cfg#L3676
All the other prefab avioncs parts, including the starting one, have this tag.

**Comment by MikeOnTea** [comment]
It might be that this was intentional to not make the starting avionics so expensive, but yeah it doesn't realyl feel right either to kind of randomly have it not apply there.

**Comment by siimav** [comment]
Thing is that Early and Start avionics parts both have the same cost but Start has the tag but Early does not. It would only make sense if it were the other way around.

**Comment by siimav** [comment]
Fixed in faa9bb9. We decided that all avionics parts should have that tag.
