### ISSUE TITLE
All pWings should cost 0.1

### ISSUE THREAD

**Issue by pjf** [KSP-RO/RP-0#112]
As per #105, it was discovered some pWings had the wrong costs.

```
B9_Aero_Wing_Procedural_TypeA: *stdwing
B9_Aero_Wing_Procedural_TypeB: *stdwing
B9_Aero_Wing_Procedural_TypeC: *stdwing
```

These should all be 0.1.

**Comment by jwvanderbeck** [comment]
Wait i'm confused.  I had costed these parts before.

**Comment by jwvanderbeck** [comment]
hmm ok apparently I only set the costs in the procedural configs, not the tree.
