### ISSUE TITLE
Raise height restriction on the first pad

### ISSUE THREAD

**Issue by nepphhh** [KSP-RO/RP-0#1120]
Currently, the first-level launch pad has a mass limit of 20t and a height limit of 20m. Vanguard was 11t and 23m tall. It should be able to fit on a 20t pad but cannot. Can we raise the height limit to 25m?

**Comment by siimav** [comment]
Sounds good to me

**Comment by lpgagnon** [comment]
20t:25m level1 would seem to make level 2's 60t:30m a little short... Do we know if there was a basis for picking the current values?

**Comment by MikeOnTea** [comment]
I propose to rescale all intermediate pads as well accordingly to have them spaced approximately exponetially. That would result in the following pad height limits: [25, 33, 44, 57, 76, 100]

**Comment by siimav** [comment]
@MikeOnTea I'm OK with those changes. 
For example Falcon 9 v1.0 had a mass of 333t and height of 55m. This wouldn't have fitted on our previous 350t pad but would work perfectly with your changes. I guess this rocket is about as tall as it's reasonable to stretch one.

**Comment by siimav** [comment]
@MikeOnTea did the changes in #1124
