### ISSUE TITLE
RP-1 Sep Integration/KCT changes

### ISSUE THREAD

**Issue by SerinaTsukaya** [KSP-RO/RP-0#1121]
Due to the new change of splitting the build time in the VAB into Build + Integration, I believe it would be prudent to change the VAB build rate from being a local (Per Space Center) To Global to represent that construction of the individual parts can occur at any location in the world, before integration occurs at the space center and then a rollout to the launch pad. This would encourage usage of more than one space center per play through as the cost of increasing the VAB build rate goes down dramatically, Making one only need to build an appropriate pad size. This would also be a step towards realism as most rockets are not built and assembled at the launch site, but instead built in various locations, tested in others, before being somewhat assembled, shipped and finally integrated at the launch site before rollout.

**Comment by nepphhh** [comment]
I disagree. I think committing to a particular VAB is an important part of the RP-1 experience, as each location provides a unique experience. 

As a compromise, I suggest that the **integration** time be dependent on the local VAB rate but the **build** time be dependent on the highest global VAB rate.

**Comment by pap1723** [comment]
This is not going to change anytime soon. It essentially allows for way too much abuse.
