### ISSUE TITLE
Training time for mk1-3pod is zero

### ISSUE THREAD

**Issue by fat-lobyte** [KSP-RO/RP-0#1125]
Hi! It seems that I can instantly do the proficiency and the mission training for the "mk1-3pod". This is probably not intentional.

I would suggest about the same training time as for the Apollo capsule.

**Comment by siimav** [comment]
What's the part internal name for that?

**Comment by fat-lobyte** [comment]
That is the internal part name, `mk1-3pod`

**Comment by fat-lobyte** [comment]
Thanks! That went fast :)
