### ISSUE TITLE
X-15 cockpit has no oxygen, X-1 does

### ISSUE THREAD

**Issue by lpgagnon** [KSP-RO/RP-0#1130]
Currently, the X-1 (Conic Cockpit) is _better_ at crewed-suborbital flights than the X-15 (1.25m Inline Cockpit), because it comes with build-in oxygen, while the X-15 just comes with a ServiceModule tank that has to wait for Human Survivability to load any oxygen.

I tried just adding an oxygen RESOURCE to match the X-1, but it seems something is stripping out all oxygen as soon as a Service Module config is found on the part.

Suggestion: move the 'can load oxygen' tech limitation to an earlier node (something that's already a prerequisite for the X-15 cockpit). No idea if oxygen can be separated from food&water, though.

Alternate suggestions: remove oxygen from X-1; make X-1 kill its pilots above 50km like the prop-plane cockpits; add hardwired oxygen to X-15 in a way that actually works

(arguably an RO issue, but since it's mainly a balance issue with the way RP-0 handles life support, logging against RP-0)

**Comment by nepphhh** [comment]
I like your alternate suggestions far far better. Let's do those.

**Comment by pap1723** [comment]
This is all completed properly, right @siimav ?

**Comment by siimav** [comment]
No, that issue with X-15 oxygen is still there

**Comment by siimav** [comment]
Fixed by defining part of the oxygen as `UNMANAGED_RESOURCE`
