### ISSUE TITLE
Hydrolox AJ-10 config unlocks wrong

### ISSUE THREAD

**Issue by PlasticGuy131** [KSP-RO/RP-0#1132]
The AJ-10-133-LH config for the AJ-10 advanced is unlocked in the "Early Hydrolox Engine (1963)" node, but the AJ-10 advanced is unlocked later, in the "1964 Orbital Rocketry".

**Comment by pap1723** [comment]
I just double checked this, this is proper, as it needs to be unlocked when the AJ10 Advanced is unlocked.

**Comment by nepphhh** [comment]
Why would both the config and the part be unlocked in the 64 Rocketry node?

**Comment by pap1723** [comment]
The AJ10 Advanced is unlocked in regular Orbital Rocketry, the Hydrolox variant is unlocked in the Hydrolox branch. There is no 1964 Hydrolox node.
