### ISSUE TITLE
First EVA contract offered when impossible.  (RP-1 preventing EVA from low tech cockpits)

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-RO/RP-0#1133]
The fact that RP-1 blocks doing EVA from some cockpits that would normally allow it in stock isn't very strongly signposted to the player new to RP-1.  It's one little info box you don't see unless you scroll way down in the description of the cockpit.

But RP-1 is offering the First EVA contract to the player regardless of whether or not the player has unlocked any of the cockpits that allow EVA.  Because of the large penalties for taking a contract then letting it expire, this is an evil trap.  The player thinks, "yes, I can do that contract", then takes it, then finds out only much later when actually trying to do the contract that the cockpit they have won't let them do EVA in space, and that none of the capsule or cockpit parts they have unlocked can do it and there's no time to unlock the tech nodes that would allow it before the contract would expire, so they take the hit of the large penalty for not knowing the contract was literally impossible and should never have been accepted.

Either the contract shouldn't be offered in the first place when it's literally impossible (like how in stock you never see any recover object from orbit contracts until after you have the grabber claw unlocked), or the very important information that "although we are offering this contract you cannot currently do it because none of your crew modules allows EVA" should be well signposted.

Unlike a lot of the other changes RP imposes on stock parts, in this case a stock capability is being *removed* from a stock part that would otherwise have it, so signposting this is vital since not knowing it leads to a 300,000 fund penalty (+600,000 for taking the EVA contract, then -900,000 for being forced to let it expire).

**Comment by zajc3w** [comment]
Second that, just bankrupted due to this.
Basic capsules unlocks first EVA contract when no pod in basic capsules allows EVA's. 
Simply enabling this contract after advanced capsules are unlocked (gemini/voskhod) and when astronaut complex is level 2+ will solve the problem.

**Comment by lpgagnon** [comment]
One vote against hiding the contract behind a tech unlock; it means the player is never told there's a reason to push for that unlock.

Better to just make the contract _say_ what's needed

**Comment by siimav** [comment]
Adding a bold red warning message to the contract description would be the easiest fix. At least then the player will be clearly informed about the limitation and it's their own fault if they fail to understand the warning.

**Comment by siimav** [comment]
936bf7d68e40975ce75a5eb49dec41444d43f368
Now capsules that do not allow EVA show a bold red warning inside the part description.

**Comment by pap1723** [comment]
Fixed with https://github.com/KSP-RO/RP-0/commit/e747261dc089787a21a96731d07651c5aeb829ee
