### ISSUE TITLE
Release for KSP 1.6.1

### ISSUE THREAD

**Issue by siimav** [KSP-RO/RP-0#1135]
#### Required for release:
- [ ] ~SM dewar fix for Service Module tanks,~ @MikeOnTea
- [x] Release minor update for RO, required for unified proc tanks
- [x] Submit SepIntegration PR to LGG and get it released on CKAN (https://github.com/linuxgurugamer/KCT/pull/28)
- [x] Increase the funds multiplier on Normal and Easy presets slightly
- [x] Fix #1112 
- [x] Do something about #1133
- [ ] ~CBK release for KSP 1.6.1 to fix https://github.com/sarbian/CustomBarnKit/issues/7~
- [x] Fix SM-I entry cost for ROTanks

#### Not really required but probably a good idea:
- [x] Implement unified tank stuff for new procedural avionics
- [x] Reduce the cost for starting procedural avionics
- [x] Change the ~mass and~ cost of prefab avionics parts to be similar to procedural avionics of the same tech level
- [x] Reduce the cost of avionics tooling (re-add ECMs for TLs)
- [x] Release ROEngines for KSP 1.6.1
- [x] Release ROTanks for KSP 1.6.1
- [x] Release ROCapsules for KSP 1.6.1
- [ ] ~Changes to RF to get entry costs for tank definitions; unlocked through PartUpgrades in the tech tree (https://github.com/NathanKell/ModularFuelSystem/pull/234 refused; need some completely different approach)~

**Comment by MikeOnTea** [comment]
Just as a reminder, the RO release should contain the SM dewar fix.
Avionics also need the unified tank stuff. Considering the price discussion, depending on when you would want a release i might prefer to just push avionics to the next release.

**Comment by siimav** [comment]
Updated the issue and moved anything related to new procedural avionics to the optional category. For the proc avionics we could also release them partially - skip the tooling but keep the mass and cost scaling. Moving the avionics level and scaling changes entirely to the next release would mean that people would have to start a new career to not run into issues.

**Comment by MikeOnTea** [comment]
Don't think a partial release is a good idea either, regarding using avionics for cheap SM tanks etc.
On the one hand, yeah, not too great to force a new start for the next release. On the other, if we proceed with the facility costs and therefore global contract balance changes, the next release would basically mandate a new start anyway.

**Comment by MikeOnTea** [comment]
#1133 should also be fixed for the next release.

**Comment by siimav** [comment]
Done!
Moved the remaining tasks over to #1087
