### ISSUE TITLE
Cost of Biosample and Film camera parts

### ISSUE THREAD

**Issue by siimav** [KSP-RO/RP-0#1136]
The cost of those parts may be a bit too high for the early game at 250 funds a piece. To make matters worse, some of the next tier experiments like Ion spectrometry and Early Television Camera cost only 100.

**Comment by pap1723** [comment]
I agree. The prices were set before the completely new way that rollout and
build times were done 2 years ago.

**Comment by siimav** [comment]
What do others think - would 100 funds be a fair price for those 2 experiments?
