### ISSUE TITLE
Stuck in VAB

### ISSUE THREAD

**Issue by aihaw** [KSP-RO/RP-0#1139]
Hi! I just installed the whole RSS/RO/RP-1 package with a bunch of recommanded mods following the steps in the guide for 1.6.1. (WIth CKAN everytime I could)
I have a major issue when designing my first rocket in the VAB. As long as I don't palce anything, I can navigate through everything as normal and go back to ksc. But as soon as I place the first part (aerobee simple sounding rocket core), I cant't rotate the camera or move the core. Adding parts won't "stick" them on my core. These cannot be thrown away too but only be put aside with red-ish transparency. At this stage, all I can do is contemplate... Cannot save, cannot exit the VAB, cannot make a new ship...

I looked at the debug everytime I try to make an action the following message appears: NullReferenceException: Object reference not set to an instance of an object.
I tried to tweak something in the debug (I forgot the name) because I saw it on an old (2013-ish) forum reply and it "de-grayed" the exit button for like a half second before showing again the error log, before I can even try to get out. Only solution: alt-F4 the game...

I tried to read the logs but when the error occurs, I don't see mentions of any particular mod in the concerned lines... But as far as I am concerned, I have a nearly to 0 knowledge on coding...
I tried to remove certain mods with no success (ROtanks+textures unlimited, WASD Camera), but honestly I have no clue about which one does the trick.

Another thing (I tell you everything), when I first launched the game, before even seeing this problem, I had a serious warning message from Tweakscale (for the stickers) about save corruption etc. I did not even try to bother and without even launching a new game I quit KSP and deleted the mod.
(Also, my game is in french, but I really don't bother to change to english)

Here's my log, sorry it seems a bit large, and I don't know how to properly clean it.
[KSP.log](https://github.com/KSP-RO/RP-0/files/3709435/KSP.log)

A really big thank you for considering my issue, I really hope someone can tell me what to do.
Aihaw

**Comment by siimav** [comment]
The first issue is that you have 2 versions of ModuleManager. If it still doesn't help, then try removing KOS and KS3P. There might also be something wrong with KCT in your install.

**Comment by aihaw** [comment]
It worked like a charm! Thank you so much!
It may have been module manager or kOS... Didn't have to touch KCT tho. You're the best!
