### ISSUE TITLE
Wiki installation steps are broken

### ISSUE THREAD

**Issue by lkucera** [KSP-RO/RP-0#1140]
Under Backport and patches, there seems to be issues:

7. Install updated X-Science -> [X] Science Update 5.17-RP1v2 

there is no releases under refered repo, and link does not work.

Addtionally  it seems that point 5. may not be needed since Custom Barn Kit in same version can be installed via CKAN...

**Comment by siimav** [comment]
Oops, I might have deleted the [X] Science fork...

**Comment by siimav** [comment]
But you should probably install the in-development version for KSP 1.6.1 instead:
https://github.com/KSP-RO/RP-0/wiki/RO-&-RP-1-Installation-for-1.6.1

**Comment by lkucera** [comment]
You guys, I love you, I always spend entire weekend setting up RP1 :) But, it is always worth.

**Comment by siimav** [comment]
Closing this as we now have an official release for 1.6 and 1.7
