### ISSUE TITLE
Tracking station update from lvl2 to lvl3 impossible

### ISSUE THREAD

**Issue by tocki01** [KSP-RO/RP-0#1145]
I can't upgrade Tracking Station to lvl 3. I have finished researching the required tech node. 
Sadly github seems unable to upload KSP.log, so I uploaded a prinscreen.
Any ideas?

![Problem](https://user-images.githubusercontent.com/25954281/67144661-3a06ce80-f279-11e9-936c-6d7eaa122792.png)

**Comment by siimav** [comment]
Looks like you pressed the Switch Editor button inside the VAB and it royally screwed up your save game.

**Comment by tocki01** [comment]
Is there a way to fix it or I should just start again and never press that button?

**Comment by siimav** [comment]
Not sure, maybe if you manage to manually edit the tacking station level back to what it previously was in your persistent.sfs.

**Comment by tocki01** [comment]
I have started again, reached the same situation and the problem is there again. I have never pressed the change editor button. One thing I have noticed is, the tracking station upgrades are not gated behind those technodes that have the upgrade unlock 'part'. For the lvl2 upgrade Lunar Range Coms where needed instead of Early Tracking Systems. Now I have edited my save file to have the Lvl3 Tracking Station. The next upgrade needs Interplanetary Communications.
I have Kerbalism installed and I think somehow Kerbalism's Coms Tech levels interfere with the Tracking Station Upgrades.
An other idea is that, I have not pressed the Upgrades from tech tree button in KCT settings.

**Comment by siimav** [comment]
Then you should find the full stacktrace for the `KeyNotFoundException` from your ksp.log. Maybe it will give some hints on what it happening.

**Comment by siimav** [comment]
@DRVeyl suggested that you should check the KCTBUILDINGTECHS node in your MM cache.

**Comment by tocki01** [comment]
UrlConfig
{
	parentUrl = RP-0/CustomBarnKit.cfg
	KCTBUILDINGTECHS
	{
		TrackingStation
		{
			1 = lunarRangeComms
			2 = digitalComms
			3 = interplanetaryComms
			4 = advancedComms
			6 = deepSpaceComms
			9 = massiveScaleComms
		}
	}
}

**Comment by DRVeyl** [comment]
Noting those are upgrade levels, so the 2nd upgrade (aka TS3) requires DigitalComms.  Do you actually have that tech and have it unlocked?  There might be some unexpected disagreement between some of the mods and/or their branches.

Do you have RealAntennas installed?  That looks like the KCT TS upgrade rules you would get from RA, or also a test branch of RP-0, but perhaps not master or the mainline releases.

Those part-upgrade parts/icons are only to indicate to the player which techs should allow which TS upgrades.  If they're placed incorrectly, the only actual effect it has is confusion.  But if they don't line up, I'm guessing you have some mods that aren't _quite_ happy with eachother.  In this case, a recent RealAntennas release along with RP-1 master branch but not test.  Confirm?

**Comment by tocki01** [comment]
Yes, I have RA. RP-1 is from main. I have reinstalled everithing yesterday. Freshly downloaded from the links on the wiki page or via CKAN. I dont have a technode called Digital Comms. Lunar range comms than the next is interplanetary comms.

**Comment by DRVeyl** [comment]
Ok.  Issue is mine and on the RealAntennas side: its CustomBarnKit patch assumes that DigitalComms tech node is active, and that's only true in the RP-1 TEST branch.  Alternatively, can we merge the current RP0TechTree.cfg in TEST into master?

**Comment by siimav** [comment]
Latest RP-1 release contains the TS configs
