### ISSUE TITLE
No science experiment levels

### ISSUE THREAD

**Issue by tocki01** [KSP-RO/RP-0#1146]
Hi, I am sorry, it's me again.
So it seems like the experiment levels are not working. The very first science parts return maximum amount of science points.  I have tested it with the master and the test branch too. Any idea how to find out what's going on? Kerbalism is not installed.

**Comment by pap1723** [comment]
Are you using some mod that does the science for you with a click?

**Comment by tocki01** [comment]
No, I'm not. Only action groups.

**Comment by siimav** [comment]
Is DMModuleScienceAnimateGeneric installed?

**Comment by tocki01** [comment]
No. Should be?

**Comment by tocki01** [comment]
OK, so I have found the DMModuleScienceAnimateGeneric.dll in DMagicScienceAnimate folder. So then Yes. :)

**Comment by tocki01** [comment]
I have looked a little bit around dMagicScienceAnimateGeneric. So, ckan says v0.21 is installed, But in KSP.log it says v0.20 is installed. Can that be the problem, or just the version nr. is not right somewhere inside DMSAG?

**Comment by siimav** [comment]
Both show v0.21 in my install

**Comment by tocki01** [comment]
It's CKAN's fault. After reinstalling the mod from github everything is correct. Maybe this should be added to the Wiki page.

**Comment by siimav** [comment]
Probably won't be an issue any longer if we get the official release out and setting older versions as compatible is no longer necessary.
