### ISSUE TITLE
1.25m Crew Carrier is overpowered in its node

### ISSUE THREAD

**Issue by lpgagnon** [KSP-RO/RP-0#1148]
Discord discussion petered out, so capturing as an issue.

1.25m Crew Carrier is in the Hypersonic Planes node (alongside the x-15 stand-in 1.25m Inline Cockpit). It has very low power usage, is fairly light, quite cheap, high heat tolerance, and allows EVA. For a very low Sci investment, it can do nearly everything Gemini _and_ space station parts can do.

Minimal fix would be to give it the no-eva tag [edit: this is done now]. But that would still leave it as an optimal way to do multi-crew records and space station contracts. Supplemented with external avionics, rcs, etc I expect it's also the optimal way to send crew to space and back - possibly to the moon and beyond.

A better fix would be to kick it to one of the 'space station' nodes(or to a spaceplane node belonging to the same era as space stations), and ensure its power requirements are in line with similar parts. (however the next planes node has similar, even better parts; those would need tweaking at the same time)

**Comment by nepphhh** [comment]
Perhaps it ought to be configured as a non-FASA version of the Gemini lander proposal [(this one)](https://github.com/KSP-RO/RP-0/blob/f2c63d21c7242ce4f446f222739cb7a0a421bd01/Source/Tech%20Tree/Parts%20Browser/data/FASA.json#L4648)?

**Comment by pap1723** [comment]
Moved to the next later Spaceplanes node with Commit: https://github.com/KSP-RO/RP-0/commit/12a8a3c825f634d2c76c7de935ed4dbeb25d3629
