### ISSUE TITLE
KCT is gone

### ISSUE THREAD

**Issue by TransparentElemental** [KSP-RO/RP-0#1153]
Completely. What happened is that i played the game literally about 2 hours ago just fine, then i decided to activate some of the duplicate engines which are usually hidden by ROEngines (specifically RD-107, RD-108 and RD-0110), clicked apply in the patch manager and closed the game. After launch i noticed that the KCT button disappeared, i quickly reverted the changes made in patch manager and restarted the thing again, but it did not helped even after reloading latest save. The button is still missing and the console is spammed by NullRefs. No mods were (un)installed in the process and the pack i'm playing with is mostly recommended by RP-1 mods or ones that did not caused any issues several careers before that. 
I had a thought that my save could've been corrupted because about that time i had a BSOD with memory management stopcode (the bsod cause is still unknown as no internet methods resolved it, it feels like it appears randomly during my ksp playthrough), i replaced the old persistent with backup one (hopefully it is not too far from where i am now) and the issue is still present.
In the archive are my latest persistent, latest save and last KSP.log, version of KCT is 1.4.6.14
Note: the KCT_Settings.cfg file that is located in saves/save name/ filled with just 1 line of repeating "NUL NUL NUL" if that matters.
[KSP.zip](https://github.com/KSP-RO/RP-0/files/3877065/KSP.zip)

**Comment by siimav** [comment]
Then just delete the KCT_Settings.cfg and configure it again.

**Comment by TransparentElemental** [comment]
That fixed it
