### ISSUE TITLE
Aerodynamics broken with certain builds

### ISSUE THREAD

**Issue by Dunkhan** [KSP-RO/RP-0#1155]
I created a ship to do the crewed 100km altitude contract. Something about what I made demonstrated a very strange aerodynamics bug. When the vehicle reaches upper atmoshpere it suddenly starts spinning wildly. The engines have to be cut to stop it flying apart. When it comes back down at around the same height it starts spinning again. It also decelerates down to around 300-400m/s in the upper atmosphere. It then floats down like a baloon until it hits the lower atmosphere mark where it straightens out and starts to accellerate.

I do not know this is an RP-1 bug, it could be any of the many mods involved here. I hope someone can move this to the correct section once that becomes clear.

I installed the newest version on 1.7.3 roughly according to the guide (not exactly because it is slightly outdated) and have added nothing not on the list from the website except the procedural parts latest fix and chatterer.

If you are investigating this and cant immediately reproduce it using these ship files it would probably be best to simply close this as it is not worth debugging the complexities of mod installation.

[Ship.zip](https://github.com/KSP-RO/RP-0/files/3881432/Ship.zip)

**Comment by pap1723** [comment]
This is definitely not an RP-1 issue. This is likely a mod conflict, but trying to figure out which one would be impossible.
