### ISSUE TITLE
Selecting a training course breaks the RP-1 Window in Sandbox mode

### ISSUE THREAD

**Issue by TheRealWiwaxia** [KSP-RO/RP-0#1156]
Was testing out my new RO/RSS install in sandbox with RP-1 installed. If I try to train a crewmember in any course the window breaks and this is spammed in the log:

[EXC 17:21:23.029] NullReferenceException: Object reference not set to an instance of an object
	RP0.Crew.FSGUI.newCourseTab ()
	RP0.TopWindow.DrawWindow (Int32 windowID)
	UnityEngine.GUILayout+LayoutedWindow.DoWindow (Int32 windowID)
	UnityEngine.GUI.CallWindowDelegate (UnityEngine.WindowFunction func, Int32 id, Int32 instanceID, UnityEngine.GUISkin _skin, Int32 forceRect, Single width, Single height, UnityEngine.GUIStyle style)

![screenshot5](https://user-images.githubusercontent.com/26444769/69503250-bda18400-0ee5-11ea-8c6e-e7781d3fda3b.png)

Only way to fix the window is to close the window and change scenes.

**Comment by siimav** [comment]
I'm unable to replicate this issue. Does it happen on someone else's install as well?

**Comment by DRVeyl** [comment]
Yes, I can duplicate this in my 1.7.3 install.  Happens upon clicking "Start Course" in sandbox.

**Comment by DRVeyl** [comment]
Fixed with https://github.com/KSP-RO/RP-0/commit/be1acf94bf96f5ce172d78088ffcfcda43d26af3
