### ISSUE TITLE
RSSVE vanished from github

### ISSUE THREAD

**Issue by zajc3w** [KSP-RO/RP-0#1163]
Not really RSS/RO issue, just noticed all links to RRVE are 404. PhineasFreak has no repositories.
Does anyone know what happened?

**Comment by Brayaown** [comment]
THis is so true! Where  did it Go?! weird as heck. I am having the same problem.

**Comment by todi** [comment]
PhineasFreak has retired from KSP modding some time ago. It seems he has now also deleted all his repositories.

The RSSVE installation wiki has been migrated to https://github.com/KSP-RO/RP-0/wiki/RSSVE-Installation-Instructions. The release files can still be found in several github forks, eg:
- https://github.com/jrodrigv/RSSVE/releases
- https://github.com/lamont-granquist/RSSVE/releases

@jrodrigv also seems to have done some work towards 1.8 compatibility.

**Comment by jrodrigv** [comment]
Yes. I have everything working in KSP 1.8.1 a custom version of RSSVE with some better textures from RVE 64k integrated.However Im not really the owner of these mod so the best I can do is to upload my setup so that it can be linked in the Wiki.

**Comment by Brayaown** [comment]
Not gonna lie that would be awesome

**Comment by jrodrigv** [comment]
You can download from here my current setup for KSP 1.8.1
https://1drv.ms/u/s!AixZLrjtqp-Rgsd0V_bea1mSd1Yn5g?e=GIKq9u

**Comment by siimav** [comment]
RSSVE is now under the KSP-RO group: https://github.com/KSP-RO/RSSVE
Thanks, @Theysen
