### ISSUE TITLE
E-1 / F-1 ECM

### ISSUE THREAD

**Issue by norcalplanner** [KSP-RO/RP-0#1164]
As discussed with Pap on gravshark's stream, we may want to apply some sort of ECM to the purchase of the F-1 engine if a player has previously purchased the E-1.

**Comment by MikeOnTea** [comment]
There already is an ECM (covering the turbo pump). Maybe it was intentional to not have more?

**Comment by norcalplanner** [comment]
Quite possibly.  If there's already something in there, then we may be good to go.  Pap asked me to open an issue so he wouldn't forget. :-)

**Comment by norcalplanner** [comment]
As I've thought about this more, I think there should be some small ECM beyond that for the turbopump. From what I understand, it was the promise of the E-1 that landed RocketDyne the contract for the F-1. Not in front of computer atm, but perhaps 5-10% off of the F-1 cost if the E-1 has been purchased.

**Comment by siimav** [comment]
I think @Capkirk123 implemented that in one of the recent PRs?

**Comment by Capkirk123** [comment]
Yes, Buying into the E-1 will provide 50000 discount on the F-1
