### ISSUE TITLE
1.7.3 CKAN install leaves out required bits of Ven's

### ISSUE THREAD

**Issue by lpgagnon** [KSP-RO/RP-0#1165]
(copy-pasted from discord for better visibility)

Ven's 1.13+ has been split in 3 on ckan (but NOT in kerbas-ad-astra's github fork's releases). 
- VensCore: new package, shared bits
- VensStockRevamp: the original package, changes to stock parts, depends on Core
- VensNewParts: new package, just new parts, extracted out of VensStockRevamp. also depends on Core

currently rp-1 only depends on VensStockRevamp, meaning a bare RP-1 ckan install ends up missing some stuff that used to be in VSR but is now in NewParts (one obvious one I spotted is the Small Sep Motor - less obvious is that it breaks AJE engines, though arguably that's a problem with AJE's own dependencies)

Now the reason it was split this way seems to be restock compatibility: ckan will allow installing Core+NewParts+Restock, which is (almost) what a rp-1 user would want if he wants restock

We'd need 2 changes for this to work out, both of which I'm unsure are actually possible
- rp-1 needs to depend on NewParts. problem: there's no such thing prior to ksp1.7
- rp-1 should depend on a "virtual" package, satisified by either VSR or ReStock

Extra complication: RO and/or AJE relies on bits of VSR (the part that would be left out in a restock install) for the "core" of jet engines; I see no way to get that without manual steps. It only affects looks, and is a small price to pay

To be clear: the problem right now is that rp-1 depends on VSR, which for 1.7.3 refers to exactly the bits that should be left out in a restock install, and leaves out the bit that's always needed (newparts)

[short-term I'll update the guide to call out the need to manually add NewParts]

**Comment by ec429** [comment]
Related: the RT20 model moved to NewParts, but RO-M55 (the Minuteman) is still looking for it in VSR/`Squad/Parts`, so the part compile fails.  I haven't submitted a patch because I'm not 100% sure how we handle the versioning, if at all.

**Comment by siimav** [comment]
Since KSP 1.6 and 1.7 are no longer supported by the latest RP-1 version, we could update the RP-1 netkan to make the correct Ven's packages install by-default. I guess we would need to depend on `VenStockRevamp-NewParts` and `VenStockRevamp` (aka existing part overhaul) should be a recommend instead?

**Comment by DRVeyl** [comment]
.netkan maintenance was done as per above comment
