### ISSUE TITLE
1.7.3 CKAN Upgrade Error

### ISSUE THREAD

**Issue by Omnipius** [KSP-RO/RP-0#1167]
When upgrading in CKAN, the following error is thrown:

RP-0 v1.2.1 requires KerbalConstructionTime-173 but it is not listed in the index, or not available for your version of KSP.

**Comment by siimav** [comment]
Not sure what's the easiest way to get past that. Maybe uninstall both KCT and RP-1 through CKAN and then try to reinstall RP-1?

**Comment by Omnipius** [comment]
Actually, the issue appears to be that there are two separate copies of KCT in CKAN. One that has continued development for 1.8.1 and another for 1.7.3. Prior versions of RP-1 used the main branch, whereas the update requires the new 1.7.3 branch. However, since anyone updating would have the main branch of KCT installed, CKAN doesn't know that it needs to be uninstalled and the new branch replace it.

So, you're approach is the only way to update. Uninstall both and reinstall the correct branch.

Ironically, this is actually an issue with how KCT has subdivided their branches. Creating a separate mod listing was unnecessary under the way CKAN handles mod and KSP versioning.

**Comment by siimav** [comment]
Closing this as there's nothing to do about it
