### ISSUE TITLE
Place all DMagic Orbital Science experiments

### ISSUE THREAD

**Issue by pjf** [KSP-RO/RP-0#117]
I'm placing all the DMagic orbital science experiments. This is my ticket for tracking that.

**Probe Science**
- [ ] dmASERT
- [ ] dmGoreSat
- [ ] dmImagingPlatform
- [x] dmmagBoom (scienceTech)
- [x] rpwsAnt
- [x] dmscope
- [ ] dmSoilMoisture
- [ ] dmSolarCollector

**Rover Science**
- [ ] dmAnomScanner
- [ ] dmbioDrill
- [ ] dmDAN (I had a DM Dan when playing D&D once!)
- [ ] dmsurfacelaser (pew pew!)
- [ ] dmRoverGoo
- [ ] dmRoverMat
- [ ] dmXRay

Relates to #43 .

**Comment by pjf** [comment]
Notes to self:

- Treating `dmscope` as a planetary imaging device, as it's biome dependent.
- `dmRoverGoo` and `dmRoverMat` are small versions of standard experiments, and will be late in the tech tree.
-  While even the earliest moon fly-bys had "TV cameras", they required the spinning of the craft to sweep the surface past a single light-sensor. By 1964 more modern digital transmission can be seen in Mariner 4. I'm using this as our approximate for `dmscope`.

**Comment by pjf** [comment]
Since Mariner 4 pre-dates project Mercury, `dmscope` can be placed relatively early in the tree.

**Comment by pjf** [comment]
Let's look at ASERT. I believe it's based on [CONSERT](https://en.wikipedia.org/wiki/CONSERT) which was deployed on Rosetta/Philae. Philae had a cost of [€220m](http://www.esa.int/Our_Activities/Space_Science/Rosetta/Rosetta_Media_factsheet), although the whole project was much more. The Philae cost is significant because it had at least one CONSERT instrument on it.

€220m in 2004 is about $40m in 1965 USD, or 40,000 RP-0 spacebucks. However Philae had ten experiments on it. If we just slice the cost evenly, that's 4k spacebucks per experiment.

So, I'm going to make ASERT cost $4k per experiment, which means at least $8k to mount a mission. That's reasonably pricey as far as science goes, but we probably want ASERT to be late in the tree as it's a relatively modern experiment (I can't spot it on any of the [earlier probes to asteroids](https://solarsystem.nasa.gov/missions/profile.cfm?Sort=Target&Target=Asteroids&Era=Past)).

**Comment by NathanKell** [comment]
Makes sense to me!

**Comment by pap1723** [comment]
RP-1 Science Overhaul
