### ISSUE TITLE
F-1B, M-1, and other parts price fixes

### ISSUE THREAD

**Issue by Capkirk123** [KSP-RO/RP-0#1170]
The F-1B and M-1 have questionable prices, I am making a PR to fix them (along with any other parts that can be shown to have incorrect prices). I will state my sources and reasoning here for my changes. Please contribute if there are any parts that you believe are incorrectly price or if you can find any useful sources.

**F-1B**
Current Price: 5000
New Price: 3400
Sources:
https://www.thespacereview.com/article/3724/1
https://gao.justia.com/national-aeronautics-and-space-administration/1970/12/overstatement-of-contract-target-costs-for-f-1-rocket-engines-for-saturn-v-launch-vehicle-b-167838/B-167838-full-report.pdf

In 1991, Rocketdyne predicted they could restart F-1A production at $15 million per engine. Adjusted for inflation to 1965, this is ~$3.47 million. This is a bit lower than the price of the F-1A in game, but Rocketdyne likely expect to be able to reduce costs somewhat with new technology. The F-1/F-1A nozzle extension cost ~49000, and since the F-1B doesn't have the nozzle extension, this price can be subtracted from the F-1A. Similar improvements would likely reduce costs on many engine components, but I will assume $3.4 million for the upper cost limit of the F-1B.

**M-1**
Current Price: 25,270 (!)
New Price: 13,600

Current Entry Cost: 280,000
New Entry Cost: 338,000

Sources:
http://www.alternatewars.com/BBOW/Space_Engines/M-1_Rocket_Engine_Project.pdf

The M-1 development contract was $238 million, and resulted in ~6 combustion chambers, 4 LH2 turbopumps and plumbing, 4 LOX turbopumps and plumbing, 11 gas generators, and 1 injector plate. It also paid for several test stands to handle an engine as large as the F-1, and the testing and development of those components. At the current price of the M-1 in game, these components alone could be estimated to cost nearly half the $238 million contract, which is an unusually large fraction, and indicates the current M-1 cost is probably too high.

Unfortunately, no estimate of the M-1 cost can be found, but it can be approximated. Based on the similarity of the M-1 to the F-1 and J-2, and the typical ratios of one large engine vs. smaller clustered engines, I can estimate the M-1's cost. The M-1 had similar thrust levels to the F-1, but it required turbopumps nearly twice as powerful, had much higher combustion temperatures, and a much larger film-cooled vacuum optimized nozzle. Compared to the J-2, it is ~5x as powerful, but a small cluster of engines is typically less expensive than a similar, large engine. Based on this information, I estimate the cost to be $13.6 million. This is ~3x the cost of the F-1, or 36% more expensive than 5 J-2-230k. With the later thrust upgrades to 1.5 mlbf and 1.8 mlbf, the M-1 can surpass the J-2-230k in performance/$ and begin to compare favorably with the J-2S.

On the other hand, the M-1 development cost is somewhat low. The initial $238 million contract built and tested M-1 components, and may have tested a M-1 without its full nozzle had it not been cancelled. However, moving the engine from prototype phase to full production would have been required still. I have added ~$100 million to the $238 million contract to account for this.

**Comment by pap1723** [comment]
Was there already a PR for this?

**Comment by Capkirk123** [comment]
Sorry, forgot about this.
https://github.com/KSP-RO/RP-0/pull/1183

**Comment by Capkirk123** [comment]
Fixed PR
https://github.com/KSP-RO/RP-0/pull/1184

**Comment by pap1723** [comment]
Completed with https://github.com/KSP-RO/RP-0/commit/05af0e61ac68c42f3eead538348ff4402a69fccd
