### ISSUE TITLE
Unusual RL10B-2 cost

### ISSUE THREAD

**Issue by Capkirk123** [KSP-RO/RP-0#1177]
All variants of the RL10 have their cost set to 500, and the extra cost is added by the engine config. However, the RL10B-2 has its cost set to 3800 in all mods. When the engine config cost of 1600 is added to this, it results in a cost of 5400 ($40 million today), much higher than even the commonly quoted '$25 million" per engine (although I could not find a solid source for this). The RL10B-2 should have its cost reduced to the standardized 500, and the cost of the B-2 engine config should be increased to compensate if necessary.

**Comment by pap1723** [comment]
Fixed with https://github.com/KSP-RO/RP-0/commit/be31d3b912ab6e9f29081c67a2b854ed573e098e
