### ISSUE TITLE
"First Scientific Satellite" Contract Affected by Kerbalism

### ISSUE THREAD

**Issue by hxl11211** [KSP-RO/RP-0#1179]
The contract requires a satellite staying alive for 120 minutes and transmit Cosmic Ray Science back.

However, with Kerbalism's redo of science system, the Cosmic Ray Science now takes 90 days to run, **and it turned out that partial transmissions do not count.**
My satellite didn't last 90 days so I don't know if the contract would be completed by then. But this definitely creates additional difficulty and confusion as not only the satellite needs to last 90 days (rather than 120 mins from contract specification; solar panel technology is probably mandatory) but also it needs to be launched into orbit at least 90 days prior to contract deadline.

I'm not familiar with modding but I would suggest either somehow make partial transmissions count toward a contract completion, or at least add a note in the contract description warning anyone who has Kerbalism installed.

**Comment by nepphhh** [comment]
Those capabilities are provided by Kerbalism Contracts, but current RP-1 doesn't make use of them. Right now, just cheat the contract complete using the Alt-12 menu.

**Comment by hxl11211** [comment]
Ok thanks for the clarification.
