### ISSUE TITLE
Loading Error about Avionics.cfg

### ISSUE THREAD

**Issue by GYskyfall** [KSP-RO/RP-0#1185]
When I loaded the game this is an error about Avionics.cfg:

[LOG 14:35:22.839] Applying update RP-0/Avionics/@PART[*]:HAS[@MODULE[ModuleAvionics],@MODULE[ModuleCommand]:HAS[@RESOURCE[ElectricCharge]:HAS[#rate[*]]]]:AFTER[RP-0] to RN_Soyuz/Parts/7k/lk_lander.cfg/PART[rn_lk_lander]
[ERR 14:35:22.839] Error - Cannot parse variable search when inserting new key enabledkW = #$../MODULE[ModuleCommand]/RESOURCE[ElectricCharge]/rate$`

and due to this error, the game can't create 'ModuleManager.ConfigCache'

**Comment by siimav** [comment]
Please download the master branch of RO. This has been fixed already.
