### ISSUE TITLE
Remove Test Flight related loading hint

### ISSUE THREAD

**Issue by SillySMS** [KSP-RO/RP-0#1188]
Line 18 of this file is a bit out-of-date with TestFlight being largely usurped by TestLite.

https://github.com/KSP-RO/RP-0/blob/master/GameData/RP-0/PluginData/LoadingScreenTips.txt

I'd also recommend adding something like this:

"Keeping around smaller launchpads to reduce launch costs for small rockets..."

**Comment by norcalplanner** [comment]
This and many other hints will be updated soon
