### ISSUE TITLE
RO & RP 1 Installation for 1.7.3  install SXTContinued

### ISSUE THREAD

**Issue by patrickselby** [KSP-RO/RP-0#1190]
I think the install notes should specify installing SXTContinued from ckan, then overwriting, then the batch file.  I only installed from github and the batch file was missing folder/files on the path.  Specifically the "/Squad/zDeprecated" folders were missing in the root.  I'm on linux so it might just be me, and a new 1.7.3 install.

**Comment by siimav** [comment]
Looks like the install guide now has step
