### ISSUE TITLE
(non intended playthrough) missing shader

### ISSUE THREAD

**Issue by dgxt002** [KSP-RO/RP-0#1226]
Just because I took my working 1.8 RP-1 install and started a science mode playthrough.  I edited my persistent file to add 999 science to open up starting parts.  Everything works fine, except when changing tank sizes or other procedural parts the game crashes and my log is spammed with missing shader errors relating to both FAR and procedural parts.  Is it possible some shaders are not loaded in science only mode?  Not an important questions, just a curiosity.

**Comment by nepphhh** [comment]
How does it occur to you to mention the errors in the log yet not provide the actual log file with the errors? Don't you think that'd be useful at all?

**Comment by DRVeyl** [comment]
Or less adversarially... you'll find that TexturesUnlimited doesn't really care what game mode you're in, and your log is going to have those errors regardless.

**Comment by dgxt002** [comment]
Looks like I tracked it down to deleting the KCT related files in RP0.  Apparently not loading the kct dll and configs borked something.
