### ISSUE TITLE
No "Normal" procedural tank on career mode - Only service module

### ISSUE THREAD

**Issue by mateusviccari** [KSP-RO/RP-0#1228]
I just installed RP1 on a new KSP 1.7.3 installation.

When I start a new career and unlock the starting parts, there's no Procedural Tank, only the Service Module and a bunch of deprecated procedural tanks. Searching on the tech tree, I don't see any node unlocking the part.

I remember that in previous versions, we had only one procedural tank and we could choose the tank 1, 2, 3  and SM 1, 2, 3 via an option on the part's properties.

**Comment by siimav** [comment]
Fixed in the latest release
