### ISSUE TITLE
TweakScale or multi-scale avionics?

### ISSUE THREAD

**Issue by pjf** [KSP-RO/RP-0#123]
It would be nice to have tweak-scale friendly avionics, or different housing
selections. The big guidance units I have are:
- 1m, 0.35 mass, 3kW, 45 tonnes,  $200
- 2m, 0.40 mass, 1kW, 120 tonnes, $600
- 3m, 0.85 mass, 2kW, 300 tonnes, $900

For a lot of my launches, the 2m unit looks pretty good, however I keep wanting
to place them on my existing design 1.5m upper stages, where they stick out. With new designs I'd change shapes to accommodate, but if I could tweakscale them up or down, that would happily solve that matter. :)

Ditto for the various probes. Most of my probes weigh in between 0.4 and 0.8 tonnes. The Ranger core is too small (and has a lot of extra struts that reduce coolocity of my craft), and the surveyor core looks huge.

So totally happy for the stats to remain the same, but different sized packages would be great. :)

**Comment by NathanKell** [comment]
I would suggest asking on the Tweakscale thread if there's a way to change size *without* changing stats. Probably, but I don't know it.

**Comment by pjf** [comment]
Gosh dang it, I was hoping I'd be able to continue in my absolute ignorance as to how parts and TweakScale in particular actually works. :)

**Comment by BevoLJ** [comment]
I would love to see some tweakscale added to these.  Especially the probe cores.  Currently trying to design an atmospheric lander is (from what I can figure out) impossible due to the surveyor probe being 2.2 meters in size and only allowing 1t, but a 2+ meter heatshield is 1.1 tons.

**Comment by BevoLJ** [comment]
One other thing tweakscale might be able to help with is trying to keep part count down.  I'm finding on some of my launches 10- 20% of my part count is now avionics.  IRL they didn't need to worry about part counts breaking physics.  :D

**Comment by pjf** [comment]
After a brief glance at the TweakScale documentation, it looks like we can tell tweakscale to keep away from our mass, price, and other attributes altogether. This means we could have tweakscaleable avionics which cost and weigh the same, but are just in different sized housings.  This means no avionics funnily sticking out from the side of rockets, no giant sized landers, no weird probes that are pinched in the middle, and all those other things that have been bothering me forever.

**Comment by NathanKell** [comment]
That sounds like a fine solution until we get real procedural avionics (which can be done by referencing the Proc Parts DLL and adding a some new classes I think), or I extend RealFuels so you can add Circuitry as a fuel type in ServiceModule tanks (but that one requires https://github.com/NathanKell/ModularFuelSystem/issues/60 and https://github.com/NathanKell/ModularFuelSystem/issues/59 ).

**Comment by rsparkyc** [comment]
A question about the "realism" factor of the probe cores.  Is it realistic that certain cores can only control ships up to a certain mass, or is it just an attempt to balance probe core capabilities (instead of just having one core that can do-it-all)?

**Comment by rsparkyc** [comment]
I'm working on procedural avionics (https://github.com/KSP-RO/RP-0/issues/623), so I'm going to close this, as I think it will be solved by procedurals.
