### ISSUE TITLE
Fuel Flow Priority

### ISSUE THREAD

**Issue by ErinaceusLinnaeus** [KSP-RO/RP-0#1238]
Hi.
I can't set any fuel flow priority.
Is this bound to a mod I didn't install, though I followed the guide on how to install it for KSP1.8.1 - everything works.

As I understand it, it's the TweakableEverything (?), but that conflicts with RO_Capsules now.

**Comment by DRVeyl** [comment]
Fuel Flow Priority isn't tied to a mod.  You need to enable Advanced Tweakables, a stock setting.  TweakableEverything is something else.  Main settings page, general tab, gameplay, towers the bottom.

**Comment by ErinaceusLinnaeus** [comment]
thanks, found it.
