### ISSUE TITLE
procedural avionics != heatshield.

### ISSUE THREAD

**Issue by glilienthal** [KSP-RO/RP-0#1239]
I find it weird that the procedural avionics part is so much more heat resistant than any other avionics. It has 1073/1073 K, whereas 

aerobee: 573/773 and others (starting, early 1m, able avioncs) have the same. 
Only the A4 avionics has even 1600 K (But this might be due to its possibly mostly mechanical nature? or German Engineering? or just a different modder ;)) 

My suggestion: Putting proc. Avionics at 573/773K like the others. 

Looking forward for comments. Shall I do a pull request?

**Comment by siimav** [comment]
This was done to make proc avionics capable of LEO re-entry and also to survive Venus landings.

**Comment by lpgagnon** [comment]
The problem is that _all_ configs share one temperature resistance, so either early parts get too-high a value, or later parts get too-low a value. siimav explains why the former is preferable

**Comment by glilienthal** [comment]
Makes sense. Then I don't feel bad for reentry from suborbital with just proc avionic and parachute :).
