### ISSUE TITLE
Missing contracts in Rp-1 for 1.8.1

### ISSUE THREAD

**Issue by Cymrych** [KSP-RO/RP-0#1245]
Hi all, 

Kind of a weird one. I tried RP-1 last July in 1.6.1 (played RP-0 in 1.2.2 for ages), but my install was never particularly stable and I mostly let it slide by the wayside. But I've had the bug for a while, so I today tried the 1.8.1 version of RP-1, and it all seemed to load fine (and with less conflicts (ie: none) vs in my old 1.6.1 attempt).

Except I have no contracts available, including the starting unlock tech automatic contract needed to unlock the base parts. Contract Configurator showed a host of stock contracts, which I disabled per the wiki installation guide for 1.8.1, but there wasn't an RP-0 group listed at all. Looking in GameData, it certainly appears that all the RP-0 contracts are in the RP-0/Contracts folder, so I'm not sure where the grievance might be. In fact, comparing the files in in this install vs my 1.6.1 install, I'm having a difficult time seeing anything different (although, I haven't gone through item by item to check the file dates or versions).

The install went line item by line item according to the wiki installation guide for 1.8.1. I went with Principia instead of PersistentRotation, TestLite instead of FlghtTest, and Kerbalism instead of RemoteTech, all new toys to me but it sounds like they each are better optimized and hopefully will improve my old computer's performance somewhat.

I saw one earlier post about a similar issue, in 1.6.1 from last October. That issue sounded like a corrupted download of RP-1. Mine seem to have everything in place. My only guess is something in ContractConfigurator isn't seeing the RP-1 contracts folder for some reason.  But I'm out of my depth here, hence this message.

Thanks, -Jason

**Comment by nepphhh** [comment]
> Contract Configurator showed a host of stock contracts

Did you view this with the Alt-F10 menu? My intuition is either a) you didn't follow the [github extraction guide](https://github.com/KSP-RO/RP-0/wiki/How-To-Install-a-Mod-From-Github) right when updating RP-1 or b) CC didn't install right, in which case Alt-F10 wouldn't open up the CC contract debug menu.

**Comment by Cymrych** [comment]
I got into CC two ways. First, from the start game menu under the difficulty settings, where the wiki guide stated to de-select the stock contracts. I also, from within a new test game, got into CC from the settings tab from the exit button, which brought up the same window as pre-game.

I didn't update RP-1, it was a fresh install via CKAN per the wiki installation guide. 

I didn't know about an Alt+F10 menu, so I will try that now.

**Comment by Cymrych** [comment]
I think I should have clarified: that host of stock contracts I mentioned were the ones I turned off in the Difficulty menu. They did not appear in the game itself.

Alt+F10 worked and brought up the debug page. It appears to show all the RP-0 contracts, including unlock parts, and no stock contracts. Which suggests that CC is removing the non-RP-0 contracts as called for in RP-0's Contracts/Groups.cfg, but for some reason they're not uploading to mission control. 

Bearing in mind that I know nothing about the CC debug GUI, I did find it odd that the contract list would only display when I click on the far right bubble, Contract Balancing. Clicking on the broken contracts didn't seem to do anything, nor did clicking force contract generation. In Alt+F12, the contracts that are displayed ARE the stock ones, but they're not listed under active, offered or completed, which were blank.

I did see in the github page for CC that there  was a minor update to 1.28.1 back in November. I uninstalled the one installed by CKAN as a RP-0dependency, and installed this minor update from github, but it didn't seem to make a difference (wasn't expecting it too, but worth a shot.)

I've included the KSP log here, but I think tomorrow I'm going to start a fresh install and test more thoroughly after getting the baseline minimums installed.
[KSP.zip](https://github.com/KSP-RO/RP-0/files/4479548/KSP.zip)

**Comment by Cymrych** [comment]
Quick update. I started a new install, and had success for quite a while following the installation guide. Steps 1-12 of the main installation through updating the broken mods went well and CC worked. I then added all the Essential Mods as listed through step 1-6 (except PersistentRotation), plus optional Kerbal Alarm Clock, and again all was fine with CC.

I then added TestLite, Principia, per steps 7-8 of the Essential Extra Mods page, but none of the visual/sound mods. And I added two from the Recommended Extra Mods list, USProbes, and Taerobee, and CC now isn't functioning properly again.

After work, I'll try adding in those final four mods one by one to see when exactly CC breaks.

**Comment by siimav** [comment]
Try removing USProbes

**Comment by Cymrych** [comment]
Well, removing USProbes did the trick. Thanks!

I didn't need the probes, but I had heard good things about all of RaiderNick's stuff and wanted to give them a whirl. Any idea if there's a work around to whatever the mod is doing to nerf CC?

**Comment by siimav** [comment]
RN mods are nice for RO but unfortunately most of the parts haven't been placed into the RP-1 tech tree. In general we recommend using procedural parts as much as possible.
USProbes breaking CC is definitely a really strange issue but I currently have no idea what specifically in that mod causes it.

**Comment by Cymrych** [comment]
Gotcha. Oh well, as I said, I was more curious about RN's work than anything else. It might be a good idea to put an asterisk on the Recommended Extra Mods page about this possibly being an issue, especially as it's mentioned that the US Probe  and Soviet Probe packs are recommended in particular of RN's repertoire.

Sounds like this issue is resolved, so I'll close it out.

**Comment by nepphhh** [comment]
The wiki has been edited, could you check to make sure it's accurate to your experience? Also... it's a wiki. Feel free to make changes yourself :)

**Comment by Cymrych** [comment]
Ha, to be honest, editing it myself never occurred to me! I'm just a consumer of your guy's brilliant work; making an edit to anything official looking like the wiki just seems .... wrong somehow. But point taken, and I'll keep it in mind for next time.

Yes, the note added to that page matches my experience perfectly.

**Comment by JohnMcLane4** [comment]
I solved the problem for me by deleting the RN_US_Probes->Rn_Scansat.cfg and it works again. 

I wrote it a year ago (https://forum.kerbalspaceprogram.com/index.php?/topic/162117-122-realistic-progression-zero-rp-0-lightweight-realismoverhaul-career-v054-june-15/page/28/&tab=comments#comment-3602022)

maybe that helps.

**Comment by Peter-JY** [comment]
Link of this issues in RN USProbes‘s issues: [https://github.com/KSP-RO/USProbesPack/issues/5 (issues #5)](https://github.com/KSP-RO/USProbesPack/issues/5)
