### ISSUE TITLE
RL10A-3-3-Lunex Unlocked Too Early

### ISSUE THREAD

**Issue by hxl11211** [KSP-RO/RP-0#1247]
**Mod versions:**
KSP version: 1.7.3
RP-1: 1.3
ROEngines: 1.4.0.0
RealEngines: 1:2.01
TestLite: 0.2.2

Just researched the `Prototype Hydrolox Engines` technology and unlocked the very base RL10A-1, and found that a RL10A-3-3-Lunex variant became immediate available. 

Unlocking at the same time with the base RL10A-1, the Lunex variant is of a much higher performance but requires no additional cost. 

**Suggestion:**
1. Unlock it at a later node, either with 3-1 or 3-3
2. It should have an additional cost between 3-1's +250f or 3-3's +500f.

![image](https://user-images.githubusercontent.com/59517291/79415736-1d272b80-7f7c-11ea-8bbf-c9bbf9790fab.png)

**Comment by Capkirk123** [comment]
You have an outdated version of RP-1.

**Comment by hxl11211** [comment]
Oh didn't notice v1.4 was released just a week ago.
Is it backward compatible with my v1.3 game save?

**Comment by siimav** [comment]
Probably but make sure you back up your persistent.sfs before updating
