### ISSUE TITLE
Crew training improvements

### ISSUE THREAD

**Issue by siimav** [KSP-RO/RP-0#1250]
* Create a training category for all subsonic cockpits and assign a short training duration for it
  * What's the best name for that?
* Add training course name to `ModuleShowInfo`

**Comment by norcalplanner** [comment]
I vote "Unpressurized Cockpits" since it's really the altitude that is key from a player's standpoint

**Comment by jwvanderbeck** [comment]
Eh but if a player doesn't understand the pressurization mechanics (IE that there are pressurized and not) then they might not understand.  

Early Cockpits or something like that might be more clear?

**Comment by NathanKell** [comment]
Is the reason for this to slow down first flight? I would have thought
mission training alone would do that, one would hope any test pilot
selected for naut training would be proficient in flying aircraft.

Sent by my thumbs, slowly.

**Comment by jwvanderbeck** [comment]
No, based on the discussion in Discord it is more to make things less confusing because right now the early cockpits have a bunch of different courses, all confusingly named that no one even knows what goes to what.

**Comment by NathanKell** [comment]
Oh, that makes sense.

Sent by my thumbs, slowly.

**Comment by siimav** [comment]
All the subsonic cockpits have now been moved to "GeneralAviation" category which has training times of 1 day for proficiency and 1 hour for mission. If the proficiency training duration feels too insignificant then maybe we could increase it along with making all the starting pilots already have it by default. Might be a bit more realistic that way but the downside is that it might *train* new players wrong.
