### ISSUE TITLE
Hiring nauts is crazy expensive

### ISSUE THREAD

**Issue by siimav** [KSP-RO/RP-0#1261]
50k per naut is way too big of an expense after the first ones expire in 1958-1960.
Maybe set the cost to something like 10k instead?

**Comment by norcalplanner** [comment]
It seems like flying them on missions also doesn't push back retirement as much as it used to. I would be in favor of a reduction, but 10K is too little imho. How about 25 or 30k?

**Comment by TheRealWiwaxia** [comment]
I believe 10-15k would be reasonable since your usually hiring nauts in batches after a few of them retire.

**Comment by leudaimon** [comment]
As I mentioned in discord, I think astronaut training and the personnel necessary to keep a crewed program needs to be represented in the game somehow. If we reduce the hiring cost, it would be reasonable to increase the maintenance for astronauts, especially once they get training in orbital capsules. That would need to be shown in the UI somehow though, maybe in the course screen, along with the training deadline, a line showing how much your maintenance will increase.

**Comment by Myshiko** [comment]
I believe 50K for a pilot is not expensive at all. A VAB upgrade costs 1M, and no one complains.

If we lower the price of crew, it would become profitable to send crew on suicide missions as a expendable part. And that's not exactly the desired mechanics. What I feel is better option is to extend usable life time of astronauts a bit. 

Ideally, if we could maintain history of highest G endured, time without food, water and air, poisoned states, radiation and etc and make retirement earlier for abused crews. Or make crew retire earlier after using old cockpits. Make a property of the part on how badly riding it affects the retirement date. Clearly, we can expect that year 2000+ parts should be happy with 77 old astronauts. While only 20+ year old in his/hers prime could survive Vostok capsule.

**Comment by Myshiko** [comment]
Alternative possibility, is to make courage or stupidity affect the max duration till retirement. This will make duration to retirement more variable and ensure that all crew does not resign on a same day / month / year, thus realistically spreading the retirements in multiple years, with some crew members just naturally interested more in being around rockets for longer.

**Comment by siimav** [comment]
Crew retirement times are already based on courage and stupidy of the naut. But I agree that there should be a severe penalty for getting people killed during missions. Any suggestions on what we could use for that?

**Comment by leudaimon** [comment]
Thinking out of the box here... could you suspend all crewed flights for a few months (6mo to 1 year) after a KIA? Just making mission training impossible for some time shouldn't be too difficult

**Comment by siimav** [comment]
I'm sure I could come up with something. Not being able to assign crew to capsules is probably the easiest way to achieve that. Only disabling mission training unfortunately doesn't cut it because looks like a lot of players disable that feature.

**Comment by norcalplanner** [comment]
I'd be on board with that.  Sort of reflecting the stand down that took place after the Apollo 1 fire.

**Comment by Bornholio** [comment]
50K =$50,000,000 in 1965 is worth $411,817,307 in 2020.
$50,000,000 in 1951 is worth $513,948,000 in 2020
 I agree with Siimavs assertion. Most of this cost would be in the massive cost of capsules currently.
Somehow the entire cost of the "NASA Budget" (25B) is divided by number of active astronauts (48) for similar numbers. obviously not all hired in one year. 
Comparatively at adjusted for inflation price this is 


$1,203,013,000,000 | 2014 |   |  
-- | -- | -- | --
$161,045,917,001 | 1965 |   |  
  |   |   |  
  |   |   |  
339 | # of US Astronauts |   |  
$475,061,702 | '65/# |   |  
$50,000,000 | '65 astronaut cost |   |  
10.52% | of budget total for all of NASA |   |

**Comment by siimav** [comment]
In PLC their cost has been lowered to 10k but the penalty for getting them killed is significantly larger as well.
