### ISSUE TITLE
Reduce reputation penalties

### ISSUE THREAD

**Issue by siimav** [KSP-RO/RP-0#1262]
Rep gains work in a non-linear way in KSP. This means that 500 rep gained will be a lot less than 500 rep lost. Wheras 500 rep might only actually give you a 10% boost, 500 rep lost will likely move the total into the red. Being low on rep also means that higher rating contracts become unavailable and can thus break someone's career.

**Comment by Myshiko** [comment]
Imho, the rep system is totally broken. Canceling contracts or missing the contract deadline should not really affect the reputation that much. Killing crew should affect the reputation for the crewed missions and price of the astronauts, but should not really affect unscrewed missions.

Imho, reputation needs total overhaul, not just tiny tuning.

**Comment by siimav** [comment]
Reputation is a completely useless resource right now. The easiest way is to just reduce the `RepLossMultiplier` to the minimum for all difficulty presets until we come up with a way to give reputation some meaningful use.
