### ISSUE TITLE
Multiplier tags still talk about "rollout cost"

### ISSUE THREAD

**Issue by lpgagnon** [KSP-RO/RP-0#1265]
Example: https://github.com/KSP-RO/RP-0/blob/f07f0c36754b82201ee366917cb72620c09614b4/Source/ModuleTag/Avionics.cs#L7

Since integration costs have been separated from rollout costs, the 'rollout cost: cost of this part * X' descriptions are now misleading

**Comment by siimav** [comment]
Fixed in a44079a5740ee9e6571a8b165c524b4a231df593
