### ISSUE TITLE
"Procedural Probe Core" does not have tooling

### ISSUE THREAD

**Issue by archibate** [KSP-RO/RP-0#1274]
The "Procedural Probe Core"  from ROTanks does not have "Purchase Tooling" button at all. Is this the expected behavior? One can easily make a procedural avonics of any tonnage without tooling cost.

**Comment by DRVeyl** [comment]
Some of the changes to tooling for ROTanks require the master branch of RP-1.  Fixed with <https://github.com/KSP-RO/RP-0/commit/d78d4be9e4a836192ffc58594b53d0b436400cf9> and will be in next release.

**Comment by archibate** [comment]
Cool! Thank for the infomation!
