### ISSUE TITLE
[Instructions] New Career Settings can't be followed in the order given

### ISSUE THREAD

**Issue by Dunbaratu** [KSP-RO/RP-0#1280]
On this page:
https://github.com/KSP-RO/RP-0/wiki/New-Career-Settings

Under this heading:
Choose and Setup your Desired Space Center

It says to FIRST click the tracking center to pick your starting space center, and THEN spend upgrades in the KCT window.

This is massively confusing because when you start a new career KCT pops up a window which has a "spend upgrades" button on it, and furthermore this window is a modal dialog that stops you from clicking the tracking center, making it unclear how you're meant to pick the starting space center before spending upgrades, when the spend upgrades button MUST be used before the tracking center is clickable.

The order that actually works is this:
1 - Click KCT's "spend upgrades" button, BUT don't actually do anything with the dialog box that it pops up.  Just close it again right away without spending anything.  Doing this clears out its UI locks that were preventing you from clicking the tracking center.
2 - NOW it will let you click the tracking center to pick a launch site.
3 - Then go back into the KCT's main control window and spend the upgrade points that you avoided spending in step 1 above.

**Comment by Dunbaratu** [comment]
A secondary note about that same thing - KSC Switcher now has to be installed as a separate mod in order to be able to do that, and you don't get KSC Switcher by default if you follow the instructions as given on the RP-1 install page here: https://github.com/KSP-RO/RP-0/wiki/RO-&-RP-1-Installation-for-1.8.1
I think the functionality of KSC Switcher used to be baked in to RSS, but now it's separate.  (And the instructions explicitly do state to uncheck *all* recommended and suggested mods, so following them as written seems to result in an install that won't let you do what the "new career" instructions are talking about.

**Comment by siimav** [comment]
KSCSwitcher is in the recommended list and we will change the install guide to direct the player to install all the recommends unless they know what they're doing.

**Comment by siimav** [comment]
Should be good now
