### ISSUE TITLE
Solar cell planner does not update when changing panel size

### ISSUE THREAD

**Issue by Ramh5** [KSP-RO/RP-0#1284]
KSP RO 1.8.1

The output at pe and ap do not update when changing the panel sizes. It updates correctly when changing celestial body.

![unknown (1)](https://user-images.githubusercontent.com/16180873/84037429-96377380-a96c-11ea-800c-4b42edea8df0.png)
![unknown](https://user-images.githubusercontent.com/16180873/84037434-9768a080-a96c-11ea-9b7b-a7996aef10ad.png)

**Comment by DRVeyl** [comment]
Issue is with the planner in RO.  Fixed with: https://github.com/KSP-RO/RealismOverhaul/pull/2311
