### ISSUE TITLE
Avionics and throttle issue

### ISSUE THREAD

**Issue by 711hancer** [KSP-RO/RP-0#1291]
I am having a weird issue with one particular rocket design.
I have valid avionics able to make full attitude control over a 19t rocket. (I have no problem with avionics design)
Real fuels and tank design always ensure very stable propellant flow.
The engine used have guaranteed 60 seconds burn (used many times with nearly 2-5% error margin on other designs).
When the rocket reaches around 230-260 m/s speed with 90,90 heading and pitch (straight up) the throttle goes to zero "momenteraly" (like 1 seconds or so) and reverts back to 100%, which is enough to kill the engine and ruin the launch.
If I use KoS and use the command "lock throttle to 1." I dont have this issue and things run smooth.

What could be the cause?

**Comment by Capkirk123** [comment]
Do you have mechjeb dynamic pressure limiter on or something?

**Comment by 711hancer** [comment]
I tried it with mechjeb disabled. Dynamic pressure is also not that high at 3000m with 230m/s. I also tried it with and without realantennas or remotetech.  The same design works also nice without avionics as well.

It is related with avionics somehow.

**Comment by 711hancer** [comment]
Ok i tried to replicate the issue with a supersonic plane and now I confirm that its mechjeb related.

Thank you Capkirk123.
