### ISSUE TITLE
Insufficient Avionics Bug When Sizing Avionics Controls

### ISSUE THREAD

**Issue by emorikawa** [KSP-RO/RP-0#1295]
Occasionally I would get a persistent `Insufficient Avionics, Locking Controls (supports 0t, vessel NNNt)` if you ever have an avionics part that's too small for the rocket (quite common when building)

## Steps to Reproduce
1. Create a minimal rocket. (XLR41 engine, Procedural Tank w/ fuel, Procedural Avionics, B9 procedural wing)
2. First make the avionics part large. Then under the Avionics section of the part, increase the Contr. Mass to be above the mass of the rocket. Save Rocket
3. Start simulation and verify control surfaces work and there's no Insufficient Avionics error. Terminate simulation and return to rocket construction
4. Shrink the Avionics part such that the Contr. Max maximum is insufficient for the rocket, then immediately re-size the avionics part back to where it was in step 2. Resize the Contr. Mass to be above the mass of the rocket. Save Rocket
5. See that you get an `Insufficient Avionics, Locking Controls (supports 0t, vessel NNNt)` error message

For some reason, it appears that if an avionics part ever gets "maxed out", it screws up the entire avionics calculation for good. The only remedy is to completely remove the part and start over again.

Does anyone have any idea what's going on here? I'm new to RO/RP-1 and don't know how to debug this further.

## Version info:
CKAN v1.27.2
RO v12.8.1
RP1 v1.5
![image](https://user-images.githubusercontent.com/489001/86197440-602c8000-bb23-11ea-83f3-e63a99cfd891.png)

**Comment by DRVeyl** [comment]
Not a bug as such.
You drove your utilization to 100% and squeezed out the electric charge tank (because all room in the part was taken up by the avionics mass when you undersized the part). Then you launched with no electric charge, and thus you have no controllable mass.

**Comment by siimav** [comment]
Avionics are currently getting a significant UX improvement on the PAOverhaul branch. The changes also include not losing all EC when shrinking the parts down.

![spoilers](https://cdn.discordapp.com/attachments/620690446540341261/726938318826242158/unknown.png)
