### ISSUE TITLE
AIES Avionics and probe balance.

### ISSUE THREAD

**Issue by pjf** [KSP-RO/RP-0#130]
Gosh dang AIES has some good looking probe cores.

However none of them have avionics. The parts I can see in the VAB at a glance are:
## stability
- AS-4000 Satellite Bus (`explonpod`), $500, 0.75 tonnes 
  ![as-4000](https://cloud.githubusercontent.com/assets/12072/7797176/d664b6bc-032b-11e5-9ab4-3342c5a2526b.png)
- Hughes HS-333 Satellite Bus (`neptuno`), $500, 0.146 tonnes 
  ![hs333](https://cloud.githubusercontent.com/assets/12072/7797195/2bb674ca-032c-11e5-9c1f-c797a9899987.png)
- Modular Common Spacecraft Bus (`sondex2pod`), $600, 0.3 tonnes 
  ![modular](https://cloud.githubusercontent.com/assets/12072/7797206/55a8f672-032c-11e5-91d9-161ac8918cd3.png)
## scienceTech
- Boeing 702MP Satellite Bus (`Maxurpod`), $1200, 3 tonnes 
  ![702mp](https://cloud.githubusercontent.com/assets/12072/7797187/0a1bab0a-032c-11e5-98e8-aa8dba86fae3.png)

In both cases, these are _heavy_ parts, the okto2 is only 0.05 tonnes. They also all have the same power rating of 50W.

Because these parts are friggin' awesome looking, we want them to be available to players (ie, me) so they can build friggin' aweome looking craft.

So, this has me thinking about probe balance again. We could go with the idea of "cheap, light, low-powered; pick two". In the case of the AIES probes, they're cheap and low-powered, but they're _heavy_.

I suggest the following:
- Keep the tonnages as-is, because they represent real hardware.
- Keep the lowish power requirements, although we can tweak them a little. These aren't your high-powered units that can be dropped when you stage.
- Give them very favourable avionics for the power used.

The 702MP is so heavy I'd even consider pimping it out with an internal reaction wheel, bigger internal tanks, rear spoiler, and cruise-control.
## Unplaced cores

The following AIES cores aren't placed:
- AIES G1 'Nova' [2m] (`novapod`), 1.25 tonnes 
  ![nova](https://cloud.githubusercontent.com/assets/12072/7797229/9191e0d6-032c-11e5-8b56-2d151d7059be.png)
- AIES R350 'TOR' [1m] (`torpod`), 0.35 tonnes 
  ![tor](https://cloud.githubusercontent.com/assets/12072/7797243/bf36eaae-032c-11e5-8909-52a7d8768347.png)
- CubeSat Core [tiny] (`investpod`), 0.0013 tonnes 
  ![nano](https://cloud.githubusercontent.com/assets/12072/7797253/d86edb3a-032c-11e5-89df-1c3b92393432.png)
- GEOStar-2 Satellite Bus [2m] (`UAEcubplate`), 0.8 tonnes 
  ![geostar](https://cloud.githubusercontent.com/assets/12072/7797267/f783100e-032c-11e5-8ed2-15803d51cfae.png)

The TOR in particular is a good looking 1m core, it'd be nice to unlock it early to give players probe variety. The CubeSat should be a late unlock. The Nova I'd unlock at the same time as the AS-4000; it has similar dimensions, but in a circular rather than square housing.

**Comment by OtherBarry** [comment]
I completely agree with all that. Only commenting to add that despite this
being rather uninteresting from an outsiders point of view, it's really
enjoyable to read. You'd make a good writer @pjf

**Comment by pjf** [comment]
@OtherBarry : D'aww, [thank you](https://imgur.com/gallery/TmNFU)! :)

**Comment by OtherBarry** [comment]
Wow. I had missed that. Clearly not living up to my username.

**Comment by jwvanderbeck** [comment]
Given that I was the one to originally place these AIES cores in RP-0, I can't help but wonder if there was a reason I didn't place them all.  Let me take another look.

**Comment by NathanKell** [comment]
For the placed cores, they should all be at the far end of the tree since they all appear to be pretty recent satellite buses... TOR however might be configured as Pioneer 0, a very, very early lunar probe, giving an additional early option beyond the octo2.

**Comment by NathanKell** [comment]
Ah, also: if we want a 'middling' probe (circa TL4) the Sondex could be configured as the Viking 1 orbiter's probe core, which it looks somewhat like.

**Comment by NathanKell** [comment]
Sorry, should have combined these. MOAR THOUGHTS. Nova could be an upper stage avionics ring. Cubesat core could have ModuleScienceCore added as a late-game cheap no-flight-control probecore for experiments that don't need RCS.

**Comment by NathanKell** [comment]
Sorry, should have combined these. MOAR THOUGHTS. Nova could be an upper stage avionics ring. Cubesat core could have ModuleScienceCore added as a late-game cheap no-flight-control probecore for experiments that don't need RCS.

**Comment by pjf** [comment]
There's a pretty obvious use for some of the big heavy satellite cores.

Contracts.

The 3 tonne core *looks* like something a government or other agency would pay to launch into orbit.

**Comment by NathanKell** [comment]
@pjf that sounds excellent to me. FinePrint's satellite contracts can have PART_REQUEST added to them, and we can reference these parts. Also Contract Configurator contracts would make sense to use, because then we can set up polar orbits, geosync orbits, whatever, with reasonable AP/PE.

**Comment by Dasms** [comment]
I definitely believe that AIES probes deserve a spot, and that probes need re-thinking.  I am currently working on a probe that is able to land on the Lunar surface and can not for the LIFE of me find a probe that will support enough fuel to achieve 2200 Dv, I've attempted various configurations and have came up with no solutions- here is one of my closest attempts- http://i.imgur.com/GXxHHo6.jpg. Compare that to what is supposed to be its real world counterpart http://i.imgur.com/0EzuCmG.jpg And you will notice that while the craft is still quite large, the guidance unit doesn't take up the majority of the craft's volume. Also- slightly off topic, but there is a bug- Fusebox will show that I have more power gain than drain, but my probes will still run out of electrical charge during time warp.

**Comment by pjf** [comment]
Updated top post with pics of all the cores.

While I'm somewhat overrun with CKAN development right now, I'll probably be placing these into RPjf-0 without avionics, which is a precursor to me placing them into RP-0 if nobody beats me to that. :)

**Comment by pap1723** [comment]
This is awesome, but AIES is all but dead. :(
