### ISSUE TITLE
Airlaunch Changes

### ISSUE THREAD

**Issue by Its-Just-Luci** [KSP-RO/RP-0#1307]
Is there any way we could get an option added to the RP-1 in-game menu to temporarily "refund" the free airlaunch upgrades to allow players to switch between carrier aircraft? If this gets done, I could add multiple new airlaunch configurations. This would allow players to have a reason to continue using the SPH after 1956 or so... which currently is not the case, sadly :(

Since RP-1 modifies the Community Tech Tree directly, it would be simple enough to implement this without requiring any modifications to KCT, allowing this update to be worked on independent of that mod and it's developer(s)

**Comment by siimav** [comment]
Like I said, it needs to be implemented in KCT instead: https://github.com/KSP-RO/KCT/issues/18
