### ISSUE TITLE
RD-211/214 could use some tuning changes to be more relevant

### ISSUE THREAD

**Issue by MaxsimalPD** [KSP-RO/RP-0#1308]
I realize this is minor, but the RD-211 gives less thrust, with much worse performance than the RD-108/107 series, as well as the american boosters.

Given that the flyaway cost of Kosmos is listed as 7.5 million in aeronautix, it seems like this should be a cheap engine.  I'd suggest a cost of 200, instead of 400, with the RD-214 just slightly more expensive?  

Also, per wikipedia (https://en.wikipedia.org/wiki/RD-214)  the RD-211 was the basis for the RD-108/107, so maybe it should either be 1 step earlier in the tech tree, or ECM'd together?

Just trying to make this early engine, that was actually flown a lot, more useful/make sense.

**Comment by Capkirk123** [comment]
I am planning to reduce the cost, and It already does share ECMs with the RD-107/108.

**Comment by Capkirk123** [comment]
Also, its not in the 55 tech node because it would make orbit trivially easy (its not a good engine, but its still much better than the Redstone engine)

**Comment by siimav** [comment]
Tuned in #1309
