### ISSUE TITLE
probeCoreCube has misleading description

### ISSUE THREAD

**Issue by pjf** [KSP-RO/RP-0#131]
The `probeCoreCube` "Satellite Bus" claims that it "includes a small reaction wheel and a large omnidirectional antenna". However the part has *no* reaction wheel, and only a 3km omni antenna.

Solution: We should add a reaction wheel and boost the antenna. This is an expensive, late-game part.

**Comment by NathanKell** [comment]
@pjf verify your RO_Squad_Command.cfg looks like this?
https://github.com/KSP-RO/RealismOverhaul/blob/bce33011b7131f5f15e9c9aed0fb56c6e414d91f/RealismOverhaul/RO_SuggestedMods/Squad/RO_Squad_Command.cfg#L1011

**Comment by pjf** [comment]
Aye, it sure does.

Gotta dash right now, so can't MM dump the resulting part, but I don't think past me would have submitted this report if it wasn't significantly different from expected.
