### ISSUE TITLE
SCANsat Parts Disappear from VAB Science Tab

### ISSUE THREAD

**Issue by hxl11211** [KSP-RO/RP-0#1310]
KSP v1.8.1, RP-1 v1.5.
I use `NoNonRO` and `NoNonRP0` to hide unsupported parts.

Initially I have SCANsat v20.1 installed and its parts do not appear in tech tree at all. So I upgraded to v20.2 (latest).
Now the parts do show up in the tech tree, but they do not appear in the `Science` tab of VAB.

However, if I turn on the "Enable advanced mode" and show the additional tabs, I can find SCANsat parts by tech levels. They just don't show up in the `Science` tab.

**Comment by hxl11211** [comment]
This issue still exists after updating SCANsat (v20.2) and RP-1 (v1.6) to latest versions.

**Comment by Ullr-3141** [comment]
The problem still exists. Is there already a solution for this?

**Comment by Bornholio** [comment]
RP-0 does not set category anywhere for them.  

RP-0 placed items vs category sets in RO
SCANsat_Scanner   scienceHuman   %category = -1
SCANsat_Scanner2   deepSpaceScience   %category = -1
SCANsat_Scanner24   scienceAdvCapsules   %category = -1
SCANsat_Scanner32   scienceExploration    %category = -1
SCANsat_Tracker   scienceExploration  {does not set} 
scansat-multi-abi-1   advancedSurfaceScience  {does not set}
scansat-multi-modis-1 advancedScience  {does not set}
scansat-multi-msi-1   advancedSurfaceScience  {does not set}
scansat-radar-poseidon-3b-1   scienceHuman  {does not set}
scansat-radar-seasat-1 deepSpaceScience  {does not set}
scansat-resources-crism-1  advancedScience  {does not set}
scansat-resources-hyperion-1  advancedScience  {does not set}
scansat-resources-mise-1   scienceNF  {does not set}
scansat-sar-paz-1   advancedSurfaceScience   {does not set}
