### ISSUE TITLE
Accepting the First Crewed Orbit Contract does not Remove the X-Planes Contracts

### ISSUE THREAD

**Issue by pap1723** [KSP-RO/RP-0#1324]

**Comment by siimav** [comment]
But should it? Crewed orbit has a deadline of 3 years and thus it makes sense that you could continue doing X-plane flights while getting ready for manned orbit.

**Comment by pap1723** [comment]
Hmmm, I don't know. It says in the first Orbit Contract that it does. But, what you can do is take the First Orbit Contract, and then when it is time to launch, you can take one of the X-Planes contracts with it and accomplish both contracts.
