### ISSUE TITLE
Balance SCANsat Power Consumption

### ISSUE THREAD

**Issue by pap1723** [KSP-RO/RP-0#1325]
Early game LoRes Altimetry scanner has a 1 kW power requirement

**Comment by hxl11211** [comment]
Isn't there another version which consumes only 100W and also lighter?
![image](https://user-images.githubusercontent.com/59517291/88997509-e4f2f100-d2bd-11ea-91ce-5b674295c24a.png)

**Comment by pap1723** [comment]
So, it would appear that the original patch in RO is broken on setting the
Power Consumption. In the current master, there is a patch that brings it
up to v20 with the new SCANsat parts. In here, the patches are properly
applied, but IMO they are too power hungry for early game and the
rebalanced solar panels.

Thoughts?

**Comment by pap1723** [comment]
Turns out the power requirements are pretty darn accurate for most of these. I will be adding some more dimensions to this mod to flesh it out more in RP-1
