### ISSUE TITLE
RP-0 causes game to not load and continues to display "Loading expansions" 

### ISSUE THREAD

**Issue by MindlessZebra2** [KSP-RO/RP-0#1329]
RP-0 causes my RO install (clean) to get stuck in a load loop, when it reaches the last little bit and starts "loading expansions" it gets stuck there, however KSP remains completely responsive, background images and tooltips keep switching flawlessly. It is for this reason that I cannot provide a crash report, as the game does not crash, I must manually close it after being stuck there for 40 minutes (maximum time I've waited). It does not exhibit this behavior when I remove the RP-0 folder from GameData, when RP-0 is not installed everything works as intended.

I have tried verifying game file integrity and deleting contents of all @thumbs, SPH and VAB folders, this did not help. I have even tried to revert to RP version 1.5 instead of 1.6, this didn't help either.

**Comment by Rockstar04** [comment]
The game should still generate a log file in the directory where your KSP.exe is located, that may help shed some light on the loading stall.

**Comment by MindlessZebra2** [comment]
[KSP.log](https://github.com/KSP-RO/RP-0/files/5011932/KSP.log)

Towards the end, it doesn't find certain props and fails to compile them. However at the very end it shows "no expansions detected", is this a consequence of the failed compiles? I'm guessing this is what causes the symptom, but any idea what causes this?

**Comment by MindlessZebra2** [comment]
Update: Upon further inspection it seems that: RP0KCTBinder.dll is not working correctly. (It's the last line in the log)

**Comment by MindlessZebra2** [comment]
This has fixed the problem.
