### ISSUE TITLE
X-Plane Contract Modifications

### ISSUE THREAD

**Issue by pap1723** [KSP-RO/RP-0#1338]
* X-Planes (Supersonic)
  * Possible increase of speed in increments instead of randomized
* X-Planes (High)
  * Fix increase of altitude so that going difficult is not a waste of time and the optimal strategy is not 5km increases repeatedly.

**Comment by siimav** [comment]
> Fix increase of altitude so that going difficult is not a waste of time

Care to elaborate what's currently wrong with it? I personally jumped from 30km straight to 45 or 50 because going from 5km steps from then on was going to be more optimal.

**Comment by pap1723** [comment]
It seemed that the payouts were better if you went from 30 to 35 to 40 to 45 instead of doing the difficult contract from 20 to 50.

**Comment by marsh1832** [comment]
Another part of it is that unless you're rushing X-15 you usually have enough time to do all the 5's which means wasted money if you skip steps. They don't pay nearly enough to be worthwhile to do difficult.

**Comment by user1453** [comment]
Regarding increasing speed in increments, it would force protegression and designing better planes rather than waiting for rng

**Comment by marsh1832** [comment]
A large component about my plane contract pack idea is that it would use progressive challenges rather than repeatable contracts. Say if each supersonic contract was 25 or 50 m/s more than the last. Superjunkers wouldn't be all that useful beyond the first contracts and the player would have to make newer and better planes if they wanted to keep doing the contracts.

**Comment by siimav** [comment]
XPSS contract is now incremental.
Do we want the XPH contract to have +10-15% extra reward on the Difficult variant? I think I already added something like that to the downrange SR.

**Comment by marsh1832** [comment]
I don’t think so. They way I see the difficult variant is a way to more quickly progress through the sequence to the better paying contracts. For an XPH it’s not really any more difficult to do the difficult version, unless it so happens to cross a cockpit barrier. This differs from the SRs (especially aerobees) that have meaningful limits to what they can do. Personally I find myself being forced to the the SR moderate difficulty version sometimes. But with XPH it’s always a choice, not quite the same thing.

**Comment by siimav** [comment]
There's a +15% reward (doesn't apply to advance) multiplier on XPH Difficult. In certain cases it should be enough of a motivation to pick that over the regular contract. Especially if coupled with a large soft cooldown reward multiplier.
