### ISSUE TITLE
Antennae Progression

### ISSUE THREAD

**Issue by pjf** [KSP-RO/RP-0#135]
Antennae should be pretty easy to place. Below are the antennae ordered by distance commnicated. Those with ticky marks have already been placed (either merged, or on the branch I'm working on):

**Omnis**
- [x] Kommunotronski 16 `SXTAntenna` (400km) (?? W)
- [ ] AIES CommTech DF-RD Antenna `AntennaDF2` (1Mm) (?? W)
- [ ] AIES CommTech ESC-EXP Antenna `Antennaesc` (5Mm) (20W)
- [ ] AIES CommTech EXP-VR-2T Anenna `Antennaexpatvr2` (10Mm) (20W) (duplicate of RT part)
- [x] Communotron 16 `longAntenna` (4Mm) (?? W)
- [x] Communotron 32 `RTLongAntenna2` (8Mm) (?? W)
- [x] CommTech EXP-VR-2T `RTLongAntenna3` (10Mm) (20W)

**Dish**
- [ ] AIES CommTech CL-1 Dish `Dishcl1` (400Mm, 25°) (30W, 0.035t)
- [x] Comms DTS-M1 `mediumDishAntenna` (400Mm, 40°) (20W, 0.015t)
- [ ] AIES CommTech-1 Antenna `Antennacomtec1` (150Gm, 4°) (120W, 0.045t)
- [x] Reflectron KR-7 `RTShortDish2` (200Gm) (180W)
- [ ] AIES CommTech PCF-5 Dish `Dishpcf` (300Gm, 0.4°) (300W, 0.065t)
- [ ] AIES CommTech-2 Antenna `Antennacomtec2` (500Gm, 1.4°) (140W, 0.055t)
- [ ] AIES CommTech Omega-2G Dish `Dishomega2g` (600Gm, 0.7°) (160W, 0.075t)
- [ ] AIES CommTech CM-60 Dish `Dishmccomu` (800Gm, 1.2°) (170W, 0.065t)
- [x] Reflectron KR-14 `RTLongDish2` (1Tm, 0.2°) (200W, 0.05t)
- [x] Communotron 88-88 `commDish` (1.5Tm, 0.4°) (350W, 0.035t)
- [ ] AIES Comlar 1 Dish `dishcomlar1` (2Tm, 0.3°) (280W, 0.105t)
- [x] CommTech-1 `RTGigaDish2` (4Tm, 0.6°) (200W, 0.075t)
- [x] Reflectron GX-128 `RTGigaDish1` (8Tm, 0.2°) (650W, 0.07t)
- [x] Reflectron GX-256 `RO_gx256` (25Tm, 0.5°) (850W, 0.1t)

**Bugged**
- [ ] Mercury Nose Fairing `FASAMercuryCap2` (No range, but has data transmitter)

**Legend**
- ?? W - Draws less than 10W, power does not display in VAB.
- W!? - This part draws an unusual amount of power compared to tech around it, and may be a bug.

**Notes**
- The `Antennaexpatvr2` is a duplicate of the RemoteTech part, and should be removed.
- The `AntennaDF2` omni is useless in terms of gameplay. It's equal to or inferior to the RP-10 in every regard. It should either have the same stats (providing a cooler model), or stats that make it gameplay relevant (eg: longer range and lighter, but higher in the tech tree).

**Comment by NathanKell** [comment]
Awesome work!
Yes, root works always. Dish-to-dish the clamp is 1000x even, not 100x (of omni-omni or omni-dish) so it makes *extra* sense to place a gigantic dish in Earth orbit and connect to it with smaller dishes; the smaller dishes will be good to 1000x their stated range, if their stated range << big dish's range.

For balance, if memory serves we set up some antennas to be strictly better than others, to account for tech progression. Late-game antennas should mass a fraction of what early ones do, and have slightly higher range vs power intake. [This was the excel sheet used to make the RO configs](https://www.dropbox.com/s/me4rmmyej1wrqqk/RO_RT2_DISH_ANTENNAS_STATS.xls?dl=0).

What is your view on progression? It seems we have two routes here:
1. You can send probes to other planets (fairly) early on, but the antennas will be heavy / draw a lot of power.
2. You gradually unlock greater ranges of antennas; first to the Moon, then to Mars/Venus at conjunction, then further out.

Option 1 leads to some duplicated-range parts, but IMO leaves more room for player choice in terms of mission selection. Option 2 means that parts never duplicate and range is always increasing, but has a strict Earth->Moon->Mars/Venus->Outer->etc progression, rather than a Jupiter mission in 1960 (even it it requires throwing 30t into orbit for the probe, and another 30t for the receiver).

**Comment by pjf** [comment]
The KR-7 is a reasonably early unlock, and allows sending craft to the inner planets if you have one on each end. The later unlocks let you get progressively further out (see the comments in #136 as to ranges), and the root range model means that as you get higher up in the tech tree, your remote probes can get away with smaller and smaller antennae, because you have bigger and bigger ones floating around Earth. From a gameplay standpoint, that's pretty solid.

As for sending craft further out, if the range model allowed for *additive* dishes, then you *can* hit Jupiter early on, but you'll need additional dishes (potentially on both ends) to do so. If dishes are additive, then five KR-7s may give you the same range as as a KR-14, but they'll weigh more than twice as much, and use almost five times the power. This means we're never duplicating parts, but you can still do really long range missions if you like.

**Comment by pjf** [comment]
Also, the stats in the spreadsheet don't seem to match the stats I can see in game. A lot of the power consumption is off, and some of the ranges are different to what's in the sheet. I'm guessing something else is replacing the RO config, or for some reason it's not applying in the first place.

**Comment by pjf** [comment]
Also, in the spirit of RP-0 not requiring the player to have too many extra mods, the big thing we need is sensible progression of RemoteTech antennae (because we know they'll have those if playing with RT). If they have AIES installed, we can give them more options, but we should be cautious of gameplay changes that *depend* upon AIES installed. (Hence I'm tending towards them being lower-range + cheaper versions of the RT antennae, which I've done in #136 using the ranges they currently display in the VAB.)

**Comment by pjf** [comment]
I've applied RO from git that includes KSP-RO/RealismOverhaul#195, and here's my assessment of the AIES antennae:

- The `Dishcl1` weighs more than the DTS-M1, has poorer coverage, and requires more power. It rapidly loses relevance, wherever it's placed. I don't like its current stats.
- `Antennacomtec1` (150Gm) and above are sufficient to hit Mars regardless of positioning, assuming a symmetrical dish connection.
- There are a *lot* of AIES dishes in the 300-800Gm range.
- There's only *one* AIES dish with a Tm range (the `comlar2`)
- The AIES omni antennae are lackluster. One's a duplicate of a remotetech part. One's a not-as-good version of the DP-10.

My suggestions:

**Dishcl1**

Repurpose the `Dishcl1` to be a lightweight, low power, lunar-capable dish, which *requires* a more powerful dish on the other end. If we give it a range of 160Mm, then a `Dishcl1` to `DTS-M1` link give us `160+sqrt(160*400)=412`Mm, enough to cover the moon at apogee, but not enough that two `Dishcl1`s can establish an Earth-Moon link by themselves.

**Antennae types**

Have two "lines" of antennae. "Commlink" antennae are heavier, and require extra power for signal processing, but provide additional range. They're the sort of things you'd launch into Earth orbit to provide your deep space network. "Probe" antennae are lighter and lower-powered, but have much shorter range.

Under this system, asymmetrical links become common. Jupiter is 1Tm away on a bad day, but your 200Mm dish can reach it if it connect to the 4Tm super-array. Rather than using a 2×4Tm symmetrical link to reach Pluto, you could use a 2Tm dish talking to a 25Tm communications array.

Ideally, multiple dish antennae pointing at the same target become additive (so you can be build long-range satellites early on, if you're willing to devote the resources), but this would likely require changes to RemoteTech (AFAIK only omnis are additive).

Super-ideally, we'd require a certain probe core on the vessel be installed for the commlink-level dishes are usable. This gives real meaning to some of the heavy cores, and further differentiates the two antennae classes.

I'd suggest the *folding* antennae be commlink-class (they look like they deserve to be on comms satellites), and the hard dish antennae be probe-class. That would make the KR-7 (200Gm) and KR-14 (1Tm) probe dishes, and the 88-88 (1.5Tm) and GX series (8Tm and 25Tm) our commlink dishes. The DTS-M1 remains a versatile, local-space antenna for the Earth's SOI.

If we go this route, then:

- Commlink dishes should unlock earlier. Players can try to use two commlink-class dishes if they really want to push their capabilities.
- We should nerf the range of the KR-7 and KR-14, lower their power requirements, and potentially their weight. Bringing the KR-7 down from 200Gm to 50Gm means a player can still get past Mars at apogee using a 1.5Tm commlink, but two KR-7s talking to each other remain limited in their range.
- We should increase the weight and power requirements of the 88-88 and GX series dishes.
- We should make it clear from the title or description what class an antenna is in.
- Antennae descriptions should suggest some asymmetrical combinations for common missions (Moon, Mars, Saturn, etc).
- Under this scenario, the AIES pack primarily increases the variety of probe dishes available, rather than commlink dishes. The system can work as-intended with just RemoteTech.

It's late in Melbourne now, but thoughts and feedback welcome.

**Comment by OtherBarry** [comment]
That sounds super smart. Not sure if it's mentioned anywhere, but if we're
relying on using the root model, we should ensure that all of the users are
very well informed that thy should be using it. Otherwise you'll get a lot
of people complaining about their sats not working or struggling with the
game.

Another thing to note, is that IIRC, the RemoteTech settings file that has
all the RSS sites in it, uses additive and 10x distance modifier, so we may
want to account for that.

Particularly like the suggested combinations in the description. Gives a
better idea of how they work too.

**Comment by jwvanderbeck** [comment]
I only skimmed this, but one other thing I encourage you to keep in mind is
transmission data rates and power efficiency for transmutation of data.
When you have multiple antenna options based on range and weight, you might
favor one over another based on these properties.  Also stats wise power
efficiency and data rate should generally be opposed.  Better power
efficiency means lower data rates, and higher data rates means using more
power for transmission.  You decide upon speed versus power use when
transmitting science reports.

- John Vanderbeck
- http://www.johnvanderbeck.com

**Comment by NathanKell** [comment]
@pjf I agree very much with that, excellent. For that reason, as @jwvanderbeck  says, might consider making the 'commlink' antennas have lower electricity usage for data transmission (as well as for normal operaton) and the probe ones comparatively more, thus going a bit of a ways to equalizing wattage required for link stations and probes (rather than the stations requiring incredible quantities of solar panels and probes very little).

**Comment by pjf** [comment]
>  I agree very much with that, excellent. For that reason, as @jwvanderbeck says, might consider making the 'commlink' antennas have lower electricity usage for data transmission (as well as for normal operaton) and the probe ones comparatively more, thus going a bit of a ways to equalizing wattage required for link stations and probes (rather than the stations requiring incredible quantities of solar panels and probes very little).

To be honest, I was looking at doing the opposite, or otherwise keeping them roughly the same. It makes sense that probe antennae are lower powered, you can afford to lift more power generation equipment into LEO than off to Mars, and we're arguing one of the reasons for greater range is extra power costs of signal processing on the commlink antennae.

In my experience, data transmission rate rarely matters with stockish-science, since you can buffer as much data as you like. However I'd love to see something like RealScience cap the science gains based upon maximum transmission rate, so a high-value imaging experiment also needs to come with a high-bandwidth antenna to gain full value.

**Comment by NathanKell** [comment]
That makes sense to me. Haven't seen @jwvanderbeck around so dunno about it getting in though.

**Comment by droric** [comment]
I grabbed these ranges from a CFG on the OP for US Probes.  Do they seem appropriate?

Said config was found here. http://forum.kerbalspaceprogram.com/threads/93389-1-0-2-US-Probes-Pack-Old-and-New-v0-33-5-Release-5-10-15

# Pioneer Interplanetary Probes should have longish ranges as they are supposed to leave the SOI
Pioneer 0/1/2 + 3/4 - 20,000 KM / 20 MM (Omni)
Pioneer 5 - 8E8 / 800 MM (Omni)
Pioneer 6/7/8/9 - 1E9 / 1 GM(Omni)
Pioneer 10/11, Ulysses, Voyager, New Horizons, Surveyor - 2.5 MM Omni, 300 GM Dish
Aura, Aqua, Terra - 5 MM Omni (earth observing sats)
Dawn, NEAR, Stardust - 2.5 MM Omni, 34 GM Dish
Deep Impact - 2.5 MM Omni, 50 GM dish
Deep Impact Impactor, Stardust collector - 5 MM Omni
DS1 - 2.5 MM Omni, 90 GM dish
Galileo Dish Actual - 52 GM
Galileo Dish Intended - 80 GM
Galileo Atmospheric Probe, Galileo Main Body - 5 MM
Magellan - 2.5 MM Omni, 5 GM Dish
vanguard-1,vanguard-2,vanguard-3,grab-1,transit2a,tiros-1 - 1 MM Omni
TDRS, TDRS_AG - 2X 20 GM Dishes, 200 MM dish, 2.5MM Omni

**Comment by NathanKell** [comment]
Hmm. On the one hand that looks fine to me given the rangemodel, on the other that's fairly lower than how RT parts are configured.

I'm not sure whether the proper response is to up these values, or lower RT's values. RT's values were done before I added the DSN stations.
