### ISSUE TITLE
Stickiness issue with all the launch towers there are...

### ISSUE THREAD

**Issue by ErinaceusLinnaeus** [KSP-RO/RP-0#1361]
...and holy cow (Nice): There are more than the two I remember.

Hi.
I tried to get back into RP-1. Loved playing this overhaul two years ago (was it still RP-0 then?).

Anyway. Got so far as to experiment with rockets to tackle the 3000 km downrange contract as the launch towers suddenly started doing weird things.
Sometimes (more often then not) when I launched a rocket the launch tower released it asymetrically. Tried to use another launchtower, sometimes it worked, sometimes it didn't. Tried reloading/resetting to launch. Sometimes that fixed it. Many times it didn't or even made upper parts of the rocket explode.
Reinstalled KJR as I remembered experiencing exploding rockets on scene load from years ago. Maybe that did something, because it fixed that issue for a while, but eventually it started happening again.
Started to launch on fins and use tiny girders at the bottom of one fin to realise angled launches. But got frustrated, as this is not the best solution and sometimes makes the rocket jump in a funny way or even performing a ballet, when loading the scene.
Got even more frustrated, tried the launch towers again....and gave up.
That was two weeks ago.

I'm sorry I can't provide logs, because my windows informed me two days ago that it doesn't want to start and needs a reset.

Maybe this issue is known and I did something horribly wrong when installing.
But if you have no idea what I´m talking about, I can try to reinstall and reproduce this.

**Comment by szundi** [comment]
I experienced this, like launch towers toss the rocket when releasing it. Now I always use 2 of them symmetrically. I cannot even use clamps because of this.

**Comment by siimav** [comment]
Using clamps in symmetry is a good suggestion. KJR rigid clamp option is now also disabled by default since quite a few people had issues with it. It's also known that some clamp parts are a bit buggy and can clip into the vessel.
