### ISSUE TITLE
Error Loading KCT Data 

### ISSUE THREAD

**Issue by TNT599** [KSP-RO/RP-0#1379]
I get the message Error Loading KCT Data at start of loading a save the logs are attached. The pop-up says the game will be unplayable from that point on and to report this as a bug.
[KSP Logs For Error.pdf](https://github.com/KSP-RO/RP-0/files/5395629/KSP.Logs.For.Error.pdf)

**Comment by TNT599** [comment]
If you need more information I can try to load the Game again.

**Comment by siimav** [comment]
First thing I noticed is that there's no RealFuels installed

**Comment by TNT599** [comment]
It is a manual install

**Comment by TNT599** [comment]
It is under ModularFuelSystem-rf-v12.8.5

**Comment by siimav** [comment]
ModularFuelSystem is for stock. RO/RP-1 needs RealFuels.

**Comment by TNT599** [comment]
It is on the RealFuels GitHub. The .zip is extracted and the folder is called ModularFuelSystem-rf-v12.8.5

**Comment by Capkirk123** [comment]
That is the wrong place to download realfuels from, you need realfuels from the RO github. Follow this install guide https://github.com/KSP-RO/RP-0/wiki/Installation

**Comment by TNT599** [comment]
Oh
Anything else that would cause this problem?

**Comment by TNT599** [comment]
So not here:
https://github.com/NathanKell/ModularFuelSystem/releases/tag/rf-v12.8.5

**Comment by Capkirk123** [comment]
Not following the install guide here: https://github.com/KSP-RO/RP-0/wiki/Installation

**Comment by TNT599** [comment]
Ok thanks
