### ISSUE TITLE
Procedural Avionics panel is oversized in 1.10.1

### ISSUE THREAD

**Issue by branan** [KSP-RO/RP-0#1384]
I've frankensteined together a 1.10.1 install. It all seems to be functional, except that the procedural avionics panel takes up the entire width of the screen rather than whatever width it's supposed to be for its content. Screenshot and log attached.

![screenshot0](https://user-images.githubusercontent.com/37594/97116048-e747ca00-16b7-11eb-99ad-547f2db78dc4.png)
[KSP.log](https://github.com/KSP-RO/RP-0/files/5435673/KSP.log)

**Comment by todi** [comment]
That seems to be a general problem with 1.10.1. Mechjeb has the same problem, as well as KCT.

**Comment by todi** [comment]
I did some digging. The bug seems to be caused by some weird interaction with RCSBuildAid. Replace it with RCSBuildAidContinued as a workaround. I'm still trying to figure out the exact source of the bug.

**Comment by todi** [comment]
Reported at https://github.com/m4v/RCSBuildAid/issues/44

**Comment by branan** [comment]
Interestingly, KCT (from RP1) and Mechjeb seemed to work correctly for me.

Either way, I've confirmed that switching the RCS Build Aid version did the trick. I've subscribed to the issue over there, so I'll be able to follow up and help test when there's a fix. Thank you!

**Comment by branan** [comment]
Finally had a chance to test this - looks like RCSBuildAid 1.0.3 did the trick.
