### ISSUE TITLE
Not starting

### ISSUE THREAD

**Issue by jultomtenreal** [KSP-RO/RP-0#1407]
![image](https://user-images.githubusercontent.com/68858896/99932781-64b73680-2d59-11eb-87b5-b1b7b47bfa3b.png)

The game just stops loading for some reason

**Comment by siimav** [comment]
These errors are a sign that there's something wrong with your install. It's probably best to start over with a clean copy of KSP 1.8.1 and to follow the instructions page: https://github.com/KSP-RO/RP-0/wiki/RO-&-RP-1-Installation-for-1.8.1
