### ISSUE TITLE
[1.10.x] Firing original kerbals then re-hiring them after their retirement date causes them to immediately retire

### ISSUE THREAD

**Issue by branan** [KSP-RO/RP-0#1409]
I mentioned this in the Discord a couple of days ago. I took some time today to categorize it a bit better.

KSP 1.10 introduced a change which prevents you from losing any of your original four kerbals by firing them - they are now always available in the to-hire list so you can get them back.

When those kerbals are re-hired, they retain their original retirement date. If that date is in the past, they'll immediately be marked as retired. Confusingly, RP-1 will calculate a new retirement date and pop up the dialog to tell you this, but it doesn't seem to actually take effect.

I don't know what properties the game is actually using to preserve these kerbals in the list of applicants. From my zero KSP modding experience and a few minutes reading the API docs, setting `veteran` and/or `isHero` to `false` on those kerbals when the retirement date is calculated may be a fix?

This is pretty easy to reproduce - just fire your original astronauts then fast-forward a decade or so.

**Comment by siimav** [comment]
Should probably just remove the Veteran status from all the starting nauts. The status nor the orange suit aren't really meaningful in RP-1 anyway.

**Comment by branan** [comment]
:+1:

I'm in the process of getting a KSP development environment set up, so I ought to be able to put up a PR for that in the next couple of days

**Comment by siimav** [comment]
For reference, this is where I would personally add that code: https://github.com/KSP-RO/RP-0/blob/master/Source/Crew/CrewHandler.cs#L199

**Comment by branan** [comment]
Looks like setting `veteran` to false didn't work (possibly it uses `isHero`, which we unfortunately can't set from code).

What did seem to work is moving the crew member from `Applicant` to `Crew` at retirement - this properly flags the kerbals as dead in the Lost list. I'm testing one more fixup to prevent firing then re-hiring just before retirement to extend retirement dates, then I'll have a PR ready.
