### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by mahmoudahmed133** [KSP-RO/RP-0#1427]
I have been waiting for the loading screen for more than 10 minutes and after playing short time the game Crash
[error.log](https://github.com/KSP-RO/RP-0/files/5878602/error.log)
This always happens please help i can't play like this

**Comment by siimav** [comment]
My guess is that you ran out of memory

**Comment by mahmoudahmed133** [comment]
@siimav omg 12gb not enough
I think I'll buy 12 more
thx
