### ISSUE TITLE
Engines doesn't appear in staging

### ISSUE THREAD

**Issue by ACH1980** [KSP-RO/RP-0#1437]
As above engines doesn't appear in staging and can therefor not be staged which leads to 0 Thrust. I've tested with the 2 unlocked SRBs which is 1 from RP-0 and the other one isn't. 

I think this is caused by RP-0, but I'm not sure to 100%...
![20210307154009_1](https://user-images.githubusercontent.com/39656381/110243761-09056780-7f5c-11eb-842c-4422b4baa30c.jpg)

**Comment by siimav** [comment]
These parts aren't even supported by RP-1. Also judging by the toolbar icons, this doesn't appear to be anything like a regular RP-1 install.
Please follow the install guide [here](https://github.com/KSP-RO/RP-0/wiki/RO-&-RP-1-Installation-for-1.8.1) to get started. There's a lot of other useful content in the wiki sidebar as well.

**Comment by ACH1980** [comment]
After doing this KSP doesn't even start. Has anyone tested this with KSP 11.1 or could it be incompatible?

**Comment by siimav** [comment]
As the install guide states - only KSP 1.8.1 is supported right now.

**Comment by Robbie75** [comment]
I can actually confirm that everything does work in 1.11, however the setup is NOT for the average user, as it can be complicated to get everything to cooperate. Best bet if you have the slightest doubt is to stay with the version that is supported.

**Comment by ACH1980** [comment]
Ok, so I think it's better when using 1.11 not to use RO, right?

**Comment by ACH1980** [comment]
I don't do anything from that. I reinstalled KSP and just don't use RO/RP1, but with other mods that make KSP more realistic ^^
