### ISSUE TITLE
[1.11.1] Incorrect Experimental Parts and Build Plans button location

### ISSUE THREAD

**Issue by dgfl-gh** [KSP-RO/RP-0#1449]
The 2 KCT buttons are displaced and overlap the stock flag button:
![image](https://user-images.githubusercontent.com/43384369/112384032-2f622b80-8cee-11eb-9451-1c52c777fc4d.png)
tested in 1.11.1, 1600x900 resolution, error appeared the second time I entered the VAB, not the first

a solution might be ditching absolute screen coordinates and fetching the stock "new craft" button position instead

**Comment by siimav** [comment]
I rewrote that code so hopefully it's fixed now.
