### ISSUE TITLE
Reverting TO VAB/SPH from simulation in the past advances KCT construction/research time

### ISSUE THREAD

**Issue by RojinBaka** [KSP-RO/RP-0#1465]
e.g. Year is 1954
- add 300 days worth of research in to queue.
- run a simulation from VAB/SPH at 18h (with 'from now' unchecked)
=> game sets temporary date to 1951
- revert to VAB/SPH
=>game advances time to the moment when simulation was started (1954) 
=> all research is done.

RP-1 1.8.1

**Comment by siimav** [comment]
I'm unable to replicate this issue

**Comment by amesnard0** [comment]
I have the same issue. It only occurs when you launch something in the simulation, not if you revert immediately.

**Comment by siimav** [comment]
I suspect this issue might've gotten fixed since last release with #1459

**Comment by siimav** [comment]
Haven't gotten any such reports in a long time.
