### ISSUE TITLE
Veronique Starting Config - Bump to the N version?

### ISSUE THREAD

**Issue by Theysen** [KSP-RO/RP-0#1473]
Say you're following a non WAC / Aerobee playthrough, the starter config upon unlock for the Veronique represents the R version - which fired for 6 seconds as a demonstrator. 

* Should the N version be included upon unlock of Early Rocketry to make it a little more feasible sending up lighter rockets with a ESA-focused approach?

**Comment by siimav** [comment]
https://github.com/KSP-RO/RP-0/commit/76f9bf03db4554b8e206fb653062d41644f6fe3a closes the issue?

**Comment by NathanKell** [comment]
I knew I had a reason it was on my to-do list. Yes it does

Sent by my thumbs, slowly.
