### ISSUE TITLE
v1.8 for 1.10.1 Install Instructions Unclear

### ISSUE THREAD

**Issue by MacKenzieHnC** [KSP-RO/RP-0#1476]
The install instructions are missing the "Essential Extra Mods" section. Following the instructions exactly leads to missing mods (e.g. Kerbalism). It is hinted at to install the suggested mods, but it doesn't have an explicit step

**Comment by lpgagnon** [comment]
https://github.com/KSP-RO/RP-0/wiki/RO-&-RP-1-Installation-for-1.10.1#main-installation

> most recommendations are indeed recommended and should be installed unless you know what you are doing. Do note that some of the recommended mods have to be chosen from 2 options:

> Kerbalism - RealismOverhaul Config or TACLS: [...]

what would be clearer?

**Comment by MacKenzieHnC** [comment]
Something that says at which stage they should be installed, and maybe something that clarifies that "most". The line you quoted comes immediately after being told in all caps not to install the recommended mods

**Comment by leudaimon** [comment]
Are you sure you are following the 1.10 instructions? There is no mention to not installing recommended mods that I can see. Additionally, the instructions clearly say you should install everything through ckan in one go...

**Comment by MacKenzieHnC** [comment]
> Do NOT let CKAN install any "Suggestions", but most recommendations are indeed recommended and should be installed ...

Okay, I can see that now. Maybe just something like putting "Recommendations" in quotes to symbolize that it refers to the heading the same way quotes are used around "suggestions" earlier in the sentence?

I had read it as something like "do not install the suggestions yet, but you will in a later step".

**Comment by siimav** [comment]
Looks like @leudaimon made the edit
