### ISSUE TITLE
Solid entrycosts are busted

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RP-0#1495]
From a quick check: Nike is not fiber, nor is GCRC; that was what made Altair special and such a high performance revelation. Also other fiberglass case motors should get the solidsFiber ECM. And basically everything past the Tim should require solidsHollow (except sep motors I guess?).

That should mean solidsHollow becomes cheaper and solidsFiber more expensive. Also it's super weird that the Castor (XM-20) is cheap to unlock but the T17-E2 requires it but _then_ adds another 10k funds on top. So there's a bunch of stuff that needs a sanity check.

<EDIT> removed ref to NGNC, Kirk set me straight>

**Comment by lpgagnon** [comment]
In addition to entry costs:
- Nike part cost is 360, vs 100 for Castor 1 (XM-20). 3x 2.5ks18000 gets roughly the same performance as 1 Nike for ~1/3 the cost, and unlocks 1 node earlier. Even if Nike's entry cost comes down, it's still a trap to use it
- 18KS7800 is weirdly placed in the 1956 node; it's a sounding rocket upper stage that unlocks right when the sounding rocket era ends

(from #1490, originally reported by Marsh)

**Comment by marsh1832** [comment]
I agree about the 18KS7800, it comes too late to be of any use to sounding rockets, and it’s inferior to the rest of the solids in 1956.

The Nike has two problems, it’s ECMs/unlock cost, and the build cost. It’s vastly inferior to a castor, and beyond a small boost off the pad it can’t really be used for an LV, which means it’s only application is a sounding rocket. Critically, it needs to be priced appropriately for an aerobee rocket.

**Comment by lpgagnon** [comment]
This one may be fine, but since we're here, maybe worth taking a fresh look at how justified this cost imbalance is:
1 GCRC: 170 funds
A full stack of Juno 1-style Baby Sergeants, T17-E2: 15*60=900 funds (plus decouplers)
Upgraded to JPL-532A: 1350 funds

(Castor's 150 funds is starting to seem like the outlier)

**Comment by lpgagnon** [comment]
Another thing worth looking at is how Fuel cost factors into part cost. For the early solids, fuel is a small fraction of the cost (1/170 for gcrc, 19/150 for castor), but some of the later ones are just broken. AJ-260 costs -16000 funds when empty, UA1204 -800, etc (both PBAN, maybe a clue)

**Comment by NathanKell** [comment]
We probably should just make solid propellant cost 0, since it's just part of the SRM cost. Or at least reduce its cost by a ton (you can't really save money by under-loading an SRM...)

The baby sergeants are definitely busted, yes. And agree on Nike base cost, and the tech node discussion for SR motors.

**Comment by NathanKell** [comment]
Later todos:
- [ ] Fix propellant types. PSPC should be starting tech, high variance. NGNC is actually double-base, and comes in with Altair (maybe GCRC/Castor?). Antares I was almost certainly not PBAN, since it is a contemporary of Altair. Probably NGNC.

**Comment by NathanKell** [comment]
@lpgagnon @marsh1832 have a peek please.

**Comment by marsh1832** [comment]
Looks good from what I can see, this will make solids much more viable both in the SR era as well as leading into orbital. Hopefully I'm reading all of this right, that knocking 1956 solids down from sat mat science should dramatically increase their value, in a career that uses solids. The costs all seem okay from here, I'm eager to start a new career with all the numbers to see how they work out. The fuel and materials progression looks really cool. Did you touch the baby sergeant costs, or is that for another time?

**Comment by NathanKell** [comment]
Oh heck I fixed entry cost for T17 but not base cost. Meant to

Sent by my thumbs, slowly.

**Comment by marsh1832** [comment]
Also I should mention that when I changed the costs for the Nike, the cost was doubled somewhere, has that been fixed? In other words, I wanted a cost of 100, so I had to put in 50 so that it appeared 100 in game. I never noticed that for any other part I have adjusted.

**Comment by NathanKell** [comment]
Yes the engine config for it had a cost, removed it

Sent by my thumbs, slowly.

**Comment by lpgagnon** [comment]
All looking good to me. Algol IB's entry cost still stands out a bit (75k after all shared costs paid), no idea if that's justified.

**Comment by NathanKell** [comment]
@lpgagnon Polaris is 20k and Minuteman is 30k, and then Minuteman depends on PBAN and Polaris on HTPB. Both HTPB and PBAN share the aluminum ECM and the Fiber ECM.

**Comment by NathanKell** [comment]
Closed by #1503
