### ISSUE TITLE
Feature Request: Apply material technology level to fairings

### ISSUE THREAD

**Issue by NoMrBond** [KSP-RO/RP-0#1509]
Currently there is no structural/material advancement in fairings, the ones you can build as soon as they're unlocked are materially identical to any built further through the years

Please consider having Fairings benefit from material advancements in terms of mass, strength, heat-rejection, radio-transparency or other factors as the various materials (alloys, composites, carbon-fibre etc) are developed/deployed and used for their construction with commensurate increases in their cost & complexity.

**Comment by siimav** [comment]
Implemented in #1782
