### ISSUE TITLE
[1.9.1] Stability tech node only includes the KDU-414 engine

### ISSUE THREAD

**Issue by ChrisWarner-Sage** [KSP-RO/RP-0#1519]
On a fresh install of the newest release only the KDU-414 engine is present in the stability tech node. It is my understanding that it should also include (at least) the ranger / mariner propulsion system engine.

**Comment by ChrisWarner-Sage** [comment]
Informed that this will be fixed in the next release

**Comment by NathanKell** [comment]
Closed by #1518  - cheers!
