### ISSUE TITLE
Moving costs into RO?

### ISSUE THREAD

**Issue by pjf** [KSP-RO/RP-0#152]
RP-0 has a lot of part costs. In particular, we have:
- Known (or best estimate) costs, based upon real parts and figures.
- Gameplay friendly costs, based upon game balance.

Many of the engines fall into the first category, whereas many structural pieces fall into the second (especially those placed by me).

I want to gauge the opinions on moving the realistic costs into the base RO package. This means folks using RO (but not RP-0) can have more realistic costs when building craft, and it means other mods (including other career modes) making use of RO can _also_ use those costs.

In the spirit of solving one's own problems I'd be updating the RP-0 build system to allow one to write `cost: inherit` to use the cost from RO, and write the patches myself for RO. But I don't want to do this if there are good reasons why it shouldn't be done. :)

If you're wondering why I'm even thinking of this, it's because every few weeks I think about how awesome it would be to have unROCK (un-Realism Overhaul Career for KSP), which would have realistic physics and bodies, but unrealistic resources and career progression, and which would be aimed more at stock players than RO players. More importantly, moving the costs upstream allows other people to write their own RO career mods with realistic pricing, which would be grand. :)

**Comment by NathanKell** [comment]
I'm perfectly fine with this. Costs for various engine CONFIGs already got ported over.

**Comment by Schnobs** [comment]
This reminds me that a good while ago, I offered to help. Fixing prices is something where even I can be of use... I hope. Frankly, I don't have any idea of what would be a fair price for anything.

**Comment by pap1723** [comment]
This can't really happen anymore with rollout costs and ECM's
