### ISSUE TITLE
Could PAPI lights have a config created for RP-0?

### ISSUE THREAD

**Issue by Arkhorse** [KSP-RO/RP-0#1530]
PAPI lights would be amazing for RP-0. The git which is most recent is this one https://github.com/linuxgurugamer/PAPIPlugin. Find it easier to land with them.

**Comment by NathanKell** [comment]
This doesn't seem related to RP-1. RP-1 is a career mod. It's not up to RP-1 where you launch from (and thus what PAPIPlugin config you need).

**Comment by Arkhorse** [comment]
PAPI lights can be configurated for all the strips on Earth. Just like the three in the base game. Adding PAPI lights is directly related to Realism as they are used at real airports. So it makes sense to add them.

**Comment by lpgagnon** [comment]
That's an argument for maybe adding to https://github.com/KSP-RO/RealismOverhaul, not to RP-0

**Comment by Arkhorse** [comment]
Oh. Wasnt aware of the difference. Thanks for the links :)
