### ISSUE TITLE
Procedural avionics not working

### ISSUE THREAD

**Issue by MustardisMurder** [KSP-RO/RP-0#1538]
I'm having this issue with procedural avionics where the first one I place down works perfectly fine and I have no issues, but when I have a second procedural avionics on the same craft and add x amount of control mass, that second one won't actually add the control mass I specified and will not control at all.

**Comment by jwvanderbeck** [comment]
Avionics "control tonnage" does not stack.  Only the highest single unit applies.

**Comment by Manuel-Bobadilla** [comment]
Is this a new feature?, because when i was playing the mod 1 year ago (if i remember good) the avionics control capacities stacks

**Comment by jwvanderbeck** [comment]
relatively

https://github.com/KSP-RO/RP-0/releases/tag/v1.9.1

**Comment by MustardisMurder** [comment]
oh, well if I asked this earlier it would have saved about 2 hours of head scratching.
