### ISSUE TITLE
Simplifying Installation

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RP-0#1539]
Counterpart to netkan issue https://github.com/KSP-CKAN/NetKAN/issues/8688 - let's keep all purely KSP-RO stuff here rather than on CKAN.

Copied over @ppboyle 's points:
Here's a few things that might be helpful:

1. Swap need to add 'nonNonRP0' to requiring a 'NonRP0' folder to be able to see the nonRP0 parts - default experience should be to not see them. Ditto NonRO, and then most people can ignore the 'add empty folders' step.
2. We should make sure some mods like TUFX, B9 Aersoapce Proc Wings and Distant Object Enhancement work with their CKan versions - I know I manually installed them and when I checked the manual install was ahead of the Ckan version. I think these are fine though, and just need to be taken off the 'manual install' list in the wiki?
3. Is there any good reason to have to add a separate repository just to get Mechjeb Dev? Not real clear on this, why not just a separate MechJeb-RO in the main repository?
4. Don't mention Principia on the main install page + all its disclaimers. Move it to the separate 'optional' mod page - it's more optional than most mods.
5. What can we do to make as many of the visual enhancements, that I do think most players install, easiest to get?
6. Update the wiki to point at the fastest, default-est set of install options up at the top, removing all the manual install instructions for the visual mods that we can get off of c-kan. (I can do that if needed?)
7. Clean up the 'suggested' list in the ckan install, add a few newer mods that got configured. Like modular launch pads for instance.
8. Clean up the extra recommended mods section, make a 1.10 version, its a bit of a mess, as it lists a bunch of mods that are required and not really optional, probably doesn't list some that people could install, etc. Every mod that comes up as 'suggested' when you install RP-1 from ckan should be here in some fashion.

@StonesmileGit 's reply:
Regarding KSPBurst; that is a dependency of Real Antennas, used to increase performance. You would have to ask the creator (dkavolis) why the 'lite' version exists.

There is also one issue currently with the recommended list; We recommend both Ven's and Restock (you should get one), but since they conflict, the standard choise in CKAN is to have none of them selected. A solution could be to have something similar to the texture selection / KSPBurst screen.

**Comment by NathanKell** [comment]
> @ppboyle sez:
> Here's a few things that might be helpful:
> 
> 1. Swap need to add 'nonNonRP0' to requiring a 'NonRP0' folder to be able to see the nonRP0 parts - default experience should be to not see them. Ditto NonRO, and then most people can ignore the 'add empty folders' step.

Heartily agree. I also want to swap to hard-deprecating rather than merely hiding these parts since it will significantly speed up load time if they don't have to be compiled.

> 2. We should make sure some mods like TUFX, B9 Aersoapce Proc Wings and Distant Object Enhancement work with their CKan versions - I know I manually installed them and when I checked the manual install was ahead of the Ckan version. I think these are fine though, and just need to be taken off the 'manual install' list in the wiki?
Discussed on the CKAN side -- TUFX and DOE are fine. B9 Proc Wings is dependent on @linuxgurugamer merging my PR (or saying that he will in fact not, in which case we make a backport fork since we're going to be on 1.10 for a while).

> 3. Is there any good reason to have to add a separate repository just to get Mechjeb Dev? Not real clear on this, why not just a separate MechJeb-RO in the main repository?
Discussed on the CKAN side, but tl;dr I think it's fine if the dev version is only dev stuff and not served to all users; the issue arises (like it arose from RO/RP-1 not releasing for a long time) when the dev version is the only reasonable game in town.

> 4. Don't mention Principia on the main install page + all its disclaimers. Move it to the separate 'optional' mod page - it's more optional than most mods.
> 5. What can we do to make as many of the visual enhancements, that I do think most players install, easiest to get?
> 6. Update the wiki to point at the fastest, default-est set of install options up at the top, removing all the manual install instructions for the visual mods that we can get off of c-kan. (I can do that if needed?)

See below.

> 7. Clean up the 'suggested' list in the ckan install, add a few newer mods that got configured. Like modular launch pads for instance.
> 8. Clean up the extra recommended mods section, make a 1.10 version, its a bit of a mess, as it lists a bunch of mods that are required and not really optional, probably doesn't list some that people could install, etc. Every mod that comes up as 'suggested' when you install RP-1 from ckan should be here in some fashion.

Very much agree that section of the wiki needs work. See below.

> 
> @StonesmileGit 's reply:
> Regarding KSPBurst; that is a dependency of Real Antennas, used to increase performance. You would have to ask the creator (dkavolis) why the 'lite' version exists.
> 
> There is also one issue currently with the recommended list; We recommend both Ven's and Restock (you should get one), but since they conflict, the standard choise in CKAN is to have none of them selected. A solution could be to have something similar to the texture selection / KSPBurst screen.


Here's what I would like to do:
I want to make a simple install-wizard-like RP-1 metapackage for CKAN. It will depend (not rec) a full set of mods to get up and running in a normal install, and it will use depends/provides to give the user a few simple choices (like "detail level", which will pull in RSS textures, RSSVE, RSS-CanaveralHD/CanaveralPads, etc, dependnig on a simple choice of low/medium/high).

Once we have a simplified CKAN-installable package, I think the main install guide will be super simple: install CKAN, point it at your KSP install, find "RP-1 All In One" or whatever we call it, click check, click apply, follow the prompts. Then the "Advanced Setup" guide can take all the existing user-choice content.

With that done, then the main Install Guide page can be super simple, i.e. just
*Copy out your KSP folder
* Download CKAN
* Start up CKAN
* Check the "RP-1 All-in-One Install"
* Click Apply
* Follow the prompts.

Then all the optional/recommended/custom-setup/etc stuff can be moved to an auxiliary page.

**Comment by HebaruSan** [comment]
Noting over here because they're metanetkans, RealismOverhaul.netkan and RP-0.netkan should recommend RSSVE-Textures (see KSP-CKAN/NetKAN#8689):

> RSS should rec RSSVE, yes. (And thus by the non-transitive property of recs, RO/RP-1 should too :D ).

**Comment by NathanKell** [comment]
I've started the Express Install PR. https://github.com/KSP-CKAN/NetKAN/pull/8701

**Comment by NathanKell** [comment]
Well, this is pretty much done now, so I'm closing.
