### ISSUE TITLE
Fuel Cell are bugged

### ISSUE THREAD

**Issue by plasmeus** [KSP-RO/RP-0#1548]
I am experiencing issues due to fuel cells not working as expected. First of all, fuel cells will often display as running when they are not, and the only way to tell is to look at the flow of electric charge on the resources panel. Second of all, turning on fuel cells does not always turn them on, fuel cells often require you to hit the dump resources button and then toggle the run button to make them work. I am not sure if this is intended behavior or not, but this prevents you from getting proper behavior when binding the fuel cells to an action group and requires you to manually turn on every fuel cell at launch regardless of the settings you set in the VAB. My final issue is game-breaking: When you switch to another vessel or load a save, all fuel cells will be turned off automatically, which causes the spacecraft to lose power and any onboard kerbals to die. Strangely, the fuel cells remain on if you go straight to the space center scene but will turn off as soon  as you switch to another vessel

**Comment by siimav** [comment]
Unfortunately nothing we can do on the side of RP-1
