### ISSUE TITLE
Science reports

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RP-0#156]
Here are the first pass of experiments that should have reports added. Note that for obvious reasons the HSF stuff is low priority for anywhere except space and the Moon (and Mars).

**Note that no surface/splashed text needs to be made for Earth, since that's disabled.**

**Instruments:**
- Temperature: always available, biomes for all but spacehigh.
- Pressure: will detect trace atmosphere in spacelow, and very faint traces in spacehigh. Biome flying low, landed, splashed. Always available.
- Geiger counter (radiation sensor): Detects x-rays, gamma rays, etc. _Detects the Van Allen belts_. Available everywhere, biome all but spacehigh. **Note**: We have all we need for this instrument for Earth.
- Gravioli: It's now a geodesy experiment and measures perturbation in orbit from gravitic changes. Biome in space low and high, and landed/splashed. Only available in those situations.
- Accelerometer: it's now a micrometeorite detector. No biomes, works in all situations. FIXME: should we make it biome when landed?
- Goo: It's now a bio sample (mice, fungus, etc). Biome when landed/splashed, no biomes elsewhere. All situations.
- Materials bay: it will be scaled to 1.5m and treated as a film-return camera (CORONA, GAMBIT, Zenit, etc, or high quality scientific camera). Works space low/high and biomes in space low.

**Probes**
- Telemetry Analysis (aka probe version of crew report). Biome based in all situations except space high, available always.

**Human Spaceflight (HSF):**
- Crew reports: biome based landed/splashed, flying low, flying high, space low. Available everywhere.
- EVA report: biome based landed/splashed. Available everywhere.
- Surface sample: biome based on surfaces.

**Comment by Warp11** [comment]
Whats the geiger counter in the google form?

**Comment by NathanKell** [comment]
The geiger counter. :)
It's at the bottom.

**Comment by Warp11** [comment]
It's not there... For me the last one is the bio drill scan.

**Comment by Shurikeeen** [comment]
The probe core report added by RP-0 does not appear to be listed.

**Comment by NathanKell** [comment]
@Warp11 that's weird. @Felger I can't remember, did you give me access to the backend as well?

**Comment by NathanKell** [comment]
I didn't even have it listed here, you're quite right. Sorry it only took me **four days** to realize what you were talking about. :\

**Comment by Warp11** [comment]
All good :D

**Comment by Warp11** [comment]
Posted this on the forum thread, just gonna put it here as well:

Would you like us to put in the same text for multiple biomes if it fits or is someone going to go through it and do that? It just takes a long time for us to do that in the google form because you can't just select multiple biomes.
 And also, I think it is sensible to write pluto reports based on the New Horizons data, assuming that they will make sense when the textures are updated.

 EDIT: just saw that that you can select no biome. Would that be good as indication that it is meant for all?
And it should be possible to use some of the Stock/Crowd Sourced science reports, especially for Earth. Would you like me to have a look through these and make you a list?

**Comment by Warp11** [comment]
And I suppose the orbital telescope would be an observation from the distance, like with hubble?

**Comment by NathanKell** [comment]
Yes. Although I highly recommend only doing reports for the experiments listed on this issue--they're by far the highest priority.
I'll either make a clone or use something from DMagic for that (seismic). I agree it's a very reasonable/interesting/real thing, it's just out of scope for the early tree except for soft-landers.

**Comment by Warp11** [comment]
I'll go through it and make you an Excel list. Is there a specific format you would like it in? E.g. like what the google form is putting out? If so just maybe share the google doc with me so I can put it in there.

**Comment by NathanKell** [comment]
Sure! PM me your email and I'll share the doc.

**Comment by jhathawaytn** [comment]
Hi Nathan.  Just wanted to say thank you for this fantastic community.  And I can't sit on the sidelines any longer.  This objective seems doable for me. So with that said, is there a way to see what's already been submitted through the google form? Just wonder, because I'd rather work on a planet/experiment that's lacking material. Thanks.

**Comment by NathanKell** [comment]
Sheet link: https://docs.google.com/spreadsheets/d/1WeuKC0aJGLwB4iJv85BmBbaVBASX56tYLaRNcKTx3z0/edit?usp=sharing

**Comment by NathanKell** [comment]
And @jhathawaytn  thanks so much! :)

**Comment by NathanKell** [comment]
@Felger the link in the RO channel goes to a form that apparently outputs to the 'deprecated' page of the sheet. Should that not be the link used?

**Comment by jhathawaytn** [comment]
@NathanKell I put two reports in on Saturn, but I'm not seeing them show up in the above sheet link.  I just want to make sure these are getting captured before I drop several in.

**Comment by Warp11** [comment]
@jhathawaytn I can't see them in the sheet. Did you finish the whole survey? The results only get counted if you click through all the planets (you don't have to write anything there)

**Comment by Warp11** [comment]
I got the all surface sample reports submitted so far in a cfg. Someone might want to have a look over it to make sure there are no spelling mistakes or anything like that.
http://pastebin.com/Q0er08fb

**Comment by jhathawaytn** [comment]
@Warp11 Well Duh!  I should have known that.  Thanks for clarifying.

**Comment by DMagic1** [comment]
I'm not sure how you're dealing with science reports (using MM to replace, or add to existing reports?), but I already have pretty extensive RP-0 reports included in my own [ScienceDefs.cfg](https://github.com/DMagic1/Orbital-Science/blob/master/GameData/DMagicOrbitalScience/Resources/ScienceDefs.cfg) file. For a more readable version you can check the [Excel file](https://onedrive.live.com/redir?resid=2582013B6F75B5F4!13629&authkey=!AG4wOTs6bP4lq8c&ithint=file%2cxlsx) for existing reports. 

There is lots of room for biome specific results, and some of the experiments only have one or two results, but most planets are pretty well covered; Earth has none.

If you are replacing existing reports you can copy the results from my files. Or they should just work as is if my ScienceDefs file isn't being altered.

**Comment by Warp11** [comment]
@DMagic1 That is awesome and will surely help. We still need reports for experiments that are not from you mod though.
We encountered an issue where only the first report I put in gets displayed and no others. Any ideas on that? code: https://raw.githubusercontent.com/KSP-RO/RP-0/e2e7f284723191af4b78d7886db23e64fb9d1361/GameData/RP-0/Science/Results/SurfaceSample.cfg
Thx

**Comment by NathanKell** [comment]
@DMagic1 that's awesome! I'll be sure to change the cfg to not nuke them then. :)

**Comment by Warp11** [comment]
now that #154 is closed it seems like the release is a lot closer. And honestly I don't really have the time at the moment to do all the report cfgs on my own. It would be great if some other other people could join in there. Sry for that, this is just a busy time for me.

**Comment by jhathawaytn** [comment]
@Warp11 Hey Brother...I can help out where possible...Not a scripting guy at all, but if we're just talking Cfg files then I'm probably good for that.  If you could just get me started I can certainly fill in the blanks.  I looked over the SurfaceSample.cfg and it looks pretty straight forward.

**Comment by Warp11** [comment]
Thx so much, that is awesome.
it is pretty straightforward. Have a look at this:
https://github.com/KSP-RO/RP-0/commit/e2e7f284723191af4b78d7886db23e64fb9d1361
for the formatting. Best thing might be to copy that file.
Then replace surfaceSample (top line) with whatever experiment you're doing. You can find the experiment names here: https://github.com/KSP-RO/RP-0/tree/master/GameData/RP-0/Science/Experiments
and the biome names in RSSKopernicus.cfg.
One more example (not finished yet): http://pastebin.com/1gT7ddgr
Logs: https://docs.google.com/spreadsheets/d/1WeuKC0aJGLwB4iJv85BmBbaVBASX56tYLaRNcKTx3z0/edit?pli=1#gid=278947428
maybe start with instruments.
Thx

**Comment by jhathawaytn** [comment]
@NathanKell I see some situations are listed multiple times.  I assume they will be picked random? If this is the case, is it ok to also pull from DMagic1's excel file?

**Comment by jhathawaytn** [comment]
@NathanKell And thanks for the directions. I'll probably start with Temp.

**Comment by Warp11** [comment]
@jhathawaytn They are suppsed to be picked at random. However that's not working. It's only displaying the first one.

**Comment by NathanKell** [comment]
@jhathawaytn great! :)
Note that the experiment names are inside those files that @Warp11 linked, not just the name of the file. Open one of them and look for @EXPERIMENT_DEFINITION:HAS[#id[**namehere**]]
That's the name.

**Comment by jhathawaytn** [comment]
Guys,  Ok..I need a bit of insight.  The "Temperature Scan" instrument is meant for a more local reading, i.e. digital thermometer? Then the Multi Spectral Analysis instruments would be more of a remote scan?  I'm asking this because as I build this config file, I'm adding as much as I can since there isn't much in the excel file for temps.

**Comment by DMagic1** [comment]
@Warp11 Is it possible that MM has some issues with trying to add multiple values with the same name?

You can try verifying the number of possible results for each experiment (I think) with ScienceExperiment.Results.

@jhathawaytn The Multi Spectral Analysis experiment has a far IR spectrometer that does basically that, measures temperature. It can also be used for other things, like determining surface or atmospheric composition, and surface mapping.

**Comment by jhathawaytn** [comment]
@DMagic1 Thanks! So based on your comments I'll keep the Temp Scans local.  In other words, there is no way to get a surface reading using temp scan instrument from say flyinghigh above for example.

**Comment by Warp11** [comment]
@DMagic1 I've got no idea how MM works and no real experience in modding, I'm really just putting the reports from the excel into cfgs.

**Comment by NathanKell** [comment]
@jhathawaytn that's perfect, RP-0's tone is very much that rather than "Oops you died haha." I suggest you add results to start with *only* for the experiments in the folder @Warp11 linked, i.e. what's listed at the top of this thread; @DMagic1 already has results for those instruments well in hand.

@DMagic1 the file adding experiments so far is [here](https://github.com/KSP-RO/RP-0/blob/master/GameData/RP-0/Science/Results/SurfaceSample.cfg) and it looks fine to me. ConfigCache shows it being patched properly, too. I'll add a bit of code to check that as you say, though  The issue however isn't that only one _result_ is registering, but that it always picks the first entered result for _each_ situation/biome.

**Comment by jhathawaytn** [comment]
@NathanKell Thanks Nathan!  I'm currently working on Temp and Film Return.  Is is safe to assume for Film Return, that I'm only writing results for Earth and Moon for now?  

And should I upload these two files as I work on them?  I'm not familiar with that process.

**Comment by NathanKell** [comment]
Awesome!
For film return, yeah, that seems safe enough. If you can, perhaps some non-biome results for Mars/Venus/Phobos/Deimos, as those are just barely possible enough, but certainly don't worry about further afield than that.

I'd suggest forking this repo, then editing your files in the fork (and committing and syncing frequently to avoid losing work for any reason, and in case you want someone to check over a syntax question). Then when you're done you can just create a pull request and it'll flow into this. :)

**Comment by Warp11** [comment]
I've got the crew report and surface sample almost done, at least what we got in the excel sheet. 

Also the survey only has titan and no other moons of saturn.

**Comment by NathanKell** [comment]
@Warp11  Yeah, the survey needs updating. For now, concentrate on Earth, Moon, and only then Mars/Venus/Phobos/Deimos, and only then the other bodies.
Can you commit what you have within the next 30 minutes or so? I'd like to release an official build of RP-0 tonight, before I go to a place with poorer net access....

**Comment by Warp11** [comment]
I'm on it

**Comment by Warp11** [comment]
I can't do Saturn biome based stuff though until the biomes there are fixed.

**Comment by NathanKell** [comment]
@Warp11 awesome, thanks!
As to Saturn, it is fixed. Grab RSS from git. :)

**Comment by Warp11** [comment]
Is the new version on CKAN?

**Comment by NathanKell** [comment]
No, I mean replace your RealSolarSystem folder with the one in GameData when you download the KSP-RO/RealSolarSystem repo as a zip.
I plan to release tonight tho.

**Comment by jhathawaytn** [comment]
@NathanKell Hey man,  I'm finished with the film return cfg file.  At least for now; as discussed I only covered Earth, Moon, Venus, Mars and it's moons.  There of course could be much more data added, but for now, I'm heading back over to Temps and then Pressure.  I did a pull request, hope I did it right.

**Comment by jhathawaytn** [comment]
Another Newbie question..sorry.....So after I pull a file, and I then want to update it, how do I do this?  Do I update the file in my folk and then pull it again?
