### ISSUE TITLE
Space Shuttle Orbiter cost discussion

### ISSUE THREAD

**Issue by StonesmileGit** [KSP-RO/RP-0#1561]
Realism Overhaul now has quite good support for the Space Shuttle (SSS and SOCK), so deciding costs for RP-1 is the only step left before it can be used in a career. The historical numbers for development and construction of the Space Shuttle Orbiter are however not feasable to use (3.5M funds to unlock and 380k funds to construct).

I'm looking for ideas and opinions on what the cost should be.

**Comment by siimav** [comment]
For comparison, what are the numbers for Apollo stack? 380k for construction might not be as bad considering the fact that it should be reusable.

**Comment by NathanKell** [comment]
Given you recover STS though, can stand to be 380k for sure.

**Comment by NathanKell** [comment]
Yeah makes sense! Anywhere in the 300-380k range seems plausible.

**Comment by siimav** [comment]
Went with ~400k for parts + integration and 3.5M for entry cost
