### ISSUE TITLE
Avionics bug

### ISSUE THREAD

**Issue by gamerxD1990** [KSP-RO/RP-0#1565]
Got a rocket with a procedural avionics core on it. The vessel weighs around 12.25t on launchpad. Therefore I set my avionics to 12.5t and gave it 500 EC (this should work fine). When I launch the rocket, everything seems fine and the avionics work, but I can't get contracts requiring maintained avionics for the first 50s fulfilled. Checked the F3 screen and noticed, that the avionics module thinks the vessel weighs ~1 ton more than it actually does (check screenshot). This seems weird and unexpected.

Currently running KSP 1.10.1 with latest version of RP-1 (installed just 2 days ago)

![Screenshot 2021-10-10 142047](https://user-images.githubusercontent.com/52623561/136695493-81059622-9e8d-4e36-95ec-b615c78ab1fe.png)

**Comment by Capkirk123** [comment]
Can I see more details about this vessel? Does it have any film camera experiments on it? Did you partially fill any fuel tanks?

**Comment by StonesmileGit** [comment]
The issue here is likely that the launch clamps bring the vessel above the avionics controllable mass. This means that the rocket immediately gets control after releasing the clamps, but the contract parameter still fails

**Comment by gamerxD1990** [comment]
> The issue here is likely that the launch clamps bring the vessel above the avionics controllable mass. This means that the rocket immediately gets control after releasing the clamps, but the contract parameter still fails

I don't think that's the issue. In the screenshot above the rocket is still attached to the launch clamp (but controls are already unlocked and working again) and the same launch clamp worked on any other rocket design I created after that with no problem.

**Comment by siimav** [comment]
Hopefully fixed by 894ec4534685f9b45774a777b501e03e6afc541b
