### ISSUE TITLE
Add "Add alarm" button for vessels under construction/tech research

### ISSUE THREAD

**Issue by happz** [KSP-RO/RP-0#1566]
Would it be possible to add the "Add alarm" button/menu item for vessels currently being constructed and technologies researched? I suppose the deadline would change any time the player adds upgrade points to VAB/R&D, but I for one would be perfectly fine with removing now inaccurate alarms and re-adding them manually - we have alerts for transfer windows and maneuvers and astronaut training, seeing vessels' ETAs in the very same window would greatly help mission planning and improve the gameplay. Rollouts would be nice, too, it's just a couple of days or hours long, but may collide with a maneuver...

**Comment by happz** [comment]
Yep, I wasn't aware of this control, and it works perfectly, thank you.

**Comment by siimav** [comment]
I think the automatic alarms work well enough that adding separate buttons isn't worth the effort.
