### ISSUE TITLE
Kerbalism has encountered a fatal error

### ISSUE THREAD

**Issue by JovietUnion** [KSP-RO/RP-0#1571]
![image](https://user-images.githubusercontent.com/62820134/137640232-388c75ba-f9ef-456b-af07-082800a61f55.png)
[KSP.log](https://github.com/KSP-RO/RP-0/files/7360612/KSP.log)

**Comment by Capkirk123** [comment]
1. This GitHub is not for installation issues, which this error almost certainly is.
2. This is not the Kerbalism GitHub. If you believe Kerbalism is the issue, please go to the Kerbalism GitHub or Discord as suggested by the error message.
3. If you need help to ask for help setting up your install, please do so in the Realism Overhaul Discord.
