### ISSUE TITLE
Engine configs for Aerobee are not working

### ISSUE THREAD

**Issue by EmperorBlackadder** [KSP-RO/RP-0#1592]
WACC Aerobee is working, but not the config after it which is the XASR-1. Started a new playthrough after a KSP clean reinstall and never encountered this problem before. The other config, the AJ10-27 aren't working either. They just don't work and it says there's a flame out. It's not a problem of ullage either. I'm using the right propellants, tank type, and no ullage and I test fire it on the ground. But when I use infinite propellant, then it fires. I'm not sure what's wrong, if anything. Pretty sure it's bugged. Before I throttle, it says prop requirement is met 100%. When I throttle, it's 0%

**Comment by EmperorBlackadder** [comment]
Correction, no alternate configs are working.

**Comment by plasticcactus92** [comment]
I'm having this exact issue for any Upgrade engine configuration. So far, all Aerobee configs like those listed above. 
And RD100 series up to RD-102. 
I throttled up, have the correct fuel and tank, and it has a launch clamp. the engine will start and get to about 1300K before dying back down. There is no ignition. When I click f3 there are no malfunctions and it says "Liftoff!"

**Comment by plasticcactus92** [comment]
Did some digging on Reddit. 

Persistent Thrust is the culprit. Disabling it solved the problem for me.
