### ISSUE TITLE
Shuttle Airlock

### ISSUE THREAD

**Issue by Aviation365** [KSP-RO/RP-0#1607]
Currently the Shuttle Crew Cabin does not allow EVA requiring use of the external airlock module, This is however not accurate as all 5 orbiters originally had the airlock inside the Crew Cabin, It was only on Spacelab or until Shuttle MIR when the internal air locks were replaced 
![airlock+merged](https://user-images.githubusercontent.com/53797722/147264701-767e752c-31bd-487d-af4f-08ab8186cf82.gif)

**Comment by StonesmileGit** [comment]
Fixed by https://github.com/KSP-RO/RP-0/commit/bd332a7c742fe5f60503279dc5489d35c09d4f02
