### ISSUE TITLE
Kerbal-friendly code refactoring

### ISSUE THREAD

**Issue by unquietwiki** [KSP-RO/RP-0#1620]
Hey all. I stumbled across this project discussing KSP stuff, and wanted to offer some guidance on how to get this to perform any better than it already is. I'm focused on non-RO/RSS KSP, so I'm leaving some pointers here & can add more as I find them. Hope everyone is keeping safe & well.

C# linting addon
https://github.com/JosefPihrt/Roslynator

Editorconfig file: can adjust this, but can't use null-coalesce on KSP/Unity 4.x apps.
https://github.com/MuMech/MechJeb2/blob/dev/.editorconfig

GlobalSuppression file: silences errors that don't really matter if you're importing other libs, or have a particular code-style.
https://github.com/MuMech/MechJeb2/blob/dev/MechJeb2/GlobalSuppressions.cs

**Edit:** https://devblogs.microsoft.com/visualstudio/making-our-unity-analyzers-open-source/ this might help too.

**Comment by siimav** [comment]
Not sure how that would help.
* Linting sounds good in theory but in practice it takes a ton of effort to configure it such as to not get overwhelmed with suggestions that don't really matter. Blindly applying all refactorings it offers definitely isn't the way to go.
* We already have an editorconfig file to flag inconsistencies in code styling.
* I don't get how that GlobalSuppression file helps. Looks like it would instead hide every styling rule violation that got configured in editorconfig.

**Comment by unquietwiki** [comment]
Hey @siimav ; wanted to respond.

- Linting's been very helpful on sorting out code on other projects, but I agree there's a process on it. I would recommend taking out what is immediately obvious, and waiting on other stuff till later. There's a crapload of analyzers out there that dig deeper into stuff even I'm not comfortable with. At the very least, that Unity one is useful, based on feedback I got from the other folks.
- I missed the editorconfig; due apologies.
- A GlobalSuppression file is useful for dealing with formatting issues, or known acceptable errors; to avoid dealing with all the overwhelming you mentioned in point 1. I know MechJeb uses ALGLIB, and there's a bunch of stuff in ALGLIB that's not cleaned up & formatted like other stuff; even discovered some of their functions are using code they flagged as obsolete, but didn't mark obsolete in C# (MechJeb doesn't use those functions).

I'll close this issue because it was really meant to just transmit the information. I hope it's of some use as you feel comfortable with it.
