### ISSUE TITLE
No science from launch?

### ISSUE THREAD

**Issue by CodeOneYT** [KSP-RO/RP-0#1622]
I just installed rp-0 for the first time (although it's not my first time with kerbalism) on my 1.10.1 install, and for some reason I can't get any science on my launches (telemetry, thermometer, barometer). I see data being transmitted, but no science. This has led me to basically just be stuck on the sounding rocket stage, unable to progress. Is this a feature that I just missed, or is it something else? Thanks in advance!

**Comment by StonesmileGit** [comment]
There is no science below 40 km, except for crewed supersonic science. Above 40 km science exist as usual
