### ISSUE TITLE
Use the Prestige system to limit how many big milestones can be accepted at a time

### ISSUE THREAD

**Issue by siimav** [KSP-RO/RP-0#1628]
Currently with the maxed out mission control there's no limits. For example being able to have active probe missions to every single planetary body at the same time is very unrealistic and removes hard choices from the gameplay. I also believe that not having to micromanage an excessive amount of missions simultaneously would help against the burnout. 1 or possibly even 2 star contracts can still be without limits so that there's always something to do.

**Comment by RurouniDonut** [comment]
I think that's a super cool concept. Late game it just feels like I always have a probe ready to go for any launch window. There's definitely less excitement and immediate goals to focus on. It definitely does cause more burnout and boredom. I think one thing that could work cool with the idea as well is a focus system. For example, imagine if you can set a focus for your program on either doing manned or unmanned missions for example.

**Comment by Falki-git** [comment]
Would love to see support for Strategia for RP-1 or an implementation of a similar experience that would use the administration building to set focus for your space program. Something that would add benefits to missions for the chosen focus (more science and/or cash for manned missions or missions to a specific planetary body). As I understand, Strategia is not configurable, but here's to hoping :)

**Comment by siimav** [comment]
Apparently this is a CC feature and isn't configurable in any way. Would need code changes in CC to override the default math it does for determining the limits.
