### ISSUE TITLE
Move film camera and bio experiment out of start node

### ISSUE THREAD

**Issue by siimav** [KSP-RO/RP-0#1642]
Either use the tracking systems node or create a new one for science experiments.
The idea here is to create some sense of advancement since all pre-orbital science would no longer be obtainable from the start node. This would also open up some interesting career-planning choices. The bio and film return contracts pay rather well but require the science experiments.

**Comment by NathanKell** [comment]
Oh crap I forgot all about this.

**Comment by NathanKell** [comment]
Decided to leave Film and just move Bio.

**Comment by siimav** [comment]
Bio experiment was moved but not film. I guess that's good enough?
