### ISSUE TITLE
Building from Building Plans During Flight Bug

### ISSUE THREAD

**Issue by dojaghostin** [KSP-RO/RP-0#1645]
I was trying to add something to the build queue while in flight and it tried to spawn the rocket, at the root part I think, when I clicked on what I wanted to build.

On 1.12 RP1 Express Latest Install Suite

![Screenshot (219)](https://user-images.githubusercontent.com/100517108/160633960-3083cb87-94d2-4375-a2ae-00c6fd34494e.png)

**Comment by siimav** [comment]
Fixed in ea132ab0de3e4d6a5c0509491498f8cc4980639c
