### ISSUE TITLE
A-9 Engine Config not Showing

### ISSUE THREAD

**Issue by dojaghostin** [KSP-RO/RP-0#1646]
Have the A-9 Config Researched but not showing in the Engine Config Selector to use. 

On 1.12 RP1 Express Install

![Screenshot (220)](https://user-images.githubusercontent.com/100517108/160635159-718b12b6-9f32-4f4a-bad0-2ae2a10509d0.png)
![Screenshot (221)](https://user-images.githubusercontent.com/100517108/160635172-c8163b94-dbf1-45d6-968b-7e7ab1ef6566.png)

**Comment by StonesmileGit** [comment]
You need to change the Speculative Level setting in the difficulty settings under RealismOverhaul
