### ISSUE TITLE
Solar panels start out extended no matter what

### ISSUE THREAD

**Issue by plasmeus** [KSP-RO/RP-0#1658]
I am having an issue where folding solar panels will begin extended upon launch no matter what setting it was given in the VAB. When clicking on the solar panel, the solar panel will have the status 'retracted' despite that obviously not being the case. I have observed this with multiple types of folding solar panels. The same is also true if I load in a ship in the VAB, even if it was previously saved with the solar panels retracted.

As far as the mods I am running, the only mod I am running that is not explicitly supported by RP-0 in CKAN is the RO procedural heatshields mod and the trajectories mod
![2022-04-17](https://user-images.githubusercontent.com/10038785/163750603-3c3cb894-c537-4e74-802c-05d288156ec5.png)

**Comment by siimav** [comment]
Install the KSP Community Fixes mod
