### ISSUE TITLE
Having trouble getting science

### ISSUE THREAD

**Issue by willflatt** [KSP-RO/RP-0#1662]
I'm having trouble getting science i seem to only be getting science from recovering a vessel even when i get 100% of a science in one go.
see screenshots below, the one where I'm fly i had gotten part of that science before but when i got in the water i had never done science their before yet when i recovered i got nothing.
![rp Screenshot 2022-04-29 045751](https://user-images.githubusercontent.com/32919702/165924302-79c032a5-7339-440c-a697-d14b08e1e47c.png)
![rp Screenshot 2022-04-29 045819](https://user-images.githubusercontent.com/32919702/165924304-e7f25b1b-a661-44b1-b294-a072b067f8b6.png)

![rp 2022-04-29 044928](https://user-images.githubusercontent.com/32919702/165924282-18cbe953-b786-4388-9cd1-7070cba6127f.png)
![rp Screenshot 2022-04-29 045015](https://user-images.githubusercontent.com/32919702/165924285-a7a7a801-136f-4c10-ad58-a5df0ed92930.png)
![rp Screenshot 2022-04-29 045125](https://user-images.githubusercontent.com/32919702/165924287-26590908-39ed-4709-8d05-9336348fc62c.png)
![rp Screenshot 2022-04-29 045317](https://user-images.githubusercontent.com/32919702/165924288-52be6a1c-f397-4b17-9f32-cfba59b5ca6a.png)
![rp Screenshot 2022-04-29 045401](https://user-images.githubusercontent.com/32919702/165924290-74e242f0-c996-4688-afec-c41e0fcf6dfb.png)
![rp Screenshot 2022-04-29 045509](https://user-images.githubusercontent.com/32919702/165924292-d4bdecc5-72c9-4124-a37c-19f8e30965bf.png)
![rp Screenshot 2022-04-29 045642](https://user-images.githubusercontent.com/32919702/165924295-09f94863-232f-4663-ac29-8a7415945d50.png)
![rp Screenshot 2022-04-29 045705](https://user-images.githubusercontent.com/32919702/165924297-fcbee188-4cad-42b7-b0e9-c8dcb3ba6175.png)
![rp Screenshot 2022-04-29 045731](https://user-images.githubusercontent.com/32919702/165924300-2b034507-3f3c-4ec2-b792-243db678a695.png)

**Comment by willflatt** [comment]
And I know its not the kerbal contruction mod as i have the same problem in stock rp1

**Comment by siimav** [comment]
There is no flying-low or landed science for Earth in RP-1. You need to get to flying-high (40km+) or space for the experiments to do anything useful.
