### ISSUE TITLE
Fix issue with crewmember flight log not getting persisted correctly. 

### ISSUE THREAD

**Issue by fensabriru** [KSP-RO/RP-0#1669]
For me it's not working.
Only way how i am solving it now is EVA and board on launchpad as this fix flight_log issues and equip astronaut with chute pack as well.

**Comment by siimav** [comment]
Looks like you're talking about 525450f92ed18fd1b78237544f25f3e665b4b20a
This fix is included in the latest RP-1 version (v1.11.9). Sure you have this exact release installed and not some other branch or even master?

**Comment by fensabriru** [comment]
I did manual install and it seems to work now. (before i updated via CKAN)
