### ISSUE TITLE
Can't get science from launches

### ISSUE THREAD

**Issue by DaUnRealN00B** [KSP-RO/RP-0#1699]
I started a new save and my sounding rockets get past 40km, but I never get any science from them. When I check the info screens of the experiments it says "collected: 0.0 in Rnd (# in flight).

**Comment by leudaimon** [comment]
Do you have experiments activated? How long are you staying above 40km? Enough to collect at least 0.1 science? Share maybe a screenshot of your kerbalism screen while in a situation you would expect to be collecting science

**Comment by DaUnRealN00B** [comment]
![image](https://user-images.githubusercontent.com/78629533/174891086-7214411c-a2a2-4b26-8ea0-f71972a8a488.png)
sorry for the late reply, I'm running it as a simulation right now but this is what it shows

**Comment by leudaimon** [comment]
It's all working correctly. You haven't transmitted the data yet, so it's not added to your collected science until you transmit or recover

**Comment by DaUnRealN00B** [comment]
Sorry once again for a late reply, once you said that it was the transmission I changed my space center, I have a mod that adds more space centers and the center I was using wasn't near a ground dish. It works now so thank you.
