### ISSUE TITLE
KSCDistance used in recovery time algorithm is incorrect

### ISSUE THREAD

**Issue by ryanc55** [KSP-RO/RP-0#1707]
In ReconRollout:

double KSCDistance = (float)SpaceCenter.Instance.GreatCircleDistance(SpaceCenter.Instance.cb.GetRelSurfaceNVector(vessel.latitude, vessel.longitude));

But SpaceCenter.Instance doesn't work properly with RSS+KSC Switcher.   So you are effectively given a random penalty here depending on which KSC you have switched to.

I took a quick look, but I'm not sure how to fix this, perhaps the contract configurator version of downrange distance could be leveraged?   Launch site location should probably be stored with the vessel somehow.   I'm also not sure if onlaunch is the proper time to set the Space Center location as that might have odd interactions with airlaunch.

**Comment by NathanKell** [comment]
Can't be set on launch, since what's relevant is where the space center is _when you recover_. Launch a rocket from Vandy and recover at the Cape and the distance should be the distance to the Cape.

That sounds like SpaceCenter.Instance's data should get properly updated by KSCSwitcher and it isn't??

**Comment by ryanc55** [comment]
Correct.  When I looked at the SpaceCenter.Instance lat/lng in debug mode it was nonsensical.  It looks like a known bug given this comment in DoAirLaunch:


            // SpaceCenter.Instance.transform doesn't work correctly with RSS + KSCSwitcher installed
            PQSCity ksc = Utilities.FindKSC(body);

**Comment by NathanKell** [comment]
So there's something wrong with this then?
https://github.com/KSP-RO/KSCSwitcher/blob/master/Source/KSCSwitcher.cs#L389

We should, uh, probably fix that. :D

**Comment by ryanc55** [comment]
Oh, I didn't realize that had been moved under RO.    Yeah, that's a better place to tackle it.   You can close this and I'll open another issue on KSP-RO/KSCSwitcher that if I can't figure it out tomorrow.

**Comment by NathanKell** [comment]
Thanks!! <3
