### ISSUE TITLE
Problem with modules in weight and performance in V delta

### ISSUE THREAD

**Issue by spasmos** [KSP-RO/RP-0#1710]
Hello,

I have done the express installation https://github.com/KSP-RO/RP-0/wiki/RO-&-RP-1-Express-Installation-for-1.12.3, following the instructions exactly. I also had to do the patch indicated at https://github.com/KSP-RO/RP-0/wiki/New-FAQs#why-are-there-shrouds-hiding-all-my-roengines-parts-models because I had those same problems.

I have also followed the tutorial https://github.com/KSP-RO/RP-0/wiki/First-Rocket-&-Early-Career-Tutorial to the end.

In the first game in easy mode that I did I already had problems even using the proposed Thor-able model to reach the low orbit so I started a new game in moderate following one of the recommended series and I began to see differences between the V delta of the series and those that I reached with the same design.

So I have rebuilt the Thor-able model and this time I have noticed that there is indeed a problem between the delta V's that the designs should provide and the ones they do provide.

I have reviewed the FAQs in case there was information regarding this problem but there is no reference.

Can you help me please?

The differences are so serious that they make it impossible to play a successful game. I attach an example following the tutorial exactly.

Thank you very much.

![thor-able-not-work](https://user-images.githubusercontent.com/14311529/177036546-396bdf9a-f2b5-4c8a-849d-fcb9a365574d.png)

**Comment by spasmos** [comment]
Update situation:

I have reinstalled ROEngines and ROTanks in case there was any problem but the problem persists. I am going to make an installation of 0 to rule out that something has not been broken during the game.

Could you tell me if in this latest version the weight and power ratio of the components has been changed, which could be causing this loss of performance of the historical rocket models compared to previous versions?

Thank you very much.

![thor-able-not-work-launch-error](https://user-images.githubusercontent.com/14311529/177041775-b230aa2e-15d5-4f1e-bd53-213f6600a83f.png)
![thor-able-not-work-update](https://user-images.githubusercontent.com/14311529/177041777-ae567a88-b3b0-4eac-86f6-445c73a73469.png)
,

**Comment by leudaimon** [comment]
I don't quite follow what is your issue. In the fist message, your stage looks broken and that's why you get 7100 m/s. In the second message and screenshots, your rocket looks good and the delta-v readings look correct

**Comment by spasmos** [comment]
The problem is that following the official tutorial and building as indicated, I should end up with this v delta that I attached

![68747470733a2f2f692e696d6775722e636f6d2f3349414d3143552e706e67](https://user-images.githubusercontent.com/14311529/177043657-28632533-b7b9-4b07-9143-db69bd084963.png)

When I try to do the same construction I get this difference in the v delta:

![177041777-ae567a88-b3b0-4eac-86f6-445c73a73469](https://user-images.githubusercontent.com/14311529/177043708-52b277b3-37ee-4ffa-ad01-3383acdd5afb.png)

Do you see the difference of about 700m/s? and that construction is not real because I had to increase the length of the tanks by about 2m in total to give those values.

The feeling is that the latest update is penalizing the v delta of the carts, either because the weights or the powers are misaligned.

With historical builds of youtube series that worked with ksp 1.8, the differences are even greater.

Thank you very much,

**Comment by spasmos** [comment]
Update entry:

It seems that yes, the change in tanks and engines in this latest update (1.12 compared to 1.8) has caused these imbalances. To match that build with something older you need Balloon tanks, whereas in previous builds with Integrals it already worked but in this build there are no Integral tanks. The Isogrid that should replace the Integral also fall short, perhaps they weigh more than they should.

I have also detected a decompensation of the Moderate level of the game compared to previous versions of the expansion, being now closer to the previous difficult level since not even the initial payments of the contracts allow 100% of the construction of the rocket necessary to fulfill said contract.

If you wish not to consider these observations an issue and rather a desired behavior, please indicate somewhere that this is the case now because I haven't been able to find this information anywhere.

Thank you very much for your time and attention.
