### ISSUE TITLE
sprites missing & white bars - RP0 LC and programs update (RP2)

### ISSUE THREAD

**Issue by YMandarin** [KSP-RO/RP-0#1771]
I installed the rp2 update in a new ksp 1.12.3 instance exactly as Nathans comment said https://github.com/KSP-RO/RP-0/pull/1696 (I got a CKAN rp1 high res express install and replaced the RP0 gamedata with the downloaded one).

After starting a new save, I was greeted with white bars where the reputation and confidence count should be and white bars for the rp1 and kct button in the toolbar. In the admin building, sprites are missing as well. Any Idea why thats the case?
(screenshots attached)

![grafik](https://user-images.githubusercontent.com/46614277/187286833-588b88e5-d2de-43b4-8ef6-e0b8d9cbd3cf.png)
![Screenshot 2022-08-29 214928](https://user-images.githubusercontent.com/46614277/187286902-4b3676ba-a380-4b68-8827-84de1434ea6a.jpg)

**Comment by siimav** [comment]
Apparently the issue was not deleting RP-0 folder before copying in the new one.
