### ISSUE TITLE
Photography 2 sample mass is broken

### ISSUE THREAD

**Issue by lpgagnon** [KSP-RO/RP-0#1776]
Presumably more fallout from the move of experiment configs from rokerbalism to rp-0: photo2 sample mass used to be 5x100kg=500kg (I think), is now 5x500kg=2500kg

![Screen Shot 2022-09-04 at 12 42 22](https://user-images.githubusercontent.com/5061230/188324241-13d38e4a-e521-4a7a-827d-90b0118fc6cb.png)

the fact that it's off by 5x is probably not a coincidence

**Comment by leudaimon** [comment]
I'm puzzled by this... I looked back at the data in the old ROK repo, and it sets sample mass as 0.5, the same value as it shows for me in the configcache. However, https://github.com/KSP-RO/RP-0/blob/master/GameData/RP-0/Science/Experiments/Photography.cfg sets sampleMass in two different places, one in line 82, as 2.5t and then it's changed to 0.5 in line 110. 
I'm not sure why it's being defined twice, but it should still be working, as the change to 0.5 should run later. I wonder what is going wrong there.

**Comment by leudaimon** [comment]
Tagging @Standecco here in case he has something to clarify

**Comment by Standecco** [comment]
> If only the definition at the KERBALISM_EXPERIMENT node matters, it actually simplifies the patching and is something I'd consider changing everywhere.

This is indeed right. Fix should be as easy as changing line 82 to `SampleMass = 0.5` :)

**Comment by Capkirk123** [comment]
resolved by https://github.com/KSP-RO/RP-0/commit/862743e3e7642cf853a5b56f3aa837688a3e37ad
