### ISSUE TITLE
(RP2) Error loading KCT Data after trying to launch a rocket

### ISSUE THREAD

**Issue by YMandarin** [KSP-RO/RP-0#1777]
KCT broke my RP2 save and said I should report it here together with the log file.

After opening the game and rolling out a rocket (called Lunaria I (Koryu-II)), nothing happened when I clicked on the 'launch' button. I tried reloading the save and rolling the rocket back and out again, wasn't able to launch it. I also built another rocket, and I was able to launch it. After going into the VAB, I got the error msg saing 'Error Loading KCT Data'.

[KSP.log](https://github.com/KSP-RO/RP-0/files/9491417/KSP.log)

**Comment by NathanKell** [comment]
First, it's not called RP2.
Second, issues relating to what you're trying don't go here, see the pins in the P&LC channel in discord.
