### ISSUE TITLE
Failure to download "ROHeatshields-v1.0.0.zip"

### ISSUE THREAD

**Issue by RB21** [KSP-RO/RP-0#1781]
When attempting to download the 1.12.3 version of the Realistic Progression One (RP-1) Express Install, the install locks up at 88%. Going down to 0 B/sec on the download speed and remaining there until canceled. 

**Replication Procedure**:

1. Install Kerbal Space Program v1.12.3 as a fresh install
2. Install CKAN v1.31.0, placing it into the Kerbal Space Program Steam directory
3. Mark game version 1.11 as compatible in the CKAN settings
4. Follow all instructions as defined in section 3 of the "RO & RP 1 Express Install Guide"

I have attempted this download several times and it has failed each time. You can see where the download is halting in the screenshot below.

![Download Fail - Copy](https://user-images.githubusercontent.com/6563764/188744475-73d16703-b197-4831-959f-25536069a766.PNG)

Notably, I can forcibly go in and download this file by following the exact link provided in that screenshot.

**Comment by siimav** [comment]
I heard that Spacedock was having issues at the time you reported this. Most likely this would have been resolved by just restarting the install process later.
The CKAN folks have already put in work to improve the user experience when downloads fail but haven't done a release yet: https://github.com/KSP-CKAN/CKAN/pull/3635
