### ISSUE TITLE
Federation Aeronautique Internationale still not working

### ISSUE THREAD

**Issue by glilienthal** [KSP-RO/RP-0#179]
Using the latest pre-release, I could not find any initial contract. :(. 

Instead I found:  

[EXC 21:56:06.113] UnityException: Texture 'RP-0/Agencies/FAI' is not readable, the texture memory can not be accessed from scripts. You can make the texture readable in the Texture Import Settings.
	UnityEngine.Texture2D.GetPixels (Int32 miplevel)
	UnityEngine.Texture2D.GetPixels ()
	Contracts.Agents.Agent..ctor (System.String name, System.String logoURL, System.String logoScaledURL)
	Contracts.Agents.Agent.LoadAgent (.ConfigNode node)
	Contracts.Agents.AgentList.LoadAgents (.ConfigNode[] nodes)
	Contracts.Agents.AgentList.Start ()

And several of: 

[EXC 22:10:30.062] ArgumentException: 'Federation Aeronautique Internationale' is not a valid agent.
	ContractConfigurator.ConfigNodeUtil.ParseAgentValue (System.String name)
	ContractConfigurator.ConfigNodeUtil.ParseSingleValue[Agent] (System.String key, System.String stringValue, Boolean allowExpression)
	ContractConfigurator.ConfigNodeUtil.ParseValue[Agent] (.ConfigNode configNode, System.String key, Boolean allowExpression)
	ContractConfigurator.ConfigNodeUtil.ParseValue[Agent] (.ConfigNode configNode, System.String key, System.Action`1 setter, IContractConfiguratorFactory obj, Contracts.Agents.Agent defaultValue, System.Func`2 validation)
	UnityEngine.Debug:LogException(Exception)
	ContractConfigurator.LoggingUtil:LogException(Exception)
	ContractConfigurator.ConfigNodeUtil:ParseValue(ConfigNode, String, Action`1, IContractConfiguratorFactory, Agent, Func`2)
	ContractConfigurator.ConfigNodeUtil:ParseValue(ConfigNode, String, Action`1, IContractConfiguratorFactory, Agent)
	ContractConfigurator.ContractType:Load(ConfigNode)
	ContractConfigurator.<LoadContractConfig>d__14:MoveNext()
	ContractConfigurator.ContractConfigurator:Update()
[ERR 22:10:30.100] ContractConfigurator.ContractType: CONTRACT_TYPE 'recordCrewedSpeed': Error parsing agent

Once I remove the "name = Federation Aeronautique Internationale", the contracts work. - And I can play. :)

PS: I did not see any  é or other diacritics.

**Comment by glilienthal** [comment]
BTW, I am running Ubuntu 12.04, and 64bit KSP.

**Comment by NathanKell** [comment]
You're using something to make the PNG unreadable. I bet @Shurikeeen is as well. Leave the FAI png as a png (don't convert it to dds), and either don't use ATM or make an exception for RP-0/Agencies/* in ATM. Same with Texture Replacer, if Texture Replacer is set to compress/mark-as-unreadable PNGs.

(You're on Linux x64 so there's no need to use ATM anyway).

Sadly KSP's GUI doesn't support é or the like, so that's why those aren't there.

**Comment by Shurikeeen** [comment]
@NathanKell Nope, i'm not using ATM or any DDS converter program.

**Comment by NathanKell** [comment]
@Shurikeeen well, what do you get in the log?

**Comment by Shurikeeen** [comment]
@NathanKell In the Contract Configuration log? http://i.imgur.com/w8Tzi03.png

**Comment by NathanKell** [comment]
Ok, what mods do you have installed? Because I don't get that.

**Comment by Shurikeeen** [comment]
Well, here's my mod folder if something stands out from there. I'm also running in OpenGL.

**Comment by NathanKell** [comment]
As I mentioned above, Texture Replacer does it too. Yank that for now, or make an override config.

**Comment by Shurikeeen** [comment]
How can I stop TextureReplacer from doing that..?

**Comment by NathanKell** [comment]
By adding an override config, as I mentioned. The thread (or other docs) should explain how. Or you can just turn off its 'make unreadable' feature generally.

**Comment by NathanKell** [comment]
You can also try replacing your RP-0/Agencies folder with the one that's now in the repo, and [do the same for SXT's](https://github.com/Signatum/SXT)

**Comment by glilienthal** [comment]
yep. That does the job. Thanks!
