### ISSUE TITLE
error while using CKAN to update parallax from 1.3.1 to 2.0.4

### ISSUE THREAD

**Issue by JoshuaSteward1193** [KSP-RO/RP-0#1796]
I followed the install guide to perform the express install of RP-1 in KSP 1.12. When I try to use CKAN to update the parallax mods to 2.0.4, I get an error message that say Parallax 2.0.4 is incompatible with the current version of Parallax-Stock Textures, and if I try to update Parallax-Stock Textures, I get a message that says Parallax-Stock Textures is incompatible with Parallax 1.3.1 (The version I have currently installed)

I've never had CKAN find a circular conflict like this before, where the desired version of two mods are incompatible with the currently installed version of the other mod, so I'm wondering if this might be related to the express install package. Is there another way to update RP-1 to use the 2.0 versions of Parallax?

Thanks in advance

**Comment by Capkirk123** [comment]
RP-1 (well, RSS) does not support parallax 2.0, and has correspondingly been marked as conflicting in CKAN.
If you wish to try to use parallax 2.0, you will have to manually install it and write your own configs, or find some someone else made.
