### ISSUE TITLE
"Avionis Units Stack" confusion

### ISSUE THREAD

**Issue by Gordon-Dry** [KSP-RO/RP-0#1797]
In the career settings UI, submenu "RP-1" is a point which says

> Avionis Units Stack

At https://github.com/KSP-RO/RP-0/wiki/Procedural-Avionics-Basics it says 

> Note that avionics units do not stack

Which is correct?

**Comment by Gordon-Dry** [comment]
If it's true and it stacks, a VAB-internal UI that shows the controllable total would be great.

**Comment by StonesmileGit** [comment]
There is indeed an option to *enable* avionics units stacking. This is left in to not break existing vessels during a deprication phase. The option is going to be removed in the future.

As a side-note; the RP-1 UI has a tab in the VAB to show the controllable mass
