### ISSUE TITLE
Cannot get Supersonic Crew Contract working 

### ISSUE THREAD

**Issue by glilienthal** [KSP-RO/RP-0#180]
My suspicion is that something is wrong with FirstCrewedSupersonic.cfg (see below). 

When I reach 350m/s, the corresponding tick box is ticket, no success as I have to return first. However, once the speed drops below that, the green tick is disappearing and I cannot complete the contract. 

As I do not know the format, I am just posting it here: 

	PARAMETER
	{
		name = VesselGroup
		type = VesselParameterGroup
		title = Reach 350 m/s with a crewed craft.
		define = crewedSoundBarrierCraft

		PARAMETER
		{
			name = NewVessel
			type = NewVessel
		}
		PARAMETER
		{
			name = HasCrew
			type = HasCrew
			minCrew = 1
		}
		PARAMETER
		{
			name = ReachSpeed
			type = ReachState
			minSpeed = 350
			situation = FLYING
		}
		PARAMETER
		{
			name = ReturnHome
			type = ReturnHome
			completeInSequence = true
		}
	}

**Comment by NathanKell** [comment]
You're quite right! It needs a disableOnStateChange = True line.
I'll add that, and to the other ones too.
