### ISSUE TITLE
R-11F2 jet engine too good for its node?

### ISSUE THREAD

**Issue by lpgagnon** [KSP-RO/RP-0#1801]
R-11F2's temperature speed limit is ~920m/s (easily reachable with a pair); this makes it competitive with highSpeedFlight's J75, and far better than matureSupersonic's J57-P-21 and AL-7F (which top out around 720?)

Google tells me the first R11 dates back to 1956, but the R11-F2 belongs to the MiG-21, which would fit with matureSupersonic's 1959 date. So move it back a node?

**Comment by Capkirk123** [comment]
Way ahead of you
resolved by https://github.com/KSP-RO/RP-0/pull/1799
