### ISSUE TITLE
Clones of sepMotor1 got no plume

### ISSUE THREAD

**Issue by Gordon-Dry** [KSP-RO/RP-0#1806]
The clones of
`sepMotor1`
so to speak
```
sepMotorLarge
sepMotorSmall
ROSmallSpinMotor
```
got no plume, the original does.

**Comment by vader111** [comment]
@Gordon-Dry First off this is a RO Issue not a RP-0 Issue.
Second I have a PR on the RO GitHub that fixes these very issues.

**Comment by vader111** [comment]
https://github.com/KSP-RO/RealismOverhaul/pull/2721

**Comment by Gordon-Dry** [comment]
Thank you.
