### ISSUE TITLE
Preformance issues.

### ISSUE THREAD

**Issue by pack7df** [KSP-RO/RP-0#1817]
After update the mods of RP1 instalation, the game after some time, become more and more slow,
when i check the task manager the memory used is decreasing every time, until 3GB of ram, it start at 10 GB when the game is loaded. The CPU and GPU usage is also low.

**Comment by siimav** [comment]
Sorry but that really isn't much to go by.
What exact mods did you update and from which versions? Are the performance issues resolved by reverting everything to previous versions? If so try updating mods one by one to single out the one causing issues.
I assume you have 16GB RAM? How does the total memory utilization change over time? Is some process other than KSP hogging the RAM? Also make sure to use the Windows Resource Monitor to additionally check the Commit size (virtual memory alloc) of KSP.

**Comment by pack7df** [comment]
I will make this test, i don't remember well wich version i had previously but i remember i updated just 1 or 2 month of updates, i suspect the problem is about graphics. i remember that KSP always stay about 10 or 11 GB of ram, but what is happening now is that KSP is consuming too low resources, in ram, GPU and CPU. Even the ram consumed drop now to 3 GB.

**Comment by pack7df** [comment]
It looks like it was an update of another program, a program i use to optimize PC, (Advanced System Care), looks like now it clean memory and let KSP with only 3 GB, some times with less than 0.5 GB of memory in use (given task manager), and then the game become extremely slow.
