### ISSUE TITLE
KCT upgrade points for R&D are shared, those for VAB build times are not

### ISSUE THREAD

**Issue by Gordon-Dry** [KSP-RO/RP-0#1825]
Shared Upgrade Pool is enabled.

I started the career at White Sands and got 20 points in VAB and 11 points in R&D, after switching to KSC the R&D times are the same but the VAB build times are way longer.

**Comment by NovemberOrWhatever** [comment]
This is intended behavior. Your research team can work anywhere, while your integration teams aren't willing to move. So you'll need to purchase new build points in the new location
