### ISSUE TITLE
Launch towers 575 m above ground

### ISSUE THREAD

**Issue by glilienthal** [KSP-RO/RP-0#183]
![screenshot9](https://cloud.githubusercontent.com/assets/8526242/9023327/b8287c78-3897-11e5-8df4-1be9725129fd.png)

The launch towers re-appear about 575m above sea level over the KSC. usually no prob, but sometimes I crash into them. (I don't notice them all the time. Maybe they only appear somtimes.) 

RO, RP-0, RSS newest ckan versions, KSP_64 on linux

**Comment by NathanKell** [comment]
Known stock bug, afraid it's all over the forums. :P
http://bugs.kerbalspaceprogram.com/issues/5206

Grab Clamps-be-gone (I think that's what it's called) from the releases forum, it's a good workaround. We'll start recommending it with RO.

**Comment by glilienthal** [comment]
Thank you.
