### ISSUE TITLE
suborbital crewed flight contract failed when I finished the first orbit. 

### ISSUE THREAD

**Issue by glilienthal** [KSP-RO/RP-0#184]
I completed the first crewed orbit without finishing the crewed suborbital before. If this intended behaviour that this is a failure? I'd rather see it as a success, no? 

![screenshot6](https://cloud.githubusercontent.com/assets/8526242/9023335/078224fe-3898-11e5-9ace-4ead6eaa1f35.png)

**Comment by NathanKell** [comment]
Definitely not intended. Great catch!

**Comment by NathanKell** [comment]
In fact the contract was impossible to complete. Oops.

To fix yourself, in the Reach Altitude PARAMETER, add the line
disableOnStateChange = true

(see the linked commit above for the change details)
