### ISSUE TITLE
1.25m Heatshield does not shield

### ISSUE THREAD

**Issue by glilienthal** [KSP-RO/RP-0#185]
On reentry, the heatshield showed 0 conv heat, but the procedural battery directly after it, took the heat. Then after it exploded, the heatshield finally took some heat. 

Any ideas? 

https://www.dropbox.com/s/qv2gun6a3sppflg/KSP.log?dl=0 

![screenshot11](https://cloud.githubusercontent.com/assets/8526242/9023341/5adb158e-3898-11e5-9036-d7cfd45b517c.png)

![screenshot13](https://cloud.githubusercontent.com/assets/8526242/9023339/4f3f186a-3898-11e5-9ba2-ac5fcf477532.png)

![screenshot14](https://cloud.githubusercontent.com/assets/8526242/9023342/6adebe36-3898-11e5-89fc-9317d5bd0c9c.png)

**Comment by NathanKell** [comment]
That sounds like proc parts isn't correctly recreating drag cubes. Presumably it still has the original cube, with the default size (where it would extend below the heat shield). @ItMustBeACamel poke ?

**Comment by glilienthal** [comment]
It is also happening without the procedural battery. Then the little sounding rocket control thing that does not control much, takes the heat.

Also, I do not understand the suggestion with staging something away. The heatshield sits atop a decouper and is decoupled before reentry.

**Comment by NathanKell** [comment]
Ok, I misunderstood. That sounds like a different issue then. I assume you're on the latest of everything? I'll try when I get home with that particular shield. Can you post a craft file?

**Comment by glilienthal** [comment]
https://www.dropbox.com/s/nnfgehs3bzby3he/Z%20022%20reentry.craft?dl=0

**Comment by glilienthal** [comment]
also KSP.log : https://www.dropbox.com/s/qv2gun6a3sppflg/KSP.log?dl=0

**Comment by NathanKell** [comment]
Woo! Stuff for everyone!
@blowfishpro I see a Solver Engines GUI exception in there (throwing in EnginesFlightGUI.Start() with the event adding) 

Interestingly it threw on decoupling, so that might be the root of your problem. Then there's a crapton of part exceptions. Then there's more solver engines exceptions...

Hmm. I'd say if you don't mind can you *only* recreate the part where the heatshield wasn't working? Looks like this is the log after a bunch of flights.

**Comment by glilienthal** [comment]
ok. another reentry it is.  - And I also found the Player.log :)

**Comment by NathanKell** [comment]
Hehe. Thanks!
(These days it isn't so critical since KSP.log includes the stack trace (so KSP.log is no longer useless), but it's still more useful than KSP.log :) )

**Comment by glilienthal** [comment]
another reentry mission. Another almost 20 science :).

https://www.dropbox.com/s/1uvxza0w25yf4bi/2015-08-01-22-54-Player.log?dl=0

here a screenshot where you can see that the avioncs is also taking in heat: 

![screenshot28](https://cloud.githubusercontent.com/assets/8526242/9023557/89aa8658-38a0-11e5-9476-2f11e8222bbd.png)

and one where you can see that sometimes the battery is not taking convection. (it changes with time, usually maybe 5% of the time no heat. 
![screenshot25](https://cloud.githubusercontent.com/assets/8526242/9023565/e6c893d4-38a0-11e5-8616-0cdb59412578.png)

**Comment by tschieggm** [comment]
Is this issue still open? I appear to be running into something similar while designing a Venus lander. All of the procedural parts behind my heatshield explode before the heatshield even looses a single point of abalator.

**Comment by Bornholio** [comment]
Pretty sure this is fixed
Close ME?
