### ISSUE TITLE
RP-1 Express Install dependencies now out of date

### ISSUE THREAD

**Issue by JordanMilly** [KSP-RO/RP-0#1851]
Parallax has now been updated to 2.0.6, where one of the features is that, even though RO/RP-1 is still using Parallax 1.3.1 configs for RSS, the newest version will work with those older configs, allowing the benefit of the new version in terms of bug fixes and performance boosts to be felt by users.

However, RP-1 Express Install has Parallax and the Parallax Stock Textures forced as a dependency to 1.3.1, meaning that currently you can't update through CKAN, only manually.

If the dependencies could be updated to reflect these changes, that'd be incredibly useful.
![image](https://user-images.githubusercontent.com/104111242/208337443-4395c4d2-1790-4ff5-a175-d3fb110d463d.png)

**Comment by siimav** [comment]
That's cool but has anyone validated that everything works correctly in practice as well?

**Comment by JordanMilly** [comment]
I did the update manually, and it loaded fine, no errors came up, and my saves have loaded and run as normal.
________________________________

**Comment by Cirelion** [comment]
I've tried a fresh install and set-up parallax 2, I've encountered no issues after cheating a lander on mars and the moon in a few different locations.
