### ISSUE TITLE
Hollow Interstage decoupler breaks VAB right-clicking

### ISSUE THREAD

**Issue by jflatby** [KSP-RO/RP-0#1856]
I am following the First Rocket tutorial with a fresh install, and in [this part](https://github.com/KSP-RO/RP-0/wiki/First-Rocket-&-Early-Career-Tutorial#adding-a-solid-motor) it says to use a hollow interstage decoupler and "set the core to aerobee interstage".

When I add the hollow decoupler to the rocket, and then right-click it, a seemingly bugged "window" appears:
![image](https://user-images.githubusercontent.com/42612372/210027913-fca7fa25-b7bf-4d56-ad57-c43777ce4dbd.png)

After this happens, I am no longer able to right click any part on the rocket. The bugged window does go away, and the correct parts are still highlighted when I hover over them, but even if I remove the hollow decoupler, I can no longer right click any other part to get their window open. nothing happens if I right-click the tank, avionics, etc.

If I leave the VAB, and re-enter, it works as normal. Until I try to right-click that decoupler again.

**Comment by Capkirk123** [comment]
Try restarting the game.

**Comment by jflatby** [comment]
Ah, you're right, **automatically fixed next time I launched the game**.

Should have tried that before opening an issue.

I added this to the [Known Issues](https://github.com/KSP-RO/RP-0/wiki/RO-&-RP-1-Express-Installation-for-1.12.3#2-known-issues) in the setup tutorial, hope that's fine.
