### ISSUE TITLE
when research is on one one vessel, other vessels cannot research it

### ISSUE THREAD

**Issue by glilienthal** [KSP-RO/RP-0#1859]
Example: I sent a probe outside the SOI of Earth to the SOI of the sun. However, my antennae are not so good yet, so I loose contact. However, if I send a new probe in the SOI of the sun, this research (e.g. micrometeroid data), will not be researched, as it has been maxed out on another vessel. 

The only solution is to destroy the vessel with the data. (Even though if it doesn't have electricity I cannot even find out whether it has this data.)

This doesn't seem to be intended behaviour, and I seem to recall that it has been differen.t

**Comment by NovemberOrWhatever** [comment]
I don't have a proper solution or bugfix, but forced run is the other way to make it work.

**Comment by Capkirk123** [comment]
This is intended behavior with Kerbalism.
