### ISSUE TITLE
crashed into moon mountain: no contract - intended? 

### ISSUE THREAD

**Issue by glilienthal** [KSP-RO/RP-0#187]
I just impacted the moon. Unfortunately at 10.242m altitude. Is this intended behaviour, that the contract is not fulfilled if one hits a mountain on the moon? IMHO, I'd set the threshold higher than 10k.

Also I got a Contract Configurator Exception

Exception occured while saving ScenarioModule 'ContractVesselTracker':
System.InvalidOperationException: Operation is not valid due to the current state of the object
  at System.Linq.Enumerable.First[ProtoPartSnapshot] (IEnumerable`1 source) [0x00000] in <filename unknown>:0 
  at ContractConfigurator.Extensions+<GetHashes>d__18.MoveNext () [0x00000] in <filename unknown>:0 
  at System.Linq.Enumerable.Any[UInt32] (IEnumerable`1 source) [0x00000] in <filename unknown>:0 
  at ContractConfigurator.ContractVesselTracker.OnSave (.ConfigNode node) [0x00000] in <filename unknown>:0

**Comment by NathanKell** [comment]
Poking @jrossignol as well on this.

@jrossignol *is* there way to have a parameter "destroyed *by* celestial body x"? My proxy was "vessel destroyed <10km alt" but as @glilienthal points out that's not quite safe...

**Comment by jrossignol** [comment]
Raised https://github.com/jrossignol/ContractConfigurator/issues/283, but can you confirm that you are *not* using a Win64 KSP build?

The [VesselDestroyed](https://github.com/jrossignol/ContractConfigurator/wiki/VesselDestroyed-Parameter) parameter has a mustImpactTerrain attribute, set that to true to make it only be met when impacting terrain.  Combine that with a [ReachState](https://github.com/jrossignol/ContractConfigurator/wiki/ReachState-Parameter) that says targetBody = Moon and put it all under a [VesselParameterGroup](https://github.com/jrossignol/ContractConfigurator/wiki/VesselParameterGroup-Parameter).

Actually, I took a look, and that's pretty much what you've got, minus the altitude and the mustImpactTerrain set to false with a comment about bugs...  if it's a bug in Contract Configurator, let me know the details and I can look into it. :wink:

**Comment by NathanKell** [comment]
@glilienthal is on Linux x64. I was scared to use mustImpactTerrain because of stock bugs (not yours)--I've seen vessels die from colliding with KSC rather than the terrain, for example. Nonetheless it's worth trying with that set true and no maximumAltitude.

**Comment by jrossignol** [comment]
Thanks, I've seen that type of weird exception from the Win64 builds, but in this case I'm probably trying to iterate over stuff in a dead vessel.

As to the bugs...  yeah I get nervous about that one too.  I believe it'll work for colliding with KSC, but haven't tested in a while.  I worry more about it deciding that the probe core survived so the ship is actually alive, or the probe core crashing into another part of the ship and so deciding that it didn't impact terrain.  Haven't done extensive enough testing to know whether those are issues or not...

Another option - ReachState has a minTerrainAltitude.  Just don't set it too low - the granulary of checks for ReachState is every 100ms.  So make sure you give enough wiggle room for the player to get a check or two in before they hit the ground.

**Comment by NathanKell** [comment]
Oh, right, yes,  that was another bit I was worried about--some things have insane crash tolerances, and lithobraking via other parts....so minTerrainAltitude makes sense, although the real issue IMO is that at high warp pretty much nothing will work (forgot to dewarp one impact mission). However, that can presumably be solved by an ANY for below given alt _or_ destroyed by terrain.
