### ISSUE TITLE
Inconsistencies in Tech tree

### ISSUE THREAD

**Issue by glilienthal** [KSP-RO/RP-0#188]
a) Apollo capsule is much easier to get than Gemini. node "Space exploration" with Apollo capsuleI only needs improved instrumentation, and costs only 90.

b) General construction has a limit of 5.6m width for tanks, whereas the succeeding tech "advanced construsction" has only 4m. 

- But maybe this is just not ready yet. ;)

**Comment by NathanKell** [comment]
As for b, yeah, spaceExploration hasn't been reconfigured yet. It's supposed to depend on the Gemini node and various other things...
