### ISSUE TITLE
Spacewalk contract failed for no reason? 

### ISSUE THREAD

**Issue by glilienthal** [KSP-RO/RP-0#189]
I just did my spacewalk contract, wanting to cash in heaps! Then it failed. Apparently because no vessel was destroyed (sic!) - The Kerbal ground crew was so upset that they decided to embezzle some funds from the nuclear missile program to make up for the loss. (i.e, I edited the save :) ) 

However, doesn't seem to be intended behaviour. Any ideas? 

![screenshot36](https://cloud.githubusercontent.com/assets/8526242/9045020/b752fcda-3a20-11e5-803b-b82d1bf46f69.png)

**Comment by batuhantasli** [comment]
I checked the contract's cfg and nothing seems wrong. However, you are supposed to get in orbit before EVA so I believe that's why it failed.

**Comment by NathanKell** [comment]
Sorry, lost net access and got busy. Back now. Will get to this (again). I'm removing the "no destroyed vessels" requirement from all contracts since it doesn't seem to be working as desired.

**Comment by NathanKell** [comment]
Reopen if this continues...
