### ISSUE TITLE
Terrain texture error

### ISSUE THREAD

**Issue by TechnicalParadox** [KSP-RO/RP-0#1891]
I did a fresh install of KSP 1.12.3, installed RP-1 Express as instructed with the high graphics options and recommended 4 mods. I have my texture and terrain settings maxed out.

The terrain is low res, and appears a few meters above the terrain you actually collide with. It's as if the LOD layer for being far away doesn't disappear when close. I have an i7 6820hk, GTX 980k, and 32gb of ram

**Comment by siimav** [comment]
Sounds exactly like how the terrain at Cape Canaveral is supposed to function.

**Comment by Capkirk123** [comment]
Pictures? That sounds like it is functioning as intended however.

**Comment by TechnicalParadox** [comment]
This makes it very difficult to land as you can't see the actual ground. How can it be disabled without affecting the other parts of RP-1? Other than installing the medium graphics express install.

![20230309022137_1](https://user-images.githubusercontent.com/5107397/223951882-8fc16320-5127-4453-853b-dd264406ed19.jpg)
![20230309022145_1](https://user-images.githubusercontent.com/5107397/223951883-821696d9-2cc4-4f43-928b-9f30f51ed8de.jpg)

**Comment by Capkirk123** [comment]
Yup, that is working as intended. I'd suggest trying to land on the runways, but you can remove it by deleting RSS-CanaveralHD
