### ISSUE TITLE
Unable to build a realisitc Delta IV M+ (5,4) as well as an TDRS sat.

### ISSUE THREAD

**Issue by Elvaider** [KSP-RO/RP-0#1900]
Hi folks after years of the usage of RSB and US Probes I noticed a huge discripancy between RSB and the new RO(Tanks+Engines). 
Back in the days the DIVM+ 5,4 had roughly 15k dV. My new replicas get only to 10k. At the moment I'm using the "Isogrid?" Tanks with the most advanced config for a test run and no matter what I try I can only get her to 10.5k dV.

TDRS is the same issue here. I'm literally unable to to get any dV out of that one as well. 

So atm the "new" RP-1 is really shiny but not really "bangy" atm. 

In the enclosures you can find my file craft. I'd be really glad if you could take a look at the matter and maybe explain me why my rockets aren't working at all.

Best regards Elvaider

PS.: please shoot me an pm in discord so that I can get in touch with you folks again.

[Delta IV M+ 5,4.craft.zip](https://github.com/KSP-RO/RP-0/files/10990667/Delta.IV.M%2B.5.4.craft.zip)

**Comment by Capkirk123** [comment]
1. This isn't really an RP-1 issue, RP-1 just handles career
2. The fuel load on your DCSS is completely wrong. Given a correct fuel load, the Delta IVM gets over 15 km/s of DeltaV
