### ISSUE TITLE
Far Future Support

### ISSUE THREAD

**Issue by Coelhomatias** [KSP-RO/RP-0#1912]
Hi, currently trying to play RO/RSS/RP-1 with Kerbalism and Far Future Technologies in 1.12.4 gives a B9 Part Switch warning and the parts do not appear in the tech tree. I have installed KerbalismFFT as well, all through CKAN. Is this mod compatible with RP-1? Saw some videos of people playing with FFT and RO/RSS but never RP-1.

Great set of mods, thank you in advance.

**Comment by Capkirk123** [comment]
Far Future Technologies is not supported by RP-1 at this time.
