### ISSUE TITLE
Missing A-4 Engine

### ISSUE THREAD

**Issue by bohemian83** [KSP-RO/RP-0#1922]
I noticed I am missing the A-4 engine, while the RD100 is available. The configs for A-4 are showing up in the science nodes. I have used only the suggested mod list that shows up on CKAN and done a clear reinstall of KSP, after purging the CKAN cache. Am I doing something wrong?

**Comment by Clayell** [comment]
By the suggested mod list, do you mean the RP-1 Express Install?

**Comment by bohemian83** [comment]
Not sure. I just installed RP-1 from CKAN and the required mods, as well as those suggested in the next screen.

**Comment by bohemian83** [comment]
Please disregard, CKAN somehow flagged ROEngines as incompatible and the package was not installed.
