### ISSUE TITLE
Soft lock with 4 right-clicks

### ISSUE THREAD

**Issue by ccchan49** [KSP-RO/RP-0#1928]
It seems that right clicks on UI can cause a soft lock in VAB or in-flight. I first noticed this problem when I was editing a maneuver with Principia in the map view. The game is not frozen (the spacecraft is still flying) but I am not able to control anything. Esc doesn't work too, but pressing the space bar in VAB does move the camera back to the default angle. This is how I can reliably reproduce the problem:

1: Enter VAB. Pick a core so that MJ and other UIs pop up on the screen. You can move the core away from the center of the screen, but it doesn't matter.
2: Move any UI to the center of the screen (I used KCT in this case). 
3: Double-right-click on the center of the screen.
4: Double-right-click on somewhere outside of that UI.
5: The cursor disappears and the game is soft-locked.

![image](https://user-images.githubusercontent.com/60914289/235841900-07764170-9040-4273-9ec7-211c89db3700.png)

**Comment by siimav** [comment]
Cannot replicate. 
Try with a window that doesn't have clickthrough blocking, like the one from RealAntennas. If the issue doesn't happen there then ClickThroughBlocker is definitely at fault.

**Comment by ccchan49** [comment]
> Cannot replicate. Try with a window that doesn't have clickthrough blocking, like the one from RealAntennas. If the issue doesn't happen there then ClickThroughBlocker is definitely at fault.

ok, applying the same procedure to RealAntennas's planning UI will cause the UI to disappear until I double right-click again. Yep, probably CTB's problem. I will submit it to CTB's github. Thanks!
