### ISSUE TITLE
Mod Parts not showing up

### ISSUE THREAD

**Issue by Coelhomatias** [KSP-RO/RP-0#1936]
Hi, first of all, love your work, love RO/RP-1.
While playing an RP-1 career on a fresh install, the latest version of everything, express install on CKAN, I noticed that some parts from additional mods were not showing in the tech tree.
Mods like Universal Storage 2 (which I confirmed has configs for both RO and RP-1 and is placed in the tech tree) and Heat Control (this one I didn't find in RO).
Am I missing something? Shouldn't these be on the tech tree?
I am asking this because I want to be able to know what mods that add parts I can install alongside the RP-1 install (apart from the ones mentioned in the Extra mods to consider wiki page). Thank you in advance!

**Comment by Capkirk123** [comment]
As mentioned [here](https://github.com/KSP-RO/RealismOverhaul/issues/2849), Heat Control is only properly configured if SystemHeat is present. Universal Storage 2 should work fine, there are very few parts that are configured, but they are configured. Can you show that Universal Storage 2 parts are not appearing in an up-to-date install?

**Comment by Coelhomatias** [comment]
I get some parts from Universal Storage 2, however, I do not get any center core, this makes it so I can't use any of the parts because they attach to the center core.
As for the Heat Control, I managed to get the parts by installing System Heat as you pointed out.
Still, there are other mods like Near Future Solar that have both RO and RP-1 configs that do not show up in the tree.
Is there any updated list of mods that work?

**Comment by Capkirk123** [comment]
Near Future Solar is an odd case, ROSolar takes its parts for itself, you can access Near Future Solar parts by using ROSolar procedural solar panels.

There is no updated list of mods that work.

**Comment by Coelhomatias** [comment]
Ok thank you for the fast response. 
Just to clarify, not having the center cores in Universal Storage 2 is the expected behaviour?
To access Near Future Solar parts with ROSolar, do I need to have NFS installed or ROSolar is enough?

**Comment by Capkirk123** [comment]
Yes, it appears the center cores are not configured fully for US2.

To use Near Future Solar parts in ROSolar, Near Future Solar must be installed
