### ISSUE TITLE
Fix issues in contracts with a Duration component

### ISSUE THREAD

**Issue by jrossignol** [KSP-RO/RP-0#194]
Follow-up to https://github.com/jrossignol/ContractConfigurator/issues/304:

In Contract Configurator 1.7.0, I made some changes to the Duration parameter to allow it to work as it is currently being used, which is in a structure similar to this:
* VesselParameterGroup
  * NewVessel
  * ReachState
    * Duration
  * ReturnHome

However, even after the change, there's still a small issue left.  If a player were to complete everything but the ReturnHome, but fail on the last part (let's say they crash their plane), then they will be able to try again with a new vessel *without needing to do the duration portion again*.  This has been improved in Contract Configurator 1.7.1 (still in pre-release, will be formally released in the next day or two if everything goes as expected).  However, there's a change required to the RP-0 contracts that follow the above structure.  The Duration parameter needs to be moved down a level, to look like this:
* VesselParameterGroup
  * NewVessel
  * ReachState
  * Duration
  * ReturnHome

Which (at least in my opinion) also looks a little bit cleaner.

**Comment by NathanKell** [comment]
@jrossignol Ok, will do. In that case though should "completeInSequence" be added for Duration as well as ReturnHome, or does CC automatically apply duration to the preceding parameter?

**Comment by jrossignol** [comment]
Duration automatically acts as if completeInSequence was set (because it predates the completeInSequence attribute).

**Comment by NathanKell** [comment]
Cool. Fixing as we speak then. :)
