### ISSUE TITLE
Can no longer add oxygen to service modules for some reason

### ISSUE THREAD

**Issue by smunstu** [KSP-RO/RP-0#1964]
In the middle of a campaign, something occurred that has rendered me unable to add oxygen to my service modules.  I can still add water and food.

I do have Crew Survivability researched.

I believe this occurred after CKAN pushed some mod updates to my install. I did attempt to reinstall the entire mod pack in case it was caused by an improper installation.

Poking around in my Persistent.SFS file, it looks as though that ability has been transferred to the research node, 'standardDockingPorts'.

Help!!!

**Comment by TwistedGiraffe** [comment]
Are you on both the latest release of RO and RP-1? Did this save start earlier than those releases? 
Please post your ModuleManager.ConfigCache (or at least the relevant lines).

**Comment by smunstu** [comment]
Yes I am on the latest version to my knowledge. No updates come up when I refresh CKAN. To give this a date, I believe it started occurring almost two days ago. This campaign began some weeks before this.

File uploaded because it is too large to paste directly.

I deeply appreciate the prompt assistance.

https://drive.google.com/file/d/1-3l8sOMwcq50DBsMCBpzyHYz7YyTgqkj/view?usp=sharing

**Comment by TwistedGiraffe** [comment]
Speaking of prompt, you can try https://github.com/KSP-RO/RealismOverhaul/pull/2857 and https://github.com/KSP-RO/RP-0/pull/1965. These two PRs should solve your problem.

**Comment by smunstu** [comment]
Just to clarify, I should manually make the changes to the files indicated in files changed tab, correct?

**Comment by TwistedGiraffe** [comment]
Yes. Though if you have GitHub Desktop, you can fetch the PRs and copy the changed files, so you don't have to do it manually.

**Comment by smunstu** [comment]
Thanks so much! I was quite worried I might have to pause this campaign for a while

**Comment by NathanKell** [comment]
Use the official release of the hot fix. The pull request was against
master and therefore had a ton of save breaking changes.

**Comment by bofhgr** [comment]
It seems that with the latest release and the hotfix for the Service Modules (confirmed that this works as expected now for SM) I still can't add Oxygen to the Dynosoar Cockpit or Dynosoar Crew Cabin, nor the SOCK Cockpit. Similarly I can't add Oxygen to the MK1 crew cabin, 2.25m Habitation module (from SSPX), the MK2 Cockpit & Crew Cabin, the Gemini L CM, the D2 CM, the MK2 Lander, probably others as well.. However I can add Oxygen to the Apollo CM.

**Comment by foxlits** [comment]
> It seems that with the latest release and the hotfix for the Service Modules (confirmed that this works as expected now for SM) I still can't add Oxygen to the Dynosoar Cockpit or Dynosoar Crew Cabin, nor the SOCK Cockpit. Similarly I can't add Oxygen to the MK1 crew cabin, 2.25m Habitation module (from SSPX), the MK2 Cockpit & Crew Cabin, the Gemini L CM, the D2 CM, the MK2 Lander, probably others as well.. However I can add Oxygen to the Apollo CM.

Can add to this list - Soyuz, Vostok and Voskhod crafts.

**Comment by arrowmaster** [comment]
Sounds like anything with tank type ServiceModule is broken and not getting the patch run against it. That is a legacy tank type that parts need to be migrated away from but it still should be fixed to be usable.

**Comment by foxlits** [comment]
i dont know if it was a glitch or something, but i have not seen it before... Last played more than 6 month ago and it wasnt there as far as i remember. When you editing cockpit, you can choose tank type (that is something that wasnt there AFAIR) and while i have opened Service tank type III (trying to figure the problem with oxygen - cheated science somewhat) there was only ST II Type for choose and nothing more. (Mercury cockpit) Maybe it is somehow connected with the problem.
![2023-06-01_20-23-11](https://github.com/KSP-RO/RP-0/assets/104077523/ad493895-72fd-4c9b-b913-a52a2b823a86)

**Comment by arrowmaster** [comment]
@foxlits Correct, previously all command pod type parts had their tank type set to `ServiceModule` and now some have been changed to explicitly use a specific tech level of SM tank such as `SM-II`. Anything using the SM-I through SM-IV tank types should be fine but anything still using ServiceModule is probably broken.

**Comment by foxlits** [comment]
Ok ) Then waiting for the patch )

**Comment by bofhgr** [comment]
the latest hotfix fixed this issue, thank you!
