### ISSUE TITLE
KCT window for new LC / modify LC / new Pad cannot be dragged

### ISSUE THREAD

**Issue by aeroeng91** [KSP-RO/RP-0#1968]
The KCT popup window created for a new pad / new LC / modify LC cannot be dragged around (re-positioned). This is an issue in the VAB as the modify LC window can be quite long, with the buttons to "renovate" or "cancel" being obscured off-screen.

This is unaffected by changing UI scaling to 80% through the in-game settings.

Tested on a new install, RP-0 nightly build, master RO, screen resolution 1920x1080.
![Modify LC window with cut-off buttons](https://github.com/KSP-RO/RP-0/assets/62497325/94067d9a-9410-46ec-bc28-88ed0113020d)
![New LC window starts at same vertical location but is shorter and has visible buttons](https://github.com/KSP-RO/RP-0/assets/62497325/07b5d019-0ef1-4212-8361-e65d15078a49)

Suspected to be related to this commit due to the impacted windows:
"Fix UI window sizing for new/dismantle LC" 3ae4986

**Comment by NathanKell** [comment]
Should be fixed now

**Comment by aeroeng91** [comment]
Sorted, thanks!
