### ISSUE TITLE
Tree missing parts

### ISSUE THREAD

**Issue by Kartzull** [KSP-RO/RP-0#199]
I have some stocks without anything in the Tree,
Examples : earlyAvionics, supersonicFlight and a lot of others

**Comment by NathanKell** [comment]
Sounds like you didn't download a release. Download a release, don't download the repo itself. Only the release has the tree file.

**Comment by Kartzull** [comment]
But I downloaded through CKan, is it enough? Or I have to download the release and manually install?

**Comment by Kartzull** [comment]
For example here's the tree I got http://puu.sh/k3Ryc/3b2db6df1c.png

**Comment by NathanKell** [comment]
Verify you have file Tree.cfg in GameData/RP-0

**Comment by Kartzull** [comment]
No I don't have

**Comment by Kartzull** [comment]
from the release i downloaded i don't have this file but with Ckan there's

**Comment by NathanKell** [comment]
Then it sounds like the CKAN install screwed up. Try removing and re-installing via CKAN.

Since I know many people who play RP-0 via CKAN, I don't think it's a permanent issue, just a temporary install weirdness on your particular machine. If the above steps don't result in having that file, post an issue on the CKAN repo describing the issue and the folks there will try to help figure out what's going wrong.

**Comment by Kartzull** [comment]
Ok I'll try this

**Comment by NathanKell** [comment]
Then you did not in fact download a release, if it was lacking that file.
I just verified--on the releases page, the most recent release. The actual release has the file, the "Source code" archives do not. As expected.

**Comment by NathanKell** [comment]
Ok

**Comment by Kartzull** [comment]
I reinstalled with ckan and some are fixed but some are not. Does it requires mods with parts like KW rocketry?

**Comment by NathanKell** [comment]
RP-0 only supports the mods listed on the front page of this repo. Some nodes later in the tree will be empty, we only go to about 1968 right now. Which nodes are showing empty for you?

**Comment by Kartzull** [comment]
There's a link with the tree and the empty ones are the red squares, the green square is where there's 2 nodes on the same place, I don't think it might be normal
![ksptree](https://cloud.githubusercontent.com/assets/14168019/9741633/c0dfbb24-565b-11e5-9779-cec6b289cdd0.jpg)

I can give some names if needed

**Comment by NathanKell** [comment]
Fixed the overlap in 537ca0751308337451342a5c327a2705cef07557 . The red nodes are expected, we haven't filled everything in yet in the later areas of the tree, and many of those nodes were created (in CTT) for mods we don't support yet.

Thanks!
