### ISSUE TITLE
GuidanceUnit claims NotElectricCharge with plenty ElectricCharge available

### ISSUE THREAD

**Issue by Peppie23** [KSP-RO/RP-0#222]
Hi RP-0 Devs,

@jonseverinsson opens an issue on RemoteTech with this problem and i figured out that this comes from RP-0. You can find more infos to this issue here: https://github.com/RemoteTechnologiesGroup/RemoteTech/issues/470

**Comment by NathanKell** [comment]
That's...really weird. Only thing I can think of is we change EC to be STAGE_PRIORITY_FLOW. If you remove RP-0/ElectricityFlow.cfg does the issue go away?

**Comment by Peppie23** [comment]
yep the issue was gone after deleting the ElectricityFlow.cfg

**Comment by NathanKell** [comment]
Actually I think it might not even be that per se, because IIRC there's an
issue with resource flow where it will fail if a part requests a resource
that it has, but with 0 amount. (It won't go on to try another part)

Sent by my thumbs, slowly.

**Comment by NathanKell** [comment]
I mention that because with stage pri, it will drain from the guidance ring
first fully so it will go to 0

Sent by my thumbs, slowly.

**Comment by NathanKell** [comment]
Fixed in 1.0.5 AFAIK.
