### ISSUE TITLE
Crewed pods w/o pre designed ballance?

### ISSUE THREAD

**Issue by BevoLJ** [KSP-RO/RP-0#226]
Are there any crewed pods w/o RCS ports? I'm doing an alternate history where I am trying to design my own vessels but it is very difficult to balance something that comes with built in balance for a totally different use.  Like there is the MK1 pod and the FASA Gemini pod early on, but both are pre designed to be used in a specific manner that make it difficult to design/ballance it for alternate uses.

Unless there is a way to remove the RCS ports and not have them show up by RCS Build Aid?

**Comment by NathanKell** [comment]
I never did make the enable/disable toggle for the RCS available in the editor, but if you add
rcsEnabled = False

to the MODULE, it should have the ports start as disabled and thus RCS Build Aid should not use them in calculation.

**Comment by BevoLJ** [comment]
That is awesome! Will do. =)
