### ISSUE TITLE
Spaceplanes and entrycosts

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RP-0#237]
For the X-15 parts, we have a known R&D cost. That's fine. Same with STS (though it would probably break the bank).

However, for DynaSoar like birds, we're speculating.

Like the X-15, the best route IMO is to have some portion of each part's entry cost be for the shielding, and some part of it be for the part itself. Once you buy one of the parts at the full price, you don't have to pay the shielding R&D cost for the rest.

So...what sounds like a reasonable R&D cost for the Mk1 System (i.e. could be DynaSoar) shielding? I would guess something like 30000.
The Mk2 system's shielding would be about 50000 I think, and the Mk3's over 100k.

Then, as for parts, another hundred k or so for the cockpit of the Mk1 system (150k for the Mk2)?

@winged7

**Comment by winged7** [comment]
as I said before i can increase development cost for the stock mk2  system 2x so it will be 260k for the cockpit standard and thus 86666 for substractors

**Comment by NathanKell** [comment]
Following from #353
Yeah, 260K sounds good to me, or even an even 300K (with the MK1 system at 180K for the cockpit).
Apologies for being unclear, I did indeed mean 1/3 of dev cost, not unit cost.

So how does this sound: 
For Mk1 system, 180K for the cockpit, with 30K of that being the shielding (and a modifier as such). Tanks would have an entry cost of about 50K each (before 30K subtract). Crew can at 60K. The inline and regular cockpits should have multipliers of 0 for each other, too.
For Mk2 system, 300K for the cockpit (and 0 multipliers between inline and regular), of which 60K is shielding general cost. 80K for tanks, 120K for the crew compartment, 100K for cargo bays.
For Mk3 system, roughly STS-level numbers, of which, hmm, do we know how much TPS development cost? Something like 800K for the cockpit, maybe? 200K each tanks and cargo bays and 300K for the crew section? With a subtractor of 150K for shielding?

**Comment by NathanKell** [comment]
*Note*: Those are all entry costs, not unit costs.

Unit costs should be probably on the order of 1/10th that, maybe less (1/15th? 1/20th?)

**Comment by winged7** [comment]
ok so 
180k for mk1 system and 30k substractor for shielding
300k for mk2 system and 60k substractor for shielding
800k for mk3 system and 150k substractor for shielding

**Comment by winged7** [comment]
and unit cost 1/20th

**Comment by winged7** [comment]
mk3 system new pricing: https://github.com/KSP-RO/RP-0/pull/243/files#diff-61fdc63e15600668e30c7e7c03fd5b13

**Comment by winged7** [comment]
mk2 system new pricing https://github.com/KSP-RO/RP-0/pull/354

**Comment by winged7** [comment]
and now I'm starting to do entrycost modifiers for them

**Comment by winged7** [comment]
entry cost modifiers for stock mk2 and mk3 system: 
https://github.com/KSP-RO/RP-0/pull/353

**Comment by winged7** [comment]
and now i'm start doing RO-Mk1system

**Comment by winged7** [comment]
entryCostModifiers for the mk1, mk2, mk3 system done:
https://github.com/KSP-RO/RP-0/pull/353/files

**Comment by winged7** [comment]
RO mk1 system - pricing
https://github.com/KSP-RO/RP-0/pull/355/files

**Comment by NathanKell** [comment]
Awesome!
