### ISSUE TITLE
SRM costs

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RP-0#26]
I seem to get wildly varying SRM costs. I _think_ we should assume, on 'nautix, that an un-yeared cost is in 1985 dollars, though I am not positive. I think that means that the Castor 1 (the motor used in the Sergeant missile, 4x in Little Joe, as strapons for early Delta / Thorad, etc) is about $270k and the UA1205 is about $5m (with costs projected to fall to $2.4 in the 1970s after cost saving measures for Apollo Applications Program use, per a Bellcomm report). This means that costs do _not_ appear to be linear, which is bad news for Proc Parts. Need more info...

For now I have gone with:
SF costs $62.3/liter ($35/kg).
Proc parts SRB costs $40/liter empty + $(thrust_in_kN \* 0.25).
So in total ~$102/liter + $0.25/kN thrust.

**Comment by ferram4** [comment]
Trawling for AJ-260 data on the NTRS, I found this SRM cost model PDF: http://ntrs.nasa.gov/archive/nasa/casi.ntrs.nasa.gov/19730004130.pdf   I haven't looked too in-depth, but it may be helpful.

**Comment by NathanKell** [comment]
@ferram4  that is AWESOME! Thanks so much!

**Comment by Bornholio** [comment]
@NathanKell did this document get used as a later decider for SRM cost.  or was some other form used?

**Comment by pap1723** [comment]
Our SRM costs have been well-researched and I believe that this can be closed now.
