### ISSUE TITLE
Docking Ports are invisible in research nodes at avionicsTL7

### ISSUE THREAD

**Issue by KellanHiggins** [KSP-RO/RP-0#264]
Did some searching and it looks like the regular old docking port is hidden in avionics TL7. So it doesn't show up at all when you are playing RP-0. You can only see the apollo ones.

I suggest we use the same Apollo docking cone pricing and same node. I thought I was going insane looking through the entire tech tree to not be able to find the regular docking port.

I know you mentioned in another post that this is 1980s tech and shouldn't be near the apollo stuff. I realize that, but I want to use the VanStock stuff, not the custom apollo landers.

```
@PART[dockingPort2]:FOR[RP-0]
{
	%TechRequired = advFlightControl
	%cost = 2000
	%entryCost = 70000
	RP0conf = true
}
```

**Comment by KellanHiggins** [comment]
I think I may have just missed this. Closing.

**Comment by danielguo** [comment]
I find it breaking player experience. In career mode, we have BE-4 engine available (2018+ tech), but no working docking port (1980 tech).

My suggestion would be to move it to another node before we have avionicsTL7.
