### ISSUE TITLE
More science values

### ISSUE THREAD

**Issue by glilienthal** [KSP-RO/RP-0#266]
Hi all, 
There are a lot of science values not yet implemented. What do you think of my proposal? - Thought I get some feedback before doing the pull request. 

G. 
# proposed Science values (not yet implemented)

| _Body_ | _landed_ | _splash_ | _flyLow_ | _flyHigh_ | _Spacelow_ | _SpaceHigh_ | _recovery_ |
| --- | --- | --- | --- | --- | --- | --- | --- |
| _Jupiter_ |  |  | 24 | 15 | 10.0 | 6.0 | 8.0 |
| Io | 30 |  |  |  | 15.0 | 8.0 | 10.0 |
| Europa | 30 |  |  |  | 15.0 | 8.0 | 10.0 |
| Ganymede | 30 |  |  |  | 15.0 | 8.0 | 10.0 |
| Callisto | 30 |  |  |  | 15.0 | 8.0 | 10.0 |
| _Saturn_ |  |  | 26 | 17 | 12.0 | 8.0 | 10.0 |
| Titan | 35 |  | 26 | 17 | 15.0 | 10.0 | 15.0 |
| _Uranus_ |  |  | 28 | 20 | 14.0 | 10.0 | 12.0 |
| _Neptun_ |  |  | 29 | 21 | 15.0 | 11.0 | 13.0 |
| Pluto | 40 |  |  |  | 18.0 | 14.0 | 20.0 |
| Mercury | 40 |  |  |  | 18.0 | 14.0 | 20.0 |

**Comment by NathanKell** [comment]
That looks good to me!

**Comment by pap1723** [comment]
RP-1 Science Overhaul
