### ISSUE TITLE
OKTO2 charge craziness.

### ISSUE THREAD

**Issue by pjf** [KSP-RO/RP-0#33]
The OKTO2 core comes with 15,840 worth of EC, and a "tank" that can hold
50,000 EC. Consequently it's possible to have the whole thing weigh
> 50kg, for a part that has a "mass" of 0.05.

I'd be happy removing the tank entirely, but in any case it doesn't look
like it's got enough space to support 50kg worth of batteries.

This may be a bug in RealismOverhaul, so attn @Felger as well.

**Comment by cherrydev** [comment]
I agree this is unbalanced.  It makes all the other probe cores in the supported parts packs completely useless, since they are all in the 200-1000kg range and don't offer significantly more charge, space, or any additional capabilities.

**Comment by NathanKell** [comment]
Probe balancing is rather dependent on this: https://github.com/RemoteTechnologiesGroup/RemoteTech/issues/234
See here: https://github.com/KSP-RO/RP-0/issues/42
