### ISSUE TITLE
Inflatable heatshield, HIAD, F9 landing gear

### ISSUE THREAD

**Issue by winged7** [KSP-RO/RP-0#341]
Could someone tell me where to place Falcon gear (for F9 landing), Inflatable Heatshield (6.25m) and Hypersonic Inflatable Aerodynamic Decelerator?

https://github.com/KSP-RO/RP-0/pull/340

**Comment by NathanKell** [comment]
I'm not sure where they should go...depends on the state of #224.

**Comment by pap1723** [comment]
RP-1 Tech Tree
