### ISSUE TITLE
Contract Configurator available in CKAN is too old for RP-0

### ISSUE THREAD

**Issue by cmr** [KSP-RO/RP-0#375]
The contract group cfg requires `minVersion = 1.5.4`, but the latest Contract Configurator available (at least for 1.0.4, which is the current RO version) is 1.4.2.

**Comment by NathanKell** [comment]
That sounds like a metadata issue on CKAN re: Contract Configurator, since the 1.7.x line of Contract Configurator was available for 1.0.4.
This is the latest 1.0.4 release: https://github.com/jrossignol/ContractConfigurator/releases/tag/1.7.8

**Comment by NathanKell** [comment]
Please bring it up on the CKAN repo, that does need to get sorted out. :)
