### ISSUE TITLE
Long term thoughts: Rep vs. Funds

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RP-0#38]
As I was thinking about the early space race, I had a thought. This is a longer-term thought, since we should get things up and running "normally" first, but what if...

At the start of the space program, contracts don't give you money. They might give you science, but what really matters is reputation. You get funding from the government based on your reputation (perhaps we should integrate Punish The Lazy, so it goes down over time...or perhaps reputation stays constant but the budget per unit of reputation goes down over time?). Ideally, you would get most of your funding at the start of the fiscal year.
As you do more and more prestigious things, you get more and more funding. As time goes on, commercial contracts start appearing to supplement your income (sounding rocket launches, FP orbital contracts, science from body x contracts, etc). You can, however, ignore them and go only for the prestige, err, reputation contracts.

Thoughts?

**Comment by Bornholio** [comment]
Given that admin building is disabled for now is this issue closed?

**Comment by pap1723** [comment]
Also interesting to see that satellite payloads were here a long time ago.
