### ISSUE TITLE
Docking Ports are invisible since there is no avionicsTL7

### ISSUE THREAD

**Issue by danielguo** [KSP-RO/RP-0#383]
Related: https://github.com/KSP-RO/RP-0/issues/264

The lack of docking port takes away a big part of player experience. In career mode, we have BE-4 engine available (2018+ tech), but no working docking port (1980 tech).

My suggestion would be to move it to another node before we have avionicsTL7.

**Comment by KellanHiggins** [comment]
The BE-4 is probably not placed correctly in RO-P. I think that I was missing the docking port when looking through all the pages and pages of different utility items.

@NathanKell how do people cost and sort RP-0 items? Are they doing it by adding config files that they manually write?

**Comment by NathanKell** [comment]
@Niemand303 has a tree reorganization in progress that will add the specified node ( see #224 ).

@KellanHiggins parts are placed and priced by editing tree.yml (in the repo root), our build script builds Tree.cfg from it.

**Comment by winged7** [comment]
@danielguo  I will add new nodes for avionics, wait a moment.

**Comment by NathanKell** [comment]
@winged7 please check with @Niemand303 since it's best not to duplicate work--IIRC he has some or most of the changes in that tree made? If not, it'd be awesome if you could help make them. :)

**Comment by winged7** [comment]
https://github.com/KSP-RO/RP-0/pull/385
I think that docking ports are really important so we should have them before tech tree overhaul ( which will probably take a while)

If this is a problem I can delete my changes just before tech tree overhaul (when everything will be ready)

**Comment by NathanKell** [comment]
Naw, that's fine! Just didn't want you spending time redoing work, that's all. :)

**Comment by NathanKell** [comment]
All sorted.
