### ISSUE TITLE
Travis issue

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RP-0#401]
@pjf travis seems to be no longer uploading release zips. Halp?

**Comment by jwvanderbeck** [comment]
Might be the same thing I ran into.  There was a bug in Travis that required a workaround for releases.

**Comment by jwvanderbeck** [comment]
https://github.com/travis-ci/travis-ci/issues/5145

**Comment by NathanKell** [comment]
Ah, interesting! Thanks! Checking

**Comment by jwvanderbeck** [comment]
Adding this fixed it for me:

before_deploy:
- gem install mime-types -v 2.6.2

**Comment by NathanKell** [comment]
Did not fix. Unless I'm travising wrong somehow.

**Comment by jwvanderbeck** [comment]
I don't see any errors in your latest build on Travis.  Is it for the "pre-release" release? You sadly can't do that, it has to be a proper full release, and it must be tagged.

**Comment by NathanKell** [comment]
Ohhh. That would explain things.

**Comment by NathanKell** [comment]
Nope, not even that.

**Comment by jwvanderbeck** [comment]
Hmm doesn't even appear that `make release` is even being run

**Comment by jwvanderbeck** [comment]
Wait did you just take the existing release and make it live? Not sure if that works.  Maybe it does, not sure.  I usually just make a new release and delete the old one when I have problems.  This part of the travis log is suspect to me:

    Already up-to-date!
    # Not currently on any branch.
    nothing to commit (working directory clean)
    Dropped refs/stash@{0} (9e978ff04300342fab9717166f154853a808238c)

I don't see anything like that in my logs when I do a release.

**Comment by NathanKell** [comment]
I upped the tag. I can add a commit and retag again...

**Comment by jwvanderbeck** [comment]
What I mean is make a brand new release, not edits to the original one

**Comment by NathanKell** [comment]
Yep, testing that as we speak.

**Comment by NathanKell** [comment]
Still nothing.

**Comment by NathanKell** [comment]
@jwvanderbeck @pjf any other ideas?

**Comment by jwvanderbeck** [comment]
Could it be your version tag for the release?  I know say for TestFlight and RO it was set up to parse version numbers in a specific way.  Your normal releases for RP-0 are with tags like 0.40 not v0.00000-testKSP105_1

Also are you doing this against master or a different branch? Not that it should matter, just curious.

**Comment by NathanKell** [comment]
Huh. @stratochief66 just seemed to have one that works, though it's tagged with a normal tag but the built file is from the older tag (!)

Using that weird tag has worked fine in the past--see all the test builds for 1.0. And everything's off master.

**Comment by NathanKell** [comment]
Seems to be working now. Shrug.
