### ISSUE TITLE
Disable world firsts

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RP-0#402]
Current code isn't.

**Comment by batuhantasli** [comment]
@NathanKell It seems that they are still not properly disabled. I completed a WF when I went to the Moon.

**Comment by NathanKell** [comment]
[Are you using this release?](https://github.com/KSP-RO/RP-0/releases/tag/v0.00000-testKSP105_5)

**Comment by batuhantasli** [comment]
I am using latest dev, not that release. Does that release have additional fixes than Arsonide's commit?

**Comment by NathanKell** [comment]
Arsonide's commit?

**Comment by batuhantasli** [comment]
https://github.com/KSP-RO/RP-0/commit/faf2f0176696ce04321f632509426084d9385fe4 I mean this, it was yours sorry.

**Comment by leudaimon** [comment]
I have moved to the latest release (the one you cited in the comment) and now WFs reappeared, when I escaped Earth. In a previous version after your fix they looked to be fixed, no WFs had appeared up to this point.

**Comment by NathanKell** [comment]
Hmm. Ok, pinging @Arsonide - maybe I'm still missing something.
[Here's the relevant code](https://github.com/KSP-RO/RP-0/blob/master/GameData/RP-0/Contracts/StockContracts.cfg#L324-L331)

**Comment by NathanKell** [comment]
Per discussion with @Arsonide the messages will not go away, but the rewards are zeroed so they have no gameplay impact. The messages themselves will hopefully be toggleable in future KSP releases.

Please ensure that you are not getting any rewards even if you are getting messages.
