### ISSUE TITLE
Prevent EVA&EVA Suits

### ISSUE THREAD

**Issue by batuhantasli** [KSP-RO/RP-0#411]
I don't know if it's possible, but don't you think it would be nice if EVA is restricted to certain pods and equipment only? Now, if you upgraded the astronaut center to necessary level, you can do EVA in Mercury or Vostok. Maybe we can add some EVA suits as ghost parts to make sure people know that they need to unlock those techs in order to do EVA and also unlock second-gen pods to do that like Voskhod or Gemini. What do you think?

**Comment by Bornholio** [comment]
ad **feature request** tag?

**Comment by NathanKell** [comment]
I added this to ksp 1.2. I, uh, forget the cfg value to use though.

Sent by my thumbs, slowly.

**Comment by NathanKell** [comment]
(the disallowing EVA from certain pods thing. I think maybe one of the mk1
cockpits uses it in stock?)

Sent by my thumbs, slowly.

**Comment by pap1723** [comment]
Found it! Here is the literature on it:
`noAutoEVAAny disables auto EVA always, whereas noAutoEVAMulti allows it if there is only one part on the vessel.`

I don't really understand the information about if there is only one part on the vessel?

**Comment by NathanKell** [comment]
Nm. Looked. The Mk1 Crew Cabin has `noAutoEVAMulti = True` so use `noAutoEVAAny = True` on those parts you want to disable. Not sure if clicking on a hatch manually would still trigger something, could probably write a quick partmodule to kill that too.

**Comment by pap1723** [comment]
This is accomplished by the NoEVA module implemented by NK.
