### ISSUE TITLE
Introduce a 'Stations' line of the tech tree, place station hardware appropriately

### ISSUE THREAD

**Issue by stratochief66** [KSP-RO/RP-0#416]
This is a goal to accomplish before the next major release, ideally.

@Niemand303 this is a serious niche that is missing in the current tech tree, and both @NathanKell and I (and I'm sure lots of folk) like your suggestion on how to place things.

Perhaps the first gen of stations should be unlockable after the Gemini node has been unlocked? (2nd Gen Capsules) rather than Mature, since the MOL is made to work with the Gemini?

We will also have to place some Raidernick (and other) stations and Soyuz to make good use of these new stations nodes.

Step one is creating a new node or two in the tech tree as you've suggested @Niemand303, can you look into that shortly?

**Comment by batuhantasli** [comment]
I'll have lots of free time in couple days and I've already begun coding @Niemand303 's new tech tree from scratch, without CTT. I can probably make a CTT version of it after I finish coding it, so that means we can have the new tech tree for the next major release. Fair enough?

**Comment by stratochief66** [comment]
once you have a working copy up to mercury or so, please give us a link to your repo and I can take a look at it :)

**Comment by Niemand303** [comment]
The tech tree I proposed in my suggestions has the separate branch for stations, it's one of the green-coded nodes (completely new ones), in the bottom of the tech tree. :)

**Comment by batuhantasli** [comment]
@Niemand303 I believe @stratochief66 proposes that we remove the Mature Capsules' link from first node of station line, so that MOL can be used with Gemini before unlocking Apollo etc. Am I right? Or maybe we can place it in a previous node, since it was supposed to be in orbit for only 40 days according to Wiki, I'm not sure. Your thoughts?

**Comment by Niemand303** [comment]
Yeah @batuhantasli  I think that would work better. I approve that change.

**Comment by pap1723** [comment]
Irrelevant with the new Tech Tree
