### ISSUE TITLE
Let's map probe progression!

### ISSUE THREAD

**Issue by pjf** [KSP-RO/RP-0#42]
RO players are going to be using a lot more unmanned probes than stock players, so let's map out the progression of probes. You *can edit* this top-post if you're an RP-0 contributor.

We can have a separate ticket for HSF pods.

I figure we can start off by determing the order in which probes should unlock, we can figre out where to place them later.

Right now the first three probes the player unlocks are (with cost, weight and energy consumption rates):

- Sounding rockets avionics (2, 0.06, 6/min)
- Dontstayputnik (300, 0.0836, 3.6/hr)
- Okto2 (1,000 0.05, 3.6/hr)

Unsorted probes include:

- QBE (600, 0.512, 3/min)
- Ranger MkIII Core (450, 0.18, 36/hr)
- OKTO (450, 0.75, 4.5/min)
- RC-L01 (2000, 0.85, 3.6/min, remote command)
- RC-001S (750, 0.4, 1.8/min)
- Stayputnik Mk1 (300, 0.0836, 3.6/hr)
- MK2 Drone Core (1,500, 0.5, 30/min)

Things to note:

- Right now, there's no real compelling reason to use any other "supported" probe aside from the Okto2 or Dontstayputnik. They have a lower power usage than any other probe, and in most cases a lower weight as well.
- The Okto2 weighs a little less than the Dontstayputnik, and comes with integrated batteries, but it doesn't feel very compelling to use given its significantly higher price tag, especially since I still have to pay for the integrated batteries.
- I would suggest many of our probes can be either removed from the tree entirely, or can be given identical stats to the okto2 (same probe, different shape).
- The RC-L01 *does* need to be placed in the tech tree, as it's the only core that provides remote command capabilities for RemoteTech (as long as the station has at least six kerbals on board).

NON RO probes that show up (from SXT and MKS/UKS) include:

- SXT375mProbe
- SXTHECSRanger
- SXT-TMA1 (easter egg)
- LprobeFoil
- MKS.LogisticsHub
- MKS.Outfitter

Some of these look quite cool, so it would be nice to support them simply so we can build cool looking craft. :)

**Comment by NathanKell** [comment]
I think we're mostly done with this, discussion has moved to #130. Reopen as desired.
