### ISSUE TITLE
Typos/descriptions

### ISSUE THREAD

**Issue by Gnurfos** [KSP-RO/RP-0#420]
You need to upgrade Astronaut Complex to level 3 before you can plant flags, whereas the description displays "Kerbals on EVA can plant flags" as soon as level 2.

On the [FAQ](https://github.com/KSP-RO/RP-0/wiki/FAQ), near the end, is said the DSN stations have antenna range of 11,400,000,000km. I think there's a missing zero, and the correct value would be the one stated earlier (1.14e14 meters). I am  not sure, but if you confirm, let me know if I should modify it myself.

**Comment by NathanKell** [comment]
For the first point, description where? When you right-click the facility and then hover over the upgrade? That *should* be autogenerated.

On the FAQ, great catch! @Schnobs when you have a sec can you update that section based off the DSN changes and your range changes to antennas?

**Comment by Gnurfos** [comment]
Yes when right-clicking from the KSP screen. I thought the text was hardcoded (maybe in stock KSP), but maybe RP-0 changed the level when flags unlock, for balance reasons.

**Comment by Schnobs** [comment]
I've updated the FAQ to the new values not too long ago. 1.14e14 is from the config and 100% trustworthy. The spelled-out value now reads 114,000,000,000km -- if that's still wrong, please feel free to change it yourself.

**Comment by NathanKell** [comment]
Apologies, I'm out of date then!

Sent by my thumbs, slowly.

**Comment by NathanKell** [comment]
The flag thing appears to be a stock bug.
