### ISSUE TITLE
"Have Part on Vessel" issue with ModuleTag(Experiment) + Questions from newbie. 

### ISSUE THREAD

**Issue by ntimpe** [KSP-RO/RP-0#421]
I have been messing around with my RO/RP-0 install so it might just my me screwing things up, but ever since I had a run-in with a ScienceAlert/RemoteTech bug I no longer see the title of the experiment in the contracts window, just the default "part." It's pretty annoying, considering I have to accept the contract and then go into the save file and figure out what part it's asking for by looking at the ModuleTag(Experiment) that it's asking for (I do this by just renaming the title from "Part" to "Barometer" or whatever, seems to work fine so far). Looking through the RP-0 folder, I came up with a couple of questions. 
1. As I understand it, you have some code in there to make the contract request a specific experiment, not a specific part so that any of the mods with thermometers can have their parts complete the thermometer requirements. I'm not sure if this is really necessary, couldn't you just put the multiples in the "ORPHANS" slot in the tech tree (This is where you put the stuff you don't want, right)?
2. I'm not seeing where the title is being set to the specifics of the experiment, so it's throwing an exception and showing "part" for the title in the contract, just it's name and the ModuleTag(Experiment). Where is this located, so I can try to fix whatever I managed to mess up?

Thanks in advance, and great work @NathanKell and others!

![screen shot 2016-01-04 at 9 39 57 pm](https://cloud.githubusercontent.com/assets/5471605/12108917/dc3ba5a0-b339-11e5-9c0a-18409b17f654.png)
This is what it looks like before I edit the save file
![screen shot 2016-01-04 at 9 40 37 pm](https://cloud.githubusercontent.com/assets/5471605/12108922/e60bd4ec-b339-11e5-87f3-55d20a3b9943.png)
These show my edits, just so I don't forget.

**Comment by ArtForz** [comment]
Ran into the same issue.

Changing the PART_REQUEST sections in RP-0/Contracts/StockContracts.cfg to use Article/PartDescription/VesselDescription instead of Title (and then regenerating contracts in my save) fixed it for me.

I don't think this is related to ScienceAlert/RT at all, looks like stock 1.0.5 changed how PART_REQUEST is handled.

**Comment by NathanKell** [comment]
Yep, the syntax changed in 1.0.5 and I missed that fact. Thanks!

**Comment by ntimpe** [comment]
Thanks @ArtForz, il do the same thing. It occurs to me now that I fixed the ScienceAlert/RT bug just after I updated to 1.0.5

**Comment by NathanKell** [comment]
This was fixed!
