### ISSUE TITLE
Experiments

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RP-0#43]
[Here](https://www.dropbox.com/s/stcznnjutegzdtp/RP0%20Launch%20Research.xls?dl=0) is the list of probes launched 1957-1962, with their experiments, kindly catalogued off [Gunter's Space Page](http://space.skyrocket.de/doc_chr/lau1957.htm) by forumer JRA.

It should provide a great base for a discussion of what experiments we should add or re-target, not least because adding different experiments to different probe cores is a great way of dealing with #42.

**Comment by DMagic1** [comment]
I finally started working on science reports for this. I've finished the orbital experiments (except for Earth/Kerbin I'm not sure how replacing those will work); it's a mix of around half adapted from existing reports and half new reports, mostly from Jupiter's moons.

I still have the four surface experiments to finish, it shouldn't take too long.

**Comment by NathanKell** [comment]
Amazing timing, as I was just looking into that for a forthcoming version. :)

**Comment by DMagic1** [comment]
I'll be releasing an update for DMOS today with all of the non-Earth RP-0 science text. 

How should I handle the Earth results? Will this [MM config](https://github.com/KSP-RO/RP-0/blob/ScienceReports/GameData/RP-0/Resources/ScienceReports.cfg) replace all Kerbin text? That's fine with me, I've always treated the Kerbin results as more-or-less an afterthought.

**Comment by pjf** [comment]
@DMagic1 : My understanding is that it will, although I'm not directly responsible for that part of the codebase. My understanding is that in RP-0 the surface science multiplier for Earth is zero, so nothing yields science until you at least get it off the ground.

Absolutely looking forward to the new release. Thank you so much for all your awesome work! :)

**Comment by pap1723** [comment]
This does not really need to be here anymore. Obviously there will always be the goal of getting to RealScience, but will most likely never happen.
