### ISSUE TITLE
Rovermate core seems to provide infinite avionics

### ISSUE THREAD

**Issue by Gnurfos** [KSP-RO/RP-0#433]
This is OK for the rover itself (maybe), but while it's attached to the rest of the rocket, avionics parts are not needed, whatever the mass.

**Comment by NathanKell** [comment]
I wasn't aware we even placed/priced it.Does it not say "Non-RP0" ?

**Comment by Gnurfos** [comment]
No it doesn't (by the way, side question: is there a way to hide these non-rp0 and nocost parts easily ?).
If it did, are there alternative for unmanned rovers cores (I did not find them), or is this aspect not overhauled yet ?

**Comment by NathanKell** [comment]
Huh, I guess we do price/place it then. I'll add an avionics limit I guess, or a PR would be great. :)

The reason I thought it wasn't yet was indeed because we haven't got there yet.

**Comment by winged7** [comment]
https://github.com/KSP-RO/RP-0/pull/434

**Comment by NathanKell** [comment]
Awesome!
