### ISSUE TITLE
Apollo Costs

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RP-0#442]
I really doubt our Apollo CSM is costed appropriately. Were they really only about $9mil for the CM (in 1965 dollars) and another 10-15 for the SM, compared to 59 mil for a Big G spacecraft?

**Comment by ctiberious** [comment]
Found this document: http://www.asi.org/adb/m/02/07/apollo-cost.html  It says the estimated cost per spacecraft for the Apollo CSM was $220M and the LEM was $170M.  Unfortunately, it doesn't give a cost per spacecraft for Gemini (let alone Big G).  Only a total cost for the whole Gemini program.  I believe this is also in 1994 dollars so you'd need to convert it back to 1965 equivalent.

**Comment by pap1723** [comment]
Can anyone confirm we have better costs now?

**Comment by pap1723** [comment]
Updated now with https://github.com/KSP-RO/RP-0/commit/3c342881f9459f8db4f636cb91a1854fe4addc66
