### ISSUE TITLE
Science Returns Scaling

### ISSUE THREAD

**Issue by Felger** [KSP-RO/RP-0#46]
A common issue complained about in Stock is the preponderence of science points you can gain by farming Mun, Minmus, and Kerbin, to the point where you can complete the entire tech tree by farming science in-system only, without venturing out into the solar system.  

Obviously, we don't want to encourage that behavior in RP-0, and I would like to include a game-mechanic means of promoting that behavior.

Suggestion - Each time you collect science from a particular body, the science reward for that experiment for that body goes down by a factor, with a maximum amount of science (based on biome number) possible.  Example:
- Luna has 8 Biomes, and there are 4 conditions available giving a total possible number of combinations of 32.
- By default, let's say our experiment would grant 50 science per biome, which comes out to 1600 science for just the one experiment.  Way too much without leaving the local system, not even considering science bonuses for contracts and the like.
- Instead, we reduce the science per-biome and condition for each time the experiment is run on the body, or perhaps in the body-condition pair.
  - Say, twice the science value - 2*50 science per Body/Condition pair: 400 science for our example.
  - Then, each time you collect science the amount you gain from that experiment goes down, since some of your data is redundant.
  - I've tinkered with the scaling in excel, and found a decent curve that never returns negligible results, but hits the cap after ~10 experiments:
    ![scireturnschart](https://cloud.githubusercontent.com/assets/8065024/5430718/b9da5084-83dc-11e4-8f73-9fec232e6987.PNG)
  - Equation that produces this:
    ![scireturnequation](https://cloud.githubusercontent.com/assets/8065024/5430805/a31992e0-83de-11e4-9eef-b54d082cee39.PNG)
  - Where S_0 is the previously returned value, S_Total is the total available science (400 in this case)

Obviously this isn't the only way to do this, but I like the idea of artificially limiting the total gains you can get from science in one particular area, encouraging you to branch out in the rest of the solar system, without making the game feel like a grind, grabbing biomes and the like.

**Comment by cherrydev** [comment]
A stop-gap measure that could make sense would be to simply make the per-biome experiments not very valuable.  Any tweaking to that could be filled out with Contracts, as @Felger says: Make a contract that would require the player to perform a science experiment from specific biomes.  This can already be done using Contract Configurator in a general way (without specifying the exact experiment) but will be available soon when [this](https://github.com/jrossignol/ContractConfigurator/issues/63) issue is implemented.  I'm interested in implementing contracts for RP-0, so please comment on issue #65 if you have ideas.

**Comment by pap1723** [comment]
Fixed (or improved) with new science system.
