### ISSUE TITLE
Perhaps more GEO or GSO contracts?

### ISSUE THREAD

**Issue by ntimpe** [KSP-RO/RP-0#463]
A lot of modern satellite contracts are go Geostationary orbits, but there's currently only the World's First GEO contract. Perhaps we should have more of them. I'd be happy to add them, but I wanted to get your input before I do so.

**Comment by NathanKell** [comment]
That would be great! In fact, we really need more satellite contracts period; we currently rely on the stock game's satellite contracts, tuned as best we can, but they really don't quite suit our needs.

**Comment by pap1723** [comment]
Completed
