### ISSUE TITLE
Raidernick part fixes/adds

### ISSUE THREAD

**Issue by raidernick** [KSP-RO/RP-0#471]
I don't know exactly who is responsible for adding my stuff to this but I want to thank you for doing it. I do not have the time or knowledge to add anything to this mod. If you notice my stuff doesn't even work properly with stock as I just make up random values for cost and tech and I don't use/like career mode. I do get a LOT of requests for adding stuff to this though.

I recently made some changes to my mods renaming parts, especially in the soviet packs, so pretty much all of those parts will be broken here now and need to be fixed.

I also would like to request that whatever is not added currently be added as I have been working on adding a lot of parts recently, especially early US stuff and I keep getting requests from people to add it here but have zero time and absolutely no knowledge of how career mode works for stock, let alone this( I have never even used career mode or watched anyone use it).

Perhaps @NathanKell can tag whoever likes working on, has worked on or is currently working on my stuff to make them all aware of these changes.

**Comment by stratochief66** [comment]
For the parts that were previously configured in RP-0: If you change the names in tree.yml from their old names to their new names, they will continue to work. You are, after all, uniquely situated to know all the parts that have had name changes, and what their new names are. :P

**Comment by NathanKell** [comment]
The problem is that parts were combined, and new parts created.

Pinging @batuhantasli  and @Niemand303  who I believe were involved in the first pass on these?

**Comment by raidernick** [comment]
@stratochief66 parts were added, removed and combined. A lot of stuff there no longer exists or is even the same part it was previously and therefore not just the name is wrong, but the entire config will be irrelevant.
