### ISSUE TITLE
RCS fuel changes behind my back

### ISSUE THREAD

**Issue by Schnobs** [KSP-RO/RP-0#477]
early career:
1) build vessel, attach RCS thrusters. They default to Nitrogen; "buy" NitrousOxide and fill a tank with the same.
2) save vessel, go away.
3) come back, load vessel. The thrusters are now set to HTP (even if it isn't researched yet).

**Comment by NathanKell** [comment]
Can you do me a favor? Try to reproduce this: at 2, check the .craft file and see what the RCS thrusters have as `configuration =` (inside ModuleEngineConfigs)

**Comment by Schnobs** [comment]
name = ModuleEngineConfigs
                isEnabled = True
                configuration = HTP
                techLevel = 0
                thrustRating = thrusterPower
                modded = False
                stagingEnabled = True

**Comment by NathanKell** [comment]
Thanks! That's very odd indeed.
