### ISSUE TITLE
scansat placement and stats

### ISSUE THREAD

**Issue by Schnobs** [KSP-RO/RP-0#494]
I think we've already agreed that the biome scanner should be in /Landing/ for gameplay reasons.
I'd like to make the early radar contemporary with Pioneer10/11, and the late Hi-Res Radar Altimetry could be Magellan, mid-to-late 80s.

Stats need tweaking and playtesting; required altitudes definitely should be pretty low.

From very limited preliminary testing I think the field of view could be narrowed down as well, without turning scanning into needless busywork.

Power consumption: when I last touched this I set it so that people have the means to operate the scanners when they first become available. If placed as stated above, that would be ~150-200W for biome and early radar, possibly more for late hi-res radar. Though I'd still like to keep it doable on RTGs (don't know what power sources would be available then).

This is a request for comments. If there are objections, please express them now. Otherwise a go-ahead would be most welcome.

**Comment by stratochief66** [comment]
This makes sense to me. A narrow FOV makes sense, as if you want to specifically photo-rec for a desired landing site you will have to customize your orbit, and/or by standard scansat system you can just throw the sat into a reasonably efficient orbit and wait, it will eventually scan everything.

(After some time for @NathanKell and others to chime in, a day or so) if you PR suggested scansat changes (having tested them yourself in game as well, of course) I will make sure not to euthanize my current late/mid game RP-0 build, and I can do some secondary playtesting and provide feedback as well. I might even make a youtube video out of it :P

**Comment by NathanKell** [comment]
I believe what we worked out in discussion in IRC a few weeks back was...not quite that. I'll dig up the logs, I guess, to refresh myself, but here's what I remember.

1. Existing radar scanner stays where it is.
2. An early-tech biome scanner is brought to the electrics/science node of Tier 4 (Improved Electrics) and the node is made mid-60s not late 60s.
3. The Large Electrics node is moved back to Tier 4.5 or early Tier 5, to be in line with early 1970s tech, and the altimetry scanner there is perhaps remade to have a narrower FOV.
4. A later-tech biome scanner is added for the 1980s, along with a combined altimetry scanner with high FOV.

**Comment by Schnobs** [comment]
There is exactly one biome scanner, no early or late models.

Going off on a tangent: I have long since thought about utilizing Scansat to create "Real Cameras" where distance would determine the size of the frame and level of detail. A straightforward (field of view) x (number of pixels) kind of thing, with transmission value based on number of pixels uncovered. This could even return actual pictures (created by appropriately blurring the planet textures), with biome information being merely a side effect. Sadly, that would require a complete workover of Scansat internals.

I also recently wondered about making early scanners dependent on a unique resource (film stock) that is consumed whenever the scanner is active.

However, that's not what we have. We have a single Biome Scanner and two Radar Altimetry Sensors. Their resolutions are set, we may only adjust a) at what altitudes they will work, b) field of view, and c) power consumption.

The biome scanner is pretty high-res and will work as long as it has power and is on the desired altitude. So it only takes a one-shot mission to map out an entire bodies' biomes at great detail. Realistically, such a thing probably shouldn't exist, or at least not before the 90s. From a gameplay angle it should be available as early as possible (biome whack-a-mole), or at least by the time one is expected to do landings in specific biomes.

Of the two radar altimetry scanners, one has a very low resolution and  the other very high resolution. For purposes of picking a landing site, the former is pretty nearly useless. Just looking at the body in map view will give you a better idea of where you can expect level terrain. I therefore propose to treat both as pure scientific instruments without gameplay ramifications, and placing them accordingly.

A quick search suggests that Seasat (1978) was the first radar imager, and I'm looking to Magellan (1989) for hi-res.

**Comment by NathanKell** [comment]
My comment was unclear. By "an early-tech biome scanner" I mean _making_ one. Which we can do, we are not in the least stuck with the parts SCANSat gives us, we can put any combination of scanning modes on any part, and/or clone parts and change them around. We could, say, use SXT's new antenna as a SCANSat scanner if we wanted.

The first radar imagers were done in the early 1960s IIRC, with synthetic aperture done in the mid 60s. See Project Quill.

**Comment by Schnobs** [comment]
Resolution doesn't seem to be accessible to MM patches. Do you want RP-0 to come with it's own dll, or is there something I'm missing?

**Comment by NathanKell** [comment]
Resolution does not, no, afaik. @DMagic ?
But it can be prohibitively expensive in mass and wattage such that one can mount _only_ that on early probes, whereas a later model could be combined with other scanners.

**Comment by Schnobs** [comment]
Merely heavy and power-hungry? That will be easy, but I'm not sure if it will be effective. Just build a bigger LV. The asteroid day camera has wonderful bulk, but I presume you don't want to keep that dependency once the other AD parts have been stockified.

**Comment by Schnobs** [comment]
The Lunar Orbiters were ~380kg apiece, light enough to be launched on an Atlas-Agena. My source says the entire scientific payload way 64kg; as there were a few other experiments, I'd guess no more than 60kg for the camera proper including film stock. Power demand was ~230W, with the solar panels able to provide twice as much in ideal conditions.

None of that is prohibitive; their main drawback was that the supply of film wouldn't last to map the entire moon in one mission.

Possibly silly, but hey: How about including a biome scanner on the film return camera? That would be a dry mass of 200kg in any event. If you want to operate it as scanner, you also need electricity and some 50-100kg of a resource. Weightless tanks included on the part. I'm loath to add film stock / exposed film just for this purpose and would just as happily convert turpentine into wastewater. TACLS converter so the stuff *will* be consumed. Default loadout could last for 3-5 days.

A 250kg scientific payload to the Moon is quite a bundle, but entirely doable with Mature Rocketry and Flight Control.

**Comment by Schnobs** [comment]
Cute idea; doesn't work. A) I'm not sure how I should hook the scanner to a TACLS converter; B) even if I could, it would keep humming along for years without problems. Only when I switch back to the vessel will it realize that it has long since run out of resources.

**Comment by Schnobs** [comment]
For my own purposes, I added the biome scanner module to the Film Return Camera, drawing 250W. The latter is kinda unimportant as no power is needed while one is away... if one were to stay focused on the craft, it should last for about five days. It takes six days to map Earth.

That's with a fov=2. Still enough to cover Wales or even Ceylon in their entire width.

**Comment by pap1723** [comment]
RP-1 Tech Tree
