### ISSUE TITLE
Provide configs for TestFlight R&D system

### ISSUE THREAD

**Issue by jwvanderbeck** [KSP-RO/RP-0#498]
TestFlight v1.5.4 is out which includes the R&D system.  I imagine RP-0 will want to have its own config for setting the R&D values.

This is the default (set by code when a config isn't found)

```
TFRNDSETTINGS
{
    updateFrequency = 86400
    TEAM
    {
        points = 100
        costFactor = 1
    }
    TEAM
    {
        points = 125
        costFactor = 1.5
    }
    TEAM
    {
        points = 150
        costFactor = 2
    }
}
```

**Comment by stratochief66** [comment]
100 data units added per day (86400 seconds), what does the costFactor multiply by? ie. how is the cost per day derived?

**Comment by jwvanderbeck** [comment]
Cost per day is simply `points * costFactor`.  In other words costFactor is how much **each point** of du costs.

These can be further modified by the individual part if it has `rndRate` or `rndCost`.

The final equations are thus:
`points applied = team points * rndRate`
`cost = team points * cost Factor * rndCost`

**Comment by jwvanderbeck** [comment]
@NathanKell 
(tag and run!)

**Comment by NathanKell** [comment]
Ok. So we'd basically need to apply the rndRate and rndCost modifiers to pretty much everything. So I think the default configs are acceptable, basically, it's just the tuning per part that is at issue, although I can probably modify our configger to do that. However, where are those added per part? To the TF core module? somewhere else? The complication is that engine configs modify base part cost...

**Comment by jwvanderbeck** [comment]
I actually think the base numbers might be a bit high but that is up to you of course.

The per part configs are on the core yes, and can be set, as with everything, different for different configs.

There are three new properties on the core:
rndMaxData, rndRate, and rndCost

**Comment by NathanKell** [comment]
The base numbers don't matter that much, it's the per-part mults. ;) I was thinking something like use 10% of price as a multiplier.

I guess we'd have to offset the multiplier based on the config, but that requires doing a HAS with a variable (MM doesn't support it) or doing it by hand, I fear.

**Comment by jwvanderbeck** [comment]
Are we talking entryCost here? That is in your yaml so in theory can be compiled.  Then again I don't think the individual engine configs are in there...hmm

**Comment by jwvanderbeck** [comment]
Oh and don't forget time too.  IE Time to research, or how many du per research cycle (1 day by default).  That applies in Science and Sandbox modes as well.

**Comment by NathanKell** [comment]
This was done a long time ago \o/
