### ISSUE TITLE
Make a .version file and make Travis build it.

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RP-0#500]
Related to https://github.com/KSP-CKAN/NetKAN/issues/3465 which describes the netkan change to our local netkan file once we do this.

**Comment by jwvanderbeck** [comment]
You could probably steal the code I wrote for RO/TF?

**Comment by pjf** [comment]
@jwvanderbeck : Where do I find this code? Laziness is my superpower, so I love the thought of not having to do anything. :)

**Comment by NathanKell** [comment]
Perls before py-swine tho. https://github.com/KSP-RO/RealismOverhaul/blob/master/makeMeta.py

**Comment by jwvanderbeck** [comment]
pfft

**Comment by jwvanderbeck** [comment]
If you **do** use it though, it will need the ever so slightest (easy) change to deal with your tags having "v" in them.

**Comment by pjf** [comment]
As you wish: #508.
