### ISSUE TITLE
RF Tech Levels

### ISSUE THREAD

**Issue by batuhantasli** [KSP-RO/RP-0#523]
It is possible to choose any type of tank type from the start.

**Comment by NathanKell** [comment]
Nope. Construction nodes unlock new tank types.

**Comment by batuhantasli** [comment]
I only unlocked first construction node in my RP-0 career and even cryogenic was on the list. Isn't it unlocked in a late node?

**Comment by Zarbizaure** [comment]
the cryogenic tank type is unlocked later, in the hydrolox TL2 node I think (but i'm not sure).
Also, that's something PP should show in the tech tree, a bit like Mechjeb: just display the standard procedural tank and explain the upgrade in the description.

**Comment by leudaimon** [comment]
Per RP-0/ResourceTechs.cfg:
Default -> Early construction
Service Module/Balloon -> Basic construction
Cryogenic/Balloon Cryo -> Adv construction
If you have anything different, you may have a problem in your install. 
It would be nice if this was shown along with the diameter upgrades in the tech tree - is it possible?

**Comment by Temeter** [comment]
I had at some point the issue where RealFuels would show me all tanks, but I only could use cryogenic. Maybe that's your problem?

**Comment by pap1723** [comment]
I can confidently say that the proper tanks are unlocking in the proper nodes, however, I think we can use the new PARTUPGRADE feature to create the icons for these so they are shown in the proper nodes.
