### ISSUE TITLE
RaiderNick Soviet Probes & Rockets Parts list for tree integration.

### ISSUE THREAD

**Issue by RezzyD** [KSP-RO/RP-0#53]
###### Will keep this updated with any changes

His latest update add's Molniya-M rocket.

| Rocket | Blok A | Blok BVGD |
| :-: | :-: | :-: |
| **Sputnik** | r7_blok_a_sput | r7_blok_bvgd_sput |
| **Vostok** | r7_blok_a | r7_blok_bvgd |
| Molniya-M | Coming | Soon |
| **Soyuz** | r7_blok_a_soyuz | r7_blok_bvgd_s1 |
##### Engines + Verniers
1. **RD-108**
   - r7_blok_a_engine + r7_vernier_engine_v_fg x4
2. **RD-107**
   - r7_bvgd_engine   + r7_vernier_engine_v_fg x2
3. **RD-0110** -  Blok I for Soyuz
   - r7_blok_i              + r7_vernier_blok_i_s_fg x4
##### Engine Config's
- 1. name = RD-107 8D74PS
- 1. name = RD-108 8D75PS
- 2. name = RD-107-8D74-1959
- 2. name = RD-108-8D75-1959
- 3. name = RD-107A
- 3. name = RD-108A
##### Sputnik PS1 - Fairing Base - Nose Cone - Probe

sputnik1_base
sputnik1_nosecone
sputnik1
##### Sputnik PS2 - Nose Cone - Probe

sputnik2_nosecone
sputnik2
##### Sputnik3/Object D - Fairing Base - Nose Cone - Probe

sputnik3_base
sputnik3_nosecone
sputnik3
##### Luna - Payload Base - Nose Cone - Probe/s

luna_base
luna_fairing
luna2 - Description = Soviet Luna E-1A Series Probe.
luna3 - Description = Soviet Luna E-2A Series Probe.

```
                                Molyina Parts Coming Soon
```

r7_adapter_blok_e    - Decoupler for Vostok & Soyuz
r7_vostok_blok_e     - Blok E for Luna Probes Untested with Vostok SpaceCrafts

```
                             ****** Others ******
```
###### Fairings for Soyuz Spacecraft or Fregat Payload
- r7_les 
- r7_soyuz_fairing - Fairing for RN Soyuz 7K / BobcatTMA
- r7_adapter_blok_iv2 - Payload base for third stage of the R7 rocket 
- r7_blok_i_fairing_s  - Standard
- r7_blok_i_fairing    - Fregat r7_adapter_blok_i
##### Fairings for Vostok Spacecraft
- r7_vostok_fairing_r -
- r7_vostok_fairing_l  - 
##### Price Considerations

r7_vernier_engine_v_fg x12 on each LV
- http://www.foia.cia.gov/sites/default/files/document_conversions/89801/DOC_0000316262.pdf
  - Last few pages has info on cost estimation
    
    ```
                                     **Issues & To Do**
    ```
- Yet to add Descriptions & Titles to most parts suggestions welcome here 
- Blok E for Vostok/Luna Probes is undergoing rework to its control ability. Should be done soon.
- Testing needed for most parts. RT settings and Battery Supply especially.
- Rework/Fix of gimbal / verniers may be needed. 
- Proper designation's for Rockets & Probes Eg Sputnik: Rocket - 8K71PS; Probe - PS1
- Clean up Fairings on this list

**Comment by pap1723** [comment]
This is too old to be useful. These need to be looked at from scratch now.
