### ISSUE TITLE
Concrete runway textures are above ground level which sinks landing gears to ground

### ISSUE THREAD

**Issue by 711hancer** [KSP-RO/RP-0#531]
When I install RP-O with RSS through ckan, the default tarmac runway turns into a normal concrete runway, but this runway texture is slightly above the default tarmac texture height so when loading planes for test and regular flights, 80% of the time the gears do not recognize the concrete runway and sink into ground (to the default tarmac runway height)

I tried with and without texture replacer mod. same results.

My mod list:

(Semi)Saturatable Reaction Wheels (SemiSaturatableRW 1.11.0)
Advanced Jet Engine (AdvancedJetEngine v2.7.1)
Astroniki Sunflare for Scatterer (AstronikiSunflareforScatterer 1.1)
B9 Aerospace Procedural Wings - Fork (B9-PWings-Fork 1:0.40.7)
Community Resource Pack (CommunityResourcePack 0.5.2.0)
Community Tech Tree (CommunityTechTree 1:2.4)
Connected Living Space (ConnectedLivingSpace 1.2.1.1)
Contract Configurator (ContractConfigurator 1.11.5)
Custom Barn Kit (CustomBarnKit 1.1.8.0)
Deadly Reentry Continued (DeadlyReentry v7.4.4)
Environmental Visual Enhancements (EnvironmentalVisualEnhancements 2:EVE-1.1-2-1)
Environmental Visual Enhancements - Config files (EnvironmentalVisualEnhancements-HR 2:EVE-1.1-2-1)
Ferram Aerospace Research (FerramAerospaceResearch 3:0.15.6.4)
Firespitter Core (FirespitterCore v7.2.4)
Firespitter Resources config (FirespitterResourcesConfig v7.2.4)
Graphic Memory Monitor (GCMonitor 1.4.3.0)
Kerbal Construction Time (KerbalConstructionTime 1.3.3.7)
Kerbal Joint Reinforcement (KerbalJointReinforcement v3.1.7)
Kopernicus Planetary System Modifier (Kopernicus 2:release-1-0-4)
KSC Switcher (KSCSwitcher 0.6)
MagiCore (MagiCore 1.1.1)
MechJeb 2 (MechJeb2 2.5.7.0)
ModularFlightIntegrator (ModularFlightIntegrator 1.1.4.0)
Module Manager (ModuleManager 2.6.24)
Procedural Fairings (ProceduralFairings v3.17)
Procedural Parts (ProceduralParts v1.2.3)
Real Fuels (RealFuels rf-v11.2.0)
Real Plume (RealPlume 2:v10.5.1)
Real Solar System (RealSolarSystem v11.2.0)
Real Solar System Textures - 4096 x 2048 (RSSTextures4096 v10.4)
RealChute Parachute Systems (RealChute v1.4.1.1)
RealHeat (RealHeat v4.2)
Realism Overhaul (RealismOverhaul v11.0.0)
Realistic Progression Zero (RP-0 v0.48)
RemoteTech (RemoteTech v1.7.0)
SCANsat (SCANsat v16.1)
scatterer (Scatterer 2:v0.0246)
ShipManifest (ShipManifest 5.1.0.0)
SmokeScreen - Extended FX Plugin (SmokeScreen 2.6.15.0)
Solver Engines plugin (SolverEngines v2.1)
Stock Extension (SXT v25.2)
TAC Life Support (TACLS) (TACLS v0.12.1)
TAC Life Support (TACLS) - Realism Overhaul Config (TACLS-Config-RealismOverhaul v11.0.0)
Taerobee - Stockalike X-1 & More (Taerobee 1:2.3)
TestFlight (TestFlight 1.6.0.2)
Toolbar (Toolbar 1.7.12)
Ven's Stock Part Revamp (VenStockRevamp v1.9.2)

**Comment by PhineasFreak** [comment]
This has already been fixed for the 1.3 version of KSP.

Close this?

**Comment by Bornholio** [comment]
Close Me.
