### ISSUE TITLE
Early Parts Locations

### ISSUE THREAD

**Issue by samroberts10** [KSP-RO/RP-0#54]
The LR-79/89 has no vernier making it much less useful. Could the stock part be moved to the same node as it? Also maybe launch clamps moved to the first node as it makes launching much easier?

**Comment by NathanKell** [comment]
This was a change Ven made in 1.6 of Stock Parts Revamp (removing the gimbal from the Mainsail). It will be reverted in the next Stock Parts revamp, but for now we can work around it.

**Comment by NathanKell** [comment]
Fixed by 8c425f4df76da6213ce5862e5d6894bc92c7f170
