### ISSUE TITLE
Kerbin Construction Time config breaking the ability to upgrade to multiple build queues 

### ISSUE THREAD

**Issue by umaxtu** [KSP-RO/RP-0#540]
***Started a new game and selected the RP0 preset. Now at upgrade screen***
![ksp_x64_2016_05_22_12_54_33_169](https://cloud.githubusercontent.com/assets/2151266/15455236/95db9160-201c-11e6-82d4-c22ac298e82d.png)

***Now viewing SPH tab***
![ksp_x64_2016_05_22_12_54_44_156](https://cloud.githubusercontent.com/assets/2151266/15455261/f5be685a-201c-11e6-8ddf-030c296487cb.png)

***The Aftermath***
![ksp_x64_2016_05_22_12_54_51_453](https://cloud.githubusercontent.com/assets/2151266/15455316/56e09d1e-201e-11e6-8929-cec82b1cb977.png)
![ksp_x64_2016_05_22_12_55_00_946](https://cloud.githubusercontent.com/assets/2151266/15455320/6ed15698-201e-11e6-8aca-830efe9aff80.png)

* In this example, I tried to purchase a second queue for the SPH, but this issue also occurs when I try it with the VAB.
* I've also tried putting the 15 remaining upgrade points into the VAB/SPH (whichever didn't have Rate 2 vanish) but the button to upgrade Rate 2 didn't reappear. 
* I have also copied the config into a fresh install with only KCT and its dependency installed and had the same issue.

**Comment by jwvanderbeck** [comment]
You need to upgrade your VAB to be able to have two build queues

**Comment by NathanKell** [comment]
It is a display bug in KCT that Rate 2 is shown at the start despite your not being able to have it.

**Comment by SirKeplan** [comment]
Possibly should be made more obvious in game that a VAB upgrade is necessary?

**Comment by umaxtu** [comment]
Wow I feel like an idiot. Sorry about that.
