### ISSUE TITLE
Getting Started Wiki needs updating - Aerobee Engines have Max Burn Time via Test Flight

### ISSUE THREAD

**Issue by lamont-granquist** [KSP-RO/RP-0#547]
See:

https://www.reddit.com/r/RealSolarSystem/comments/4nguld/first_rorssrp0_playthrough_wiki_question/
https://www.reddit.com/r/RealSolarSystem/comments/4jpoh8/help_aerobee_engine_shutting_down_early/
https://www.reddit.com/r/RealSolarSystem/comments/4m4qgp/aerobee_engine_shutdown_mid_flight_and_cant/

The issue is that Test Flight now gives engines a rated burn through time.  You can't have a single Aerobee engine for a WAC-Corporal now with ~3k deltaV and 1.5 TWR -- it'll just cut out with 2,000 dV left.

**Comment by NathanKell** [comment]
Yep! Definitely need to update it. Thanks for the ticket!

**Comment by NathanKell** [comment]
https://www.youtube.com/watch?v=FGqPWHCbvdY although I will also update the text version.

**Comment by NathanKell** [comment]
Was this ever fixed?

**Comment by lamont-granquist** [comment]
hahah, i have no idea.  i never did.

**Comment by pap1723** [comment]
I will work on redoing this, but I want to wait until our early game changes are more complete

**Comment by lamont-granquist** [comment]
heh back when RSS/RO/RP-0/TestFlight were so big and scary I wouldn't think of touching the wiki myself...

**Comment by pap1723** [comment]
@nepphhh has done a great job of getting the Wiki into a good place!
