### ISSUE TITLE
Kerbalism support?

### ISSUE THREAD

**Issue by gt33** [KSP-RO/RP-0#556]
It'd be nice if the life support mod Kerbalism was supported (well, it's Realism profile supported). I prefer it to TAC-LS, and I can guess some other people do. I could likely do this, but i'd probably make the prices and stuff unrealistic.

**Comment by NathanKell** [comment]
My understanding was that Kerbalism was deliberately aimed at being a "lighter" TACLS and RemoteTech. Not so?

**Comment by jwvanderbeck** [comment]
Seems like it would be a handful given that Kerbalism appears to be an
entire mod suite on its own.

- John Vanderbeck
- http://www.johnvanderbeck.com

**Comment by Quartz101** [comment]
@NathanKell Actually, Kerbalism has more features than TAC-LS. As far as I know, Kerbalism will notify you and stop time warp if, for example, one of your ships is running low on, say, food, or oxygen. Kerbalism also has solar storms, malfunctions, stress, and alot more. Not trying to put down TAC-LS as an inferior mod....

**Comment by NathanKell** [comment]
Ok, then perhaps it's time to revisit. Certainly the comm side of it was always (IIRC) sold as as a "lite" version--i.e. what we'll likely get in 1.2--not RT's level of complexity. RO being a realism suite, we have been of course less than enthusiastic about lite or "gamplay first!!!one" mods. :]

**Comment by jwvanderbeck** [comment]
The problem I see with it is that it is an entire suite of mods, kind of like RO is itself.  It's TACLs, It's RT, It's TestFlight, etc, etc.

Is it even possible to take parts of it and not the others?

**Comment by Quartz101** [comment]
@jwvanderbeck With it's "profiles" you can enable some parts, disable others, and modify some. It has a realism profile, etc etc.

**Comment by jwvanderbeck** [comment]
Ahh cool, because some parts of it do some neat.

**Comment by Zarbizaure** [comment]
Kerbalim has some great options that others mods don't have, like radiation or crew psychological status. However, it is less advanced for the com section/life support section (I believe it lacks water). It could be good to implement only some parts of it (the greenhouse, radiations, quality of life, malfunctions, space weather and status monitor), and to let the others be managed by RT/TACLS but this is probably hardcoded into the .dll plugin and there's probably no way to change it withouth help from ShotgunNinja.

**Comment by N70** [comment]
Kerbalism does have water (just enabled the realism profile, aka renaming "Realism.cfg-disabled" to "Realism.cfg" and "default.cfg" to "default.cfg-disabled". Also, ANY part of it can be disabled w/ a profile.

**Comment by EagleEyeLogic** [comment]
I've made the first step to integrate TACLS and Kerbalism automated or if no LifeSupport to prefere on for later use.

I need a bit input if anything works fine and what kind of Modules we will integrate.

In particular we have to test if the Backgroundprocessing of Kerbalism can handle 

MudulGenerator and ModuleResourceConverter and up to which TimeWarp it is then safe.

https://github.com/KSP-RO/RealismOverhaul/issues/1309#issuecomment-234768307

**Comment by N70** [comment]
Would it be possible w/ RSS to intergrate actual magnetosphere data, etc, if known w/ Kerbalism's radiation mechanic?
