### ISSUE TITLE
Check periods in part names

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RP-0#56]
I noticed in tree.yml that some parts have periods in their names. @pjf when you have a chance can you verify the Universal Storage parts you added (e.g. US.c.Hub.QuadCore ) -- do they really have periods in their partnames, or do they have underscores in part.cfg and a period ingame? (KSP replaces _ with . when loading parts, so you must double check in the cfg). I'm fixing the FASA ones I notice...

**Comment by pjf** [comment]
As there are no more parts in tree.cfg with periods, I'm marking this issue as closed.
