### ISSUE TITLE
Crewed speed record with uncrewed probe

### ISSUE THREAD

**Issue by leudaimon** [KSP-RO/RP-0#561]
When I had a crewed spacecraft in orbit, switched to make a lunar probe launch, and the 9000m/s record was completed. I talked to @NathanKell and it should be an issue with Contract Configurator. @jrossignol?

**Comment by jrossignol** [comment]
I'll take a look.  Do you know when exactly it triggered (space
center/VAB/launch pass with other ship)?  Also if you have a log covering
when the contract completed, that would be great.

**Comment by jrossignol** [comment]
Got it.  If you set things up in the right order, you can get different vessels to complete each portion (crewed & speed > 9000).  Fixed for next Contract Configurator release.

**Comment by pap1723** [comment]
Old contracts
