### ISSUE TITLE
Manned/Rover Contracts

### ISSUE THREAD

**Issue by Zarbizaure** [KSP-RO/RP-0#564]
An addition to #562 (comsat contracts) and linked with commits in #563.

I recently added some lunar base contracts as well as more landings contracts. However, we still don't have any station/base expansion contracts. What I though is to create a variety of expansion contracts of different types:
- [ ] Electrical module: bring a module capable of generating X kilowatt.
- [x] Crew module: bring a module with X crew capacity (between 2 and 8?)
- [x] Science module: bring a module with this experiment or a science lab
- [x] Station Resupply missions
- [x] Space Hotel Resupply missions
- [x] Lunar Base Resupply missions

I don't really know how to create all of this (especially electrical check), maybe there's a good documentation for the contract typo? If so could you send me it? EDIT: nervermind, [found it!](https://github.com/jrossignol/ContractConfigurator/wiki)

Another problem: how to dock with a lunar base? It sounds hard to do with just RCS, with the moon gravity. Does docking work with KAS too?

Abour the potential rover contracts: how can we check the distance travelled? If the vessel is on wheels? Maybe waypoints?
- [x] Moon rover contracts (repeatable?)
- [x] Mars rover contracts (repeatable?)

Also, there is something else that would be cool:
- [x] Space hotels!
- [x] Tourism contracts to this space hotel

And some milestones ideas:
- [ ] First SSTO
- [ ] Reusability contracts

**Comment by leudaimon** [comment]
Station expansion contracts is just the kind of contract that rates as awesome, and would fit really well into the manned progression, before bases and interplanetary stuff.

**Comment by Zarbizaure** [comment]
I'll start to write some of these! maybe we should move station/base contract in another contract group? otherwise we'll start to have a lot of stuff inside "HumanContracts"

**Comment by pap1723** [comment]
Added with contract overhaul
