### ISSUE TITLE
Stock planets in the "Science Archives"

### ISSUE THREAD

**Issue by winged7** [KSP-RO/RP-0#567]
Is it normal that I'm getting stock planets here?

http://i.imgur.com/hUAmUga.png

Clean RP-0 install, only recommended and supported mods, everything up-to-date. This happens also on my second install.

**Comment by PhineasFreak** [comment]
IIRC it is a bug with Kopernicus (some other user on the forums also pointed out the same problem). If you start or load a career game and go straight into the R&D building then the planets are OK. If you exit, load another scene (for example the Tracking Station) and go back then the planets will be the stock ones.

I can make it happen with just a basic RSS installation (Kopernicus, MFF, RealHeat, RSS + Textures).

**Comment by winged7** [comment]
Thanks for the explanation.

**Comment by NathanKell** [comment]
Closing since we can't really do anything on our end.
