### ISSUE TITLE
Todo: Update CC for 0.15

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RP-0#571]
http://forum.kerbalspaceprogram.com/index.php?/topic/143244-nightingale-softworks-development-thread/&do=findComment&comment=2688588

**Comment by leudaimon** [comment]
Looks really cool! 
@NathanKell, if you provide a more detailed todo list, I may try to do some of this, given the efforts I was doing in uncrewed exploration contracts (#566) will probably be simpler after the contracts are converted with the dependency structure in place.
Things that came to mind after reading the updates:
- The DATA_EXPAND nodes are very promising in providing contracts for all planets/bodies, instead of the long lists currently implemented. With the flyby contracts as a "backbone", all other contracts can be implemented with the dependencies increasing from the respective flyby.
- How does this system deal with randomness in the contracts? Especially in cases that some random factor creates very different contracts.

**Comment by NathanKell** [comment]
Awesome, thanks! <3

Per the post, looks like the best bet is to load up with the new CC build, and see what looks odd. Then we can take it from there?

**Comment by leudaimon** [comment]
I had a look at the logs from CC after changing minVersion to 1.15.3 as suggested in the post. 
The warnings and errors abound, but most are minor:
- Almost all contracts have a weight attributed which is deprecated, but this is minor and doesn't affect anything. 
- Many of the other issues are also minor, related to genericTitle and genericDescription fields. Should be an easy fix.
- Some contracts have other issues that will require further investigation.

I'm posting the logs for contracts with issues (except the ones with only weight present as issue) in the following link:
https://www.dropbox.com/sh/pvqlkvvykpdy4s8/AAAzcqD5IrnDnrQJ1nwQXVOWa?dl=0 That's unfortunate that log files are not provided for group warnings. There is some useful stuff there in the debug logs ingame, so I'm providing an example screenshot along with the contract logs.

Besides, some stuff to take into account to use the new system better:
- Nightingale apparently strongly suggests using agents for different groups
- contract groups are now explicit to users, should they be made more meaningful?
- I don't think MaxSimultaneous for groups makes sense anymore, one more reason to rework groups.

**Comment by NathanKell** [comment]
* We can remove weight, yep! Hallelujah!
* Great!

I'll look through the archive tonight (I hope).

* We kinda only want one agent for many different groups, though. FAI should be the agent for milestones, records, and first flybies (which are milestones but not in the milestones group), landings ditto)...maybe even more. That causes problems.
* Yes, we probably do need to do that.
* It makes sense if we want contract offering for non-milestone contracts to be not all-at-once. Milestones should always be available, yes, but the repeatables should have some variance in availability.

**Comment by leudaimon** [comment]
If I understood the new contract system correctly, all contract types with requirements met are shown as available - one instance for each. I don't quite understand how this works with MaxSimultaneous. Maybe @jrossignol may shed some light.

**Comment by leudaimon** [comment]
I'm working on removing all weights and adding generic titles and descriptions where needed. (saying that just to avoid duplicate work)

**Comment by jrossignol** [comment]
@leudaimon - all contracts types with requirements _unmet_ are shown one instance each.  All contracts with requirements met show as before - one line for each offered one.

In other words, if maxSimultaneous is 2, it will show between 0-2 (where "0" is the version which shows the requirements).

> We kinda only want one agent for many different groups, though. FAI should be the agent for milestones, records, and first flybies (which are milestones but not in the milestones group), landings ditto)...maybe even more. That causes problems.

This is totally fine - the downside is that you get the same icon for multiple groups, but probably not a big deal for RP-0.  If you did decide to create the art assets for each group, you can create a dummy agent for the group, even though the contracts might all be under FAI.

**Comment by NathanKell** [comment]
Ah, neat. Yeah, we don't mind if the icon's the same, the group name is what matters here. :)

**Comment by rsparkyc** [comment]
Ok, I'm setting the agent as FAI for the 3 contract groups mentioned, but what do we want to do about the other contract groups (like sounding rockets, landing contracts, etc)?

**Comment by rsparkyc** [comment]
ok, in doing some more updates, I had some questions that are explained in this post:
http://forum.kerbalspaceprogram.com/index.php?/topic/91625-12x-contract-configurator-v1222-2016-12-16/&do=findComment&comment=2924303

**Comment by leudaimon** [comment]
@rsparkyc AFAIK you only need to state minVersion once, in the "root" contract group RP-0

**Comment by rsparkyc** [comment]
Yeah, that's what I would expect, but I was still getting warnings about it (I checked my Player.log into git so I could track changes as I removed stuff)

**Comment by rsparkyc** [comment]
This can probably be closed now.
