### ISSUE TITLE
Weather satellite contract issue

### ISSUE THREAD

**Issue by danielguo** [KSP-RO/RP-0#574]
I was doing the "Weather Network" contract requiring launching three satellites. However, the contract is mark as completed when I finished launching the three satellites.

Attaching save file section. In it, vesselID 3a366db7-beb4-4a89-8888-f074ed8c75e3 is selected for all three satellites.

[save.txt](https://github.com/KSP-RO/RP-0/files/392564/save.txt)

**Comment by danielguo** [comment]
Same issue for Geostationary Weather Network contract.

**Comment by rsparkyc** [comment]
Duplicates https://github.com/KSP-RO/RP-0/issues/591
