### ISSUE TITLE
Suggest Including Sane Strategies

### ISSUE THREAD

**Issue by cherrydev** [KSP-RO/RP-0#58]
Some of the strategies are game-breakingly over-powered, like outsourced R&D.  This Mod balances them out well, I think:

http://forum.kerbalspaceprogram.com/threads/96230-0-90-Sane-Strategies-0-42-1-Dec-18

**Comment by NathanKell** [comment]
Ah, you know I hadn't even looked at strategies because they *all* seemed so nuts. Feel free to PR recommending it, although our currency balances aren't quite stock's.
