### ISSUE TITLE
Weather Satellite Contract Completes After One Launch

### ISSUE THREAD

**Issue by gruneisen** [KSP-RO/RP-0#591]
The Weather Satellite Contract to insert three geosynchronous satellites in orbit completed out after only inserting a single satellite into orbit.

**Comment by hargn** [comment]
I see what is happening : 
`PARAMETER
   {
   name = IsNotVessel
   type = IsNotVessel
   vessel = weatherSatellite
}`
are missing in contract parameter group.
I'll probably release the fix this weekend
