### ISSUE TITLE
Can't always transmit data

### ISSUE THREAD

**Issue by rsparkyc** [KSP-RO/RP-0#607]
Testing with a simple sounding rocket, it seems like even though my data transmits, I don't get the science for it.  However, if I strap an antenna to it, it seems like there's a better chance that I get the science reward.  Perhaps an issue with remotetech integration?

**Comment by leudaimon** [comment]
This is weird. I didn't test anything myself after 1.2, but the latest RemoteTech versions supposedly fixed this science transmission bug that have been around for a long time (https://github.com/RemoteTechnologiesGroup/RemoteTech/wiki/Release-Notes).

**Comment by rsparkyc** [comment]
Yeah, I had thought that as well. The weird thing is i can't seem to get it to transmit with the sounding rocket core, but the 1m guidance unit seems to transmit ok.

**Comment by leudaimon** [comment]
If it is working with the antennas, did you check if the remote tech module for the cores is any different from the antennas? Maybe there was some recent change to it that was made to the antennas and not made to the cores, which are parts mostly exclusive to RP-0 IIRC

**Comment by rsparkyc** [comment]
The thing is, the antennas go through the transmission routine, and without remotetech installed they say that there's no transmission capabilities on those parts, so it looks like it should be making it to the cores.  Especially since the 1m core seems to work.  IIRC (about to do more testing), the first time i tried to transmit data on the 1m core, it didn't give me science, but the second time it did.

**Comment by rsparkyc** [comment]
Ok, so after testing a bumper rocket, as long as the 1m control core is attached, I can get science.  As soon as the sounding rocket core is the only core, I no longer get science data.  Going to see if i can see any differences between those parts.

**Comment by rsparkyc** [comment]
ok, the way the antenna is configured for the sounding rocket core is as follows:
```
@PART[RP0probeSounding0-3m]:NEEDS[RemoteTech]:FOR[RealismOverhaul]
{
    MODULE
    {
        name = ModuleSPU
    }

    MODULE
    {
        // This mostly matches RealismOverhaul's RTShortAtenna1 transmitter.
        // That's starting technology, and I think reasonable to be integrated.

        name = ModuleRTAntennaPassive
        TechRequired = start

        // 200k is enough for atmospheric testing.
        // Want more? Add your own antenna.
        OmniRange = 200000

        TRANSMITTER
        {
            PacketInterval = 0.4
            PacketSize = 0.27
            PacketResourceCost = 0.01
        }
    }
}
```

the 1m part is like this:
```
@PART[GuidanceStart1m]:AFTER[RemoteTech]
{
	%MODULE[ModuleSPU]
	{
	}

	%MODULE[ModuleRTAntennaPassive]
	{
		%TechRequired = start
		%OmniRange = 20000

		%TRANSMITTER {
			%PacketInterval = 0.3
			%PacketSize = 2
			%PacketResourceCost = 0.2
		}
	}
}
```

I'm not too good with MM patches yet, so putting it here to get other eyes on it.

**Comment by rsparkyc** [comment]
I tried replacing the sounding rocket core MM config with the 1m config, and I was able to get science.  However, when I replaced the `PacketInterval`, `PacketSize`, and `PacketResourceCost` values with the original values, I no longer get the science.  My guess is the `PacketSize`, just because the others are decimals in the 1m config.  I'm going to try 2 things, 1) setting packetSize to .25 (because that's evenly divisible),  and if that doesn't work, setting it to 1, and changing the interval to be 400% slower (and the cost to be 400% higher)

**Comment by rsparkyc** [comment]
Ok, sure enough, setting packet size to 1 let me get science.  So I figured "ok, maybe packetSize is an integer field".  After all, doing a grep in my gamedata directory shows only RealismOverhaul and SXT using non-integer packet sizes.  Nope, KSP docs show it as a float.  So then I say "what the heck, let's try 0.5", and that seems to work (where 0.25 didn't).  I'm going to try to find a lower bound to where floats don't work.

**Comment by PhineasFreak** [comment]
If you keep a packet interval to **1.0** (seconds) and a packet size of **1.024** (kbit/s) do you still have the same problem?

**Comment by rsparkyc** [comment]
Ok, so I created a MM patch:
```
+PART[RP0probeVanguardXray]:AFTER[RP-0]:FOR[Ryan]
{
	@name = VanguardXray-1024
	@title = Vanguard 1024
	@MODULE[ModuleRTAntenna]
	{
		@TRANSMITTER
		{
			@PacketSize = 1.024
			@PacketInterval = 1
		}
	}
}
```
I was never able to transmit data with that part.  Even changing `PacketSize` to 1 only resulted it about a 50% transmission rate.  I've tried a bunch of different settings, and can come up with no rhyme or reason as to what works and what doesn't.

**Comment by rsparkyc** [comment]
Added RT bug: https://github.com/RemoteTechnologiesGroup/RemoteTech/issues/714
