### ISSUE TITLE
Avionics not required for RCS translation

### ISSUE THREAD

**Issue by chippydip** [KSP-RO/RP-0#609]
Not sure if this is a bug or working as intended, so feel free to close this if it's fine.

I recently started playing RP-0 and have been messing with some early LEO launcher designs and discovered that RCS translation controls continue to work without sufficient avionics (as long as RCS is already enabled).

I totally assumed early probe cores without avionics wouldn't be able to control themselves with RCS, but I thought maybe I could set them to fore/aft throttle-controlled and still be able to use them for ullage and fine-tuning an orbit by toggling the throttle on/off. Turns out, the translation controls just continued to work 100% as long as I had enabled RCS before decoupling the heavier avionics.

Personally I think this is awesome and hope it doesn't get changed, but it was so unexpected to me and I found zero mention of it one way or the other anywhere that I figured I should report it.

**Comment by pap1723** [comment]
Known issue, most likely not to be fixed.
