### ISSUE TITLE
1.2.2 Update

### ISSUE THREAD

**Issue by rsparkyc** [KSP-RO/RP-0#610]
Lists of mods need for RP-0
(Taken from my spreadsheet: https://docs.google.com/spreadsheets/d/19_dhwSioZODCCtMFD0kZOtbmbg--ryoE0nzoWJL2cRc/edit#gid=0)

REQUIRED:
- [x] Community Tech Tree
- [x] SXTContinued
- [x] Ven's Stock Part Revamp
- [x] Contract Configurator
- [x] Custom Barn Kit

RECOMMENDED
- [x] Kerbal Renamer (using the KSP-RO fork)
- [x] KCT
- [x] KSCSwitcher
- [x] KRASH
- [x] Taerobee
- [x] SCANSat

**Comment by rsparkyc** [comment]
KCT has a dropbox link, but I don't think it's an official release yet: https://www.dropbox.com/s/crnxof84xvr6dto/KerbalConstructionTime.zip?dl=0
I have a PR for Kerbal Renamer, but it doesn't rename all the starting 4 kerbals.  Maybe someone else can try too? https://github.com/KSP-RO/KerbalRenamer/pull/2

**Comment by stratochief66** [comment]
@jbengtson, any input on that Kerbal Renamer issue?

**Comment by jwvanderbeck** [comment]
Didn't renamer always have that problem?

**Comment by rsparkyc** [comment]
not that I recall, pretty sure my 1.1.3 campaign had all renamed kerbals.

**Comment by Theysen** [comment]
IIRC it started at 1.1 where the starting kerbals didn't rename properly, in 1.0.5 it worked. Minor issue, if @jbengtson feels like fixing it that's even better but no dealbreaker

**Comment by rsparkyc** [comment]
@Theysen that might make sense, as I had migrated my 1.0.5 save to 1.1, so my kerbals must have already been renamed.

**Comment by Theysen** [comment]
So, I fired it up twice and all RP-0 parts which worked nice in 1.1.3 are now labelled non-RP-0. I didn't find any solution to this so I hopefully just bombed my install with the whole drag and dropping instead of a mod problem. 

Otherwise did the Filter Extension mod put the parts into strange categories and I think it should be removed from the RO/RP-0 suite (means keep it as suggested).

**Comment by stratochief66** [comment]
@Theysen I left you a message about this in IRC; you will need a Tree.cfg for your RP-0 folder. You can either generate one yourself from the repo using PERL (less likely) or nab the old one from the previous release.

**Comment by Theysen** [comment]
@stratochief66 I just remembered during dinner, Thank you very much for helping though. Will add this for sure. (I confused the .zip master with the RO prerelease and somehow thought I downloaded a compiled prerelease for RP-0).

**Comment by AndreMessier** [comment]
@rsparkyc I just put in a PR with a hack/fix for renaming (2 of) the original 4 kerbals.  Let me know if I'm doing this right...

**Comment by rsparkyc** [comment]
@AndreMessier awesome, I'll have to take a look at it.

**Comment by Jerre122** [comment]
Regarding the issue with MechJeb: the next maneuver node being executed immediately.
I too had this problem using the dowload of the link in the golden spreadsheet.
But having compiled the most recent version thereof, I could no longer replicate that behaviour.

Can you still replicate that behaviour?

**Comment by stratochief66** [comment]
Watching this for ProcFairing
https://github.com/e-dog/ProceduralFairings/issues/26

**Comment by rsparkyc** [comment]
@stratochief66, since e-dog shot down that issue, do you think you could open up one describing the issues that you've been able to verify using his release?

**Comment by rsparkyc** [comment]
@stratochief66 since we have KSCSwither now, do you think we should cut a pre-release tag?

**Comment by stratochief66** [comment]
@rsparkyc sure, go for it :)

**Comment by Ixonal** [comment]
There any updates or status for this?

**Comment by Bornholio** [comment]
CLOSE ME!
