### ISSUE TITLE
Take a look at refining weather contracts

### ISSUE THREAD

**Issue by rsparkyc** [KSP-RO/RP-0#614]
Since many of these contracts are "Trivial", it was noted that perhaps we should increase the tolerances of them since they're meant to be performed early on.  Also, possibly adding the ability to complete these multiple times.  I also suggested removing the randomness on electric charge, especially since all these sats are in the same weather network.

**Comment by ctiberious** [comment]
My two cents, I have to agree with the question on the randomness of EC for the weather network satellites.  Never made sense to me that you wouldn't put up three basically identical satellites.

**Comment by rsparkyc** [comment]
EC change is in https://github.com/KSP-RO/RP-0/pull/615

**Comment by hargn** [comment]
More than refining the weather satellite contracts, I suggest to add a brand of contracts for early satellites.
In the contracts I have written for the ComSat contracts issues #562, the two first milestones are satellites capability demonstrators : the first must be connected to KSC, the second must have solar panels.
Behind theses milestones that are _one-shot_ contracts, I can add repeatable contracts with the same requirements, but where the apoapsis and the periapsis are not taken into account for the contracts validation.

**Comment by BevoLJ** [comment]
Another recommendation if I may, the contracts like "First Artificial Satellite" used to be able to be completed by returning an experiment with 0 science (if it had already been performed in the career, such as during sounding rocket contracts).  I can't seem to get the science return portion of the contract to complete, regardless of experiments attempted.

**Comment by rsparkyc** [comment]
@BevoLJ That sounds like a different issue, I have not had that issue with these contracts.  I know there is an open issue with RemoteTech not always sending science data, but that has been fixed in their develop branch (you'll need to pull it down and compile it yourself)

**Comment by stratochief66** [comment]
@rsparkyc I agree with your initial suggestion, it seems like a great ideal. I know I had a hell of a time completing those initial contracts using a Thor-Agena B or whatever I was using at the time. Wider tolerences seems like a better way to gradually step people into more challenging, precise, and profitable contracts.

**Comment by pap1723** [comment]
This should now be closed as it is part of the Contract System Overhula #642
