### ISSUE TITLE
Other misc contract ideas

### ISSUE THREAD

**Issue by rsparkyc** [KSP-RO/RP-0#620]
- [ ] Get payload of weight X into GTO, and then relinquish control (this would be cool to simulate real life missions, where the agent designs the satellite, and your job is just to get it to GTO). Right now there's no "relinquish control" option, so this would need to be included in a mod.

**Comment by stratochief66** [comment]
Agreed, that would be a reasonably realistic and varied type of contract.

**Comment by BevoLJ** [comment]
Contracts using @raidernick probes would be AMAZING! :)
