### ISSUE TITLE
Cost scaling of procedural interstage doesn't match fairings/thrust plate

### ISSUE THREAD

**Issue by chippydip** [KSP-RO/RP-0#625]
While working on a family of rockets I noticed a larger cost difference between two similar rockets with different diameters than I expected. After some poking around I realized the bulk of the cost difference was due to larger diameter interstages. On the larger rockets it was actually significantly cheaper to replace all interstages with regular payload fairing (nested Russian doll style).

I'm not all that familiar with ModuleManager stuff, but I took at look at ProcCosts.cfg and saw configs for KzFairingBaseResizer and KzThrustPlateResizer setting costPerTonne to 10 (down from the default 1000). It looks like the adapters have their cost info in the ProceduralFairingAdapter module and I don't see a config to tune that down, so I added this to ProcCosts.cfg:
```
@PART[*]:HAS[@MODULE[ProceduralFairingAdapter]]:FOR[RP-0]
{
	@cost = 1
	@MODULE[ProceduralFairingAdapter]
	{
		@costPerTonne = 10
	}
}
```
Seems to be working as expected with adapter costs now in line with fairings and thrust plates and my 4.6m lifters are now ~$1,500 less expensive without needing to resort to nested fairings.

**Comment by pap1723** [comment]
This has been fixed with the way tooling works.
