### ISSUE TITLE
Procedural Avionics should use upgrade system similar to RCS/Engines

### ISSUE THREAD

**Issue by rsparkyc** [KSP-RO/RP-0#630]
Where they have their own dedicated GUI to choose their upgrade level

**Comment by BevoLJ** [comment]
That would be super cool.  Oh, another thought, what if we could also adjust the tanks in the probe cores.  Could limit it to hypergolics and electrical charge?  Could reduce part counts (separate batteries), and make them competitive with the Early Controllable Core's huge battery.
