### ISSUE TITLE
procAvionics - Lots of clicking to adjust controlled mass

### ISSUE THREAD

**Issue by stratochief66** [KSP-RO/RP-0#633]
A procAvionics unit starts controlling a few tons. It can be scaled up to control thousands of tons, but then (nearly) thousands of clicks are required to bring the control mass up to that level.

@rsparkyc 's proposed fix:
Change the control mass adjust click bar to be a percentage utilization, which is a factor that does scale with the size of the unit.

**Comment by rsparkyc** [comment]
potential fix here: https://github.com/rsparkyc/RP-0/tree/procAvi/GameData/RP-0/Plugins

**Comment by rsparkyc** [comment]
fixed here: https://github.com/KSP-RO/RP-0/pull/634
