### ISSUE TITLE
FASA install doesn't see commandChargeResource

### ISSUE THREAD

**Issue by ec429** [KSP-RO/RP-0#636]
In the VAB, if I have a crew capsule then I get an NRE
`[EXC 01:54:19.034] NullReferenceException: Object reference not set to an instance of an object
        RP0.ModuleAvionics.UpdateRate ()
        RP0.ModuleAvionics.Start ()`
and all parts with ModuleAvionics get 100kg extra mass.
This appeared recently and I'm tempted to blame 6d1bbccae9305e163ea8552ddcb1a66c30a288a3 and proc avionics.

(My specific reproducer: building a Mercury Atlas with FASA parts.)

**Comment by rsparkyc** [comment]
I'm not getting the NRE that you're seeing, however I can confirm that I'm getting a 100kg mass penalty on every avionics unit, and not just the pod, so I'll take a look at fixing that

**Comment by ec429** [comment]
Just to check - do you have a kerbal assigned to the pod?  That might determine which path UpdateRate takes.  OTOH if the mass penalty isn't caused by the NRE, I don't care quite so much about the NRE ;)

**Comment by rsparkyc** [comment]
Yeah, every time I add a kerbal, I see the mass go up by 100kg X the number of pods I have.  I should just go up 100kg

**Comment by rsparkyc** [comment]
Ok, I may have found where that NRE is coming from, so i'll post a patch for that, but I'm still trying to find where the kerbal mass is added in.

**Comment by rsparkyc** [comment]
At this point, I'm pretty sure the mass bug is a Squad bug.  I've created a simple install, and added just a '%kerbalCrewMass = 0.1` modifier, and I see the bug.

**Comment by rsparkyc** [comment]
As of the latest commit, you will now see `[RP-0] - Can't change rate with no commandChargeResource`

**Comment by pap1723** [comment]
This will be fixed once Kerbalism is fully integrated, until then, we have all survived this bug for years. :)
