### ISSUE TITLE
Plane Takeoff Sliding

### ISSUE THREAD

**Issue by thecoolshark** [KSP-RO/RP-0#638]
I built the x-1 from the Terobee mod and used two small landing gear and a tiny steering one in the front. When I loaded a simulation the front landing gear said the gear was blocked, and the plane began to go in tight circles as soon as the engine ignited until a the gear overstressed and exploded. Can you please solve this problem so I can launch planes in career.

**Comment by PhineasFreak** [comment]
KSP 1.1.3?

**Comment by pap1723** [comment]
Planes are the devil. But in all seriousness, this has been fixed with the implementation of KSPWheel and the RSS Runway Fix
