### ISSUE TITLE
Milestones Contracts reappear after completion [1.2.2 wip install]

### ISSUE THREAD

**Issue by Theysen** [KSP-RO/RP-0#639]
Started a new test career yesterday with all updated dependancies and the contracts like First Flight and First Artificial Satellite reappear after completion. 

I'm trying to find any change on CC side and dig through the logs, there shouldn't have been a change but I try to tackle the issue.

EDIT: Out of the 4 saves I started it happened for 3 of them, the newest one behaves as expected. More investigation to follow.

**Comment by pianojosh** [comment]
I'll +1 this with a current install from the spreadsheet. Anything I can do with my save to help diagnose?

**Comment by pianojosh** [comment]
Actually, this might be WAD. Looking at the milestone contract definitions here, at least some of them have `maxCompletions = 3`.

https://github.com/KSP-RO/RP-0/tree/master/GameData/RP-0/Contracts/Milestones

@Theysen Can you check which ones of yours reappeared, and if they were all ones with more than 1 maxCompletion? So far, it looks like all of mine are in that boat.

**Comment by Theysen** [comment]
As I said, didn't have that issue on the third save I started and wasn't able to reproduce since.

**Comment by pap1723** [comment]
This should probably be closed now that we are moving to the new contract system.
