### ISSUE TITLE
All parts showing non-rp-0

### ISSUE THREAD

**Issue by Maxzhao1999** [KSP-RO/RP-0#640]
I've installed RP-0 from the master branch and installed its dependencies. However, in the VAB all parts show non-rp-0. Not sure why this happened. I've attached the logs [here](https://www.dropbox.com/s/2yll2ct0gvm5ako/Player.log?dl=0)

**Comment by leudaimon** [comment]
You need a tree.cfg file from a previous release of RP-0 (just paste into the RP-0 folder), or to compile it from the source tree.yml. This file is essential for RP-0 and is produced only on release.

**Comment by Maxzhao1999** [comment]
Ah right. Thanks a lot for your help! Please close this issue.
