### ISSUE TITLE
Contract System Overhaul

### ISSUE THREAD

**Issue by pap1723** [KSP-RO/RP-0#642]
I was talking with Stratochief on the RO IRC channel and we got to discussing contracts for RP-0. Since I exclusively play career mode and I have created hundreds of contracts in the past, I agreed to look at overhauling the contract system used by RP-0. I have read through the contract threads of #620, #614, #566, #564, #562, #463, #177 to get ideas of what has been discussed before. I have essentially created this blueprint of ideas already with my [Career Evolution Contract Pack](http://forum.kerbalspaceprogram.com/index.php?/topic/157417-wip-122-career-evolution-contract-pack-beta-release-v03-updated-3-27-2017/&page=4#comment-3029187) but with RSS-RO, I have the ability to create much more detailed contracts that are not trying yo appeal to different solar systems and sizes.

I will try to lay out my thoughts and will edit this top post to clarify details as we agree to change them, or clarify them.

Let me know your thoughts, mission ideas that I may have forgotten, or anything else you would like to contribute.

## **Milestones**

- First Launch (unmanned)
- Reach Upper Atmosphere (unmanned)
- Cross Karman Line (unmanned)
- Suborbital Biological Sample (Suborbital & Return)
- First Satellite
- Orbit & Return
- Rendezvous
- Docking

## **Satellites**
These will open up after the First Satellite contract is successful. These will be grouped into early satellite contracts and then will be more advanced as certain milestones are reached.

**Early Satellites**
- First Satellite with Solar Power (like Vanguard 1958)
- Early Science Satellites (these will be put a satellite in a specific orbit with a specific science experiment on it. Must stay in orbit for a certain amount of time and then will give the player science, not money focused)
- First Communications Satellite (like Telstar 1962)
- Early Communications Satellites (REPEATABLE - these will be for money, but they will all essentially be standard put satellite into specific orbit contracts, but all LEO and MEO orbits)
- First Weather Satellite (like TIROS 1 1960)
- Early Weather Satellites (REPEATABLE - these will be for money, but they will all essentially be standard put satellite into specific orbit contracts, but all LEO and MEO orbits)
- First Polar Satellite (inclination = 90 +- 4 degrees) (required to unlock advanced satellite contracts)
- Early Communications Network (based on the RemoteTech contracts you can choose 3 or 4 satellites to provide RemoteTech coverage of the planet)
- First Molniya Orbit (required to unlock advanced satellite contracts)
- First Sun Synchronous Orbit (required to unlock advanced satellite contracts)
- First Trundra Orbit (required to unlock advanced satellite contracts)
- First Geosynchronous Orbit (required to unlock advanced satellite contracts)

**Advanced Satellites**
This group of satellites will be broken out into Communications, Military, Commercial and Scientific

- COMMUNICATIONS
  - These contracts will be repeatable and will be a good source of monetary income. They will require power generation as well as Electric storage. The contracts will require placement of satellites into various orbits, but will mainly focus on Geostationary, Geosynchronous and Tundra Orbits. They will require the satellites to be over a specific part of the globe in order to be marked as completed.
  - Communications Constellation (Not Repeatable. This will require a satellite constellation of 4 satellites at Geosynchronous Orbit that can communicate with each other.)
- MILITARY
  - These contracts will be repeatable and will be a good source of monetary income. They will require that a Film Camera is on board and will have to take images of a specific area. 
  - Other contracts will require specific types of orbits with multiple antennas that will work like spy listening satellites. These orbits will focus on Molniya, Tundra and Sun Synchronous orbits.
  - Military Constellations (not Repeatable)
    - GPS System
      - If player chooses GPS -> GLONASS Contracts will not be available
      - Will require 4 satellites in 6 orbital planes (not really possible to force the satellites to be spaced correctly, but we can force the number of satellites and it will be up to the player to make it realistic)
      - SMA = 26559.8 km
      - Inclination = 55 degrees
      - Eccentricity = 0
      - RAAN = Each satellite plane is 60 degrees apart (0, 60, 120, 180, 240, 300)
    - GLONASS System
      - If player chooses GLONASS -> GPS Contracts will not be available
      - Will require 8 satellites in 3 orbital planes (not really possible to force the satellites to be spaced correctly, but we can force the number of satellites and it will be up to the player to make it realistic)
      - SMA = 25440 km
      - Inclination = 64.8 degrees
      - Eccentricity = 0
      - RAAN = Each satellite plane is 120 degrees apart (0, 120, 240)
    - Galileo System
      - This will be a late game upgrade to both systems
      - Will require 9 satellites in 3 orbital planes (not really possible to force the satellites to be spaced correctly, but we can force the number of satellites and it will be up to the player to make it realistic)
      - SMA = 29600.318
      - Inclination = 56 degrees
      - Eccentricity = 0
      - RAAN = Each satellite plane is 120 degrees apart (0, 120, 240)
- COMMERCIAL
  - The player will be required to put a payload of a specific mass into a particular orbit. Once the contract is fulfilled, the player will lose control over the payload. This will be a good way to make money for the player. These contracts will mainly be focused on Geostationary orbits over a specific area on the globe.
- SCIENTIFIC
  - Earth Observing Satellites (Repeatable)
    - These will be weather satellites as well as scientific payload satellites that will return money / science for weather satellites and science for science payload satellites. These will be a wide variety of orbit types.
  - Sun Observation Satellites (Repeatable)
    - These missions will require the player to put satellites in a simulated L2 area past the Moon and will also require orbits inside and outside the SMA of Earth to explore the interplanetary weather and solar activity. (these are like Pioneers 5-9 as well as some of the other Helios type probes)
  - Interplanetary Satellites
    - These missions will require the player to put a satellite into specific orbits around other planetary bodies and to have specific scientific payloads on board. These will be used to simulate missions like MAVEN, Juno, Galileo, etc. These will be great way ways to get late game science.

## **Sounding Rockets, Human Records and Records**
No changes

## **X-Planes**
As of right now, there will be no changes. With the contract system the way it is, these cannot be forced to be completed by planes. I often will pick some of them when launching a rocket just to get the extra money. This might just have to be one of the player's self-imposed rules.

## **Lunar Exploration**
- Unmanned Flyby
- Unmanned Impact (can repeat 3 times)
- Unmanned Orbit
- Unmanned Landing (can repeat 5 times)
- Unmanned Landing & Return
- Unmanned Rover
- Manned Orbit
- Manned Landing & Return
- Manned Targeted Landing & Return (like Apollo 12 give specific target to aim for)
- Manned Landing & Return (Repeat) (can repeat 2 times)
- Manned Duration with Rover (can repeat 2 times)

## **Flyby Contracts**
These will stay the same for all bodies in the game.

## **Orbit Contracts**
 - Add contracts for orbiting all major celestial bodies
 - Orbit & Atmospheric Probes
    - These missions will have the player orbit a body and to also send a probe into the atmosphere. This is like the Galileo probe at Jupiter as well as some missions to Venus as well.

## **Landing Contracts**
 - Keep unmanned landing contracts for all celestial bodies with solid ground
 - Rover Contracts
    - Add unmanned rover contracts for various solid body planets
    - These will be "Land a rover on Mars, travel to A, B, C, get science
 - Sample Return Missions (land on a solid body, perform experiment, return experiment to Earth)
 - Asteroid Return Mission (land (grapple) on an asteroid, perform experiment, return experiment to Earth)

## **Station Contracts**
- First Space Station
- Send First Crew to Station
- Lunar Space Station
- Martian Space Station
- Repeatable Missions
  - Crew Rotation
  - Add Extra Crew Capacity to Station
  - Add New Power Module to Station
  - Send a New Crew (if a station is empty)
  - Resupply Life Support
  - Refuel the Station (This will probably not be implemented. With the amount of fuels that can be used,   this will pose a big issue with trying to determine what fuel to use. Is there a catch-all *fuel* for RealFuels that the contract could require?)
  - Add New Fuel Module (This will probably not be implemented. With the amount of fuels that can be used, this will pose a big issue with trying to determine what fuel to use. Is there a catch-all *fuel* for RealFuels that the contract could require?)

## **Human Milestones**
- Supersonic
- Upper Atmosphere
- Karman Line
- Suborbital (Repeat) - These will stop once you have completed Manned Orbit
- Orbit
- Orbit (Repeat) - These will stop once you have completed a 2 Crew Orbit
- Orbit 2 Crew (Repeat)
- Orbit 3 Crew (Repeat)
- EVA

## **Human Exploration**
- Human Flyby Mars
- Human Flyby Venus
- Human Orbit Mars
- Human Orbit Venus
- Asteroid Landing Mission
- Land on Mars
- Land on Phobos
- Human Flyby Jupiter
- Human Flyby Mercury
- Land on Europa
- Human Flyby Saturn
- Land on Ganymede

## **Surface Base Contracts**
- Establish Lunar Base
- Send First Crew to Base
- Establish Martian Base
- Repeatable Missions
  - Base Crew Rotation
  - Base Power Expansion
  - Base Crew Capacity Increase
  - Base Population Expansion
  - Base Life Support Resupply

**Comment by rsparkyc** [comment]
Awesome, thanks for putting this together.  I love the idea of losing control of the satellite for the commercial contracts, and it would be nice if part of that states that you need to have your payload be a certain weight.  Also, many real life contracts only state that you need to put the satellite into a transfer orbit (GTO for instance), so perhaps that would be worth trying to replicate as well (instead of getting to the full geostationary orbit)

**Comment by rsparkyc** [comment]
Also, I have no idea how possible this would be, but it would be awesome to include some sort of principia support.  I would love to have to have contracts that tell me to get to Earth Sun L1, and then perhaps other "maintenance" contracts to keep it there for a year at a time or something.

**Comment by NathanKell** [comment]
Awesome! This is gonna be super-great! So glad you're taking this on.

Some quick notes:

1. For those of a civilian mind, it might be worth keeping plausibly deniable whether the film camera missions are military or high-resolution earth observation for science/commercial purposes. Same with the navigation networks (and look into the Transit constellation for an early version of that....)
2. I highly recommend playing some [BARIS](http://www.raceintospace.org/) if you haven't yet. That's broadly where I stole the milestone system from, and it should have a bunch of good ideas too, as well as how to weave milestones together.
3. I'm skeptical of contracts providing science as a reward, because of how we try to limit science gains so much. Speaking of, we still need to implement a system to lower science gains across the board when you have more parts with more science instruments...anyway, I'm worried about more than a few token points (as the lunar flyby and orbital return missions grant), and I certainly think there should never, ever, be infini-repeatable contracts that grant science.

Lastly, pedant: Trundra -> Tundra ;)

**Comment by pap1723** [comment]
1. That is a good idea, so we will "eliminate" the military contracts and
just group them all in Earth Observing Satellite contracts so that the
other side doesn't know exactly what we are doing. Good strategy!
2. So the whole reason I got into playing RO (which I vowed I would never
do) is because I was playing BARIS and BASPM (the upgraded version) and
wanted to make a Space Race Career conversion for KSP. I have done a lot of
the work and have a fully fleshed out US tech tree with some contracts
implemented. One example of what I was trying to do is to have a tech that
unlocked a boilerplate version of say the Mercury capsule. It also unlocked
missions that you had to accomplish. For example, you needed to test the
LES and successfully land, and prove the human rating of the capsule with
an unmanned suborbital and orbital flight. Once those missions were
completed, it would unlock the tech that gave the player the fully working
Mercury capsule.
3. I hear you on this. This is the hardest part of balancing in my mind.
One idea I had -> maybe a terrible idea -> is to nerf the science gains
around Earth. Say set the multiplier to something very low like 0.25 or 0.5
for all Earth science. The primary way to generate science around Earth is
to use these contracts. I know this is a HUGE fundamental change to how it
works now and could become too grindy so it might be best to just skip that
idea all together.

One day I'll learn how to spell!

**Comment by pap1723** [comment]
Finished with #653

**Comment by ppboyle** [comment]
Hi, may I make a suggestion?

Instead of using a weight for the commercial satellites, I suggest you use a new resource type you'd define 'commercial payload' - with X liters required for a contract.  That way engines and unburned fuel cannot count for completing the contract, and also you can assign a high cost to this resource, commensurate with the typical cost of such satellites - making launch reliability more prized.  I'd expect the cost of the satellite to be part of the pre-contract reward of course.

Personally, I would also like such a system used for military and scientific repeatable launches - because the other items that have previously been required on repeatable contracts are very low weight, I find that I never have to vary my rockets for repeatable launches, just change out science equipment, and I'd really like the contract system to encourage me to build a variety of LV's for different payloads.   Milsats especially historically required the heaviest LV's, and bigger rockets = moar fun. :)

**Comment by glilienthal** [comment]
There is no Deimos landing contract. :). And my spacecraft just did a deimos flyby and could land. 
Is this on purpose? or shall I do one?

**Comment by pap1723** [comment]
I hadn't included one because I didn't think it was possible. Yes, please
do!

On Jun 18, 2017 11:41 AM, "glilienthal" <notifications@github.com> wrote:

There is no Deimos landing contract. :). And my spacecraft just did a
deimos flyby and could land.
Is this on purpose? or shall I do one?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/KSP-RO/RP-0/issues/642#issuecomment-309288542>, or mute
the thread

**Comment by glilienthal** [comment]
Ok, let me try to land, and then add a contract if that's possible: : )

**Comment by glilienthal** [comment]
other point: I don't get  a NewCrewStation contract offered, despite my station being up. 
This code seems a little weird to me: You first have to Complete a NewCrewStation Contract before you can start one? I waited >120d, but didn't help. 


	REQUIREMENT
	{
		name = CompleteContract
		type = CompleteContract
		contractType = NewCrewStation
		cooldownDuration = 120d
		minCount = 0
		title = Complete @contractType Contract
}

**Comment by glilienthal** [comment]
Landing on Deimos is possible. Staying there is difficult. It's like Tschuri. ;) So landing contract is fine. Rover doesn't seem to make sense.

**Comment by glilienthal** [comment]
One comment on the atmospheric probe contracts: They seem to be very, very simple. You just dip with your normal orbiter/flyby mission 1km into the atmosphere. No headshield necessary, basically additional free money (+ Science!) for nothing. 

I think they should be harder: e.g., requiring data from the low atmosphere, or asking for a an altitude below 50% of the height of the atmosphere or something like that.

**Comment by rsparkyc** [comment]
@pap1723 @ppboyle I love the idea of a commercial payload resource.  May I add one suggestion?  Perhaps for every mission you accept, you can programmatically make a unique commercial payload for each contract.  That way, you couldn't reuse the same vessel for two different commercial missions.  This would be important if we're upping the reward you get when accepting the contract to offset the price of the resource.

**Comment by hargn** [comment]
When I was working on repeatable satellite contracts, I did a requirement for a minimum amount of RCS fuel that the satellite should have when placed on the right orbit.
The amount was varying from 100kg to 500kg and I placed factors of x1, x6 and x20 depending of the prestige of the contract.
So repeatable ComSat contracts may require you to place a 100kg satellite on a low polar orbit to a 10t satellite on a GSO orbit, then you must have a brand of different launchers for all kind of these contracts.

The main difficulty of this is to select only propellant that are available (unlocked in tech tree), and the other part is to manage the hypergolic bipropellants (NTO+UDMH eg.).

**Comment by pap1723** [comment]
> other point: I don't get a NewCrewStation contract offered, despite my station being up.
This code seems a little weird to me: You first have to Complete a NewCrewStation Contract before you can start one? I waited >120d, but didn't help.

REQUIREMENT
{
	name = CompleteContract
	type = CompleteContract
	contractType = NewCrewStation
	cooldownDuration = 120d
	minCount = 0
	title = Complete @contractType Contract
}

So the important part of this is the minCount = 0. Basically it says that none of these types of contracts HAVE to be completed, but if one is, the cooldownDuration makes it so that one will not be offered for 120 days.

As to why you are not getting the contract, CC seems to be having a tough time picking out the station that is currently in orbit. This is an issue that has been raised.

**Comment by pap1723** [comment]
> One comment on the atmospheric probe contracts: They seem to be very, very simple. You just dip with your normal orbiter/flyby mission 1km into the atmosphere. No headshield necessary, basically additional free money (+ Science!) for nothing.

I think they should be harder: e.g., requiring data from the low atmosphere, or asking for a an altitude below 50% of the height of the atmosphere or something like that.

I agree. I will be going through the planets and figuring out a good altitude the probe must reach to be marked as a success. Thanks for pointing it out!
