### ISSUE TITLE
Many procedural part's size limit managed by the same config

### ISSUE THREAD

**Issue by TwistedMinds2** [KSP-RO/RP-0#645]
https://github.com/KSP-RO/RP-0/blob/master/GameData/RP-0/ProcSizes.cfg#L114

Procedural tanks, structural, stack decouplers, batteries and nose cones' size are managed by the same config allowing crazy design right from the start (2x15m, 80tons battery).
I feel it would be better to move them to their own separate config to allow fine tuning their maximum capacity and/or tech unlock.

**Comment by pap1723** [comment]
No longer applies.
