### ISSUE TITLE
Procedural Avionics missing equivalent node for "Early Controllable Core"

### ISSUE THREAD

**Issue by rsparkyc** [KSP-RO/RP-0#649]

**Comment by rsparkyc** [comment]
It's worth noting that this probe core is SUPER dense compared to the Ranger Block I core, so it may seem strange when people upgrade the tech tree that a larger part doesn't control as much.  It will weigh less per controllable ton, and while in the end, that's what really matters, the fact that it's so much larger I feel will throw people off.

**Comment by leudaimon** [comment]
I am aware this suggestion might be complicated to implement and is a completely different direction compared to what you have been doing for the tech progression, but don't you think some departure from the non-procedural parts would make things more straightforward?
What I have in mind is to define a more linear (or rather monotonic to be more precise) tech advancement throughout tech levels for all efficiencies, just trying not to be (significantly) worse than non-procedural parts.

**Comment by rsparkyc** [comment]
@leudaimon that sounds completely reasonable, and may be something @pap1723 could work on with his tech node changes.
