### ISSUE TITLE
Procedural Avionics can have a negative mass

### ISSUE THREAD

**Issue by ajvaughan** [KSP-RO/RP-0#676]
I started a new RP-0 career in a clean 1.2.2 install setup today, and decided to play around with the procedural avionics in the start node.  

If I set the diameter to 200mm, and leave the length at default, I end up with utilisation of 883.6%, and mass of -691.6 kg  (and prohibitively expensive cost). 

I can also achieve the same result by leaving the diameter at default and just turning the length down.

**Comment by rsparkyc** [comment]
sounds like we need to set a min volume on the configs
