### ISSUE TITLE
Procedural Avionics : Balance Issue(s)

### ISSUE THREAD

**Issue by ajvaughan** [KSP-RO/RP-0#679]
Comparing procedural avionics to the Able Avionics package (immediately after unlocking Early Avionics). 
A procedural avionic unit at 800mm diameter and 100mm length (in booster config) is about 10% lighter, but less than half the cost (so you could easily save a few more kg by going to 70mm length).  It has lower power consumption and battery storage, with both having roughly the same 2000 seconds of charge.  

But the real issues are the Able costs 4000 to unlock and only supports 5 tonnes, whilst the procedural avionics is already unlocked, and supports 15 tonnes. 

Unless someone objects, I'll report other balance issues in this same bug.

**Comment by rsparkyc** [comment]
Yeah, this should be solved by adding unlock costs to procedural avionics, which i'm working on.
