### ISSUE TITLE
Flame bug with kerbals

### ISSUE THREAD

**Issue by chickenswag101** [KSP-RO/RP-0#690]
so when i go eva my kerbal looks like hes on fire and it doesnt affect my kerbal in anyway

**Comment by Bornholio** [comment]
Use either DRE 7.6.0 or apply EVA Kerbal patch config in comment http://forum.kerbalspaceprogram.com/index.php?/topic/50296-122-deadly-reentry-v760-june-9-2017-the-ariel-edition-pre-release/&page=212#comment-3059970

**Comment by Bornholio** [comment]
After 7.6.0 is CKAN I'd say yes. Until then this will provide trouble shooting help.
