### ISSUE TITLE
[Suggestion] Make part size and utilization independent in procedural avionics

### ISSUE THREAD

**Issue by leudaimon** [KSP-RO/RP-0#702]
Currently, procedural avionics size and utilization are totally dependent, leading to strange situations in which you end up with so tiny parts it even gets impractical. My suggestion is to have an utilization slider independent of part size (of course capped by part size), and in which excess size not utilized for avionics becomes an empty tank that can be used, for instance, for batteries or RCS fuel.

**Comment by pap1723** [comment]
Completed
