### ISSUE TITLE
[Suggestion] Data received from a TF failure

### ISSUE THREAD

**Issue by Dozed12** [KSP-RO/RP-0#706]
Yesterday (20/06/2017) during NathanKell stream he mentioned that TestFlight failures should give a certain amount of data. ( this was also added to the Current To-Do List #680 )

My suggestion is to use the potential data from a rated burn time, that is the total would be gained data from a rated burn time. (RBTD - Rated Burn Time Data)

So for example engine A with a rated burn time of 30 seconds and a rate of data of 15 per second (flightDataMultiplier?) would have a RBTD of 30 * 15 = 450.

We can then give a percentage of this data to the engine depending on the failure. For example:

|Failure | Fraction of RBTD|
|--------------|--------------|
|TestFlightFailure_Explode | 20% of RBTD|
|TestFlightFailure_IgnitionFail |30% of RBTD|
|TestFlightFailure_LockGimbal | 20% of RBTD|
|TestFlightFailure_ReducedMaxThrust | 50% of RBTD|
|TestFlightFailure_ResourceLeak | 20% of RBTD|
|TestFlightFailure_ShutdownEngine | 30% of RBTD|

(Percentages are just a guess)

**Comment by jwvanderbeck** [comment]
TestFlight already gives data for a failure, and RO takes advantage of that.  I think they just need to tweak the values up a bit.  That is all handled in the RO TF configs.

**Comment by Dozed12** [comment]
I am aware TestFlight already gives data for a failure but I believe these values are just guesses (at least from the few I saw) and that requires more time to balance so the idea was to use a percentage of RBTD for every engine potentially making it easy to balance engines.

**Comment by jwvanderbeck** [comment]
What I man is TestFlight simply applies the data in the config.  It doesn't calculate or guess at anything.  So RO could config that value to be a percentage of the burn time like you suggest, and TF doesn't care it just uses what it is given. So really this suggestion should be in the RO repo.  It would just be a tweak to RO's TF config preparser thingyI think.

**Comment by jwvanderbeck** [comment]
I'll link this on the RO repo for you.

**Comment by jwvanderbeck** [comment]
Ok now I realize I am an idiot.  This is already where it belongs.

Ignore the idiot behind the curtain who needs more caffeine.

**Comment by jwvanderbeck** [comment]
Cleaned out the useless comments that arose from my clear misunderstanding of what repo this issue was in.  So sorry about that!

I think this is a fair suggestion and could be handled by RO's preparser I think.  @NathanKell would be the best to answer that though.

**Comment by NathanKell** [comment]
I believe I achieved this. Closing.
