### ISSUE TITLE
Launch Vehicle contracts

### ISSUE THREAD

**Issue by ahmedcharles** [KSP-RO/RP-0#707]
@NathanKell suggested that I post this here to start a discussion.

For context, one of the issues I still have when playing RP-0 is designing LVs. Though, since I've watched NK play tons of RP-0 and he seems to really like building LVs, some of the principles have rubbed off on me. But I still think that I struggle here more than other areas. Then the idea of having LV contracts came to mind and started talking with NK about it.

The high level idea is to facilitate the learning curve of (newer/less experienced) players by having contracts which task them with delivering a payload of a specific mass to a specific orbit (perhaps as simple as above a certain perigee or as complex as the stock satellite contracts, with a specific orbit).

NK mentioned a few concerns, which I'll try to address:

1. Most real LV's were developed as missiles (the closest real analog to LV contracts is missile development) and RP-0 doesn't do military stuff. I think this is a false dichotomy, since a missile can be abstracted into two requirements, a payload with specified weight and a destination, which can be LEO or a city or another planet. The payload and destination requirements can be specified without it being tied to the military in any way.
2. Milestone contracts can currently be achieved by a wide range of vehicle designs and having LV contracts may somehow give players a false sense of security (developing an LV which is too small for a given milestone) or may result in people thinking that they need to develop an unnecessarily large LV before attempting a given milestone. My goal would be to present the two types of contracts as orthogonal, as much as possible, though I'll explain the mechanism below.
3. Milestones having deadlines adds to the level of commitment. Perhaps this boils down to personal preference, but while NK and probably lots of others accept contracts and use the advance to pay for developing the LV to meet that contract, I seem to have a preference to not do that. In my recent play through, 80+% of the contracts I've done were accepted after the LV that I intended to use for that contract was ready to launch. Granted, if the launch failed, I'd have to build another one, but the contract times trivially allow for that eventuality. I don't think there's a 'right' answer here and after exploring my proposed design, I'll revisit this.

Specifics:

- The contracts should only be allowed one completion.
- The contracts should become available when certain tech nodes are unlocked (I don't know which).
- The contracts should have tiers, so people realize that they can build multiple vehicles with the same technology for different payloads. Much like the bulldog vs beagle.
- Each tier should unlock in succession, so it's sort of a ladder.
- Each tier should be more rewarding than the previous, commensurate with difficulty.
- To prevent gaming the system too much, the contracts for a specific tech level should cease being offered after the next tech level has been researched. Though, I'm not sure how aggressive this should be, but the goal would be to prevent a 1 ton to orbit using A-4's contract from being completed once someone gets hydrolox, for example.

The goal is that at each tech level, the player would be incentivized to develop 2-4 LVs with differing payload characteristics. That alone should negate a lot of the potential for players to mistakenly get stuck relying on a single LV design for all mission profiles.

With LV contracts being tech based and milestone contracts being accomplishment based, someone who manages to complete the hardest LV contract at a given tech level should be able to complete more challenging milestone contracts. Whereas a newer player might complete only the easiest LV contract at each tech level and therefore have slower milestone progression.

If one were to imagine having the following tiers with the following properties (earlier in the tech tree would probably have less tiers than higher, but I'm not sure):

1. Enough upfront to build ~2 LVs for testing and unlock the relevant engines and enough completion to unlock another engine or related parts. The deadline should be fairly relaxed and the penalty relatively small. The mission profile of this LV should be smaller sized LEO satellites for that tech level. E.g. 20-30kg to LEO for Early Orbital Rocketry.
2. Enough upfront to build ~2 LVs for testing and combined with the completion to unlock part of a building (especially the launch pad early on), since the engines and other parts should already be unlocked. The deadline and penalty should be 'average'. The mission profile should be average LEO satellites with arbitrary inclination and lighter satellites in molniya/tundra orbits for that tech level. Human rated flight should be possible but perhaps not easy at the lower tech levels on this LV.
3. Probably no upfront and the completion reward should be mostly about giving extra cash for good LV design given the constraints (as much as possible). The deadline should be tight and the penalty should be enough to sting but not ruin a play-through or cause accepting this to be a trap (perhaps a reputation penalty, though I'm not sure if reputation is used much in RP-0). The mission profile for this should trivially include interplanetary probes and human rated missions for lower tech levels with station parts and human lunar missions at higher tech levels.
4. I find it interesting to consider a tier that is a trap with NK LV design levels of difficulty. I don't know how viable this is, but ideally, if you get past the previous contract, you'll know whether you can accomplish this one. It shouldn't have an upfront reward and the completion should be large with a larger penalty. (RP-0 doesn't seem to have stretch contracts at the moment other than the human interplanetary contracts, but in early game, nothing pushes you to accomplish something that won't get easier with tech upgrades.)

The mission profiles above focus mostly on the early game, mostly because I haven't played the later game. Though, I think it's good enough to allow extrapolating what higher tech levels would be like.

On the issue of 'commitment' with regard to milestone contracts: If having LV contracts provides a relatively easy going way of developing LV's, that allows milestone contracts to provide less up front cash. It also allows for tighter deadlines for completing firsts. The expected play style would be that you design LV's immediately after unlocking the tech for them and then you'd finish testing them with a few launches before accepting milestones that you think are appropriate for your LV's, before building vehicles and launching the missions. This would result in a more gradual curve in both finances and level of commitment.

However, the minmax play style looks different. Since the contracts are independent, you can accept the milestone contracts before completing the LV contracts. With sufficiently tight deadlines, trying to complete the LV launches and milestone launches will be harder. If the deadlines were 4-12 months instead of 1-3 years, accepting a contract would be a huge commitment, especially if the current penalties are kept, rather than reducing them (due to the reduced upfront reward).

At a high level, if you ignore science acquisition, one should be able to complete the first three contracts of each tech level and then progress to the next tech level and so on. This implies that only the launch pad and R&D really needs upgrading (and perhaps the VAB) and so the milestones would remain the primary way to get cash to upgrade the other buildings.

Obviously, this would require lots of work and testing/balance. Granted, given that LV design is probably in the top three most important aspects of RO/RP-0, I think it should be incentivized and treated slightly more explicitly than it currently is.

As an aside, this would incentivize using TestFlight, since the launches would be dummy payloads on LV's with brand new engines.

**Comment by Bornholio** [comment]
I think that integration of the new resource requirements will go along way to meeting some of what you propose.  When pap has reorganized the sounding rockets we will see this come into play in early game.
right now it is heavily integrated into the post orbital part and think it's done well.

That said I think a place for something similar to what other contract pack mods have meets your goals.
Take a look at them and see if they can provide a starting point for development.

**Comment by ahmedcharles** [comment]
I only played Pap's new tree yesterday, so after I wrote this post. I don't see any of the contracts being different yet, but I'm only a few hours in. People keep saying that what exists does what I'm suggesting, but I don't really see it and they don't explain why, which is both frustrating and confusing.

So, I guess I have no idea what you're talking about since I don't know how to experience the new resource requirements you mention.

**Comment by pap1723** [comment]
@ahmedcharles What I am not understanding is exactly what you are looking for. That is why I thought it was similar to what we had already.

Things I am working on that "might" fit this request (I cannot say yes for sure, but from my understanding, it does):

1) After the first launch, creating contracts that will require the player to put X amount of mass to a specific altitude. This will work in a progression format. So you will need to get say 100 kg to 150km, then you need to get 100 kg to 300km, then 100 kg to 600 km, etc. (note, none of these numbers are accurate, just trying to give an idea of what the plan is for progression)

2) After the first satellite contract, there are various contracts that require the player to put satellites into different orbits to get the player used to a polar orbit, Molniya orbit, Synchronous, Polar, Tundra, Geostationary, etc. These are designed to familiarize the player with the different types of orbit types and so they understand the delta-v requirements to get to these orbits. Note, the player is not told how much delta-v is required. (this is already implemented)

3) There are communications and weather satellites that require the player to carry a specific amount of a resource into a specific type of orbit. This resource creates mass so that the player has to have a suitable launch vehicle to carry it to the proper orbit. (this is already implemented)

If these do not fulfill what you are looking for, can you please try to explain in a different way what it is you are looking for?

Thanks,
Pap

**Comment by ahmedcharles** [comment]
1. These don't exist yet (and therefore, I can't know for sure), but they would be before the contracts I'm suggesting, since I assume none of these require orbit, just apogee above a certain value. So, these help but seem orthogonal to my suggestion. (I.e. good idea, let's get these in.)

2. I've played these contracts and completed a few of them. The fact that delta-v requirements aren't stated make designing vehicles to complete these more annoying than it otherwise would be. Listing minimum delta-v from a circular 180km orbit in the same plane would probably help. But no, these don't really solve the situation I'm bringing up, since these are the contracts that, in part, made me realize that there was an issue.

3. Can you be more specific about which contracts these are, since I'm not familiar with them and therefore, can't speak to whether they solve my exact issue. And I'd rather not speculate given that they actually exist and I could just play test them and give better feedback.

To try and explain my overall thinking better, I'll try a higher level view of RP-0 currently and what I'm suggesting:

Currently:

Contracts in RP-0 are very 'mission' or 'goal' oriented, in that they focus on doing something out in space and don't say much about how to get there. These are ideal for at least two groups of people: 1. avid fans of space/rocket history and design who already know how to build vehicles and don't need guidance. 2. people who are probably less experienced anyways, but prefer figuring things out on their own. However, hopefully we can agree that this game play experience isn't well suited for people who are learning and don't know the historical properties of various mission profiles and who aren't as willing/able to figure things out on their own.

The interesting thing however, is that if you look at @NathanKell play RP-0, he doesn't play it as goal or mission oriented when designing launch vehicles. Instead, he 'understands' that there's commonality between various missions, their requirements and vehicles that meet those requirements. He takes advantage of that to build launch vehicles which can be used to complete multiple missions, simply by changing the payload. So, there's a clear split between launch vehicle design and payload design. Payloads are designed to be specific to a given mission and then you determine the payload's mass and pick a launch vehicle which can get that mass into LEO.

I think the current 'milestone' mechanism is new player unfriendly. They are characterized by being a one time contract with high advance and high duration which is intended to fund development of a set of LVs and upgrades to the space center, though that's not explicit. New players have almost now context for how to spend the advance or how to time accepting the contract. For the moment, I'm going to ignore commitment to a contract, since I think that can be balanced for independently. As an example, understanding whether or not you can complete a crewed lunar flyby in the next 1-2 years is not something a new player will be able to reason about. I've been playing RP-0 for almost a year, on and off and I still don't think I can reason about it with any confidence.

Proposal:

Let's ignore my proposal for the moment, in terms of specifics, and just go for the high level idea for a potential solution for newer players that gives more guidance. The first aspect of my proposal is to conceptually simplify missions by splitting them into two parts:

1. Given the technology that is currently available, what LVs can be built and what payloads can they place into LEO. At later tech levels, geostationary transfer obit, lunar transfer orbit, interplanetary transfer orbit, etc become interesting as well.
2. Given the next set of missions that can be accepted, what payloads can be built to accomplish them within the various mass capabilities of the LVs that are available.

Rather than go into more details, I'll leave it here. Hopefully the high level view of things is understandable.

**Comment by pap1723** [comment]
After reading through this again, I think what you are looking for makes sense, but it doesn't make sense in the contract system. The contract system is designed to give you over arching goals, but not how to achieve them. What you are looking for definitely has  a place in the upcoming manual however and should be integrated.
