### ISSUE TITLE
Non RP-0 Procedural parts?

### ISSUE THREAD

**Issue by aw94** [KSP-RO/RP-0#71]
Just installed the latest RO + RP-0 from CKAN, and started a new career. Noticed that the procedural parts (fuel tank, SRB, decoupler, etc.) were marked as non RP-0, unlike previous versions (as far as I know). Is this intended? I thought the size limits from earlier worked ok...

**Comment by jwvanderbeck** [comment]
Procedural Parts are definitely supported.  Sounds like a bug in the non-rp0 tagging.

**Comment by NathanKell** [comment]
@aw94 yep that sounds like a big issue. Are you using RP-0 v0.22, just released last night? If not, upgrade it (and RO) since Module Manager has an interaction issue...

**Comment by aw94** [comment]
Yep, reinstalled just now from CKAN to check again. Still marked as non RP-0.

Strangely, CKAN is reporting RO v7.0.7, and KSP-AVC (and the RO.version file) shows 7.0.4, but the files seem to be ok.

**Comment by NathanKell** [comment]
@aw94 dang. I'll fix that when I get home tomorrow. It worked for meeee :(
As for the latter, sounds like @Felger forgot to update the version file :] (Yet another reason to go the travis route!)

**Comment by aw94** [comment]
@NathanKell Alright. Thanks for the quick response!

**Comment by NathanKell** [comment]
Fixed in bc60c18d57674c459b870ac7826c98d72e79e710
