### ISSUE TITLE
Bug with orbital flight with two crew contract.

### ISSUE THREAD

**Issue by Sander815** [KSP-RO/RP-0#712]
With the HSFOrbitalLEO2Repeatable contract this just happened:

I had a contract that said I first had to orbit 2 days with a Pe of at least 180km and an ap between 225 and 425km.
The second part of the contract specified an Ap between 1000 and 1200km for another 2 days.
I overshot my fist burn a bit and got an ap of 520km. Yet the timer of the fist part of the contract started counting and I completed this part successful.
I then tested the second part and it activated with an Ap of 1000km, but kept activated when the Ap went higher then 1200km (I tested up to 2000km).

After the second timer was done I landed and the contract completed.

**Comment by pap1723** [comment]
This is probably a sequence issue in the contracts, I will take a look

**Comment by pap1723** [comment]
Normal CC issues
