### ISSUE TITLE
"First Rendezvous" contract can be completed with one launch by switching to the spent upper stage after jettison

### ISSUE THREAD

**Issue by pianojosh** [KSP-RO/RP-0#721]
I accidentally completed the "First Rendezvous" contract by launching a crewed vessel and, after reaching orbit, switching to the spent upper stage to mark it as debris. The launch counted as a "new vessel" and the upper stage counted as the second vessel, completing that step of the contract. And, since only one of the vessels needed to be returned safely, re-entering and recovering the capsule was enough to complete the contract.

Not sure what the right way to make this contract more specific is exactly. Perhaps make both vessels have to be crewed and recovered? In theory one could still game it by launching two capsules on one launch stack but that's unlikely to be done by accident, that would be someone intentionally trying to game the system.

**Comment by pianojosh** [comment]
@pap1723 I didn't notice this until after I had recovered the vessel, so unfortunately I don't have screenshots showing it happening, but let me know if I can provide any additional info to help replicate.

**Comment by glilienthal** [comment]
whatever the solution, IMHO, the description should be clearer. When I saw the contract I wasn't sure that those two vessels should come from different launches. Maybe just make it explicit in the description? People can game the system (or is it system the game?) anyway.

**Comment by pianojosh** [comment]
To me, the important bit is it not being so easy to complete *accidentally*. I agree that it's not worth it to stop people from gaming, but not completing the contract by switching to the the upper stage to mark it as debris, which is pretty standard behavior in RP-0, probably should happen.

**Comment by pap1723** [comment]
Unfortunately, we are a little stuck with this contract. We can attempt to require a second craft that is launched with crew in order to complete this contract, but then we get into issues with which craft it tracks for the completion parameters.

I will look at some other ideas to see what we might be able to do in order to make it work better however.

**Comment by pap1723** [comment]
Normal CC issues. Don't know a way to fix it. Maybe removing the contract is the right decision. It is mostly already handled by First Docking. I would be good rolling the rewards of this into First Docking, but it will obviously come later.
