### ISSUE TITLE
[Bug] Lunar impactor mission doesn't complete until launch of next vehicle

### ISSUE THREAD

**Issue by mattdarveniza** [KSP-RO/RP-0#728]
So noticed this on my latest playthrough, as per title, when you impact the moon, the impactor mission doesn't complete. Was a bit puzzled by this, but figured I'd just send another impactor over, and upon launch the contract completed.

Have had a poke around and it seems like launching a new vehicle is the only thing that will trigger the contract, loading up vessels from the tracking station doesn't seem to trigger it either.

**Comment by pap1723** [comment]
I have not seen this issue, and I have had no problems completing it. I have found that sometimes the game does not mark the contract complete if you impact with the probe core before any other parts of the craft. I know that often times this is unavoidable and is the most likely outcome.

CC does not like when craft get destroyed as it sometimes messes with the completion parameter being checked.

**Comment by Bornholio** [comment]
I find that it completes fine if I make the impactors PE just below the surface so relative vertical velocity is low.  Otherwise the time step can be too high to recognize it properly for CC.

**Comment by pap1723** [comment]
@siimav has done a lot of work to get this working a little better.
