### ISSUE TITLE
Early probe core is using a fraction of intended EC while warping

### ISSUE THREAD

**Issue by kendoka15** [KSP-RO/RP-0#731]
I was building a probe when I noticed when testing it that when timewarping, its EC usage was much lower than it was supposed to be. When not hibernating, it should use 50 watts (0.05 EC/s), therefore empty its battery in 88 hours. When hibernating, it should use 1 watt for a drain time of 183 days. Here are my test results:

With Testflight (same with hyperedit) to 1000km orbit:
No hibernation with no warp, EC meter at top shows 0.05 EC/s (as intended)
With warp x10, EC meter shows 0.01 EC/s (instead of 0.5)
With warp x100, EC meter shows 0.1 EC/s (instead of 5)
With warp x1000, EC meter shows 1 EC/s (instead of 50)
Etc.

After around 3 days 16 hours in orbit with warp x10000, the probe should show 0 EC, but it still has 15518 EC left. This means 322 EC has drained instead of the full 15840. This amounts to 0.001 EC/s when warping instead of 0.05.

Now for hibernation mode. My test starts with 15838 EC and 0.001 EC/s with no warp. The battery meter shows 0.00 EC/s. At 0.001 EC/s, 12 days should drain 864 EC. I activate 10000x warp, the battery meter shows 0.1 EC/s (instead of 10 EC/s). After 12 days 2 hours, 15828 EC is left, for a total discharge of 10 EC. That amounts to around 0,00001 EC/s at warp instead of 0.001.

I've tried this with the Able probe but everything works fine. I initially posted this to the RO github before testing and finding out this doesn't happen on an RO only install.

**Comment by NathanKell** [comment]
This is due to confusing the stock hibernate functionality with RP-0's powered-down-avionics functionality, as I explained in the RO issue. They're completely separate systems. To ease confusion we've removed stock hibernate functionality from everything. Please see the RO issue for the explanation for all your numbers.
https://github.com/KSP-RO/RealismOverhaul/issues/1732#issuecomment-317127718
