### ISSUE TITLE
Procedural avionics probe core attached directly to heat shield overheats and explodes on reentry

### ISSUE THREAD

**Issue by pianojosh** [KSP-RO/RP-0#739]
I've tried a few variants of this mission now having a 1m heat shield connected to a procedural probe core of 700mm diameter, 200mm length, massing 35kg. It often, though not always, overheats and explodes on reentry. Doing similar with an early controllable core seems to work fine. It's not the no-G-force bug, it's rapidly decelerating (~10G) but steadily heats up to the point of failure during the reentry.

If I place a cubic strut between the procedural probe core and the heat shield it works just fine with no heat bars even showing up.

So the issue seems to be excessive conduction between the heat shield and the procedural avionics connected to it, though the low max skin temperatures of the procedural avionics may be contributing as well.

**Comment by pap1723** [comment]
All procedural temperatures have been updated, this should fix the issues.
