### ISSUE TITLE
Testing DLLs

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RP-0#749]
[Get yer plugins here!](https://www.dropbox.com/sh/oify23mazfma7h7/AACDhQF1JoxG8hxKlhA_Px7Za?dl=0)

Replace your existing copies of them with these.

**Comment by Bornholio** [comment]
NK is this still valid for kurrent build?

**Comment by NathanKell** [comment]
Valid for KSP 1.3.1 and all Dev branches

Sent by my thumbs, slowly.

**Comment by Bornholio** [comment]
RF DLL is no longer needed for 1.3.1 release is good to go.

**Comment by agustincaniglia** [comment]
Question:
Is the KCT dll linked above still needed?

**Comment by Bornholio** [comment]
Answer: no

**Comment by Bornholio** [comment]
close me?
