### ISSUE TITLE
Report of New NTR engines producing no thrust.

### ISSUE THREAD

**Issue by Bornholio** [KSP-RO/RP-0#759]
investigating.

**Comment by wb99999999** [comment]
Seems to have something to do with the enriched Uranium configs: engine flames out on start-up and reports lacking of propellant despite attached on a  full tank.
Attempts were made to add Uranium tank as well as Hydrogen with no progress.

**Comment by Bornholio** [comment]
Each of the new NTR's need Uranium fuel resource addition corrected, PEWEE 100 works as intended.

**Comment by Bornholio** [comment]
see RO PR 1758 through 1766
