### ISSUE TITLE
Cryogenic tank option not showing in VAB

### ISSUE THREAD

**Issue by oberst88** [KSP-RO/RP-0#762]
from the save file:
`RFTank-cryogenic-tank-unlock = True`
`RFTank-balloon-cryogenic-tank-unlock = True`
I unlocked the cryo tank type in the VAB, both for normal tanks and balloon ones, but when in the VAB the option is not available. Only have normal or HP for the normal tanks, and the balloon tank does not offer any option.
Using latest dev RP-0 and RO. 
![screenshot 1276](https://user-images.githubusercontent.com/31419403/29790515-1168c9b0-8c32-11e7-9b8f-7bdc67d07ce6.png)

**Comment by NathanKell** [comment]
Yep, RO/RP-0 dev doesn't have cryogenic tanks yet. Working on it. :)
