### ISSUE TITLE
Post-War Rocketry Testing does not enable XASR-1 upgrade [RP-1 dev]

### ISSUE THREAD

**Issue by NoMrBond** [KSP-RO/RP-0#765]
When the Post-War Rocketry Testing node is finished researching, the other upgrade items (RD-100 to RD-101 and A4 to A9) are both available through the VAB/SPH engine GUI for upgrading, but the XASR-1 config does not become available for the Aerobee (WAC-Corporal) even though the upgrade icon appears in the PWRT node in the R&D building.

Am using the latest [Developmental] package and the updated DLL's for KCT/RF as posted in #749 

[Edit] The ROAerobeeSustainer appears to be throwing an NRE (Object reference not set to an instance of an object), not sure if related

[Edit2] KSP.log attached

[KSP - Copy.zip](https://github.com/KSP-RO/RP-0/files/1291000/KSP.-.Copy.zip)

Similarly for the RD-100 lineage, the icon for the RD-102 upgrade is under Early Rocketry but actually becomes available when you finish researching Post-War Rocketry Testing.

**Comment by EagleEyeLogic** [comment]
Not sure if all will be correct, but try changing the first line in GameData\RP-0\Tree\TREE-Engines.cfg to

@PART[*]:HAS[@MODULE[ModuleEngineConfigs]]:AFTER[RealismOverhaulEngines]

this will overwrite all techRequired and cost from RO to the now used in RP-1

**Comment by NoMrBond** [comment]
Ah, I was back to report that unfortunately the @part[*]:HAS[@module[ModuleEngineConfigs]]:AFTER[RealismOverhaulEngines] suggestion edit for the TREE-engines.cfg hadn't worked.  I'll test the zip package now.

**Comment by Bornholio** [comment]
close me?
