### ISSUE TITLE
SSTU modular tanks don't require tooling

### ISSUE THREAD

**Issue by jobadiah08** [KSP-RO/RP-0#768]
Not sure if this is known yet or not. I couldn't find anything regarding it searching through the issues.

**Comment by MikeOnTea** [comment]
I'm wondering whether and how the SSTU tanks should be integrated into the new level system of tanks.
It probably would be overkill to create every level for every SSTU tank. Most tanks should be fine with level 3, 3 Balloon and 4. That would still be quite some amount of tanks, though: MFT-A, -R, -S, -D, -LV, MUS times 3 = 18 tanks. MFT-A might want to have level 1-2 aswell, MFT-R level 2, so we're at 21 tanks.
Now include Service modules 1-4 for -A and 3-4 for MUS and we're at 27 tanks.

Thoughts?

**Comment by pap1723** [comment]
The main tanks are now part of tooling. The rest of them will be coming shortly.
