### ISSUE TITLE
Manned flight costing issues?

### ISSUE THREAD

**Issue by ppboyle** [KSP-RO/RP-0#771]
So, currently the costing for manned missions is way too high

I know there are stacks of multipliers, at various points, but I think the overall effect is not what was intended.  Here's what I'm seeing:

I place the Apollo command module - which the browser claims costs 9810 kerbucks.   After it's placed, my current cost reads as 9,444 kerbucks.

The second I click the capsule, however, my current cost NOW reads 27,386 kerbucks.   This is very strange.

Ok, so I build the apollo capsule.  Now, if I take it out to a level 7 unlimited mass pad, it lists a cost of 3,1118,263 to rollout the capsule ALL BY ITSELF.  That's a factor of 113x on the already increased-price capsule - I don't see how even all the part-cost modifiers stacked together generates such a high figure.  Even on the 20ton pad, it costs 496,822, a factor of 18x.

Then I built a full up Saturn V, which costs 149,987 to build, rollout costs are 4,591,259 on the unlimited pad - so it's mostly the command module, though even without it rollout costs are still high.

Mercury-Atlas has the same issues.  Build Cost of 12.4k, rollout cost of 124.6k, even though the whole 6-launch +tests mercury program cost 277 million in 1965 dollars.

Suggested TODO's to fix:
I think the following needs to be corrected:
- Track down and remove the odd 3x multiplier on capsule costs.  
- Remove or massively reduce the scaling cost of rolling out to different pad levels - keep the fixed-cost per launch addition so there is still incentive for different pad levels.

Redo the tuning for part rollout multipliers so that the following is roughly true
- Rolling out the Apollo Command module should cost at most 100k kerbucks to the unlimited pad
- Rolling out the Mercury Pod should cost at most 15k kerbucks to the 150k pad
- Mercury-Atlas will then cost ~6k.   Rolling it out should be something like 19k (~3x construction).  This yields a launch cost of 6 M-A's of 150k, the other 127k would have gone to R&D.
- Rolling out a 130k BP  Saturn V to the unlimited pad should cost 400k kerbucks (~3x construction).  This yields a per-launch cost for S V of ~530k, or 6 billion for 11 Apollo shots.  This is reasonable considering the higher facilities cost, and that 20billion Apollo program cost in 1970's money is closer to 15 in 1960's money.
- Retouch all the manned contracts.  Even with the above figures, the LEO repeatables are verging on losing money, for instance.

I can look at redoing the tuning for most of the rollout cost issues, but I have no idea where this in-VAB capsule multiplier is coming from, does anyone know?

**Comment by m4gus88** [comment]
In the KCT config, I've found Part_Variables and Module_Variables. I'm not so familiar with KCT config, but I guess these are BP and cost multipliers set for individual parts, and for parts having certain modules. As I see, the multipliers for tags are set up, but parts containing multiple tags (like pods) need special care. This, however is only set up for the Mk1 Pod, and nothing else. This might be why other crewed parts (including FASA pods) are so expensive to roll out, and have such high BP costs.

**Comment by siimav** [comment]
No longer an issue, I think
