### ISSUE TITLE
Assume all proc parts are tooled when calculating cost for KRASH simulation?

### ISSUE THREAD

**Issue by aw1621107** [KSP-RO/RP-0#774]
Think it makes more sense, since you aren't actually creating anything (for a simulation).

**Comment by aw1621107** [comment]
Here's a patch for KRASH that messily fixes the issue. I'll need to clean it up and make it more resilient to missing RP-0 installs before submitting a PR though.

[proc.patch.txt](https://github.com/KSP-RO/RP-0/files/1660376/proc.patch.txt)

**Comment by NathanKell** [comment]
Good idea! :)

**Comment by Bornholio** [comment]
awang did this make it into krash or anything yet?

**Comment by aw1621107** [comment]
@Bornholio Yep, it was merged back in April
