### ISSUE TITLE
Should return capsules have a science core tag?

### ISSUE THREAD

**Issue by ts826848** [KSP-RO/RP-0#777]
For example, RaiderNick's Stardust Return Capsule (neo.stardust.collector) and Almaz Film Return Capsule (almaz.sample.return) have command capabilities + MJ/TCA, but idk if that really make sense, given what these parts appear to be intended for...

**Comment by Bornholio** [comment]
maybe just to be able to fire parachutes and otherwise stage or stabilize during entry?

**Comment by Bornholio** [comment]
close me?

**Comment by Bornholio** [comment]
probably should be done on RO side then

**Comment by pap1723** [comment]
None of that is set in RO, it is all an RP-0 function

**Comment by siimav** [comment]
Science core tag is just informative right now. ModuleAvionics should be used instead by setting the `massLimit` to 0.
