### ISSUE TITLE
Questions on avionics/science core tags

### ISSUE THREAD

**Issue by ts826848** [KSP-RO/RP-0#780]
When working on #779, I was wondering if there might be a better way to keep track of what parts require a science core and what parts don't, since the current method requires manually tracking what parts are probe cores and what parts aren't. For example, maybe add science cores to all parts with ModuleCommand that don't have ModuleAvionics or ModuleScienceCore? Something like

```
@PART[*]:HAS[@MODULE[ModuleCommand],!MODULE[ModuleAvionics],!MODULE[ModuleScienceCore]]:FOR[RP-0]
{
        MODULE
        {
                name = ModuleScienceCore
        }
}
```

Main issue I can think of is that ModuleAvionics doesn't appear to be applied consistently for parts. For example, some crewed parts say that they support x tons of vessel, some don't (both parts that require crew and those that don't).

Thoughts? How badly flawed is this?

**Comment by DRVeyl** [comment]
The entirety of code for `ModuleScienceCore` is now
```
    class ModuleScienceCore : PartModule
    {
        public override string GetInfo() => "This part alone only allows limited command interaction; you will not be allowed full attitude control unless another command part without this module is attached.";
    }
```
The earlier code from https://github.com/KSP-RO/RP-0/commit/b877b64a3ffab5e93ccf80872caa06d88a1fc4a8 has been integrated into the avionics handling (Control Locker).  So effectively this module is now just a notice but has no impact, and I guess the definition of a part that has ModuleCommand but no ModuleAvionics?

Is this still an issue?  There is https://github.com/KSP-RO/RP-0/blob/9cfc9b2d7b7d375ed477a60b189051948d9adaf8/GameData/RP-0/Avionics.cfg#L11-L17 which patches all crewed parts to ensure either ModuleAvionics or ModuleScienceCore.  Does the crew limitation need to change?

**Comment by ts826848** [comment]
Yeah, looks like I actually made that change in #813 and probably forgot to close this issue.

I *think* the intent there was to disable control for parts that don't have control through other means, so the `@MODULE[ModuleCommand]:HAS[~minimumCrew[>0]]` bit was to catch parts with `ModuleCommand` but `minimumCrew == 0`.
