### ISSUE TITLE
Proc avionics resets to "most modern" upon vessel load

### ISSUE THREAD

**Issue by aw1621107** [KSP-RO/RP-0#792]
I have a ship that uses the `avionicsPrototypes` upper stage avionics configs. The part switches to `earlyAvionics` upon vessel load, which increases vessel mass because `earlyAvionics` has a higher minimum supported mass (5 tons) than `avionicsPrototypes` (3 tons), which causes the game to automatically resize the part.

Possibly related to #775? Maybe the level isn't being saved correctly?

**Comment by DRVeyl** [comment]
Fixed.
