### ISSUE TITLE
Changing proc avionics tech level changes tech level for *all* proc avionics parts

### ISSUE THREAD

**Issue by aw1621107** [KSP-RO/RP-0#793]
I have a rocket with two proc avionics parts, both set to the "upper stage" type. The one corresponding to the TLI stage should stay on the `avionicsPrototypes` tech level, since its stage is only ~1.5t and the `avionicsPrototypes` tech level has a minimum avionics mass of 3t compared to the minimum of 5t for the `earlyAvionics` tech level. This allows the `avionicsPrototypes` part to be smaller and lighter.

The other avionics part is on the orbital insertion stage, which is ~8.8 tons. I would like to set to `earlyAvionics`, since the stage is heavy enough that the newer tech should allow for a lighter part.

Unfortunately, it seems that setting the tech level for one of the parts sets the tech level for both parts, making my preferred setup impossible.

This does not appear to happen if the parts are of two different avionics types (i.e. one "booster" type and one "upper stage" type)

**Comment by aw1621107** [comment]
Looks like this can also cause some kind of update spam. If I have the TLI stage proc avionics configured to `prototypeAvionics`, supporting 3 tons, with a diameter of 1m and length of 0.2m (utilization 198.3%), and the orbital insertion stage proc avionics configured to `prototypeAvionics`, supporting 5.240 tons, with a diameter of 1m and length of 0.5m (utilization 100%), changing the orbital insertion proc avionics to `earlyAvionics` causes a framerate drop until I can right-click on the TLI proc avionics and update the dimensions.

[Here](https://gfycat.com/gifs/detail/EvergreenSkeletalJabiru) is a gfycat demonstrating the issue

**Comment by aw1621107** [comment]
[Here](https://gfycat.com/gifs/detail/SpecificPopularFoxhound) is a better gfycat, hopefully. tl;dw: If you have config windows for multiple proc avionics parts open at the same time, changing the tech level of one instantly changes the tech level of them all at the same time

**Comment by DRVeyl** [comment]
Fixed.  The window is tied to the owning part and will only change that part's configuration.  Having multiple GUI configuration windows open does not affect this.
