### ISSUE TITLE
Bluedog Agena engines show up under avionics despite not providing avionics

### ISSUE THREAD

**Issue by aw1621107** [KSP-RO/RP-0#796]
`bluedog_AgenaA` and `bluedog_AgenaD` show up under the `basicAvionics` and `improvedAvionics` tech nodes, respectively. Since their in-game title is "XLR81 (Agena) Vacuum Engine", and since neither of them actually have ModuleAvionics, I would have expected them to show up under the orbital rocketry series of tech nodes (1959 and 1963, I think?).

Their RO config says that their titles should be `Agena-A/B Flight Pack` and `Agena-D Flight Pack`, respectively, which I guess makes more sense, but they still don't provide avionics...

**Comment by ec429** [comment]
Assuming these are the same thing as `FASAAgena_Engine_FP` (which is _also_ in `improvedAvionics`) and friends…

They don't belong in orbital-rocketry nodes, they're control parts.  The main things in them are RCS thrusters, tanks for same, and (in the -D version, iirc) the SPS (small manœuvring thrusters).
So _maybe_ they belong in the Flight Control series rather than Avionics, since that's where RCS thrusters and the not-1kN engine live.  But we should probably get @pap1723 or someone to chime in.

**Comment by aw1621107** [comment]
If that's the case then I think their description/title needs to be changed at least, since they imply (to me, at least) that they are "regular" engines. They also have a pretty hefty ~70kN engine, which seems like a bit much for RCS/SPS

**Comment by ec429** [comment]
Hmm, so the bluedog parts have the Agena engine and the Agena flight pack in a single part?  That seems unhelpful.

**Comment by aw1621107** [comment]
I think so? Looks like it was designed that way, from the description of the unaltered `bluedog_AgenaA` part:

>This 0.9375m engine includes darn near everything you would need for your upper stage, including two monopropellant bottles, a full RCS attitude control system, a fairly powerful vacuum engine, and a small supply of fuel.

**Comment by dgeastman** [comment]
I'm still seeing this issue, even with a recent pull of RP-1 developmental, the BDB Agena Engine shows up in the avionics node, not a rocketry node.

**Comment by aw1621107** [comment]
@dgeastman What's the part name of the offending engine, e.g. `bluedog_AgenaA`, `bluedog_AgenaD`, etc.?

**Comment by aw1621107** [comment]
Oh, and what does your MM cache say?

**Comment by dgeastman** [comment]
I take it back, it was still happening in my 1.2.1 branch which is a bit older, my current 1.3.1 game looks good.

**Comment by pap1723** [comment]
This was completed here: https://github.com/KSP-RO/RP-0/commit/c740e24f8881538d4a666d5da0822ff06c5aab05
