### ISSUE TITLE
Rescue Missions

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RP-0#8]
I said I was going to open an issue on this; must have forgotten.

What do we think about rescue missions? Some ideas:
1. Remove them completely.
2. Assume that there are other space agencies, and thus merely correct any weird orbits.
3. Only enable them when craft are in orbit, and remove the kerbal from a random craft.
4. Only enable them when craft are in orbit, and remove all kerbals from the craft and destroy the craft.

**Comment by Bornholio** [comment]
Close this, as its a decided issue easily controled with contract configurator?

**Comment by pap1723** [comment]
Confirmed
