### ISSUE TITLE
[Dev] Tooling and TANK_DEFINITION for NewRFTanks

### ISSUE THREAD

**Issue by EagleEyeLogic** [KSP-RO/RP-0#805]
I've found nothing about tooling function, so here are some questions.

1. What is tooling try to simulate?
2. Were should costs of tooled parts in comparsion to normal parts end?

**Comment by NoMrBond** [comment]
Tooling simulates setting up the production facilities and infrastructure necessary to produce those items on a regular basis.  It may include molds for casting, dies for pressing, hoists, jacks and other specialised handling equipment, welding rigs, environmental chambers, x-ray machines for join/weld surveying and all manner of specialised tools to aid in production.

Not sure what the angle is on question (2), but I'll take a stab at it.  For 'regular' parts you have a 'buy-in' to unlock their use after you're finished researching them, this 'buy-in' cost is their equivalent of the 'tooling' setup costs for procedural parts.  I'm not sure how close to 'balanced' their values are considered at this point (buy-in for fixed vs tooling for proc parts).

**Comment by EagleEyeLogic** [comment]
1. good to know you think like I do

2. For now it's way of. I post some screens to show where we are. Compared Tank-I-HP (buyin 1) and FL-T800 (buyin 20), but not sure where this come from. RP-1 shrink UnitsperT for ProcBattery down and maybe there is also some mistake on tanks. Will look at this later. First screen is without tooling any Tank-I in 1.25m and second with one tooling in 1.25m

![screenshot0](https://user-images.githubusercontent.com/33643476/33956129-f1584500-e03d-11e7-9d2b-813ff09e5603.png)
![screenshot1](https://user-images.githubusercontent.com/33643476/33956140-f96cb9ba-e03d-11e7-88db-e0d90ad7a3fc.png)

Because buildtime is direct reflecting the costs, we are far of if we try to use Procedurals. But using PP should only give more parts that will be standard by tooling them.

In buildcosts we end up by 8 for Tank-I and 41 for FL-T800

**Comment by Theysen** [comment]
i'm pretty sure "stock" RO tanks haven't been touched for ages in RO and thus shall not be used to compare towards what the devs created especially for RP-1 in my mind and the proc tanks. They are balanced for the gameplay and recommended tanks to use.

**Comment by EagleEyeLogic** [comment]
@Theysen 
Thats not only stock tanks. Every tank from a mod must use the old RO way. Thats how these tanks are designed und balanced. Stock and RN, FASA etc. are last touched long time ago, there is no need to do this.

Question is only, is the new system balanced against this or will some partpacks switch from Suggested to Recommended if we try to reach the same goal with same progress in sience.

FL-T800 is only one example and a usefull if people play without partpacks

**Comment by Theysen** [comment]
RP-1 as a test bed development environment incorporated the new fuel tank definitions especially for Procedural Part tanks afaik since those are the go to for craft building. If RP-1 ever becomes official I'm sure all other tanks have to be readjusted, yes.
