### ISSUE TITLE
RP-0/RP-1 custom menu empty

### ISSUE THREAD

**Issue by GrKl30** [KSP-RO/RP-0#810]
In my current RP-1 playthrough, the custom menu (the one in wich you see the toolings, maintenance costs, crew training,...) is somethimes broken, whatever the scene (VAB, SPH, space center,...)

The problem is clearly save related, loading a previous save and the menu is working. Re-loading the most recent save after that and the menu is lost again.

Restarting KSP, deleting MM cache, reinstalling KSP+mods cleanly does not solve the problem either. So really save-file related

The RP-0 menu is shrinked, only the borders corners are visible, thus total size is very small, nothing is within the menu. Like if the mod was not able to find any data in the save file to load into this window. I checked the save file, and was not able to find anything wrong with it, compairing with a healthy save file.

Worse thing, is that on my current save, loading my last healthy save file, then flying my next mission (1st moon crewed fly-by) then recovering craft: menu empty/shrinked/broken again. Restarted the same process 3 times and systematically have the same result. Preventing me to continue on this save.

I had the problem before, but reverting an older save + restarting the mission did solve the problem. Also had the issue (solvable) in a previous playthrough that was a seperate RP-1 install, so I would suppose other could encounter the issue too

If anybody is willing to help/debug, I could of course upload a problematic save-file

**Comment by ec429** [comment]
That sounds very much like an exception was thrown somewhere in the GUI.  Can you look in your log file for exception messages?

**Comment by GrKl30** [comment]
I do indeed, I have a shitload of errors. Every unity Update() I suppose, every 5/6 millisecond:
[EXC 21:40:54.134] IndexOutOfRangeException: Array index is out of range.
	RP0.MaintenanceHandler.updateUpkeep ()
	RP0.MaintenanceHandler.Update ()

**Comment by GrKl30** [comment]
Ok. Closed.

Looking at the dev source, I see you update MaintenanceHandler.cs 22 days ago to "Fix calculation of level index in updateUpkeep()"

My RP0.dll was older than this. Downloaded it. Tested it, fixed. Sorry for not having looked into the log before myself and thanks ec429 for your prompt help

**Comment by ec429** [comment]
Glad to be able to help :)
