### ISSUE TITLE
Dev RP-0 / RP-1. Unlock costs not deducting funds

### ISSUE THREAD

**Issue by GrKl30** [KSP-RO/RP-0#811]
I have noticed this a lot, and Reddit/Dicord users all seem to have this problem with RP-1:
When unlocking a part, no money is removed from bank account.

This is not linked to same engines/same unlock feature, as it happens with engines but other parts too.
I was not able to find a patern, linked to a specific mod or anything. Some unlocks though correctly remove funds, my last experience with working unlocks was with a bunch of science experiments.

It seems that unlocking the complete node from the R&D building does remove funds correctly. Even when it contains parts that would have not been correctly costing unlock costs if unlocked separatly from the VAB.

I tried yesterday a clean new RP-1 install, even my first unlocks (aerobee avionics core & WAC engine), each costing 1$ already have this bug. Not huge problem with these minimal costs, bug bothering when parts costs 100k+

I'll check the logs tonight to see if any error is printed and report back

**Comment by GrKl30** [comment]
Oddly, this seems to be RealFuels fault. I tested an 1.3.1 RF dll that solved the unlock costs issues. Obviously, this is not usable for 1.2.2 because of the UI changes since 1.3 but confirms that change to RF side solves this and that it is not RP-1's "Fault"

Fixes seems to be here (somewhere): https://github.com/NathanKell/ModularFuelSystem/pull/199/commits

**Comment by NathanKell** [comment]
Yep, RP-1 required updates to RF to change how unlocking is handled. #749 has the 1.2.2 RF dll required, if memory serves.

**Comment by GrKl30** [comment]
Thanks NK, the .dll you gave in #749 for RF is the one I use. Should have noted it before. And is the one causing this bug. Just as an FYI, as 1.3.1 is soon and IIRC this issue is already fixed for that version, no need to loose time with 1.2.2 fix as simple workaround is to manually remove funds when needed, no big deal

**Comment by NathanKell** [comment]
Huh, weird. That dll should have been for RP-1 on 1.2.2 so...dunno. Anyway, glad it's sorted.
