### ISSUE TITLE
RP-1 todos for release

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RP-0#812]
I'm holding off actually releasing the rest of the constellation since RP-1's changes are so far-reaching they may require changes in other mods. But AFAIK the remaining work is pretty much all RP-1, or at least closely tied to it.

- [ ] Cryogenic tank clones - NK
- [ ] Relays (RT now supports turning relays off for SPUs.)
- [x] launch cost tuning - NK
- [x] launch cost multiplier for all pods/crewed stuff other than mk1 pod (which was done)
- [x] Venus-resistant parts (or turn off pressure limits)
- [ ] Bake funding mult into contract payouts, reduce mults in cfg.
- [x] Unpressurized cockpits need the module applied
- [ ] KerbNet settings need fixing for probes/capsules. (PS-1 shouldn't have full access, e.g.)
- [x] Bio sample - should it be once-only? Unclear. @pap1723  ?
- [x] Fix loading screen changer for 1.3.1.
- [x] Sounding rocket contract rewards
- [x] X-405 mixture differs main to verniers
- [x] Fix comm network contract rewards (1/10th?)
- [x] FASA vs stock Castor 1 cost, unlock cost, ECM

**Comment by NathanKell** [comment]
Tagged the ones I know I'll be tackling.

**Comment by ppboyle** [comment]
I haven't looked at it lately, but last I knew proc avionics needs fixing & retuning too.   And I'd be happy to help with tuning.

**Comment by ec429** [comment]
Pod multipliers are Issue #771 and I've done some work on them in PR #815.  The main thing missing is Soyuz, because I don't know RN's naming convention for parts.

**Comment by NathanKell** [comment]
Forgot the Venus resistant bit. Added.

**Comment by NathanKell** [comment]
Updated OP regarding tanks, since while MLI is in dewar isn't, which means service module cryo won't work right. So for now we can go with the old cryo still, and retrofit later. So I'll make some more tank clones.

**Comment by NathanKell** [comment]
For the relay thing, see https://github.com/KSP-RO/RealismOverhaul/commit/4a12ffd1d3f89ba82bb1b7e7126bda1ddcb81310 for how to enable relays on cores. For now, we default to non-relay.

**Comment by NathanKell** [comment]
Tuned launch costs.

**Comment by Bornholio** [comment]
HE111 and possibly other cockpits with not orbital rating need to be cleaned of oxygen to avoid being used as SO manned pods

**Comment by NathanKell** [comment]
Also KerbNet

**Comment by NathanKell** [comment]
ModuleUnpressurizedCockpit isn't used.

**Comment by blowfishpro** [comment]
Discussed on stream with NK, bio sample can be taken multiple times in flight whereas it should be expended after the first sample

**Comment by NathanKell** [comment]
Unless it's all by @pap1723 's design :)

**Comment by Bornholio** [comment]
https://github.com/KSP-RO/RP-0/wiki/Science  possibly he intended that. Unfortunately reset/reuse is not listed in the wiki. Everything else matches, lets poll the spreadsheet of Science

**Comment by Bornholio** [comment]
NTR's that i made configs for are missing a { or } somewhere for a few of them.

Also update MM requirement to 3.0.4 or something

**Comment by pap1723** [comment]
@Bornholio I believe that Wild Blue Tools should be able to use the newest release, but I cannot confirm (as I don't have a working install).

**Comment by cmr** [comment]
is there an easy way to test this?

**Comment by Bornholio** [comment]
crew science isn't working on my install

**Comment by Bornholio** [comment]
Closing this? Move items to new issue #931

**Comment by pap1723** [comment]
Done.
