### ISSUE TITLE
Dev branch no longer compatible with 1.2.2

### ISSUE THREAD

**Issue by ockidj** [KSP-RO/RP-0#816]
The game won't startup with the new files from the dev branches. I'm assuming it's because they are 1.3 now.

**Comment by NoMrBond** [comment]
Yes, since 24th of January

> https://github.com/KSP-RO/RP-0/commit/eb5b4f7f676c92870a3f86791e6e59fdc1b90cbb

**Comment by pap1723** [comment]
This is correct, it is now for 1.3.1
