### ISSUE TITLE
no tech tree :(

### ISSUE THREAD

**Issue by fighter4life** [KSP-RO/RP-0#817]
hi, i just decided to give rp 0 a shot to extend the life of my saves, but when i start a new game, its like rp 0 is there, i can config it...but when it prompts me to select a tech tree, i can only choose stock or the engineering tech tree. any ideas?

**Comment by alimoncul** [comment]
I think you need to compile tech tree. 

https://www.reddit.com/r/RealSolarSystem/comments/5yioyu/ro_tech_tree_engine_placement/

**Comment by pap1723** [comment]
@fighter4life If you wait until the 1.3 release, it will be working correctly. Has your issue been fixed?

**Comment by pap1723** [comment]
Old issue
