### ISSUE TITLE
Hide retired Kerbals from RP-1 screens

### ISSUE THREAD

**Issue by GrKl30** [KSP-RO/RP-0#818]
In the 1.2.2 version of RP-1 , retired Kerbals are still in RP-1 screens (Training & Courses)
Should be removed from there

Also, less important, in Astronaut Complex, retired Kerbals are noted as "K.I.A." instead of "Retired". Not sure if this is editable though

**Comment by GrKl30** [comment]
While on those screens, buttons containing Kerbal names should be a bit wider. Currently cant store 'long' name. You can see here the too small button, and Kerbals with no retirement date, as they are already retired
https://imgur.com/gallery/UvImF

**Comment by siimav** [comment]
Looks like all of those mentioned issues have been fixed.
