### ISSUE TITLE
RP-1 : pod naming in the "training" tab

### ISSUE THREAD

**Issue by GrKl30** [KSP-RO/RP-0#821]
for the first time I want to use the MK2 pod in my RP-1 campaign. But this name is not visible in the courses tab. There is a "Apollo", wich I suppose to be it, it probably regroups different type of "Apollo" pods from different mods. It could also be the apollo ascent pod.

Same for other cases: unclear to me what course I need to use.

Where can I find this info? Could we find a way to make this visible to all, at least on the wiki or better in game?

**Comment by pap1723** [comment]
Mk2 does not exist in RP-1. It is re-named to be correct real world parts. Therefore it will be called the Apollo CM.
