### ISSUE TITLE
Lit liquid engines die when staging launch clamps.

### ISSUE THREAD

**Issue by SpaceCatHaxor** [KSP-RO/RP-0#822]
Very easy to reproduce, several people in the Discord have had this issue as well.

On KSP 1.3.1 dev branch RP-1.

Build a sounding rocket that doesn't have a solid rocket stage to start with. Light engine to let it build thrust. Release launch clamps. The engine will die and your rocket will fall to the ground.

I have this problem on the LVT-15, Aerobee, and A4 engine, all of the engines I've tested. Probably effects all engines though. Remote Tech is not the cause, although this bug looks similar to a Remote Tech bug fixed forever ago. Have also tested with nothing but required mods + visual mods and still have problem.

The propellant state flashes when this happens, (as in the line that says "stable", or "risky", etc)not sure how its related though. I'm not sure what mod is causing this, but only people with RP-1 have this problem. It might be the testing Realfuels dll.

**Comment by Elouda** [comment]
Removing RemoteTech or setting the signal delay off causes this to not happen, which would indicate that RT is atleast somehow involved in causing this. Also, it does not happen with RT 1.8.7. My suspicion is that the changes between 1.8.7 and 1.8.8, specifically [https://github.com/RemoteTechnologiesGroup/RemoteTech/commit/16acae77f2159d33c0075ae11fa9eaaa52644d1f](this) is somehow connected.

**Comment by NathanKell** [comment]
IIRC it's "throttle down on connection loss" and you can change the setting in RT's space-center GUI on one of the tabs. RO forces it to false by default, but for some reason it became true for you?
