### ISSUE TITLE
Aerobee need pressure-fed tank, default tank for engine is not pressured.

### ISSUE THREAD

**Issue by alimoncul** [KSP-RO/RP-0#824]
![screenshot0](https://user-images.githubusercontent.com/15328038/35993965-00d0ee10-0d20-11e8-8c31-ad3ac4787477.png)

Here is the tank config from RO : https://github.com/KSP-RO/RealismOverhaul/blob/master/GameData/RealismOverhaul/RO_SuggestedMods/Taerobee/Aerobee.cfg#L386

Fuels not correct either. Do i have a problem with Real Fuels?

**Comment by SpaceCatHaxor** [comment]
Looks like a config issue, I don't know exactly how configs for Realfuels and such work, so I can't fix it, but its not surprising that its gone unnoticed. RP-0 heavily encourages you to use the procedural fuel tanks, and the upcoming update makes them practically mandatory with tooling costs.

**Comment by pianojosh** [comment]
Something is wrong with your setup, it still has LiquidFuel. RealFuels should have removed that entirely. Are you sure the rest of your RO + dependencies are set up correctly? RealFuels requires SolverEngines, which isn't included in the dev branch download, you'll need to get it separately or from a release.

**Comment by alimoncul** [comment]
https://docs.google.com/spreadsheets/d/1A7gQkIiQKi0VtRecE6p86KCKuoawZPdzk7NlaxssRJ4/edit#gid=417044107

I followed this order with the notes, game never crashed during installation process. I putted 4-5 mods and tested it. I got solver engines.

Modlist:
000_FilterExtensions
000_FilterExtensions_Configs
000_Toolbar
000_TRR_Config
AJE
CommunityCategoryKit
CommunityResourcePack
ConnectedLivingSpace
ContractConfigurator
CustomBarnKit
DeadlyReentry
EngineGroupController
FerramAerospaceResearch
Firespitter
FShangarExtender
JSI
KerbalConstructionTime
KerbalJointReinforcement
KerbalRenamer
Kopernicus
KSCSwitcher
MagiCore
MechJeb2
ModularFlightIntegrator
ModularFuelTanks
ModuleManager.3.0.1.dll
ModuleManager.ConfigCache
ModuleManager.ConfigSHA
ModuleManager.Physics
ModuleManager.TechTree
NetKAN
PersistentRotation
ProceduralFairings
ProceduralParts
RCSBuildAid
RealFuels
RealHeat
RealismOverhaul
RealPlume
RealSolarSystem
RemoteTech
REPOSoftTech
RetractableLiftingSurface
RP-0
RSS-Textures
ShipManifest
SmokeScreen
SolverEngines
Squad
SXT
Taerobee
TestFlight
TextureReplacerReplaced
ThunderAerospace
toolbar-settings.dat
VenStockRevamp
WildBlueIndustries
[x] Science!

**Comment by NoMrBond** [comment]
Right, but which versions of each mod are you using.  For example, if I invoke AVC for the version check I get;

KSP: 1.3.1 (Win64) - Unity: 5.4.0p4 - OS: Windows 10  (10.0.0) 64bit
TexturesUnlimited - 1.0.0.8
Toolbar - 1.7.15
Advanced Jet Engine - 2.9
B9 Part Switch - 2.1.1
B9 Aerospace Procedural Parts - 0.40.13
BD Animation Modules - 0.6.4.9
Chatterer Extended - 0.6.1
Chatterer - 0.9.93.1804
Community Category Kit - 2.0.2
Community Resource Pack - 0.8
CommunityTechTree - 3.2.1
Community Trait Icons - 0.1.2
Connected Living Space - 1.2.5.7
Contract Configurator - 1.23.3
CustomBarnKit - 1.1.16
Deadly Reentry - 7.6.2
DistantObjectEnhancement - 1.9.1
DMagic Orbital Science - 1.3.0.10
CapCom Mission Control On The Go - 1.0.2.7
Contract Parser - 1.0.7
Contracts Window Plus - 1.0.8.1
Progress Parser - 1.0.8
EditorExtensionsRedux - 3.3.16
Ferram Aerospace Research - 0.15.9
Firespitter - 7.6
Forgotten Real Engines - 0.7.1
FShangarExtender - 3.5.2
HideEmptyTechTreeNodes - 1.0.1
HullcamVDSContinued - 0.1.8
Kerbal Construction Time - 1.3.9
Kerbal Inventory System - No Fun - 0.1.2
Kerbal Joint Reinforcement - 3.3.3
Kerbal Inventory System - 1.7.6468.41490
<b><color=#CA7B3C>Kopernicus</color></b> - 1.3.1.3
KSP-AVC Plugin - 1.1.6.2
KSPWheel - 0.10.5.23
MagiCore - 1.3
ModularFlightIntegrator - 1.2.4
PlanetShine - 0.2.5.2
Portrait Stats - 1.0.15.1
Precise Node - 1.2.6
Procedural Parts - 1.2.12
RCS Build Aid - 0.9.5.1
RCS Sounds - 5.2
RealChute - 1.4.4
RealFuels - 12.4.1
RealSolarSystem - 12.0
RemoteTech - 1.8.9
RetractableLiftingSurface - 0.1.5
US Probes Pack - 0.68
RSSDateTime - 1.1
SCANsat - 1.1.8.1
ShipManifest - 5.2
SolverEngines - 3.4
SSTULabs - 0.7.39.149
SXTContinued - 0.3.17
TextureReplacerReplaced - 0.5.4
TAC Life Support - 0.13.6
Trajectories - 1.7.1
Kerbal Alarm Clock - 3.8.5
Transfer Window Planner - 1.6.2
VenStockRevamp - 1.9.5
[x] Science! - 5.11

With the updated RP-1dev testing/replacement DLL's from https://github.com/KSP-RO/RP-0/issues/749

Now this (probably) doesn't match your mod list, but when I add the Aerobee engine to the tank (with the above build/versions) I get IRFNA-III/Aniline/Furfuryl as the fueling options

![](https://i.imgur.com/5gLeC1n.jpg)

Which suggests an issue with your mod versions, or DLL mismatch (preventing loading) so please post your ksp.log or version information so this can be investigated.

**Comment by alimoncul** [comment]
Alright its completely my mod install issue.

here is the ksp.log : https://drive.google.com/file/d/1Aw9V__5d8eMeRPwnf7sHV1GmQcPCOYEq/view?usp=sharing

**Comment by pianojosh** [comment]
@alimoncul You have ModularFuelTanks installed. Remove it. It is not compatible with RealFuels.

**Comment by alimoncul** [comment]
removing modularfueltanks fixed the issue. Thank you 😄
