### ISSUE TITLE
Completing 2nd gen weather sat contract fails early weather sat contract.

### ISSUE THREAD

**Issue by ajvaughan** [KSP-RO/RP-0#828]
If you complete a second generation weather contract whilst you still have early weather sat contract then the early weather sat contract is automatically failed.

**Comment by pap1723** [comment]
I don't think that there is a way to stop that from happening. The way the contract has to be written is that the Early Weather Sat contracts are no longer offered / active when the Second Generation Weather contract is accepted. There is no way to stop it from failing. I will however add a note to the contract letting the player know that.
