### ISSUE TITLE
regarding tooling

### ISSUE THREAD

**Issue by Schnobs** [KSP-RO/RP-0#833]
First off, I think tooling is a good idea. However...

Given the number of proc parts on my typical rocket, tooling swamps me with stuff to worry about. Whether it's actually worth worrying about is another matter -- it's there in the menu and demands my attention and a decision. Tooling adds a new circle to the UI hell that is RP-0 and I wonder if it really needs to be as bad as it currently is.

--

User stories:
For my first satellite, i made up a Thor-Able kind of thing. At first I had a decoupler below the AJ-10, followed by a structural piece to adapt diameters. Then I replaced that with an interstage+fairing for the added benefit of offering some storage space for the avionics. The cost difference was quite striking.

After the first flight, I wanted to replace the interstage fairing sides with detachable ones; lo and behold, that's a new part requiring tooling. That's kinda-sorta alrightish, I guess, though I'm a bit disappointed at the lack of carry-over from other similar shaped parts. 

More:
looking at the tooling menu, I noticed one tab saying KzProcFairingSide2ger. Why does it say "ger" at the end, can it really be...?
Yes. Replacing the black-and-white fairing with a plain-white one _of the exact same dimensions_ will require me to purchase new tooling. Puh-lease.

--

Given the cost structure, not tooling any part doesn't seem to be an option. In the above examples, using untooled payload fairings would inflate LV cost by 80%, the interstage by 300%.

If the cost alone isn't reason enough, the inflated construction time surely is: until now, it has always justified expensive tooling even for one-offs. My default reaction is "just tool it all, fer crissakes" and awang has provided me with a button to that effect, for which I'm quite grateful.

Still, is that working as intended?

I'm so not looking forward to the age of space probes where I will needs lots of small but slightly different tank sizes, each of them justified by mission requirements.

**Comment by Schnobs** [comment]
Two things which I think might help:

a) handle fairings by their bases. They have properties for base, max diameter, and length - just use that and don't care which fairing sides are being used (yeah, so one could swap egg-shaped for conic, big deal).

b) blanket tooling that provides for anything smaller than X. If it's vital that people have to tool their sounding rocket decouplers, make it an upgrade that can be purchased later on.

**Comment by aw1621107** [comment]
>Yes. Replacing the black-and-white fairing with a plain-white one of the exact same dimensions will require me to purchase new tooling. Puh-lease.

Apparently this is fixable either by tweaking `toolingType` in the cfgs, or by using PFFE to switch fairing textures instead of having distinct parts with different textures. @NathanKell just hadn't had time to get around to it.

**Comment by Schnobs** [comment]
By and large, the "tool it all" button has turned out to improve matters by a lot. I still think tooling is way too fine-grained -- most of the time I just pay the tax without thinking about it too much, it can't be helped anyway. Only for rather large parts (and cost) do I seriously consider alternatives, but more often than not I end up paying anyway. Which is a long-winded way of saying that for me, it's not having much of an effect other than being a money sink.

Well, I *do* design fairings with room to spare, so there's that.

**Comment by aw1621107** [comment]
>  I still think tooling is way too fine-grained

IIRC the range over which a tooling applies is a percentage somewhere in the RP-0 source, so the easy fix would be to bump that up. It'd screw with balance, though, and could be considered less realistic, because real-life tooling may/may not be that flexible. I'm not the person to make those kinds of decisions.

> most of the time I just pay the tax without thinking about it too much, it can't be helped anyway. Only for rather large parts (and cost) do I seriously consider alternatives

I wonder if that's actually the intended behavior. It might depend on whether tooling is supposed to have equally large relative differences between tooled/untooled parts or whether some parts are supposed to have a much larger relative difference (e.g. difference between tooled/untooled for proc structural parts isn't that large, but fairings are insanely expensive untooled and even more insanely expensive to set up tooling for). If that's the case, perhaps the wiggle zone could be bumped up for the smaller parts, and decreased for the larger ones. That way, you're still forced to think about the parts that matter more, and can worry about the smaller things less frequently.

It'll still be a money sink, but I guess the same could be said about different engine configs -- the different dimensions/stats makes a difference, but you'll have to pay for them.

**Comment by Schnobs** [comment]
> I wonder if that's actually the intended behavior.

I wouldn't mind if it was. That's fine, really, but having just started over I notice that I spoke with a Titan-Gemini mindset. In the sounding rocket era, tooling is much more intrusive and feels quite silly.

> If that's the case, perhaps the wiggle zone could be bumped up for the smaller parts, and decreased for the larger ones.

I think that would indeed help a lot. 

Also, there should be more carry-over between supposedly different parts like structural, fairing and so on.

Maybe by-class treatment? Ballon tanks being sensitive to tiny changes starting at smaller scales, Tank-I the opposite?

Oh yes, and one important thing: the "tool item" shouldn't disappear, but only grey out. As it is, the PAW will change every time you come across a known size, which is quite disturbing.

**Comment by aw1621107** [comment]
>  In the sounding rocket era, tooling is much more intrusive and feels quite silly.

Maybe it's a historical-accuracy-vs-gameplay thing? I need to know more about how tooling worked back then.

> Also, there should be more carry-over between supposedly different parts like structural, fairing and so on.

What parts would you suggest carry-over between? The only ones I can think of off the top of my head are between structural and proc wings, and I don't think the latter even has tooling in the case of B9 proc wings. I don't know about fairings; modern ones apparently can get really expensive, but I have no clue what early ones were like.

> Maybe by-class treatment? Ballon tanks being sensitive to tiny changes starting at smaller scales, Tank-I the opposite?

Historical-accuracy-ly speaking, I guess it depends on how flexible the real thing was. Gameplay-wise, that doesn't sound unreasonable. I don't know enough about RP-0 design to say whether it would be a good fit.

> Oh yes, and one important thing: the "tool item" shouldn't disappear, but only grey out. As it is, the PAW will change every time you come across a known size, which is quite disturbing.

Yeah, I find this annoying too, but at least from the little I remember and what I can dredge up, adding this may not be trivial. IIRC the variable that determines whether a button shows up in the PAW at all is `guiActiveEditor`, and that's a boolean, so no room for graying out there. Looking through the API revealed `guiActive`, `guiActiveUncommand`, and `uiActiveUnfocused`; I don't know what exactly what the first one does, and the other ones are booleans that control whether something shows up for vessels that aren't under control and vessels that are not being currently focused on, respectively, so no luck there either. I wouldn't be surprised if I missed the right variable/method, though.

**Comment by Bornholio** [comment]
Given tool all is in the UI, is this issue still open, still understand the wiggle space argument.

Close?
