### ISSUE TITLE
Communications Satellite contract has unreasonably high payload requirements

### ISSUE THREAD

**Issue by sgrif** [KSP-RO/RP-0#835]
Payloads are a bit of a pain early on since the utilization of service module tanks is so low (this is kinda cool, forces huge satellites early on to look like Telstar). However, this doesn't seem to let up at the point where it should. Once advanced avionics is unlocked, you gain access to the cube satellite bus, which can hold 1500 units of payload, which *should* enable a lot of contracts. However, at that point the payload requirements for the Communications Satellite contract jumped up to **six thousand**. At this point the only other way to hold this is in a Service Module II tank. To store 6k units of payload in a tank that could fit in a period appropriate fairing (e.g. Agena upper stage, 1.5m diameter), the tank would have to be 7 meters long.

The weight requirements for this seem reasonable (e.g. in this case it's putting 1.5t into a Molinya orbit which an Atlas-Agena B should be capable of doing). However, the volume requirements are a bit absurd. Perhaps the density of CommSatPayload should be 4x what it is now? Maybe even higher? The Cube satellite buss has avionics for 3.3t, I'd expect the amount of payload space it provides to be roughly that amount, but right now if I fill it to the brim with ComSatPayload it's only 0.857t.

**Comment by pap1723** [comment]
Thanks for pointing this out! Once we changed the tanks around, it required us fixing these payloads as well. I have taken care of it and the contracts and payload have been updated.
