### ISSUE TITLE
Sounding payload gets filled by pumps

### ISSUE THREAD

**Issue by pianojosh** [KSP-RO/RP-0#837]
If you de-tank sounding payload (maybe other payloads too, haven't tried yet) and have a launch clamp with a pump, the pump will fill the tank with that payload.

Would it be possible to exclude the payload categories from being fed by launch clamp pumps?

Originally filed: https://github.com/NathanKell/ModularFuelSystem/issues/204

**Comment by PhineasFreak** [comment]
These resources should be defined with a **flowMode = NO_FLOW** and **transfer = NONE** (since they are considered hardware and cannot be filled or transferred around). Now, if only i could pinpoint where these resources are defined...

**Comment by pianojosh** [comment]
Found it: https://github.com/KSP-RO/RP-0/blob/Developmental/GameData/RP-0/Contracts/RP0_Contract_Resources.cfg

**Comment by PhineasFreak** [comment]
And we are live!

**Comment by pap1723** [comment]
I pushed and fixed this before I saw @PhineasFreak fix to it! Thanks for finding it out!
