### ISSUE TITLE
Boil-off for the new proc Tank Types are not working as intended

### ISSUE THREAD

**Issue by Karhgath** [KSP-RO/RP-0#847]
I tested boil-off for the 4 new tank types (SM, Tank, Tank-HP, Balloon) for LOX (I assume LH2 will be the same) and found unexpected results.

- SM-III is the worst tank and boils off LOX the fastest!! It has the most insulation so that should not happen.
- Balloon-III has the best LOX boil-off protection (well, slightly better than normal tanks), but in reality should have the least insulation and be the worst.
- Tank and Tank-HP have no difference between them, I assume that's good.

Methodology:

- Created 4 equal size tank (1m x 1m) of each type
- Added dummy empty tanks at each end so that they have the same area exposed
- They have different capacity, but I added 400 units of LOX in each one

Results:

![screenshot103-boiloff](https://user-images.githubusercontent.com/440648/36768018-0e4c0918-1c0b-11e8-84a2-1f1619db9f6a.png)

- From top-left to bottom-right: Tank-III-HP, Tank-III, Balloon-III, SM-III
- The above used timewarp at speed x3 and was after 2.5 days at a 750,000 km orbit around earth. Before that I did 20 minutes without timewarp and had proportionally the same as above, so this is not about the timewarp boiloff issue.

Other results not shown:
- Tank size affects the boiloff - same type, but smaller, will boiloff faster (they have less area exposed... so not sure the physics here) - That might be a RealFuel thing.
- Even a larger SM-III tank with the same exact capacity as the Balloon-III tank (about 40% larger) boiled off faster.

Conclusion:
- Clearly something is misconfigured in the NewRFTanks.cfg file, I will try to investigate further. This is the opposite of how it should behave.

**Comment by Bornholio** [comment]
Thanks, quick question, what branch?  I'll repeat your test in developmental.
One thing to note is make sure you have sepereation on tanks , heat transfer from one component to another is used.  Maybe ask starwaster for a test .dll to place internal and skin current temp in UI.  I've used that before troublehooting explody cryotanks.

**Comment by Karhgath** [comment]
Developmental branch, dated around Feb 25-26th (not sure of the date).

I tested individually and all together as above, in different orders, and I did not see any change in general behavior.

Yeah, I checked thermal, convection and all - they all looked similar in terms of heat, I made sure to align so that the sun was hitting the thanks perpendicularly.

I'll come back to this bug later this week and check if I can find any other red herring.

**Comment by pap1723** [comment]
@Karhgath Did you ever figure this one out?

**Comment by pap1723** [comment]
Is the issue the Tank Types or Real Fuels?

**Comment by Bornholio** [comment]
RP-1's modification does not affect boiloff values.  If still a problem its on RF.

`+PART[proceduralTankRealFuels]:FOR[RP-0]
{
	@name = RFTank-III-Balloon
	%RSSROConfig = True

	@title = Tank, III (Balloon)
	@manufacturer = Generic
	@description = Level III Balloon Tank. Balloon tanks are expensive and complex as they need to be pressurized at all times, but they are much lighter than regular tanks. These are similar to tanks used on the Atlas and Centaur stages. <b><color=green>Min Utilization: 99% - Max Utilization: 100%</color></b>

	@maxTemp = 773.15
	%skinMaxTemp = 873.15

	!MODULE[ModuleFuelTanks] {}
	MODULE
	{
		name = ModuleFuelTanks
		volume = 1060
		utilizationTweakable = true
		minUtilization = 99
		utilization = 100
		type = Tank-III-Balloon
		typeAvailable = Tank-III-Balloon
	}
	MODULE
	{
		name = ModuleToolingPTank
		toolingType = Tank-III-Balloon
		untooledMultiplier = 0.25
		finalToolingCostMultiplier = 1.25
	}
	@MODULE[ProceduralPart]
	{
		!TECHLIMIT,* {}
		TECHLIMIT
		{
			name = start
			diameterMin = 0.01
			diameterMax = Infinity
			lengthMin = 0.01
			lengthMax = Infinity
			volumeMin = 0.001
			volumeMax = Infinity
		}
	}

}`

**Comment by Bornholio** [comment]
Lets close this for now, if anything re-open one in RF
