### ISSUE TITLE
1956-1957 Orbital Rocketry reliability accuracy

### ISSUE THREAD

**Issue by pianojosh** [KSP-RO/RP-0#852]
I know our early generation rockets were unreliable, but the current failure rate for this node feels far too punishing. I don't have any data to back this up, but I have set up launchers with the following specs:

Booster stage: 3x LR79 or 3x LR89
Sustainer stage: 1x LR105
Upper stage: 1x AJ10

All using their 1956-1957 Orbital Rocketry configs. All were fully researched, and the LR79/LR89 and AJ10 were at full (10,000) data. The LR105 was between 3,000 and 7,000 data (increasing as the launches proceeded).

I've done 10 launches of that launcher, and only 1 proceeded with no engine failures of some kind. 3 had an LR79/LR89 fail to ignite on the pad, 2 had a loss of thrust from at least one LR79/LR89, two had the LR105 fail to ignite, one had the LR105 shut down early, 1 had the LR105 loss of thrust, and 2 had the AJ10 fail to ignite. Some of these failures overlapped. Not all launches even got to the LR105 or AJ10 ignition attempt, depending on earlier failure modes.

Upgrading all engines to their 1958 Orbital Rocketry improved their reliability significantly, with 7 or 8 out of 10 launches being full success.

Is this failure rate intended?

**Comment by NoMrBond** [comment]
The success rates for launches of that era were indeed quite poor.  Atlas-B's record was 1 success for 7 launches in 1958, increasing to only 3 successes for 11 launches overall.

https://en.wikipedia.org/wiki/SM-65_Atlas#Launch_history

**Comment by pianojosh** [comment]
Yeesh, that is worse than I thought. And you'd certainly expect my results to be worse, given the higher number of engines and in-flight ignition events.

I suppose there's also an open question regarding on-pad failures, since any list would not include as a "failure" a launch attempt that never left the ground, as long as the failure was benign (ignition failure vs. explosion).

Still, that pretty well demonstrates that the failure rates I'm seeing are within reasonable expectations based on that data. Thanks.

**Comment by NoMrBond** [comment]
I way to deal with on-pad failures now that roll-out costs are in would be nice (refresh ignitions etc for non catastrophic failures / failures to ignite etc) , but apparently there is not a nice way to handle that (yet) but the issue is on the dev radar (I asked NK about it during one of his streams).

**Comment by pianojosh** [comment]
For sure. ~10k funds for each failure is really the killer for these early launches, and the lost time, not the cost of the vehicle itself.

**Comment by pap1723** [comment]
It is a cost vs benefit that needs to be weighed. There is a reason that
there were not a lot of clustered engine launches by the US in the early
days. More engines = more complexity = more failures.

The cost vs benefit is that, sure, you might be able to get more payload
into space with a larger LV with multiple engines, but there is a good
chance you are going to fail. Smaller payloads with simpler LVs is usually
the way to go.
