### ISSUE TITLE
no initial tech purchase costs for NK-9 engines

### ISSUE THREAD

**Issue by glilienthal** [KSP-RO/RP-0#860]
I just researched those engines, and didn't have to pay anything for it when activating them in research.

**Comment by Schnobs** [comment]
Many of the later engines seem to have no purchase price. Astris, Apollo SPS, several Nukes...
In case of the SPS engine (AJ10-137) the game crashes when I try to unlock them. Not sure if related.

For most engines, I can give them a cost by editing ECM-Engines.cfg, but this doesn't work for SPS.

**Comment by pap1723** [comment]
Fixed.
