### ISSUE TITLE
Pioneer and Voyager Antenna

### ISSUE THREAD

**Issue by glilienthal** [KSP-RO/RP-0#861]
If I see correctly RP-0/1 doesn't support the Pioneer and the Voyager antennae (anymore?) This makes journey to Jupiter obviously difficult. What is missing there? Can I help?

**Comment by PhineasFreak** [comment]
No, they are supported but they are missing the cost parameters: https://github.com/KSP-RO/RP-0/commit/c6cdfbd44e0fec4fa81db43048caa64f88d55f24

**Comment by droric** [comment]
I have submitted pull request 899 to address this issue.  This can probably be closed out.

**Comment by Bornholio** [comment]
close me :)
