### ISSUE TITLE
KSP 1.31 compatibility

### ISSUE THREAD

**Issue by Rex1812** [KSP-RO/RP-0#863]
I love RSS/RO/RP-0 and I just upgraded RO and RSS from 1.2 to 1.3 for the extra bodies etc. Will the current version of RP-0 work with RSS/RO 1.3 -- will it install correctly with Ckan?
 
Thanks to all the developers for their hard work!

**Comment by PhineasFreak** [comment]
Not the current but the [Developmental (RP-1)](https://github.com/KSP-RO/RP-0/tree/Developmental) one will do the job. For now, you will have to download and install it manually though.

When RP-1 is officially released then it will be available on CKAN just like all previous releases.

**Comment by Rex1812** [comment]
Thanks that

**Comment by PhineasFreak** [comment]
No, RP-0 and RP-1 are the same thing. It is unofficially called RP-1 because of the total overhaul that the mod received.

**Comment by Bornholio** [comment]
Yes hope to see at least RP-0 release soon.  I'm updating things I can for RP-1
If RP-0 is lightweight, then RP-1 is heavy weight :)

**Comment by Rex1812** [comment]
Thanks- I tested your Developmental RP-1 Mod this weekend +/- kerbal construction time & remote tech. I love your tech tree, contract progression, and scientific instruments.
  As you know small adjustments in kerbal construction time settings have a massive effect on gameplay- with the suggested RP-0 times, I wasn't doing any manned orbital missions before 1975. Although, I am also still not sure how tooling tank thing helps /works.
Do you have different construction time settings for RP-1?.... Are the engine tech prices finalized?  Is it possible to build more than one rocket at once or have quicker builds of the same basic vehicle? Are you going to include an early two crew aircraft cockpit?

BTW-I had to use the American rockets (Atlas lower +/- AJ10 upper stage) for early manned / luna missions as the RD-107 & verniers is unstable. Also, none of the antennas are in range for Pluto in the latest RO update.

**Comment by pap1723** [comment]
Thank you for the notes. This is much the same as the experiences we have had as well. It is a much different experience even from RP-0. Watch some of the YouTube videos on it if you are still playing and interested.

**Comment by Rex1812** [comment]
To pap1723 - I was attaching the RD-107 verniers wrongly ..my bad... also I just ended up making my own KCT settings.
