### ISSUE TITLE
Performance degradation

### ISSUE THREAD

**Issue by DocRockwell** [KSP-RO/RP-0#871]
At some point in the 1970's my game performance becomes awful, this is especially noticeable with craft in orbit of Venus and the Moon, where instead of the usual smooth 40-60 fps, I get 15-20 fps with time dilation (yellow clock). This has happened on two separate RP-1 careers, which hadn't exhibited any problems on earlier missions to these bodies.

I've tried a bunch of things, such as deleting older vessels (left about 20 vessels, including half a dozen RT relay satellites and a few probes landed on the moon), turned off SCANSat scanners once they completed, set debris to 0, pruned parts and mods I could do without, reinstalled KSP + mods (fresh KSP 1.3 download, used Theysen's RP-1 game data folder), even bought new ram modules for my computer.

I'm not certain that this is caused by RP-1, but I'm really at a loss as to what is causing this or how to fix it. I don't want to start another career and grind through the first two decades only for this to happen a third time.

**Comment by MikeOnTea** [comment]
Maybe you can find the causing mod by removing mods and measuring performance. In my game, remotetech seems to cause a major slowdown, for example.

**Comment by pap1723** [comment]
This is an issue that is going to be caused by many things, most likely things like RemoteTech when you have a lot of satellites in orbit. Unfortunately, there is nothing we can do as RP-1/RP-0 does VERY, VERY little that would cause it.
