### ISSUE TITLE
Avionics Problem

### ISSUE THREAD

**Issue by Brummi1234** [KSP-RO/RP-0#876]
I have found an issue with avionics on parts,
that have crew capacity and the module command
and that are not listed in the avionics.cfg
(Noticed it on the RN Soviet Spacecraft and Salyut parts)

If you place, for example the soyuz descent module, in the VAB
and look up the RP-0 avionics window it says something like:
Supports: 0.000t
Vessel:  2.799t
Avionics are sufficient!

If you do the same with the progress part (no crew capacity but module command) 
from the same part pack  or a station part (crew capacity but no module command)
it displays correctly "Insufficient Avionics".

So i put a part avionics part on the soyus spacecraft, so it has unmanned command 
capability, but still less supported avionics than the vessel has and placed it in orbit
(without crew) and still had full control over it.

My question now is, is this intendet to be like this? And if not, how to fix it.

Please excuse my english, non native speaker over here.

**Comment by ec429** [comment]
I believe what's supposed to happen is that crew cabins provide a certain amount of avionics iff occupied (for instance, a Mercury pod can control itself plus retro packages etc., but not an entire Atlas).  But I'm not sure what's going on when it displays 0t; possibly in that case it is providing unlimited control?  (That would be a config error.)  Maybe see what happens when you add more mass to the vehicle, whether the avionics cease to be sufficient at any point?

**Comment by Brummi1234** [comment]
Well, i tried increasing the mass of the craft, launching it crewed and uncrewed, with an additional avionics pack (still less supported than the vessel is) and without. Always the same thing happens, it displays 0t (or some amount, but less than the vessel) but i can control it just fine.

What i maybe forgot to mention, the parts i had this problem with, are not in the avionics.cfg at all.
So what should happen (to my knowlegdge), is, that they should not have avionics at all.
If i add some amount of avionics to them with a mm config, everything behaves exactly as expected.
(avionics are sufficient to the set amount, but nothing more)

The strange thing here is that parts without an avionics module added via config default to unlimited 
mass avionics.

**Comment by PhineasFreak** [comment]
This is a safety fallback for parts that are not corectly configured, it is not a bug per se. If a part does not have avionics defined in the config then it will have unlimited mass support. Usually, parts that are configured for RP-0 are also configured for select avionics limits. Some of them manage to slip through though so you get parts like the one you are using.

**Comment by Brummi1234** [comment]
Thank you for your answer, this clears things up for me.
I did a PR to add avionics to the parts i mentioned.
