### ISSUE TITLE
LR79 config and testflight concerns

### ISSUE THREAD

**Issue by Herrkurt** [KSP-RO/RP-0#879]
The LR79 unlocks with the S-3 config but not the S-3D, which requires '58-'59 Orbital Rocketry, and the way this configs are built an engine capable of lifting the Thor DM-18, which flew in '57 is not available in the '56-'57 tech node.  This should be amended.  There is a lot of confusion in the sources (I relied primarily upon astronautix http://www.astronautix.com/l/lr79.html ): the S-3D and LR79-7 are given a first flight date of 1957 while the S-3 is given a first flight date as being 1958, but then the LR79-7 and S-3 are given the same thrust figures while the S-3D is given a lower sea level thrust and no numbers for vacuum thrust.  The Thor DM-18 which started flights in '57 is given the higher thrust figure and is said to have used the LR-79-7.  The Juno II is listed as having the same thrust with the S-3 engine and also a longer burn time than the rated number given by testflight by 17 seconds.  The S-3D's only listed vehicle is the Jupiter IRBM.  According to Heroic Relics the Thor engine is only occasionally called the S-3D and rather than the LR-79-7 or S-3 http://heroicrelics.org/info/s-3d/s-3d-overview.html .  What is clear is that the LR79-7 and Thor DM-18 are agreed to launch in 1957.  The S-3 as modeled in the configs cannot launch a Thor DM-18 (burn time well over 3 minutes and SLT of 1.08).  The variant which is given a lower thrust is probably the S-3D although it is possible the S-3 and S-3D are greatly confused.  According to Heroic Relics the main differences are actually in "primarily in the more precise thrust control system of the Jupiter engine and the use of ground-mounted start tanks on the Jupiter rather than the engine-mounted Thor tanks".

My conclusion is that one version, S-3 or S-3D, with lower thrust was used on the Jupiter IRBM but both were available at the same time.  The engine for the IRBM may have flown later because of development time required for the missile it was to be tested with.  The military missiles were also produced in larger numbers, perhaps lengthening the development cycle.  Whatever the reason an engine with the thrust to lift a Thor DM-18 existed in 1957 and so should appear in the '56-'57 Orbital Rocketry node.

**Comment by pap1723** [comment]
We made a decision that no engine variants should open up in the same node. It stops the progression as the earlier engine would be completely skipped everytime. There is an LR-79 that opens up in that mode already, isn't there?

**Comment by NathanKell** [comment]
I'd trust Ed Kyle most on this.
https://forum.nasaspaceflight.com/index.php?topic=40733.40

**Comment by Herrkurt** [comment]
I didn't know about that source.  Very informative.

**Comment by pap1723** [comment]
Close me?
