### ISSUE TITLE
Updated Tech Tree spreadsheet

### ISSUE THREAD

**Issue by phantomc3po** [KSP-RO/RP-0#883]
Hello, I'm wanting to add some pricing to parts that are missing them, but the spreadsheet seems to be behind the current version of the TREE-Parts.cfg Does anyone have a more up to date copy that I can use so that it doesn't replace all the recent updates?

**Comment by pap1723** [comment]
Phantom,

Do you know what specifically is different? It should not be different as I
believe I was the last one to push the parts file.

**Comment by phantomc3po** [comment]
Hey Pap,
I was looking through the history of changes you did on March 6 and comparing them to the spreadsheet. a couple of examples are the tarobee aerobee parts have moved from unlock to either earlyRocketry or postWarMaterialScience. Another is the bleudog Juno engine has changed from 650 to 300 cost. These changes are still their old values on the spreadsheet.
I don't think that spreadsheet got updated when you did your cfg update, it's last update was August 1 last year.

**Comment by phantomc3po** [comment]
@leudaimon, I noticed that you made a .csv copy of the parts tree, just wondering if you point me in the direction of the google sheet you used to make it from. It would save me going through line by line on the spreadsheet on here to make the changes so it matches the latest version

**Comment by leudaimon** [comment]
@phantomc3po I'm not sure I understand your question... I used a personal copy of @pap1723 's spreadsheet (https://docs.google.com/spreadsheets/d/1TzHCbEYIPNUJzhtObiY6IMtkRk_njqG_sXtrCTNVvz4/edit?usp=sharing), but afaik the csv is not updated compared compared to the current config files. My hope when I set up the csv was that it would be linked with pap's spreadsheet (google sheets can read remote files directly and automatically), so that all changes to the csv would automatically be changed in the spreadsheet.
However, I haven't been involved here or on irc much, so I don't know what route this took.

**Comment by pap1723** [comment]
@leudaimon Do you know how to make Google Sheets automatically pull from a CSV file?

**Comment by leudaimon** [comment]
@pap1723 I had set this up before... in that linked version in my previous message it has uses the following command in place of the "Parts" sheet in Google Sheets
=IMPORTDATA("https://github.com/leudaimon/RP-0/raw/RealEngines/Source/TechTreeParts.csv")
You will probably have to adjust this to the correct path in the official RP-0 repo to make this work in the "real" Google Sheets

**Comment by leudaimon** [comment]
@pap1723 did you figure this out? I guess it's an important part of making the tree more generally editable, right?

**Comment by pap1723** [comment]
Hey leu! We decided to go a different route. One of the guys we wrote a
program that converted the spreadsheet into JSON files that will be stored
on git. Those files can be manipulated through a web GUI that he wrote that
has filtering / editing capabilities similar to the Spreadsheet.

It is a really well done and controlled environment that is perfect for our
needs.
