### ISSUE TITLE
RP-1 Kerbonauts retirement rebalance 

### ISSUE THREAD

**Issue by kurgut** [KSP-RO/RP-0#885]
Hi, I think the retirement for the astronauts comes to early and quicly, as I don't have the tech in early career to provide them great missions, it forces me to make regular sub-orbital flights in X-1 to make them retire later, so it's slowing more my game/tech/contrats progression, and finally unendable. Or maybe I don't the play the right way?
Thanks :)

**Comment by kurgut** [comment]
Ok, I was playing the bad way, not the right tech progression, and too much focusing on astronauts, I dismissed two of them at the start, and it's fine now, I can keep jebediah :) Sorry for disturbing.

**Comment by glilienthal** [comment]
An option to set the quickness of retirement would be great!

**Comment by kurgut** [comment]
my error was to want keeping the longest possible,  but just look at real life, the mercury astronauts didn't flew on Appolo, so now at the beginning I dismiss two astronauts because I don't need them, and I keep them active during x-1 and mercury program, then they can go :) And hire other one to the gemini program, etc, actually those settings are pretty well balanced in fact :)

**Comment by NoMrBond** [comment]
Virgil I. "Gus" Grissom was a Mercury astronaut who would have flown on the
first manned Apollo program mission if not for the Apollo-1 incident, and
Walter M. "Wally" Schirra Jr. was a Mercury astronaut who flew on Apollo-7

**Comment by ec429** [comment]
Sure, but they weren't Astronaut Class of '51.  Kerbonauts hired in 1959 (as per Mercury) who get a single orbital flight won't be retiring until about '71 (iirc), so the current balance is OK.
(There _are_ problems with 'nauts vanishing from the roster long before they're due to retire, but I haven't filed a bug yet because I can't prove it.)
