### ISSUE TITLE
SRBs too expensive compared to liquid boosters

### ISSUE THREAD

**Issue by MikeOnTea** [KSP-RO/RP-0#893]
So, i was a bit shocked at SRB prices (in RP-1/Developmental), and thus did a little comparison. Test vehicle was a Titan 1 like rocket with 7.7t lead ballast. All parts tooled. For the SRB test, i attached two 100 inch SRMs with decouplers. For the liquid booster test, i attached 4 more titan 1 first stages, again with decouplers. To get similar performance, i reduced the fuel level of the liquid boosters. Both rockets used identical staging, the center engine is only lit after the boosters decoupled.
Results:

X|2 100 inch SRM boosters|4 Titan 1 core LR87 boosters
-|-----------------|-----------------------------
**Delta V**|8990 m/s|9055 m/s
**Mass**|344 t|296 t
**Sea level TWR**|1.77|1.84
**Build time**|49.5d|36.5 d
**Part costs**|20,213|8,481
**Rollout costs**|25,873|20,672
**Total costs**|**46,086**|**29,153**

Even rollout costs alone are higher for the SRB version, probably because the stark difference in part pricing. This makes SRBs so expensive as to more or less be useless, i guess. There must be something wrong with this pricing? Maybe liquid stages got too cheap with tooling? Opinions and even more so facts welcome. :)

Screenshots and part files attached:

![screenshot4](https://user-images.githubusercontent.com/11480934/45047368-29959380-b079-11e8-8bae-11a7fe65ad4c.png)
![screenshot7](https://user-images.githubusercontent.com/11480934/45047369-29959380-b079-11e8-91dc-caae59d493a3.png)

[craftfiles.zip](https://github.com/KSP-RO/RP-0/files/2349600/craftfiles.zip)

**Comment by MikeOnTea** [comment]
https://ntrs.nasa.gov/archive/nasa/casi.ntrs.nasa.gov/19720007149.pdf estimates the recurring cost of an UA1205 at 2.414 million 1972 dollars.

**Comment by glilienthal** [comment]
I really like the idea to make SRBs more competitive.

**Comment by pap1723** [comment]
This makes a lot of sense, would you be willing to run a few more tests? From my understanding on it, SRB's are used because they are MUCH cheaper than liquid fueled stages. The whole point of NK introducing rollout costs was to make them a viable option. I would like to see there not be as significant of a decrease in build time, but instead in rollout costs.

**Comment by pap1723** [comment]
I would choose the last option as the best setup. I feel like the H-1 might
be OP for the cost.

**Comment by MikeOnTea** [comment]
Yep, exactly my thoughts, i think the last option looks pretty good. I also think the H-1/E-1 balance looks a little off, because the H-1 at 200 funds is super cost effective, but it's "big brother", the E-1, is super expensive at 1,300 funds/6.5 times the cost while only providing about twice the thrust. The E-1 is also alot more expensive than the LR-87 versions despite similar performance. Without checking historical sources, i feel like the H-1 would be better balanced around a cost of 250-280, while the E-1 might slot into the 600-800 region? But it might be better to open a separate engine pricing issue to track/discuss this.

**Comment by pap1723** [comment]
This was fixed by d0941db2f9a6e246aab758427dcdccd5e30f7281
Eventually we will need to rework all of the costs to balance the rollouts for all types of parrts.

**Comment by MikeOnTea** [comment]
Updated for the latest pricing changes, SRBs are again more expensive:

X|4 LR87 boosters|2 100" SRBs
-|-----------------|-----
**Build time**|51.6 d|36.6 d
**Part costs**|8,731|16,271
**Rollout costs**|21,825|16,459
**Total costs**|**30,556**|**32,730**

**Comment by NathanKell** [comment]
More discussion in discord /w Mike. Solid propellants were adding to costs, and the 100-inch boosters were over-cost. Think we're good now.
