### ISSUE TITLE
Mission time counter only works if vessel is in focus

### ISSUE THREAD

**Issue by madaraszvktr** [KSP-RO/RP-0#894]
I'm trying to accomplish one of the targeted moon landing missions in RP-0 career, using the Saturn V parts from the FASA mod. I had no trouble doing the normal moon landing, but I have two bugs now which seem to make the mission impossible.

The first problem is that I have to stay on the moon for a day and a half with the lander, and the counter for the mission only works if the lander is the active vessel. This wouldn't be too bad, as I could just warp time with the landed vessel in focus. The second problem is that the orbital module (service module+command module) runs out of oxygen if it's not the active vessel. Normally it generates enough oxygen for 3 people, but it runs out of oxygen in a few hours with a single guy in it if it's not the active vessel. If I switch back to it when I get the oxygen depleted message it has a full oxygen tank, but if I don't the crew dies. Switching away from the lander however restarts the mission timer. It seems like the only way to accomplish the mission is to sacrifice the guy in the orbital module.

**Comment by pap1723** [comment]
I don't know if this can be fixed. I believe it to be a limitation of Contract Configurator, but I will ask some questions.

**Comment by Bornholio** [comment]
the new background resource functions of TACLS post 1.3x should fix half your problem

**Comment by pap1723** [comment]
Not much we can do here to be honest. Things work great with ROKerbalism though.
