### ISSUE TITLE
Hidden parts

### ISSUE THREAD

**Issue by Uaessuor** [KSP-RO/RP-0#898]
Hi, I have a big problem with RP-1. A lot of the shares are hidden and I do not want it. How can I make them appear normally?

**Comment by droric** [comment]
Uaessuor,

Could you clarify what you mean by 'a lot of the shares are hidden and I do not want it.'?  Do you mean to say parts are not showing in RP-1?

**Comment by Uaessuor** [comment]
yes it is. Sorry for my week english.

**Comment by Uaessuor** [comment]
on 1.3.1

**Comment by GavJenks** [comment]
I have found this as well. For example, the KAS wrenches. Things like this would do better in a non RO special clearly labeled section in the VAB (like the old version with the radioactive icon) rather than hiding entirely.

**Comment by droric** [comment]
Could you try to use filter extensions?  You may be able to see the non-rp0 parts.  Either way they won't function properly in the mod so I am not sure what the end goal is here.  The parts need to have config files that support the mod and if they don't you may not be able to use them.  I think this is going beyond the support that RP-0 will provide since RP-0's goal is to provide support for the mods listed on the wiki and if they are not listed you could work on making configs for them and submit them to RP-0 as a pull request.

**Comment by pap1723** [comment]
The parts are not hidden, they do not exist in the tech tree.

The tech tree does not use any nodes that are named the same as vanilla
KSP. That means that if parts are not explicitly added to the tree, they
are not on it.

**Comment by PhineasFreak** [comment]
Idea for a tree "enhancement": add a single, separate tech node called "Orphans" (not linked to any other tech node) and point all non-RP parts to that node using a simple MM script (we already have the last one in place for tagging the parts).

**Comment by pap1723** [comment]
That is a good idea I think.

**Comment by pap1723** [comment]
@PhineasFreak what was your idea for that Orphans node? I do not want it to be unlocked from the start as then there are a CRAZY amount of parts that it would unlock.

**Comment by PhineasFreak** [comment]
Just having the tech node in the tree, not linked to anything else. I was thinking that since they are not/half balanced for RP there would be no reason to lock it behind other artificial nodes/requirements. If someone wants to use NON/WIP-RP parts then so be it.

**Comment by Bornholio** [comment]
I plan on making a final patch to run and put anything that still has CTT or stock nodes in :orphans:  but i think it may be a very heavy process so i don't think it should be rolled in. Won't post anything till next weekend earliest.

**Comment by pap1723** [comment]
Part of #931
