### ISSUE TITLE
Earth Observation Imaging Satellite timer 

### ISSUE THREAD

**Issue by rsparkyc** [KSP-RO/RP-0#902]
If I've accepted the Earth Observation Imaging Satellite contract, but then launched another vessel before that one, the one day timer starts, and then expires, failing the contract.  The timer should probably start once a craft with a camera is in orbit (or should there even be a timer?)

**Comment by pap1723** [comment]
This contract needs to be removed. It is bugged and Contract Configurator
cannot process it correctly.

**Comment by Tidal-Stream** [comment]
Issue #850 is related.

**Comment by rsparkyc** [comment]
closing as duplicate
