### ISSUE TITLE
RaiderNick's R7 Block A engine (RD-108) is missing from the tech tree

### ISSUE THREAD

**Issue by m4gus88** [KSP-RO/RP-0#918]
Part name rn_r7_blok_a_engine.
Interestingly enough, it's in the Tree.xlsx, but not in TREE-Parts.cfg

Looks like it was removed by this commit:
https://github.com/KSP-RO/RP-0/commit/e5d276cd35d105794e10dcdcf6148ce5c42bdb77#diff-ef60dfbca03aae6e814c78007999f2f7

**Comment by pap1723** [comment]
Fixed with 3a46171106b85b4a7f764f70a07193f69ebaf88c
