### ISSUE TITLE
Crazy KCT Launch Pad Ideas

### ISSUE THREAD

**Issue by pap1723** [KSP-RO/RP-0#935]
So I had an idea to do some crazy things with launchpads and completely change how they work, but I am going to guess that this is a much bigger change than we can handle. Anyway, here is the idea...

**Custom Launch Pads**
The player chooses some settings that will set the cost of the launch pad development. Actually, I think we could use the different levels of launchpads in CBK and just set which one is being used based on what the user decides.

Essentially instead of choosing to upgrade an existing launch pad from one level to another, the player chooses the supported mass of the launchpad. So if there are the 7 levels we currently have, when the player clicks on build a Launch Pad, they then select what size.

On top of those options, it would be great if the player could choose some upgrades or downgrades. I don't know exactly what they should be called, but something like this:
* Increased Support Staff = Faster Rollout Times, Faster Reconditioning, More Expensive Rollout Costs, More Expensive Maintenance
* Horizontal Integration = Faster Rollout Times, More Expensive Rollout Costs, More Expensive Maintenance
* Vertical Integration = Cheaper Rollout Costs, Longer Rollout Times (The crawler has to move slower?)

**Comment by Bornholio** [comment]
yes please

**Comment by pap1723** [comment]
Added a few upgrade ideas, would love some more ideas!

**Comment by ec429** [comment]
I would like this, but with "input your GLOM limit" rather than "choose from these 7 sizes", just because I'm bored of exploring the optimisation space for 60t and 150t GLOMs, and want to try some engines etc. that just don't fit those sizes nicely.

As for upgrades:

* Crew Access Arm.  Needed for manned launches, but pushes up the pad build cost.  Probably no effect on rollout.
* Cryogenic Storage Tanks.  Needed for vehicles using LH₂.  Again, more expensive to build but no need for a hit to rollout because the vehicle will already suffer that.

Also I'm not convinced that Horizontal Integration should have higher maintenance costs than Vertical; I think a TEL is a lot cheaper to maintain than an equivalent crawler.  Same probably goes for the buildings.  Then again if we want building maintenance costs to matter for anything then they need to be increased a *lot*.

**Comment by NathanKell** [comment]
Unless things have changed, you'd have to
(1) rewrite KCT to support force-setting a pad's limit right before calling KSP's launch code (if KCT does? I think it does)
(2) change our maintenance code to check the stored-in-KCT pad value, not the "building level" pad value
(3) Do what KCT does when it sets pad level to create an arbitrary pad level.

Note that any other mods that check facility level would of course be wrong.

I see no technical reason for this to be impossible, just...hard. :)

**Comment by NathanKell** [comment]
The traditional problem with this is detecting what collection of parts is
"the same LV"

**Comment by norcalplanner** [comment]
Maybe just increase the number of steps in the launch pad sizes, up to 15 or 20.  That should provide enough fine-grained design opportunity to build 40 and 80 ton rockets.  There could also be "reduced support staff" for pads sizes you want to keep around but don't use that often as your program progresses.

**Comment by RoboRay** [comment]
Would things like launch-pad staffing levels and types of transporter/erection equipment (affecting roll-out costs and speeds) be easier to handle in the Admin Building as policies?

**Comment by m4gus88** [comment]
I think KCT must have some kind of craft comparison logic to recognize the amount of changes when editing a vessel. It could be possible to build launch pads to launch vehicles based on the percentage difference calculated by KCT, and having a limit, for example a max. 10% difference counts as the same LV.

Of course there's still the matter of recognizing what's the LV and what's the payload.

**Comment by NathanKell** [comment]
Its detection logic is literally "does the new stack cost the same as the old stack", no more. So...not really useful here, when the payload is a large chunk of the cost. :\

**Comment by siimav** [comment]
Most of those ideas should now be a lot easier to implement with #1580

**Comment by pap1723** [comment]
Most of this is already done and being implemented in Launch Complexes. Closing this for now.
