### ISSUE TITLE
KRASH config does not apply

### ISSUE THREAD

**Issue by leudaimon** [KSP-RO/RP-0#936]
I think there is something missing in the MM call for this:

https://github.com/KSP-RO/RP-0/blob/44ad20864f83f8263092d7ce20f8510d8bc47784/GameData/RP-0/KRASH_Settings.cfg#L1

I tried to add :FOR[RP-0] in the end of line 1, but still had no success.

**Comment by PhineasFreak** [comment]
I do not think that it is possible to edit that, as it is placed under the "PluginData" directory: https://github.com/linuxgurugamer/KRASH/blob/master/GameData/KRASH/PluginData/KRASHCustom.cfg

Now the question: can we convince LGG to move that file outside of "PluginData"?

**Comment by leudaimon** [comment]
Hmm, thanks @PhineasFreak for the info.
Is there any reason why he would resist moving it to make it changeable? It's kind of silly not to allow MM to act on the file that looks made to be the integration with other mods.

**Comment by PhineasFreak** [comment]
Probably that stupid "crusade" against ModuleManager reloading the cache when a change happens in the GameDatabase. There is a whole thread in the KSP forums for that (funny that they recommend using the PluginData directory **outside** of GameData, considering that these folders are deprecated and could be removed at any time...)

**Comment by pap1723** [comment]
Information added to the Install instructions. Not much we can do if the Mod Author doesn't allow it.
