### ISSUE TITLE
Fixing weird parts in hydrolox

### ISSUE THREAD

**Issue by pjf** [KSP-RO/RP-0#94]
Raised in #57. Right now the hydrolox node contains all the IR parts and other things, because it used to be construction. Ideally we should place all these, but if the player installs new mods they may still end up with unplaced parts in odd spots.

This ticket is to track work fixing this.

The aerodynamics node doesn't have much value in RP-0, since they're all things we'd expect to be available early on, but I'm happy for this to be argued otherwise.

---

Possible solutions:

**Change the "Hydrolox" node to overwrite the Aerodynamics node, rather than the construction node.**

- This will break saves.
- The construction node was chosen because of its relations (nodes that it depends upon, and vice-versa).

**Leave hydrolox where it is, and repurpose aerodynamics.**

- I like this more.
- This leaves us with some odd node IDs for what they contain, which is unfortunate.

- [ ] Sweep all parts from aerodynamics to somewhere else (orphans?). Aerodynamics seems to be a bunch of stuff which isn't that hard.
- [ ] Rename the human-readable Aerodynamics label to be (Advanced) Construction.
- [ ] Sweep everything from Hydrolox to new the new construction node.

**Something else?**

- Is there another node we can sweep parts into? If so, we can just do a straight sweep and be done.

**Comment by NathanKell** [comment]
I assume you mean node strings? Construction was chosen because there's a nice, well-lined-up line of nodes running from tier 3 all the way to the final tier of the tree, and all of them get changed.

We actually do need the aero string of nodes, for X-planes and (later) true spaceplanes, so I don't think we can just replace that whole string.

**Comment by pjf** [comment]
Sweeping parts into the unmanned tech line. It's not like it's something we'll use much of otherwise.
