### ISSUE TITLE
Crew Training Settings

### ISSUE THREAD

**Issue by pap1723** [KSP-RO/RP-0#942]
This is a continuation of the conversation from this Pull Request: https://github.com/KSP-RO/RP-0/pull/925

I have closed the pull request as we are cleaning up the old Branches to streamline the Repo. Here is the conversation:

@siimav 
Based on the feedback of RO Discord, make proficiency trainings no longer expire and remove mission trainings. This commit also removes all code that's related to training expirations.

Test DLLs are available here: https://github.com/siimav/RP-0/releases/tag/dev3
But be sure to back up your save before loading a game with these DLLs.
It looks like my changes will cause the training expiration blocks to be removed from saves. So even after going back to old DLLs, all trainings would still lack expiration dates.

---

@NathanKell 
hashtag DELURK Quick note: I think proficiency training not expiring makes a lot of sense, but I'm leery of removing mission training because the point of having it at all is so that you can't do instant launches. In particular, without mission training, it's possible to keep a built LV ready to go on the pad and launch a rescue (or other crewed mission) just-in-time, rather than having to plan ahead.

What's the major gripes people have with mission training?

---

@RoboRay
The only issue I have with Mission Training is that I can't schedule it to begin on a specified future date... I can only start it now.

If it's July and a vehicle will be ready to roll out in mid October, I have to be careful to not blow past the date I need to start training on, or manually set up a KAC reminder. In reality, I would just tell the crew and instructors in July to start training in early October and not need to worry about that anymore.

If the training system could generate KAC or stock event system reminders, that would help eliminate the need to babysit the calendar while timewarping or doing other missions.

I do find that Mission Training adds another layer of planning to the game and think it's worth saving. I just find it tedious to use as implemented right now.

---

@lpgagnon 
For me, the worst feature of mission training is that it gets lost on a launch failure. Now that launchpad ignition failures can be disabled, that's greatly mitigated; but it still makes no sense to me that the astronauts need to train again for the "same" mission if the first one only gets 2km up.

---

@NathanKell 
Should be able to not clear training on recovery if MET was below threshold?

---

@pap1723 
@NathanKell here is a different approach to the question...Looking at the code, you pretty much already have the constraints built in with the Training Time limit of (is it 120?) days and also the mandatory inactivity period afterwards. If the flight is very short, the inactivity period will be short and they will be able to fly again since the inactiveTime is:

`double inactiveTime = elapsedTime * multiplier + constant * 86400d;`

I think having training expire just because a mission is accomplished doesn't make sense. Instead, we should leave the expiration date to the current setting and get rid rid of the removal of training proficiency upon recovery. So I think we should remove this section completely:

```
if (e.type == "TRAINING_mission:)
   SetExpiration(pcm.name, e, Planetarium.GetUniversalTime());
```

Proficiency is also something that can be set by the config file if I remember correctly? I think we should move the proficiency expiration dates into the RP-0 Settings Fields so if people want to, they can set it to much different values if they would like.

**Comment by pap1723** [comment]
After talking with @siimav here is a possible proposal.

* Remove all proficiency expirations - once you are proficient in a command module, you should never lose it. The required mission training should act as a refresher for the proficiency.
* Set mission training to expire at the end of a flight as it currently is, but do not expire it if the flight lasted less than 30 seconds. 

Thoughts?

**Comment by NathanKell** [comment]
Makes sense to me! I definitely support having training expire on a flight that lasts more than 30 seconds though, because otherwise you'd be able to reuse the same crew for multiple Real Missions.

**Comment by NathanKell** [comment]
Should be possible. Only problem is you can cancel research (or reorder it)
so you may have nauts training while not researching the thing. But that
might be acceptable.

Sent by my thumbs, slowly.

**Comment by pap1723** [comment]
NK would you rather see the training time shortened or for use to allow the
training ahead of time?

**Comment by NathanKell** [comment]
I was talking about allowing proficiency training during capsule tech
research. I had thought about doing it when I wrote the system actually,
forget exactly why I didn't do it. Probably because it would require KCT
binding in that dll. Other option is to allow proficiency training on any
part that's in a tech node that *can* be researched, not just is being
researched. That wouldn't require any KCT links. Like how the reentry
contract shows up once you can research the heat shields tech, not once you
already have researched it.

**Comment by norcalplanner** [comment]
Great discussion on training.  My $0.02:

Love the idea of never losing proficiency, with the refresher being built into the mission training.

On not losing mission training for a short flight, it might be worthwhile to push that out to 2.5 or 3 minutes, so it occurs after a typical first staging event.

For mission training, the main annoyance for me is the short shelf life, as noted by Roboray.  It seems like simply doubling the mission training expiration date to 240 days after completion would solve this fairly painlessly.

**Comment by siimav** [comment]
PR #949 is up which makes the proficiency training not expire and adds the 30s flight duration margin where current mission is not set as expired.

**Comment by pap1723** [comment]
Great work by @siimav !!
