### ISSUE TITLE
RD108 very differently priced - reopened

### ISSUE THREAD

**Issue by glilienthal** [KSP-RO/RP-0#946]
This is a re-opening of https://github.com/KSP-RO/RP-0/issues/944 

according to my tests, this isn't fixed. 

BTW: I don't understand how the whole part/tech tree system works in RP-1. Is there a place where this is explained? I'd be happy to check this further.

**Comment by glilienthal** [comment]
One correction to the above: SXT RD108 is now correctly priced. the ones from "RN Soviet Rockets" are not.

**Comment by pap1723** [comment]
Most of Raidnernicks stuff is not properly priced. With the Lego nature of his parts, it makes it difficult to know costs. This will be easier now with tooling and tanks. As for the engines, that is something that needs to be looked at.

**Comment by pap1723** [comment]
This is ongoing and is continually being addressed and updated as we find the issues. Thanks!
