### ISSUE TITLE
Airstream Protective Shells Pricing

### ISSUE THREAD

**Issue by Serina0** [KSP-RO/RP-0#947]
There's a substantial price difference between using the Airstream protective shells vs using the purely procedureal fairings.

For a two stage sounding rocket I ended up wanting a interstage fairing, using the Airstream protective shell 1.25 M part I got this. (stage underneath was 1.4M) Giving me a Mach 1  Wave Drag Area of 0.239 Meters squared for a price of 42 credits with no need for tooling. Total weight 36 Kg

![untitled](https://user-images.githubusercontent.com/45949216/50124487-1e9bf300-0265-11e9-93b9-bd5eac027c27.png)

Using the cheapest equivilant (I need the interstage shells to decouple due to those lower wings.) With the interstage fairing base and the Conic fairings, the cost for the fairs plus base ends up at approx 2974 Pre-tooling. Tooling being about 7500, and post tooling costs: 42. which is the same as the  Airstream protective shell 1.25 without needing to go through tooling. The  Wave Drag Area is 0.268 Meters squared. Total weight 69 Kg
 ![untitled](https://user-images.githubusercontent.com/45949216/50124892-d2ea4900-0266-11e9-9860-fc549c822d14.png)

The latter is slightly inferior i believe in terms of air resistence for the approx same area. 

The question is this: Is it possible/should tooling also be implemented to bring the Airstream protection shells in line with the procedural fairings or does the fixed size of the Airstream protection shells give cause to exempt it, thus potentially making people lean more towards the fixed fairing diameters to avoid tooling costs.

**Comment by Bornholio** [comment]
fix, release PFFE and make requirement :P

**Comment by NathanKell** [comment]
Or just write tooling support for them. :)

Sent by my thumbs, slowly.

**Comment by pap1723** [comment]
Can the height and width, etc be read from it to setup the tooling for it?

**Comment by Serina0** [comment]
The issue with tooling is that if you remove the base of the fairing, the fairing itself will vanish, and you'll have to manually reconstruct them.. which.. well tooling and modification don't go hand in hand.

**Comment by pap1723** [comment]
> The issue with tooling is that if you remove the base of the fairing, the fairing itself will vanish, and you'll have to manually reconstruct them.. which.. well tooling and modification don't go hand in hand.

This is a good point. Trying to ever match the same size again would probably not happen.

**Comment by NathanKell** [comment]
Do it same as regular fairings, just height and width, rather than shape.
That's the hack I used there.

Probably have to write a wrapper plugin since those aren't trivially
reflectively available, but they still should be quite easy to calculate.

**Comment by pap1723** [comment]
This was fixed a long time ago and tooling was added.
