### ISSUE TITLE
Balance: Agena D is overpriced and underpowered.

### ISSUE THREAD

**Issue by pjf** [KSP-RO/RP-0#95]
The Communotron 16 costs $5, has a range of 4Mm, and requires so little energy to run that KSP shows it as 0.00/sec.

The FASA Agena D antenna (FASAAgenaAnt) costs $20, has a range of 3.75Mm, and requires a whopping 0.36 EC/sec to run.

Given it's four times the price, and breathtakingly expensive power requirements (twice that of a 200Gm
dish), there's no gameplay reason anyone would ever use this.

I propose we give the Agena D antenna the same stats as the Communotron 16, making it a visual-only
change.

**Comment by pjf** [comment]
Good news: RealismOverhaul gives the antenna sensible stats. 0.05 EC/sec, and a range of 6Mm. While
that still makes it a not-so-attractive choice of antennae (4 x C16s in root mode costs the same, weighs
less, and gives more range), it's nowhere near as imbalanced as what I thought.

Bad news: Either RO isn't applying the change properly, or RemoteTech is overwriting it:

`RO_FASA_Agena.cfg`:

    @PART[FASAAgenaAnt]:AFTER[RemoteTech]
    {
            @MODULE[ModuleRTAntenna]
            {
                    @Mode1OmniRange = 6000000
                    EnergyCost = 0.05
                    @TRANSMITTER
                    {
                            @PacketInterval = 0.4
                            @PacketSize = 1
                    }
            }
    }

`RemoteTech_FASA_Antennas.cfg`:

    @PART[FASAAgenaAnt]:AFTER[FASA]:NEEDS[RemoteTech] // Agena Antenna
    {
        !MODULE[ModuleDataTransmitter] {}
        
        @MODULE[ModuleAnimateGeneric]
        {
            %allowManualControl = false
        }
        
        %MODULE[ModuleRTAntenna] {
            %Mode0OmniRange = 0
            %Mode1OmniRange = 3750000
            %MaxQ = 6000
            %EnergyCost = 0.36
            
            %DeployFxModules = 0
            
            %TRANSMITTER
            {
                %PacketInterval = 0.10
                %PacketSize = 2
                %PacketResourceCost = 8.0
            }
        }
        
        %MODULE[ModuleSPUPassive] {}
    }

I'm not exactly sure why RO's changes aren't taking. It may be we're running at the wrong time, especially since the RT config isn't `:FOR[RemoteTech`.

**Comment by jwvanderbeck** [comment]
I had a similar problem changing a FASA Probe and ended up having no choice but to do it in FINAL

**Comment by NathanKell** [comment]
@pjf  With the reordering of node execution in the new MM (or whenever it gets done) does this still occur?

**Comment by pjf** [comment]
I don't expect so. I corrected and tested all the AIES antennae, but didn't touch the FASA ones.

**Comment by pap1723** [comment]
Not applicable any longer.
