### ISSUE TITLE
Items Missing entry Costs

### ISSUE THREAD

**Issue by Bornholio** [KSP-RO/RP-0#952]
Accumulate Those items here:

First all the nukes. (should be x20 cost)

**Comment by leudaimon** [comment]
Some things I'm trying to fix in the parts browser but I'm not managing:

* The AJ10 Series early has an entry cost of 0
In the parts browser it's supposed to be 3000 and have AJ10-37 as cost modifier

* The S1.5400/RD-58 series has an entry cost of 1000
That's very very low. The parts browser puts it at 8000, with modifier 11D33. Here my guess is that this modifier should be S1_5400 instead of the 11D33. Am I right?

* The Sputnik PS1 has an entry cost of 8750
Besides being pretty high, the configs and part browser state 200 and the cost modifier says 250, avionicsProbesPW (I have no idea what a tech in this field means)

* The 20in X-Ray Detector has an entry of 1000
Also very very low. The browser says 3200, and modifier is 1000, avioincsProbesEarly. Again, I don't know what role the tech plays here.

**Comment by glilienthal** [comment]
Missing: Smart Parts.

**Comment by Bornholio** [comment]
FASA geiger counter missing Log radiation experiment, PSEP, ALSEP and LRRR missing coresponding Experiments.   MK1-5 lights in unlock node should probably only be 1 cost unlocks, also their cost should be reduced.

RN payload assist module should be in Solids '72

CH-R1 avionics module should be costed as a Vanguard 1 prob for now (ignore this)

Galileo and Hygens EDL parts should be in Interplanetary rovers node
Stardust return capsule and 'chute should be in large rover node

**Comment by Bornholio** [comment]
Juno I nosecone should be in Early Avionics and Probes
R7 and Thorable winglest should be in Mature Supersonic Flight
1.8KS-7800 Solid should be in Solids '58
2.5KS-18000 Should be in Solids '59-60

Aerobee and Scout Fins in Early Flight Control should be in either Mature Supersoic Flight or Hypersonics flight

Belle Docking Port should be in Early Docking Proceedures (ignore this)

**Comment by Bornholio** [comment]
Saturn tailfins being under Early Docking.
    stretched Atlas tanks way up in materials science
    Agena Flight Packs sorted under avionics
    specialty parachutes in the landing branch
from #875

**Comment by leudaimon** [comment]
Not really a problem with entry costs, but still... Some inconsistencies between the tree symbols for some parts and the "real" configs:

* Procedural avionics: The first tier of upper stages appear in the tree at Basic Avionics and probes, but the config is really unlocked at Early avionics and probes, which seams reasonable, as there is the Able upper stage there. It seems this symbol is missing, as it's supposed to be another upper stage avionics in the Basic avionics node.

* RCS fuels: There is a some mess here. There are three different places where they are shown, the RCS gui (the "real" one), and parts in the tree with a tank symbol and an engine symbol. What is the reason to have both? Currently the engine symbols match the configs, but the tanks values seem more reasonable to me. They currently look like this:

Fuel | Config | Engine symbol | Tank symbol
-- | -- | -- | --
Hidrogen | Start | NA | NA
HTP | Early Rocketry | Early Rocketry | 56-57 Rocketry
NitrousOxide | 56-57 Rocketry | 58-57 Rocketry | Basic Rocketry
Helium | Start | NA | Basic Rocketry
Hydrazine | Early Flight Control | Early Flight Control | Early Flight Control
Bi-propellants | Early docking | Early docking | Early docking
Cavea-B | Stability | Stability | Stability

**Comment by Bornholio** [comment]
okay now for a beating of the Mature Capsules node

https://cdn.discordapp.com/attachments/512556346869284864/528566283147542548/unknown.png

Apollo Antennas should move to Antenna node, I propose the Interplanetary Comms ('61-63) where the Reflectetron KR7 is, otherwise they would be parallel in Advanced Communications.

Launch Escape Towers, I propose all heavy launch escape towers move to '66 SRB node
The first fully operational test flight of an LES was Apollo mission A-004 on January 20, 1966 and the zond version was flying in '67

RCS quads appear to be Early Docking Procedures technology, but they could also be parallel in Advanced Flight Control.

Docking points should go in Advanced Flight Control. Heat Shields should go in Lunar Rate Heat shields.


Parachutes  need the costs reduced since realchutes controls most of that, right now its wise to not use the mercury/gemini/apollo 'chutes cause the case cost is high

**Comment by ec429** [comment]
Pioneer dish.  (On past form, probably also Voyager dish, but I didn't check it yet.)

**Comment by ec429** [comment]
> RCS quads appear to be Early Docking Procedures technology, but they could also be parallel in Advanced Flight Control.

Early Docking Procedures is a Flight Control line node. It's where biprop RCS appears.  So it's probably the right place for Apollo RCS (which I don't think is any more advanced than, say, Gemini RCS).

**Comment by pap1723** [comment]
Everything up to this point is completed with https://github.com/KSP-RO/RP-0/commit/06cbbfbcedd98f91b783f9094f6a464177b3c890

**Comment by Bornholio** [comment]
awesome, i'm okay with you assumptions shall we close?

**Comment by pap1723** [comment]
Smart Parts needed still. When I rage quit my RiS attempts to get to the Moon, I'll work on those.

**Comment by Bornholio** [comment]
moving to new Issue ROUND TWO

**Comment by Bornholio** [comment]
#969
