### ISSUE TITLE
RP-1 (RP0.dll) Causing massive performance hits

### ISSUE THREAD

**Issue by vallin91** [KSP-RO/RP-0#954]
I discovered that my fps was extremely low the other day after starting to make orbital mission to the Moon in the current Race into Space game.

Upon investigation it seems that RP-1 (or the RP0.dll) is causing these issues. Removing the .dll negates any performance issues. This was tested in a heavily modded install, as well as a minimal install with and without RSS. The issue is apparent in all cases, the only difference is that in the heavily modded installs RP0.dll pushes the fps to about a steady 26, as opposed to about 100 in the minimal installs.

The way to reproduce the issue is to put something into an orbit around any body other than Earth/Kerbin, and then visiting said craft via the Tracking Station or the map (the issue does not appear when you put it into orbit via cheat menu or hyperedit until you've reloaded the craft in said orbit).

[Imgur Album with comparisons](https://imgur.com/a/PoUhQhh)

A table to show the approximated FPS that is showing in the screenshots for those who don't want to scroll through the album.

Install | FPS with RP0.dll | FPS without RP0.dll 
------------ | ------------- | ----------------
Heavily modded (visuals and parts) | **Earth:** 112.0 **Moon:** 26.8 | **Earth:** 104.0 **Moon:** 158.1
Minimally modded without RSS | **Kerbin:** 201.5 **Mun:** 102.6 | **Kerbin:** 259.0 **Mun:** 323.8
Minimally modded with RSS | **Earth:** 272.0 **Moon:** 98.2 | **Earth:** 303.5 **Moon:** 319.1

**Comment by Bornholio** [comment]
from siimav https://cdn.discordapp.com/attachments/512556137380315139/527915833817563154/RP0.dll

**Comment by siimav** [comment]
PR #957 fixes the performance hit. 
Big thanks to you, @vallin91, for all the testing. Probably wouldn't have narrowed this issue down without your help.
