### ISSUE TITLE
Procedural SRB not apearing.

### ISSUE THREAD

**Issue by JPCGAM** [KSP-RO/RP-0#959]
I'm playing RSS/RO in ksp 1.3.1 and I have Procedural parts, I don't know why but the procedural srb is not appearing, when I move the mod to ksp stock , it appears.

**Comment by MikeOnTea** [comment]
It doesn't appear because it was removed for RP-0 because it had issues. I think some of those have been fixed, i'm not sure if there are any remaining issues though, there might be.

**Comment by JPCGAM** [comment]
The main problem that I got with them not appearing is that they are very useful for recreating rockets with srb that there are no parts made for it., which I do a lot.

**Comment by pap1723** [comment]
This might be something that we try to implement in a different way soon(TM), but otherwise, this is intended.
