### ISSUE TITLE
RN/BDB probes misplaced for balance

### ISSUE THREAD

**Issue by vallin91** [KSP-RO/RP-0#960]
I think some of RaiderNicks awesome probes and BDB are a bit misplaced in the early techs for balancing purposes.

Part name|Current Node|Proposed node|Reasoning
-- | - | - | -
Pioneer 0/1/2 & Pioneer 1 Probe | Early Avionics and Probes | Basic Avionics and Probes | Contains science from "Basic" and "Satellite Era" science nodes, very low power consumption and has a 5 Mm lunar ranged antenna. Also very cheap compared to any other probe with all the same science, considering entry costs and part costs.
Pioneer 3/4 | Early Avionics and Probes | Basic Avionics and Probes | This is a powerful long range probe with a 150 Mm antenna. And contains science experiments from "Early Science". The BDB version could remain in the current node. Seeing as it's underpowered when it comes to antenna range.
Pioneer 5 | Basic Avionics and Probes | Interplanetary Probes | This is an interplanetary probe, and should be placed in the correct node. It's a bit too early atm for such a powerful probe.
Explorer 6 | Basic Avionics and Probes | Interplanetary Probes | Although not technically interplantery irl. This probe has a 5 Gm antenna and is almost identical to Pioneer 5, which is interplanetary.

I also want to propose making **Satellite Era Science** a _**prerequisite**_ for unlocking **Basic Avionics and Probes**. Seeing as the probes contain the science needed from that node.
This is of course if it wouldn't be a lot of work to do this. But it would be very good for balance.

A bit further into both nodes there are also probes with science the node underneath unlocks. But I think it's a bigger issue early on. Especially during races and just overall balance.

Also to note, the BDB Pioneers and Explorer have a weaker antenna than RN's equivalent probes. But some still contain the same science experiments and is lunar capable with a few smaller antennas attached as extra.

**Comment by pap1723** [comment]
These are all very good points. We have elected instead to remove science parts from all of these parts. When the comms are rebalanced, these will be looked at again, but for now, they should be ok where they are.
