### ISSUE TITLE
Aircraft engines problems

### ISSUE THREAD

**Issue by md13381** [KSP-RO/RP-0#963]
Downloaded the latest RP1, and for every engine (excluding rocket engines) within the spaceplane hanger I get the following errors:
- No IThrustProvider module found at index 0
Get this for all the SXT mod engine parts, and the following as well for the stock (R0 config) mod:
- Object reference not set to an instance of an object at PartNameList.FindEngineNearby

Reinstalled all the mods and same errors, this results in no jet/prop engine appearing in the staging nor having any ability to activate the engines

**Comment by Bornholio** [comment]
can you link a Output_log.txt and modlist

**Comment by md13381** [comment]
The relevent section from the output_log is:

> (Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
> 
> Voxelization Time (ms): 217
>  
> (Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
> 
> FSswitchEngineThrustTransform: no engine module found
>  
> (Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/UnityEngineDebugBindings.gen.cpp Line: 42)
> 
> Module ModuleAlternator threw during OnStart: System.NullReferenceException: Object reference not set to an instance of an object
>   at PartModuleList.FindEngineNearby (System.String engineName, Int32 engineIndex, Boolean preferMultiMode) [0x00000] in <filename unknown>:0 
>   at ModuleAlternator.OnStart (StartState state) [0x00000] in <filename unknown>:0 
>   at Part.ModulesOnStart () [0x00000] in <filename unknown>:0 
> 

The full file is to large to post (too large for pastebin as well) but I can upload it in two parts if you need it.

Modlist: All installed in a fresh install through CKAN and are all listed as required or recommended
Advanced Jet Engine 2.11.4.1
Background Resources 0.13.6.0
BahamutoD Animation Modules v0.6.5.1
Click Through Blocker 0.1.2
Community Resource Pack 0.8.1.0
Connected Living Space 1.2.6.2
Contract Configurator 1.23.3
Custom Barn Kit 1.1.16.0
Deadly Reentry Continued 7.6.2
DMagic Orbital Science 1.3.11
Extended information about scientific experiments in VAB 1.3.1.1
FASA 7.2.3
Ferram Aerospace Research 0.15.9.1
Firespitter Core 7.6.0
Firespitter Resources config 7.6.0
Hanger Extender 3.5.2
Kerbal Alarm Clock 3.8.5.0
Kerbal Construction Time 1.3.9
Kerbal Engineer Redux 1.1.3.0
Kerbal Joint Reinforcement 3.3.3.
Kopernicus Planetary System modifier 1.3.1-7
KRASH 0.5.26.2
KSC Switcher 1.4.5.0
KSP AVC 1.1.6.2
MagiCore 1.3.1.3
Mechjeb 2 2.7.0.0
Modular Flight Integrator 1.2.4.0
Module Manager 3.0.4
Procedural Fairings 4.0
Procedural Parts 1.2.15
RCS Build Aid Cont 0.9.5.1
Real Fuels 12.6.0
Real Plume 11.1.0
Real Scale Boosters 0.16
Real Solar System 13.1.0 (4096 textures)
Realchute 1.4.5
RealHeat 4.5
RO 12.1.0
RP-1 1.00
RemoteTech 1.9.0.131
Retractable Lifting Surface Module 0.1.5
SCANsat 18.4
Science Alert 1.9.1.1
Ship Manifest 5.2.0.0
Smokescreen 2.7.6.1
Solver Engines 3.5
Soviet Rockets 2.9
Soviet Spacecraft 1.7.5
StageRecovery 1.7.2
SXTcontinued 0.3.23.1
TAC Life 0.13.6.0
Testflight 1.9.0.0
TextureReplacerReplaced 0.5.4
TexturesUnlimited 1.0.0.8
The Janitor's Closet 0.3.3
Toolbar 1.7.16.5
Toolbar Controller 0.1.4.7
US and Soviet Solar Panel 1.6
US Rockets 0.9.1
Ven's stock part 1.9.6
WasdEditorCameraContinued 0.6.12
Waypoint Manager 2.7.1

**Comment by adam-dej** [comment]
I've had the same problem, and fixed it by downgrading Advanced Jet Engine to version https://github.com/KSP-RO/AJE/releases/tag/v2.10.0. See https://github.com/KSP-RO/AJE/issues/20 for more info.

**Comment by md13381** [comment]
Can confirm that this is the fix, seems a fairly easy fix that just needs changing on CKAN

**Comment by Bornholio** [comment]
Good deal, close when ready.  have you listed this issue on CKAN git?  you can reference this over there.
