### ISSUE TITLE
Early Lunar fixes

### ISSUE THREAD

**Issue by NathanKell** [KSP-RO/RP-0#966]
Per discord, we should probably, for both flyby and impact, require science to be transmitted from close to the moon (5000km in flyby case, maybe 1000km in impact case). This will require the probe to live to see the moon.

**Comment by Bornholio** [comment]
Sounds okay, better than having to complete it with ALt-F12 like half the time impact happens.

**Comment by NathanKell** [comment]
Discord also proposes a weight minimum. I like having one for impactors, not sold on having one for flyby or orbit.

(After all, the point of an early impactor was to kick up a big plume of lunar soil that could be studied from Earth.)

**Comment by leudaimon** [comment]
Concur... putting a weight minimum in anything else incentivises only keeping low tech, and has no base in realism.

**Comment by Jerre122** [comment]
Considering the first US flyby probes (pioneer 0-4 ) had a mass of only 7kg, it would be entirely unhistorical to have a weight minimum on flyby mission. I agree that it makes some sense on impact missions, but not for flyby or orbit missions.

**Comment by pap1723** [comment]
Added a requirement of 300kg for the impactor. Luna 2 and Ranger 3 were both above 320 kg.
Fixed with https://github.com/KSP-RO/RP-0/commit/45c97e368caacb5086062796be6b7868bc90ffea
