### ISSUE TITLE
Round 2 of ECM and entry cost changes

### ISSUE THREAD

**Issue by Bornholio** [KSP-RO/RP-0#969]
I'll start with AIES orbital perturbation needs identical parts with regular one

**Comment by Bornholio** [comment]
Continues from complete #952 
SMART PARTS :)

**Comment by Bornholio** [comment]
Fairings showing up in starting node  starting to investigate from what.

PF Parts
```KzInterstageAdapter2
KzResizableFairingBase
KzResizableFairingBaseRing

pf_tech_fairing04m
pf_tech_fairing4m
pf_tech_fairing12m
pf_tech_fairing30m
pf_tech_rocket12m
pf_tech_rocket30m

KzProcFairingFuselage1
KzProcFairingFuselage2
KzThrustPlate
KzProcFairingSide1
KzProcFairingSide2
```

**Comment by PhineasFreak** [comment]
@Bornholio Aren't all PF parts supposed to be on the starting node?

**Comment by PhineasFreak** [comment]
Oh right, we have two "starting nodes", i forgot.

**Comment by pap1723** [comment]
Castor 1 from FASA (FASADeltaCastorSrb) = 6000
Castor 1 from RealFuels (solidBooster1-1Small)= 60000

**Comment by pap1723** [comment]
I am fairly certain all of these have been handled. Any clue @Bornholio

**Comment by Bornholio** [comment]
I think so, i'll close after a fresh load tonight

**Comment by Bornholio** [comment]
looks good
