### ISSUE TITLE
Ven's Stock Revamp

### ISSUE THREAD

**Issue by pap1723** [KSP-RO/RP-0#978]
Apparently, there are some forked versions of VSR that change some fundamental things about some of the engines and parts that we use. I can honestly say that I don't think I use any VSR parts, but I don't know if I am an outlier, or I am the norm.

Whatever the case is, there is no one that is truly maintaining it and making consistent releases to CKAN. I requested a CKAN release for the 1.4.5 version, but someone mentioned on #976 that there are changes and reverts we would need to make to that in order to work.

With VSR as a hard dependency for RP-0, this causes problems. The way I see it, there are 3 ways we can go about things and I would like to see what the consensus is before moving forward:

1. Abandon VSR and just use the stock designs as they are constructed (with the new meshes, etc they are adding now)
    - I don't know if this is viable, it would probably require a lot of rework of models, but I truly don't know enough about the parts to comment on them. @NathanKell ??
2. Take only the must have models / parts and integrate them into RP-1
    - Ven released the source and assets a couple of years ago and they are free to use / adopt for anyone so we could cherry pick what we want
    - This has the benefit of being a lightweight option as VSR is a dependency anyway, but I am pretty sure we do not need all of the stuff it provides
3. Keep VSR as it is and hope that RO takes it over or someone starts normal releases
    - I don't think this option will work as I doubt anyone in the RO group has a passion for VSR parts and there are few people with enough time to maintain.

Thoughts?

**Comment by MikeOnTea** [comment]
RCS, especially the 1/2 kn thrusters, look horrible without VSR, while VSR provides some nice models for the latter especially. If we ditch VSR, we would need another replacement for those. Some other common parts are probably affected as well, i think about solar panels, RTGs? etc.

**Comment by PhineasFreak** [comment]
I agree with @MikeOnTea. Considering the extensive and very nice models that VSR offers, compared to both the current Squad and their "new" "revamped" parts, i'd say that it would be just better to fold select models to RO itself:

* VSR may end up deprecated
* The Squad "revamp" is just too shitty to be used with RO
* The new Porkalike "Restock" does seem promising but i am not sure if it will offer compatible models/parts

In any case: no, do not ever think about using just the stock parts to exist...oh my, the horror!

BTW RO already uses some things by VSR: you will easily recognize the RO LR79/89/E-1 engine models if you install some old VSR version. And the licensing is compatible.

**Comment by pap1723** [comment]
@PhineasFreak I would think that yes, it should be in RO. We have started to dabble more into parts with science experiments and stuff that save breaks some RO stuff. If we can stabilize, I would like to move most of it over to RO.

I think we need to roll the models into RO as standard distribution. What I need to know is what models are absolutely necessary and what is just "nice to have" and what is not worthwhile?

**Comment by PhineasFreak** [comment]
One of the separation motors, some of the smaller solar panels and the RD-100 engine are VSR parts only.

**Comment by Bornholio** [comment]
If we did any Ven's absorption i'd suggest AIES if possible also

**Comment by Bornholio** [comment]
Could we have a submod that takes only parts from Vens that RO modifies and strip all else.
This could all be given unique names to avoid problems if someone errantly installs both.

Part used or made by RO for/from vens


1x3SPanels
--
1x3WPanels
45DegreeRCS
Angledpanel
CryoXBig
CryoXendButt
CryoXmed
CryoXnoseCone
CryoXsmall
fuelTank1-5
HeavyRcs
InflatableHAB
InlineRCS
KerbCan
LargeOMS
largeTrussMount
LGLadderUtility
liquidEngine3
liquidEngineMiniTurbo
LongDeployableAntenna
LongLadder
LVT15
MedLadder
MedLadderUtility
microIbeam
MK1Cargobay
MK2VApod
OCTOs0Adapter
OCTOServiceBay
OCTOTank
OscarAtank
OscarDtank
OscarEtank
parachuteSingle_drogue
RadialavionicsHub
RadialLF
RadialLFLong
RadialLFO
RadialLFOLong
RadialMonoMini
RadialReactionWheel
RO-AgenaEngine
RO-XLR99
ROBabySergeant
RT1
RT2
rtg
rtgMini
S2Pila
ShieldCapLarge
shortDecoupler1-2
Size2MedEngine
SmallPointLight
smallRadialDecoupler
SmallSpotLight
SMLadderUtility
SnubOtron
solidBoosterMAX
stationHubLarge
strutCube3way
strutCube90
strutCubeLarge
strutCubeMedium
strutCubeMountingPlate
strutCubeOCTOAdapter
strutCubeS0Adapter
strutCubeSmall

Intrinsicly deleted

!PART[commDishVSR]
--
!PART[engineSkipperButtless]
!PART[Ks25]
!PART[MicroEngineB]
!PART[MK1LFOFuselage]
!PART[RT20]
!PART[VenLV909b]

**Comment by NathanKell** [comment]
The thing about Ven's is, it's not at all a question of the engines (with the exception of the LV-1 which we use as the 1kN thruster, and also we need an alternate XLR99 from somewhere). It's everything *else*. There's two categories of "everything else"
(a) all the parts which exist (per se) in stock KSP, but are ugly or ill-suited to RO use. Examples here: the LV-1 (1kN thruster), the RCS parts, the structurals. THE SEP MOTOR. Please, please don't force me to use the stock Sepratron.
(b) the parts which VSR adds (extra spaceplane parts, the large sep motor, structurals, etc).

Losing Ven's would hurt on two levels. First, the everyday parts we use would be uglier (don't make me fly the stock Mk1-2 pod pls, let alone the stock 1kN Thruster).  Second, solar panels, RCS, and most of all spaceplanes (where the X-15 parts wouldn't even exist) will have far fewer parts, parts that we rely on for progression.

All this is a separate discussion from engines, where I agree Ven's is not super helpful, and where I think a larger reorganization is probably in order (it would be nice to not have many duplicates). I'll make an issue about that on RO.

**Comment by NathanKell** [comment]
Updated because I forgot about the Sergeant and the WAC. In particular the Taerobee engine is an Aerobee engine, too big for use on WACs, despite it allowing the WAC config.

**Comment by pap1723** [comment]
Ven's Stays :) I will continue to work with Kerbas to get these updated and posted to CKAN.

**Comment by Bornholio** [comment]
https://github.com/Kerbas-ad-astra/Stock-Revamp/branches
