### ISSUE TITLE
Make engine upgrades more explicit

### ISSUE THREAD

**Issue by pjf** [KSP-RO/RP-0#98]
Today I discovered that unlocking some engine nodes (eg: Mature Hydrolox) also unlocks engine configs for existing engines. This means that some nodes which appear to be completely empty in RP-0 (eg: Mature Hydrolox) actually have an in-game effect when unlocked. However this is _not_ obvious to the player.

Indeed, finding out which configs are unlocked means not being in the R&D screen, but instead the VAB, hovering over each engine, and eyeballing all the configs there. I'm not even sure _that_ helps, because I don't remember locked configs in the VAB mentioning which nodes unlock them.

**Virtual Parts**

A great solution would be to insert virtual parts into the tech-tree. I know that MechJeb and pFairings both have parts which show up in the tech-tree, but really just unlock features on existing parts. If engine configs were to do the same, it would obvious to players what each node in the R&D screen is giving them.

The risks here is that I have no idea how virtual parts work. This may be a lot of work, or completely incompatible.

**Document the node**

An acceptable solution would be to update the node description to list which engine configs are unlocked. This isn't ideal, as it limits the amount of information we can present, we may list engines the player doesn't have (because they don't have those part packs), and players don't tend to read documentation anwyay.

**Comment by NathanKell** [comment]
Virtual parts are pretty easy: AFTER[RP-0] you +PART the engine, change its name to something unique, change its title and description to note it's the new config, set its cost and entryCost to 0 (so people don't waste time buying it) and then set category = none

**Comment by jwvanderbeck** [comment]
Thats a crapload of work

- John Vanderbeck
- http://www.johnvanderbeck.com

**Comment by pjf** [comment]
> Virtual parts are pretty easy: AFTER[RP-0] you +PART the engine, change its name to something unique, change its title and description to note it's the new config, set its cost and entryCost to 0 (so people don't waste time buying it) and then set category = none

You are *awesome*. Is this likely to add much to our memory overhead?

Am I correct that engine configs are currently defined across RO and RP-0, or are they exclusively defined in RP-0? If it's the latter, I can adjust the build system to hopefully insert virtual parts automatically.

**Comment by NathanKell** [comment]
They are in RO pretty much entirely. I think I backported all CONFIGs. It will not add more than 5kB per part, since all assets are shared, it's just the Part, PartModule, etc code-objects in memory.

Ooh, I have an interesting dealio for you, heh. We'd been talking some time about putting RO on travis, and the unmanageability of having to copy engine CONFIGs between different parts. If you wrote a build system that took CONFIGs and the parts to apply them too, and spit out MM, the creation of the duplicate parts would be just a few lines of perl away.

**Comment by chippydip** [comment]
I realize this is a nearly two year old issue at this point, but as someone who recently started playing RP-0 I'd like to bump this by saying how enormously useful this feature would be. So far the only way I've figured out to get this info in-game is to plop a bunch of engines onto a dummy rocket in the VAB and dig through the config GUI for each to see which configs are unlocked with which tech.

Other things that would be useful to get the same treatment:
* Procedural tank type unlocks
* Tech level upgrades for RCS (if I hadn't seen this in @NathanKell 's videos I wouldn't even know this was a thing)
* Unlocks that I don't even know about yet?

**Comment by pap1723** [comment]
This has been accomplished by utilizing the PARTUPGRADES feature and will be implemented in the next major release of RO/RP-0
