### ISSUE TITLE
Cost difference between A4 guidance and starting guidance unit.

### ISSUE THREAD

**Issue by ajvaughan** [KSP-RO/RP-0#980]
The A-4 Guidance unit (from the Tarrobee mod) and the starting guidance unit 1m are both in the start node, have the same mass, electric charge, and unlock costs but have differing costs after unlock (300 and 350).  the tarrobee version also has 2 electric charge consumption numbers 3.0 (no unit stated) and 10 watts, whilst the starting guidance unit is 3 kilowatts.

Not sure what mod provides the Tarrobee configs used in RP-1, (also not sure which value is correct) so filed here.

**Comment by pap1723** [comment]
This is actually a Realism Overhaul issue, but it is fixed here: https://github.com/KSP-RO/RealismOverhaul/commit/c34e5c791566b319c9738a1c4f89002296034500
