### ISSUE TITLE
Contract descriptions should indicate removal conditions

### ISSUE THREAD

**Issue by lpgagnon** [KSP-RO/RP-0#982]
Most contracts indicate how many times they can be completed, but not what other events can cause them to become unavailable (for example, a First Gen satellite contract disappearing the first time a Second Gen contract is completed). This information can help the player plan his missions, so it should be available without having to look in .cfg files

**Comment by pap1723** [comment]
Fixed with https://github.com/KSP-RO/RP-0/commit/b438e284442ce6ce5c23dd988889a52b9d2184eb
