### ISSUE TITLE
Level 4 launchpads have no maintenance

### ISSUE THREAD

**Issue by lpgagnon** [KSP-RO/RP-0#983]
(seen with Jan 1 commit eaef7c529abdf47e42772ba4b9733da5569bdbf7)

screenshot 1: I have 4 launchpads: one lvl 1, one lvl2, and two lvl3. one of the lvl3s is being upgraded to lvl4. Aside from the costs seeming super-low, everything is accounted for

https://media.discordapp.net/attachments/516431076680531978/532309083047460890/220200_20190108162259_1.png

screenshot 2: launchpad upgrade completed. I'm no longer paying maintenance on a second lvl3... and I'm not paying for the new lvl4 either

https://media.discordapp.net/attachments/516431076680531978/532309267470876673/220200_20190108162359_1.png

**Comment by lpgagnon** [comment]
Same issue with Level 5, so presumably with higher levels as well

**Comment by pap1723** [comment]
I have a sneaking suspicion about this. @lpgagnon Do you know if there is any maintenance on the R&D building once it gets above level 3 as well?

**Comment by siimav** [comment]
Should be fixed by 819d459b09d418f2c0822db00f575f794ca56e45
